Issue 40106: UX Query Metadata Editor - editing url and import aliases field does not re-show
LabKey/platform pull request #1016
Opened 2020-04-01 04:19 UTC by labkey-ankurj

2020-04-01 17:20 UTC, labkey-jeckels requested changes

2020-04-01 17:20 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +                return null;
Probably better to throw an exception here, because returning null will likely cause a NullPointerException wherever it's used which will be disconnected from the place that detected the problem.

2020-04-01 17:20 UTC, labkey-jeckels commented on query/src/org/labkey/query/MetadataTableJSON.java
> +                importAliasesXml.addImportAlias(metadataColumnJSON.getImportAliases());
This doesn't look right - we should be supporting storing aliases as separate strings when there are multiple defined. See ColumnRenderPropertiesImpl.convertToString() and convertToSet() for code that splits and combines them

2020-04-01 17:24 UTC, labkey-ankurj commented on query/src/org/labkey/query/MetadataTableJSON.java
> +                importAliasesXml.addImportAlias(metadataColumnJSON.getImportAliases());
How would the users define multiple? by passing comma separated strings?

2020-04-01 17:31 UTC, labkey-jeckels commented on query/src/org/labkey/query/MetadataTableJSON.java
> +                importAliasesXml.addImportAlias(metadataColumnJSON.getImportAliases());
Yup. See ColumnRenderPropertiesImpl.STRING_PATTERN for how they get parsed.

2020-04-07 00:30 UTC, labkey-jeckels approved these changes

2020-04-08 20:11 UTC, cnathe reviewed
@labkey-ankurj See TODO in StudyPublishTest related to this issue 40106. I assume this should be fixed up as part of this PR as well.

2020-04-13 14:07 UTC, merged