Issue 40118: Client dependencies are cached too aggressively
LabKey/platform pull request #1032
Opened 2020-04-03 21:00 UTC by labkey-adam

2020-04-06 17:59 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/DefaultModule.java
> +    private final Set<Supplier<ClientDependency>> _clientDependencySuppliers = new LinkedHashSet<>();
We've historically used LinkedHashSet for these declarations because order matters, and it's a way to keep people from swapping it with something else. Maybe keep the declaration the same, but add a comment? Perhaps less important here because the variable is final.

2020-04-06 21:16 UTC, labkey-nicka requested changes
Looks good and seems to fix scenario described in 40118.

2020-04-06 21:16 UTC, labkey-nicka commented on api/src/org/labkey/api/view/template/LibClientDependency.java
> +                        _suppliers.add(() -> fromCache(pair));
I think this usage and the css usage could be changed to

```java
//add paths to the compiled scripts we expect to have created in the build. these are production mode only
if (hasJsToCompile)
{
    String path = filePath.toString().replaceAll(TYPE.lib.getExtension() + "$", ".min" + TYPE.js.getExtension());
    _suppliers.add(supplierFromPath(path, ModeTypeEnum.PRODUCTION));
}

if (hasCssToCompile)
{
    String path = filePath.toString().replaceAll(TYPE.lib.getExtension() + "$", ".min" + TYPE.css.getExtension());
    _suppliers.add(supplierFromPath(path, ModeTypeEnum.PRODUCTION));
}
```

2020-04-06 21:16 UTC, labkey-nicka commented on api/src/org/labkey/api/view/template/ClientDependency.java
> +    protected static @NotNull ClientDependency fromCache(String requestedPath, @NotNull ModeTypeEnum.Enum mode)
Why is this `fromCache` `@NotNull` but the one below `@Nullable`? IntelliJ is warning this is annotated `@NotNull`, however, could still return `null` since the value in the cache could be `null`.

![image](https://user-images.githubusercontent.com/3926239/78603752-8507a480-780d-11ea-9064-eed3f8274eac.png)

2020-04-06 21:16 UTC, labkey-nicka commented on api/src/org/labkey/api/view/template/LibClientDependency.java
> +                        TYPE primaryType = supplier.get().getPrimaryType();
The repro case for 40118 is successfully working now (i.e. modifying a dependent library definition in dev mode) but I just wanted to make sure it is intentional to cause an NPE. The result is logged as follows:

```
ERROR ClientDependency         2020-04-06 13:53:35,850     http-nio-8080-exec-5 : ClientDependency "clientapi/core/Nope.js" not found, skipping. URL: /labkey/home/project-begin.view?
ERROR LibClientDependency      2020-04-06 13:53:35,850     http-nio-8080-exec-5 : Invalid client library XML file: clientapi_core.lib.xml. null
```

When I followed this back it is NPE'ing on the `supplier.get().getPrimaryType()` due to the path not existing for "clientapi/core/Nope.js". I see that this entire method is wrapped in try/catch so behavior ends up working as expected.

2020-04-06 22:57 UTC, labkey-jeckels requested changes

2020-04-06 22:57 UTC, labkey-jeckels commented on api/src/org/labkey/api/view/template/ClientDependency.java
> +            supplier = () -> fromCache(pair);
Since there may end up a Set of some sort, I think we need a real class here that knows how to do equals() and hashCode()

2020-04-06 23:14 UTC, labkey-adam commented on api/src/org/labkey/api/view/template/ClientDependency.java
> +            supplier = () -> fromCache(pair);
I'm not opposed to a real class, but I think the right approach is to just hold lists of suppliers... and then resolve the ClientDependency objects into a Set. That's a change, but a lot easier than trying to implement equals() and hashCode() on all the suppliers.

2020-04-06 23:16 UTC, labkey-jeckels commented on api/src/org/labkey/api/view/template/ClientDependency.java
> +            supplier = () -> fromCache(pair);
Ah, OK. Yes, as long as the suppliers are ordered (List, LinkedHashSet) we should be fine.

2020-04-07 15:40 UTC, labkey-adam commented on api/src/org/labkey/api/module/DefaultModule.java
> +    private final Set<Supplier<ClientDependency>> _clientDependencySuppliers = new LinkedHashSet<>();
We're now consistently holding List<Supplier<ClientDependency>>, as discussed.

2020-04-07 15:41 UTC, labkey-adam commented on api/src/org/labkey/api/view/template/LibClientDependency.java
> +                        _suppliers.add(() -> fromCache(pair));
Right you are... updated

2020-04-07 15:43 UTC, labkey-adam commented on api/src/org/labkey/api/view/template/LibClientDependency.java
> +                        TYPE primaryType = supplier.get().getPrimaryType();
My changes propagated an existing bug... I've added a null check so we don't abandon this lib altogether. Should still see the first error.

2020-04-07 15:43 UTC, labkey-adam commented on api/src/org/labkey/api/view/template/ClientDependency.java
> +            supplier = () -> fromCache(pair);
Lots o' Lists now

2020-04-07 15:44 UTC, labkey-adam commented on api/src/org/labkey/api/view/template/ClientDependency.java
> +    protected static @NotNull ClientDependency fromCache(String requestedPath, @NotNull ModeTypeEnum.Enum mode)
I'm sure I had some reason, but everybody's @Nullable now.

2020-04-07 17:26 UTC, labkey-nicka approved these changes

2020-04-08 01:29 UTC, labkey-jeckels approved these changes

2020-04-08 16:25 UTC, merged