Issue 39696: Search reference for file breaks when renaming container
LabKey/platform pull request #1041
Opened 2020-04-08 17:16 UTC by labkey-ians

2020-04-08 18:08 UTC, labkey-susanh commented on core/src/org/labkey/core/webdav/DavController.java
> +    private void fireFileMovedEvent(WebdavResource dest, WebdavResource src, Collection<? extends WebdavResource> movedChildren)
```suggestion
    private void fireFileMovedEvent(WebdavResource dest, WebdavResource src, @Nullable Collection<? extends WebdavResource> movedChildren)
```

2020-04-08 18:08 UTC, labkey-susanh commented on api/src/org/labkey/api/webdav/AbstractWebdavResource.java
> +        this(folder.append(name), resolver);
This is now bypassing the validateName check in AbstractResource.  Is there a reason we want to bypass that check?

2020-04-09 21:29 UTC, labkey-susanh requested changes

2020-04-09 21:29 UTC, labkey-susanh commented on api/src/org/labkey/api/webdav/AbstractWebdavResource.java
> +        super(folder.append(name), resolver);
```suggestion
        super(folder, name, resolver);
```
Still not sure why this needs to change.  Am I looking at the wrong version of the file somehow?

2020-04-09 21:46 UTC, labkey-susanh approved these changes

2020-04-09 21:46 UTC, labkey-ians commented on api/src/org/labkey/api/webdav/AbstractWebdavResource.java
> +        super(folder.append(name), resolver);
This was homeschooling fatigue. Intended to revert it.

2020-04-14 13:40 UTC, labkey-susanh approved these changes

2020-04-14 17:09 UTC, merged