Item 7095: Add detailed audit logging for samples as separate audit type event
LabKey/platform pull request #1060
Opened 2020-04-13 17:50 UTC by labkey-susanh

**Rationale**
For the sample timeline feature within LabKey Sample Manager, we require detailed audit logs for samples that can be more easily reference by sample Id.  The current placement of these detailed logs in the QueryUpdateEvents makes it difficult to find relevant logs and also doesn't capture all the desired metadata.  We also want to have this detailed audit logging turned on for Sample Manager without requiring that it be turned on for all Sample Types.

**Related PRs**
- TBD

**Changes**
- Refactor handling and display of detailed audit records for better reuse
- Allow some APIs to override auditBehaviorType via a parameter 
- Add new Audit Provider, domain and event type for storing detailed logs for Samples, replacing their inclusion in the QueryUpdateEvents audit log.

2020-04-14 15:26 UTC, XingY reviewed
My concern is that a SM user will not be able to turn detailed logging off via XML. Maybe auditConfigurable should be preferred over context param? Looks good otherwise.

2020-04-14 15:26 UTC, XingY commented on api/src/org/labkey/api/audit/DetailedAuditHandler.java
> +public abstract class DetailedAuditHandler
I find the class name a bit misleading... It seems to handle all audit types, not just detailed

2020-04-14 15:26 UTC, XingY commented on api/src/org/labkey/api/audit/DetailedAuditHandler.java
> +            auditType = auditType == null ? auditConfigurable.getAuditBehavior() : auditType;
With this approach, will sample manager still able to disable detailed logging via xml config?

2020-04-14 15:26 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
> +            if (sampleSetLsid == null && row.containsKey("sampleset"))
maybe a comment on when sampleset is the lsid

2020-04-14 15:26 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
> +            case MERGE:
Since the old/new data map objects are available, we should be able to determine if a single row is register or update.

2020-04-14 20:41 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
> +            case MERGE:
OK nvm, I see that merge doesn't have old data map.

2020-04-15 16:15 UTC, labkey-susanh commented on api/src/org/labkey/api/audit/DetailedAuditHandler.java
> +public abstract class DetailedAuditHandler
True. The addAuditEvent specifically handles adding the oldRecord and newRecord fields, which are available only in a DetailedAuditTypeEvent, and that's the main part I was trying to avoid duplicating.  I can rename to AuditHandler.  It seems maybe too general, but we'll see.

2020-04-15 16:21 UTC, labkey-susanh commented on api/src/org/labkey/api/audit/DetailedAuditHandler.java
> +            auditType = auditType == null ? auditConfigurable.getAuditBehavior() : auditType;
No, but that is intentional.  All actions that come from the sample manager application should use detailed logging, otherwise we have no timeline feature to speak of.  This also follows the general practice for command line tools and precedences, where the options set on the command line have highest precedence (I consider the URL parameters to be analogous to the command-line options.)   

For performance testing purposes, we can possibly have an admin flag that can be set to turn off the detailed logging (and right now we can use the experimental flag created in your branch), but this isn't something a LSKM user will have access to.

2020-04-15 16:24 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
> +            if (sampleSetLsid == null && row.containsKey("sampleset"))
Good thought.  Now if I can just remember when that happens...

2020-04-15 17:17 UTC, labkey-jeckels commented on api/src/org/labkey/api/audit/DetailedAuditHandler.java
> +            auditType = auditType == null ? auditConfigurable.getAuditBehavior() : auditType;
I don't think we should allow the URL to override what an admin set up for logging. A malicious user shouldn't be able to opt out of audit logging.

2020-04-15 18:19 UTC, labkey-susanh commented on api/src/org/labkey/api/audit/DetailedAuditHandler.java
> +            auditType = auditType == null ? auditConfigurable.getAuditBehavior() : auditType;
Ah, yes.  Malicious users.  OK, I'll make this change.  I predict there will be some difficulties with this timeline feature because of the different ways it can be affected.

2020-04-16 14:51 UTC, XingY requested changes

2020-04-16 14:51 UTC, XingY commented on api/src/org/labkey/api/audit/AuditHandler.java
> +            if (auditType == null || auditConfigurable.getXmlAuditBehaviorType() != null)
What if both auditType and auditConfigurable.getXmlAuditBehaviorType are null, but auditConfigurable.getAuditBehavior is not null? I think getAuditBehavior is never null, since it defaults to NONE. But it can also be not NONE. DataClass has an override that would set default to DETAILED, although getXmlAuditBehaviorType is null.

2020-04-16 15:03 UTC, labkey-susanh commented on api/src/org/labkey/api/audit/AuditHandler.java
> +            if (auditType == null || auditConfigurable.getXmlAuditBehaviorType() != null)
If both are null, we'll use the result of getAuditBehavior, whatever that is (and I don't think it can be null).  Isn't that what we want?

2020-04-16 17:01 UTC, XingY commented on api/src/org/labkey/api/audit/AuditHandler.java
> +            if (auditType == null || auditConfigurable.getXmlAuditBehaviorType() != null)
You are right, I misunderstood the if condition.

2020-04-16 17:02 UTC, XingY approved these changes

2020-04-17 00:36 UTC, merged