Issue 39696: Search reference for file breaks when renaming container
LabKey/platform pull request #1067
Opened 2020-04-15 07:54 UTC by labkey-ians

Fixing tests and other issues from https://github.com/LabKey/platform/pull/1041

2020-04-15 15:02 UTC, labkey-susanh approved these changes

2020-04-20 16:39 UTC, labkey-tchad requested changes
This isn't working for me locally. It also appears to only address folder rename but not move.

2020-04-20 16:39 UTC, labkey-tchad commented on core/src/org/labkey/core/CoreContainerListener.java
> +                addAuditEvent(evt.user, c, message);
Why doesn't the reindexing get triggered in `SearchContainerListener`? That's where we trigger the initial crawl for new conainers (`DavCrawler.getInstance().addPathToCrawl`)

2020-04-22 15:03 UTC, labkey-tchad commented
They still aren't getting reindexed but at least we're only clearing the index for actual files now (12 search failures instead of 15).

2020-04-29 17:27 UTC, labkey-tchad approved these changes
This is an improvement and should resolve failures in Sample Manager tests. We can continue work in a new branch.

2020-04-29 17:39 UTC, merged