7066: Dataset Designer Server Side API updates
LabKey/platform pull request #1069
Opened 2020-04-15 20:23 UTC by RosalineP

Some notes:
- We don't currently check to make sure that the dataset name is under a maximum amount of characters—do we want to add that?
- Current code allows for a keyPropertyName that is the name of a column that is not numeric or string in type. Should this be changed?
- If you change the name of a dataset in the options but not the domainDesign, it saves and changes the dataset name. Is this expected? The save does not go through if you change the domainDesign name but not the options name.
- Category issue I noted

2020-04-15 23:28 UTC, labkey-jeckels commented
@RosalineP 
1. What's the behavior if you pass in a very long dataset name? study.dataset.name is 200 characters, so that's what you'd want to be sure to exceed. It might give you a decent enough error message already.

2. Yes, restricting to just integer and string fields makes sense.

3. It's not great, but what you're describing probably matches what happens if you edit a dataset's name through the GWT designer. I'm not sure there's a lot of value in having duplicate copies of the value in the JSON, only one of which matters when you save.

2020-04-16 19:26 UTC, cnathe commented
> @RosalineP
> 
> 1. What's the behavior if you pass in a very long dataset name? study.dataset.name is 200 characters, so that's what you'd want to be sure to exceed. It might give you a decent enough error message already.
> 2. Yes, restricting to just integer and string fields makes sense.
> 3. It's not great, but what you're describing probably matches what happens if you edit a dataset's name through the GWT designer. I'm not sure there's a lot of value in having duplicate copies of the value in the JSON, only one of which matters when you save.

For #2, don't we want to allow any of the fields to be used for the additional key (i.e. keyPropertyName) for the non-managed case? Doesn't the type restriction only come into play when the additional key is also selected as a "managed" 3rd key (i.e. one that LK server will populate for you)?

2020-04-16 20:20 UTC, labkey-jeckels commented
Yes, thanks @cnathe . I was only thinking about the managed case. We shouldn't restrict to int and string for unmanaged keys.

2020-04-16 20:25 UTC, RosalineP commented
Yup, that's right, I should have clarified that—I was only talking about the managed third key case

2020-04-16 22:08 UTC, cnathe reviewed
Adding some initial comments, I will re-review the DatasetDomainKind changes in more detail after Rosaline is done with the last part she is currently working on.

2020-04-16 22:08 UTC, cnathe commented on study/src/org/labkey/study/controllers/StudyController.java
> +            return true;
@RosalineP @labkey-ankurj Either of you know why this change was made? Seems unrelated to this PR.

2020-04-16 22:08 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
@RosalineP This part needs to be in the DatasetDomainKindProperties constructor itself instead of here. That way both code paths that use the `new DatasetDomainKindProperties(ds)` will get these set. 

The code to put into the DatasetDomainKindProperties constructor should be this, I believe:
```
Study study = StudyService.get().getStudy(ds.getContainer());
        if (ds.getContainer().isProject() && study.isDataspaceStudy())
        {
            _definitionIsShared = study.getShareDatasetDefinitions();
            _visitMapShared = study.getShareVisitDefinitions();
        }
```

2020-04-16 22:08 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
actually since that is based off of the study itself and not specific to the dataset, we'll need that in the default constructor case as well. So this should go in the `public DatasetDomainKindProperties() {}` constructor and then we'll need to call it with the container as a param for that constructor.

2020-04-16 22:08 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +            throw new IllegalArgumentException("There can not be an Additional Key Column if the dataset is Demographic Data");
@RosalineP as discussed, can some of these validation checks that apply to both the create and update case be factored out to a separate method which both createDomain() and updateDomain() can call?

2020-04-16 22:08 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +    private ValidationException validateDatasetProperties(DatasetDefinition def, ValidationException exception, Container container, User user,
@RosalineP from the comment above, maybe this method is the one that has the validation checks that are common between the create and update case?

2020-04-16 22:29 UTC, RosalineP commented on study/src/org/labkey/study/controllers/StudyController.java
> +            return true;
It looks like this got pulled in when I initially pulled in Ankur's react page setup changes on fb_datasetDesigner: https://github.com/LabKey/platform/compare/fb_datasetDesigner
@labkey-ankurj Do we still want it?

2020-04-16 22:41 UTC, RosalineP commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
Oh, that makes sense. Have added it as suggested to both constructors.

2020-04-16 23:37 UTC, labkey-ankurj commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
Should this be added in the constructor as well?
![Screen Shot 2020-04-16 at 4 35 49 PM](https://user-images.githubusercontent.com/39965420/79516534-8b153680-8000-11ea-8e61-c9934298c2a5.png)

2020-04-17 13:37 UTC, cnathe commented on study/src/client/DatasetDesigner/DatasetDesigner.tsx
> +                    showDataSpace={false}
@labkey-ankurj You may have already seen this, but looks like the relevant value for this is being returned with the dataset model: `definitionIsShared`

2020-04-17 13:40 UTC, labkey-ankurj commented on study/src/client/DatasetDesigner/DatasetDesigner.tsx
> +                    showDataSpace={false}
Yes, I have addressed this and it's in my local set of changes.

2020-04-17 14:44 UTC, labkey-ankurj commented on study/src/org/labkey/study/controllers/StudyController.java
> +            return true;
@cnathe I see these are not recent changes and not sure why they are getting displayed in this diff.
![Screen Shot 2020-04-17 at 7 43 54 AM](https://user-images.githubusercontent.com/39965420/79581425-42e92900-807f-11ea-94cf-8fb996c9f953.png)

2020-04-17 15:55 UTC, RosalineP commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +    private ValidationException validateDatasetProperties(DatasetDefinition def, ValidationException exception, Container container, User user,
Because this validateDatasetProperties() function has some stuff that can't be called by the create case, I've reverted its name to checkCanUpdate() and created a different, shared validateDatasetProperties() function

2020-04-17 16:04 UTC, RosalineP commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +    private ValidationException validateDatasetProperties(DatasetDefinition def, ValidationException exception, Container container, User user,
I ended up having a couple of questions about reusing the existing validation inside of this function across create and update. I have a temporary implementation right now that reverts this validateDatasetProperties() to the original name of 'checkCanUpdate' and creates a different validateDatasetProperties() function that shares the common validation checks—I'll ping you about those questions!

2020-04-20 16:03 UTC, cnathe requested changes

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
>                  throw new IllegalArgumentException("Unable to find a category named : " + categoryName + " in this folder.");
Looks like the createDomain case for a dataset does not currently support the "create a new category by name and use it for this dataset". The updateDomain case supports this via its call to `StudyManager.getInstance().updateDatasetDefinition`, which ends up calling `ensureViewCategory()` in the StudyManager. We should sync up on how to handle this for the create dataset scenario.

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +            if ( datasetProperties.isDemographicData() && !datasetProperties.isDemographicData() && !StudyManager.getInstance().isDataUniquePerParticipant(def))
Looks like both of the first two parts of this if statement are using `datasetProperties`, I believe the second one should be using the `DatasetDefinition def` param:
```suggestion
            if ( datasetProperties.isDemographicData() && !def.isDemographicData() && !StudyManager.getInstance().isDataUniquePerParticipant(def))
```

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +            if ( datasetProperties.isDemographicData() && !datasetProperties.isDemographicData() && !StudyManager.getInstance().isDataUniquePerParticipant(def))
Also, I think we should move this validation check to the `checkCanUpdate()` method so that it lives with the other update dataset specific validation checks.

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +//                throw new IllegalArgumentException("Unable to find a category named : " + datasetProperties.getCategory() + " in this folder.");
See previous comment in this code review. For the update case, we already have the proper checks happening for the category (i.e. to use an existing one or create a new one) via the StudyManager code path. So these commented out lines can be removed.

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +            }
It looks like the `validateDatasetProperties` already checks for this case, so I think this if statement is basically a no-op. That is, if the property is set as demographic we would have already thrown an exception if the keyProperty name wasn't null or the managed flag was true. I think this can be removed.

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +                datasetProperties.setDataSharing("NONE");
The comment here says to ignore the illegal argument for sharedDataset, I think we should instead throw an exception for this case instead of just changing it for the user/caller. I suggest moving this to the `validateDatasetProperties` method and have the check throw an error if the study does not allow for shared visit definitions and the dataSharing property is anything but NONE.

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
I don't see where this is throw from, maybe it can be deleted?

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +            throw UnexpectedException.wrap(x);
The createDomain() case uses `throw new RuntimeException(e);` for this general catch. We should make them consistent.

2020-04-20 16:03 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
This code confuses me. It looks like this "remove duplicate default fields" only happens in the create dataset case. I wonder if we either want to have it happen for both create and update cases or if we should just remove it and let the "reserved field name" validation check handle this case?

2020-04-20 17:09 UTC, cnathe commented on study/src/client/DatasetDesigner/DatasetDesigner.tsx
> +    hasDatasetDesignPermission?: boolean,
@labkey-ankurj this doesn't look to be used at all in this component/file.

2020-04-20 17:12 UTC, cnathe commented on study/src/client/DatasetDesigner/DatasetDesigner.tsx
> +                    onComplete={this.onComplete}
@labkey-ankurj  Two things missing here `successBsStyle={'primary'}` and the `onChange` prop/listener. See list/Designer.tsx.

2020-04-20 19:26 UTC, RosalineP commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
Yeah, I agree and have deleted it—it looks as though this is trying to gate for is the third key column is changed to a column that has duplicates and violates the participant + visit + key uniqueness constraint? Does that sound to you like something we should gate for in validateDatasetProperties()?

2020-04-20 19:35 UTC, cnathe commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
Ah ok yes, that is the scenario. So if you have a dataset configured and saved which already has data in it, then you go into the designer and set an additional key column for that dataset but the data in the table violates that constraint (i.e. the ptid/timepoint/key are unique), then we'd expect an error. Maybe this catch is the right place for that.

2020-04-20 19:55 UTC, RosalineP commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
I tested this through and it looks like the reserved field name validation check does catch for if a field name is a duplicate of an existing field name—and it also provides a nice error message rather than silently removing the offending column, which is good. I've removed this bit of code

2020-04-20 20:30 UTC, RosalineP commented on study/src/org/labkey/study/model/DatasetDomainKind.java
> +        }
Cool, I've put it back for now

2020-04-20 21:48 UTC, RosalineP commented on study/src/org/labkey/study/model/DatasetDomainKind.java
>                  throw new IllegalArgumentException("Unable to find a category named : " + categoryName + " in this folder.");
As of last commit (927c8e2) creating a new category with a new dataset is working

2020-04-22 14:23 UTC, cnathe approved these changes

2020-04-24 16:34 UTC, labkey-ankurj commented on study/src/client/DatasetDesigner/DatasetDesigner.tsx
> +                    onComplete={this.onComplete}
added

2020-04-27 14:04 UTC, cnathe commented on study/package.json
> +    "@labkey/components": "0.52.1-fb-datasetDesigner.6"
@labkey-ankurj I have been bumping the other @labkey/components package usages in the platform repo along with this one so that we can get TeamCity to run with all the related modules (i.e. query, core, list, experiment, assay, study).

2020-04-30 16:04 UTC, merged