Fb projects webpart
LabKey/platform pull request #1107
Opened 2020-04-29 01:03 UTC by labkey-matthewb

#### Rationale
Server-side version of "projects" web part.
Projects web part is really slow and on the "welcome" page of many sites, including labkey.org.

2020-05-11 20:22 UTC, cnathe requested changes
I found several issues comparing this implementation with the implementation in develop. I noted those here but will hold off on the rest of the code review until those items / questions are addressed.

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/CoreModule.java
> +                        customize.setScript("(customizeProjectWebpart" + webPart.getRowId()+"||customizeProjectWebpart)(" + webPart.getRowId() + ", " + PageFlowUtil.jsString(webPart.getPageId()) + ",
Is the `||customizeProjectWebpart` part needed here? Looking at the changes in projects.jsp, I don't think we'd ever have a `customizeProjectWebpart()` function to call.

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/CoreModule.java
> +                        customize.setScript("(customizeProjectWebpart" + webPart.getRowId()+"||customizeProjectWebpart)(" + webPart.getRowId() + ", " + PageFlowUtil.jsString(webPart.getPageId()) + ",
Also, there is another usages of this for the subfolder case a few lines down in this file, at line 601, which would need the same change. I tested this by adding the "Subfolders" webpart locally to one of my containers and when going to the Customize option for that webpart, I get a JS error: `ReferenceError: customizeProjectWebpart is not defined`

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +        return;
When I add the Projects webpart to my container and then use the Customize option to change the "Folders to Display" to a specific folder which I know has subfolders, I am getting a rendered webpart that says "No subfolders to display" and it also doesn't let me go back into the Customize dialog (resulting in a JS error). The second issue looks to be because of this return statement. The JSP never ends up adding the JavaScript code to the page because of this. I'm not sure yet what is causing the first issue.

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +    Map<String,String> defaultProperties = Map.of("containerTypes", "project", "containerFilter", "CurrentAndSiblings", "hasCreateButton", "false", "iconSize", "large", "labelPosition", "bottom", "no
There doesn't look to be a usage of the `hasCreateButton` prop. Was that a typo? the original code looks to have a `hideCreateButton` prop which defaults to false, so I assume you meant that here?

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +    var containers = new TableSelector(core.getTable("Containers",cf), Set.of("name","entityId"),filter, (Sort)null).getArrayList(Map.class);
Whenever I customize the projects webpart and select a specific folder other then the current one, I get the "No projects to display" message even when I know that my selected specific folder does have subfolders. Could there be a containerPath property usage missing in this container filter somewhere?

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +                    config['@hideCreateButton'] = '1'; // for spring binding of boolean
Should this use the `config.hideCreateButton` value instead of always hard coding to '1'?

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +                        checked: config.hideCreateButton,
I had created a Projects webpart on develop and customized it for a specific folder, but left that webpart as "unchecked for the hide create button" option. However, when I switch to this fb, the customize dialog shows this "hide create button" as checked, even though the webpart correctly still shows the create button.

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +    var containers = new TableSelector(core.getTable("Containers",cf), Set.of("name","entityId"),filter, (Sort)null).getArrayList(Map.class);
Actually this is the behavior I see for using "Subfolders" at the project level. When I use the "Subfolders" option in a non-project folder, the webpart looks to show itself (which is not what the previous implementation was showing).

2020-05-11 20:22 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +                %><div data-project="<%=projectName%>" style="display: inline-block;" class="thumb-wrap"><div style="width: <%=width%>;" class="tool-icon thumb-wrap thumb-wrap-bottom"><a href="<%=h(c
The previous implementation was showing the DisplayName for a container in this webpart. Now it looks to have been changed to showing the container name, was that an expected change?

2020-05-11 21:04 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +                    config['@hideCreateButton'] = '1'; // for spring binding of boolean
The @ thing is a spring trick for dealing with checkboxes.  Just from the URL you can't tell the difference between input element at all, and an unchecked checkbox.  This tells spring there is a checkbox on the page called hideCreateButton.

2020-05-11 21:05 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +        return;
changed return to else {}

2020-05-11 21:07 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +                %><div data-project="<%=projectName%>" style="display: inline-block;" class="thumb-wrap"><div style="width: <%=width%>;" class="tool-icon thumb-wrap thumb-wrap-bottom"><a href="<%=h(c
Nope, fixed.

2020-05-11 21:37 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +        return;
";" delimter not ","

2020-05-11 21:50 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +                        checked: config.hideCreateButton,
maybe fixed with ==="true" check?

2020-05-11 21:54 UTC, labkey-matthewb commented
Thanks Cory!

2020-05-11 22:34 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +                    config['@hideCreateButton'] = '1'; // for spring binding of boolean
Got it. Cool. Good to know.

2020-05-11 22:35 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +                        checked: config.hideCreateButton,
Yup, looks like that took care of it. Thanks.

2020-05-12 01:36 UTC, cnathe commented
@labkey-matthewb I didn't find and existing tests that use the "Projects" webpart, but there was one that used the "Subfolders" wepbart (SubfolderWebPartTest.java). I ran that test on this fb and it looks like there is one failure: https://teamcity.labkey.org/viewLog.html?buildId=993039&tab=buildResultsDiv&buildTypeId=LabkeyTrunk_DailyPostgres&branch_LabkeyTrunk=projects_webpart

2020-05-12 13:25 UTC, cnathe commented
> @labkey-matthewb I didn't find and existing tests that use the "Projects" webpart, but there was one that used the "Subfolders" wepbart (SubfolderWebPartTest.java). I ran that test on this fb and it looks like there is one failure: https://teamcity.labkey.org/viewLog.html?buildId=993039&tab=buildResultsDiv&buildTypeId=LabkeyTrunk_DailyPostgres&branch_LabkeyTrunk=projects_webpart

SubfolderWebPartTest now passing on this fb on TeamCity

2020-05-12 13:47 UTC, cnathe requested changes

2020-05-12 13:47 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +    containers.sort((m1, m2) -> StringUtils.compareIgnoreCase(String.valueOf(m1.get("name")),String.valueOf(m2.get("name"))));
The previous implementation took into account the sort order of projects/folders and the display name (see code here). This looks to be sorting just by name, was that an intentional change?

```
        sorters: [{
            sorterFn: function(rec1, rec2){
                // Issue 36731: use natural sort for projects webpart to match the nav menu ordering
                var sort1 = rec1.get('SortOrder') + rec1.get('DisplayName');
                var sort2 = rec2.get('SortOrder') + rec2.get('DisplayName');
                return LABKEY.internal.SortUtil.naturalSort(sort1, sort2);
            }
        }],
```

2020-05-12 13:47 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +                StringUtils.equals("Subfolder",noun) && getContainer().hasPermission(getUser(), AdminPermission.class))
If the webpart is configured as a different, specific folder, shouldn't we be using that container for this permissions check instead of the `getContainer()` (i.e. current container)?

2020-05-12 13:47 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +                Container c = getContainer();
Found an issue with this during manual testing. If the webpart is configured to use a different, specific folder then this looks to always use the current container for the path of the create new button instead of that other container (which the previous implementation was doing).

2020-05-12 13:47 UTC, cnathe commented on core/src/org/labkey/core/project/projects.jsp
> +    filter.addClause(new SimpleFilter.SQLClause(new SQLFragment("Name NOT LIKE '\\_%' ESCAPE '\\'")));
Found an issue during manual testing where if I select a specific folder which I know does not have any subfolders and I also check the box for "Include direct children only", the previous implementation would show the "No folders..." message but this shows the selected folder in the webpart. I believe the previous implementation was handling this with the following code in a client side filtering:
```
            //NOTE: path is not directly filterable, so we settle for Client-side filtering
            panel.store.on('load', function () {
                var path = this.containerPath || LABKEY.Security.currentContainer.path;
                this.filterBy(function (rec) {
                    return rec.get('Path') !== path;
                })
            }, null, {single: true});
```

2020-05-12 19:12 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +                StringUtils.equals("Subfolder",noun) && getContainer().hasPermission(getUser(), AdminPermission.class))
Hmm, I think the old code got this wrong too.

2020-05-13 20:07 UTC, cnathe approved these changes

2020-05-13 20:24 UTC, labkey-nicka commented on core/src/org/labkey/core/project/projects.jsp
> +        LABKEY.requiresScript(["Ext4","Ext4ClientApi"], function()
Why switch this to using `LABKEY.requiresScript()` instead of `dependencies.add("Ext4ClientApi")` like it was before?

2020-05-13 20:31 UTC, labkey-nicka commented
I'm just curious, was this slow due to the actual rendering performance or due to the API backing it? If it is the latter, then does this implementation result in a faster page load? Are we trading async waiting time for waiting for full page to load time?

2020-05-13 20:45 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +        LABKEY.requiresScript(["Ext4","Ext4ClientApi"], function()
The answer to this is part of the answer to you next question.  This component pulls a lot of dependencies onto this page.  In the new version, I only pull in the dependency when the customize form is rendered.  I could have also rewritten it to not use Ext4, but it works.

2020-05-13 20:47 UTC, labkey-matthewb commented
> I'm just curious, was this slow due to the actual rendering performance or due to the API backing it? If it is the latter, then does this implementation result in a faster page load? Are we trading async waiting time for waiting for full page to load time?

1) Lots of resource dependencies (Ext4 + others)
2) Async request for continainer info
3) Page re-layout

2020-05-13 20:56 UTC, labkey-nicka commented on core/src/org/labkey/core/project/projects.jsp
> +        LABKEY.requiresScript(["Ext4","Ext4ClientApi"], function()
Alright, I'd still recommend using `dependencies.add("Ext4")` over `LABKEY.requiresScript(`Ext4`)` since we're already in a JSP and support the mechanism.

2020-05-13 21:56 UTC, merged