Change domain form display options
LabKey/platform pull request #1141
Opened 2020-05-05 14:01 UTC by labkey-ankurj

#### Rationale
This PR is to pull ui-components version of domain form display options fix.

#### Related Pull Requests
https://github.com/LabKey/labkey-ui-components/pull/240

2020-05-05 14:06 UTC, cnathe approved these changes

2020-05-05 14:32 UTC, cnathe requested changes

2020-05-05 14:32 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +                            hideAddFieldsButton: true,
Shouldn't this also set `hideTextOptions: true`?

2020-05-05 14:36 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +                            hideAddFieldsButton: true,
it wasn't set to showTextOptions: false before, I don't recall the text options in old gwt editor. I can change if you think we need to hide them.

2020-05-05 21:25 UTC, cnathe commented on core/package-lock.json
> +      "resolved": "http://registry.npmjs.org/rgba-regex/-/rgba-regex-1.0.0.tgz",
@labkey-ankurj  Need to revert this change. It usually can be fixed by clearing the node_modules for core and then rebuilding that module.

2020-05-06 18:24 UTC, cnathe commented on core/package-lock.json
> +      "resolved": "http://registry.npmjs.org/rgba-regex/-/rgba-regex-1.0.0.tgz",
done.

2020-05-06 22:11 UTC, cnathe approved these changes

2020-05-07 15:55 UTC, merged