fix module object leaks
LabKey/platform pull request #1143
Opened 2020-05-05 20:52 UTC by labkey-matthewb

#### Rationale
fix module object leaks due to FolderTypes loading WebParts from modules that may be pruned

#### Changes
* don't call registerFolderType() in Module.init()
* prune modules due to unsupported database earlier

2020-05-06 01:09 UTC, labkey-adam requested changes

2020-05-06 01:09 UTC, labkey-adam commented on api/src/org/labkey/api/module/FolderTypeManager.java
> +            throw new IllegalStateException("Don't call registerFolderType() this early.  It will cause WebPart to get populated from ALL modules");
```suggestion
            throw new IllegalStateException("Don't call registerFolderType() this early; it can cause WebParts to get populated from modules that are about to be pruned");

```

2020-05-06 01:09 UTC, labkey-adam commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        }
Don't you want to remove this check from initialize() now?

2020-05-06 04:02 UTC, labkey-matthewb commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        }
Can't hurt, sure.

2020-05-07 01:23 UTC, labkey-adam approved these changes

2020-05-07 01:24 UTC, merged