Fb dataset designer story4 7205
LabKey/platform pull request #1153
Opened 2020-05-07 19:13 UTC by labkey-ankurj

#### Rationale
This work provides the server side support for dataset creation by importing a file.

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/243

2020-05-08 14:49 UTC, cnathe requested changes
The code change in StudyController looks good, but one change to revert in the core/package.json

2020-05-08 14:49 UTC, cnathe commented on core/package.json
> +    "@labkey/api": "0.2.4",
We don't want to downgrade this @labkey/api (we need it here for the LABKEY var in LK server). Nick bump this to pick up a fix for some automated test failures. Instead, you could pull in 0.2.8 in your @labkey/components package.json to make them match.

2020-05-08 14:52 UTC, labkey-ankurj commented on core/package.json
> +    "@labkey/api": "0.2.4",
no idea how this got changed, will change it back.

2020-05-08 14:53 UTC, cnathe commented on core/package.json
> +    "@labkey/api": "0.2.4",
It probably got reverted during a merge conflict resolution (i.e. merging develop into your fb).

2020-05-08 15:00 UTC, labkey-ankurj commented on core/package.json
> +    "@labkey/api": "0.2.4",
done

2020-05-08 15:01 UTC, labkey-ankurj commented on core/package.json
> +    "@labkey/api": "0.2.4",
I've it in the ui-components package.json, will merge that later.

2020-05-13 19:21 UTC, cnathe approved these changes

2020-05-14 13:27 UTC, merged