Change optionalModules to modules as checkout location
LabKey/platform pull request #1155
Opened 2020-05-07 23:50 UTC by labkey-ians

#### Rationale
Consolidate to server/modules as the preferred location for building module code 

#### Related Pull Requests
https://github.com/LabKey/trialServices/pull/17
https://github.com/LabKey/tnprc_billing/pull/55
https://github.com/LabKey/tnprc_ehr/pull/236
https://github.com/LabKey/premium/pull/187
https://github.com/LabKey/medImmuneFlow/pull/16
https://github.com/LabKey/MaxQuant/pull/24
https://github.com/LabKey/provenance/pull/21
https://github.com/LabKey/cds/pull/269
https://github.com/LabKey/evaluationContent/pull/29
https://github.com/LabKey/PanoramaPremiumModules/pull/29
https://github.com/LabKey/redcap/pull/24
https://github.com/LabKey/scrumtime/pull/57
https://github.com/LabKey/medImmune/pull/66
https://github.com/LabKey/gel/pull/195
https://github.com/LabKey/mobileAppStudy/pull/101
https://github.com/LabKey/harvest/pull/95
https://github.com/LabKey/nlp/pull/160
https://github.com/LabKey/sampleManagement/pull/264
https://github.com/LabKey/complianceActivities/pull/10
https://github.com/LabKey/nci/pull/62
TBD

#### Changes
Update JUnitUtil

2020-05-08 16:59 UTC, labkey-susanh requested changes

2020-05-08 16:59 UTC, labkey-susanh commented on api/src/org/labkey/api/util/JunitUtil.java
> +                        for (java.nio.file.Path path : Arrays.asList(Paths.get("server", "modules")))
WNPRC_EHR has a test/sampledata directory, so I think we will need to keep externalModules in here for now.

2020-05-11 19:42 UTC, labkey-tchad approved these changes

2020-05-12 01:58 UTC, labkey-susanh requested changes
Sorry about this, but since we're now planning to migrate wnprc-modules out of externalModules, we should be able to remove that path from the list of paths.

2020-05-13 15:04 UTC, labkey-susanh approved these changes

2020-05-13 16:32 UTC, merged