Epic 6800 : Issue Definition designer (Story 3)- Issues module implementation
LabKey/platform pull request #1170
Opened 2020-05-13 00:00 UTC by labkey-bpatel

#### Rationale
TODO

#### Related Pull Requests
TODO

#### Changes
- Includes setup of Issues module for react page development
- Includes entrypoint for Issue’s Designer usage
- Includes URL param parsing, loading the existing issue model for edit and navigation on success
- Experimental feature flag
- New issues api actions to getProjectGroups and getUsersForGroup

2020-05-13 21:20 UTC, cnathe commented
@labkey-bpatel Don't forget about items `1.iv` and `4` in the "Setting up a LabKey module doc here: https://github.com/LabKey/platform/blob/develop/webpack/README.md

2020-05-13 22:40 UTC, cnathe requested changes

2020-05-13 22:40 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +                }
This check for `issueListDef == null` and returning the HtmlView should likely stay out of this if/else block. It will still apply for the new designer ui as it is a way to show an error message if the URL param is invalid.

2020-05-13 22:40 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +                String displayText = (group.isProjectGroup() ? "" : "Site:") + group.getName();
I think you previously had a space added after the `Site:` string. It would be nice to put that back in.

2020-05-13 22:40 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +                principal.setUserId(group.getUserId());
Looking at the client side code, I think we only end up using the group id and the displayName. Do you think we need to return the rest of this information?

2020-05-13 22:40 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +                principal.setUserId(group.getUserId());
Alternatively, could we just build up a `List<Group>`'s here and then return that from the API? then I think we could do the displayText part on the client side since the Group object would include the `isProjectGroup` info. That way we could do away with this extra `public static class Principal` class.

2020-05-13 22:40 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +    public static class Principal
these class names seem backwards, isn't this one for a "Group"?

2020-05-13 22:40 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +    public static class UserGroup
these class names seem backwards, isn't this one for a "User/Principal"?

2020-05-13 22:40 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +                            usergrp.setUserName(user.getDisplayName(getUser()));
Similar question as the other response object. Does the client side code use/need all of this? I assume it only cares about the id and displayName.

2020-05-13 22:40 UTC, cnathe commented on issues/src/client/Designer/Designer.tsx
> +    hasDesignIssuesAdminPermission?: boolean
I don't think we need this as I don't think there is a specific permissions class for issue list def admins. I believe it is just a container admin check which we already have on the IssuesController.AdminAction.

2020-05-13 22:40 UTC, cnathe commented on issues/src/client/Designer/Designer.tsx
> +        });
I think this can all be removed as the action requires the permissions and the entryPoint requires admin as well.

2020-05-13 22:40 UTC, cnathe commented on issues/src/client/Designer/Designer.tsx
> +        }
I think this can be removed as well.

2020-05-14 07:14 UTC, labkey-bpatel commented on issues/src/org/labkey/issue/IssuesController.java
> +                }
ah youre right, now fixed

2020-05-14 07:14 UTC, labkey-bpatel commented on issues/src/org/labkey/issue/IssuesController.java
> +                String displayText = (group.isProjectGroup() ? "" : "Site:") + group.getName();
yes! done

2020-05-14 07:15 UTC, labkey-bpatel commented on issues/src/org/labkey/issue/IssuesController.java
> +                principal.setUserId(group.getUserId());
Nope, not needed, I've simplified it now, let me know what you think!

2020-05-14 07:16 UTC, labkey-bpatel commented on issues/src/org/labkey/issue/IssuesController.java
> +    public static class Principal
This class was same as client side Principle model. But its really an overkill, so now removed.

2020-05-14 07:17 UTC, labkey-bpatel commented on issues/src/org/labkey/issue/IssuesController.java
> +    public static class UserGroup
This class was the same as client side's UserGroup - but now removed.

2020-05-14 07:18 UTC, labkey-bpatel commented on issues/src/org/labkey/issue/IssuesController.java
> +                            usergrp.setUserName(user.getDisplayName(getUser()));
nope not needed, please review my updates.

2020-05-14 07:25 UTC, labkey-bpatel commented on issues/src/client/Designer/Designer.tsx
> +    hasDesignIssuesAdminPermission?: boolean
ah, good point, now removed

2020-05-14 07:25 UTC, labkey-bpatel commented on issues/src/client/Designer/Designer.tsx
> +        });
done

2020-05-14 07:25 UTC, labkey-bpatel commented on issues/src/client/Designer/Designer.tsx
> +        }
done

2020-05-14 14:13 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +                principal.setUserId(group.getUserId());
Looks good

2020-05-14 14:14 UTC, cnathe commented on issues/src/org/labkey/issue/IssuesController.java
> +                            usergrp.setUserName(user.getDisplayName(getUser()));
Looks good

2020-05-14 14:15 UTC, cnathe requested changes
Code changes look good. I think the only thing left are those two items missing from the "Setting up a LabKey module" doc for the README file and .gitignore changes: https://github.com/LabKey/platform/blob/develop/webpack/README.md

2020-05-14 19:21 UTC, cnathe approved these changes

2020-05-14 19:46 UTC, merged