Ticket 40464: Consistency on Delete Permissions for Workbooks
LabKey/platform pull request #1180
Opened 2020-05-15 22:47 UTC by bbimber

@labkey-jeckels like we discussed, last year I made a change that made workbooks use the standard container delete pathway.  the problem is that workbooks should require DeletePermission, not AdminPermission.  These changes enforce the right permission based on what's being deleted.  Based on your suggestion, I also changed ContainerType based on your suggestion on the ticket.

Note: I dont know if team city will run tests off this.  i think it will require a branch on the labkey side of the work, but I dont think I can do this.

2020-05-15 22:57 UTC, labkey-jeckels commented
This change looks good to me.

@labkey-tchad can you assist with pointers on the workflow to get this tested on TeamCity? Ideally, if you could capture the sequence in a doc page (or share an existing link) I can follow them. I looked but couldn't find an existing set of guidelines.

2020-05-18 16:49 UTC, labkey-tchad requested changes
A test in `AdminController` needs to be updated:
```
testActionPermissions(org.labkey.core.admin.AdminController$TestCase)
  Should not have permission: user (editor@actionpermission.test), action (org.labkey.core.admin.AdminController$DeleteFolderAction)
  java.lang.AssertionError: Should not have permission: user (editor@actionpermission.test), action (org.labkey.core.admin.AdminController$DeleteFolderAction)
	at org.junit.Assert.fail(Assert.java:88)
	at org.labkey.api.security.permissions.AbstractActionPermissionTest.assertNoPermission(AbstractActionPermissionTest.java:374)
	at org.labkey.api.security.permissions.AbstractActionPermissionTest.assertForAdminPermission(AbstractActionPermissionTest.java:245)
	at org.labkey.api.security.permissions.AbstractActionPermissionTest.assertForAdminPermission(AbstractActionPermissionTest.java:225)
	at org.labkey.core.admin.AdminController$TestCase.testActionPermissions(AdminController.java:10276)
```

2020-05-18 17:33 UTC, bbimber commented
@labkey-tchad thanks trey.  i just added a commit here to fix that.  do i need to explicitly merge my change from bbimber/platform:fb_workbooks into labkey/platform:fb_workbooks?

2020-05-18 18:39 UTC, labkey-tchad commented
I just updated our fb to match yours. We can't do the update via PR because the HEAD on our side needs to be on the same commit for the status checks to show up here.

2020-05-18 18:40 UTC, labkey-tchad approved these changes
Looks good now. The remaining failure has been fixed in develop.

2020-05-18 23:24 UTC, merged