Auto retry after database deadlock
LabKey/platform pull request #1197
Opened 2020-05-20 17:54 UTC by labkey-matthewb

#### Rationale
Although best avoided deadlocks happen, and the correct thing to do is retry.  Here is a simple retry strategy to automatically retry GET requests that deadlock (probably not as common as POST, but it can happen).

2020-05-20 17:55 UTC, labkey-matthewb commented
I had this floating around, what do you guys think?

2020-05-20 20:18 UTC, labkey-kevink requested changes

2020-05-20 20:18 UTC, labkey-kevink commented on api/src/org/labkey/api/action/SpringActionController.java
> +        // ASK the caller to retry^M
```suggestion
        // OK, if we get here with a deadlock exception AND this is a get AND we haven't committed the response yet,
        // ASK the caller to retry

```

2020-05-20 20:18 UTC, labkey-kevink commented on api/src/org/labkey/api/action/SpringActionController.java
> +            if (!request.getQueryString().contains("_retry_=1"))
Since we are in the SpringActionController, can't we get the ViewContext and the ActionURL instead of using the request query string?

2020-05-21 17:49 UTC, labkey-kevink approved these changes

2020-05-21 18:47 UTC, merged