portal cache
LabKey/platform pull request #1221
Opened 2020-05-26 15:11 UTC by labkey-matthewb

#### Rationale
PortalPage and Portal.WebPart are cached, but not immutable.  So, of course, they are muted...  
Made immutable versions and fixed up code that broke.

2020-05-26 15:34 UTC, labkey-adam requested changes
Mostly looks good. Just a few questions.

2020-05-26 15:34 UTC, labkey-adam commented on api/src/org/labkey/api/module/MultiPortalFolderType.java
> +
Can we get rid of all of this migrateLegacyPortalPage() nonsense now? Dave added it 7.5 years ago, unfortunately not as an upgrade step but as a lazy upgrade. I say 7.5 years is long enough... if no one has touched a page in that period of time then no one cares about it and we can remove the migration code. Looks like @labkey-jeckels touched this code as well, so perhaps he has an opinion.

2020-05-26 15:34 UTC, labkey-adam commented on api/src/org/labkey/api/view/Portal.java
> +    public static class WebPart implements Serializable, Factory<WebPart>
I'm sure this would be more invasive, but do we want to make WebPart an interface?

2020-05-26 15:34 UTC, labkey-adam commented on core/src/org/labkey/core/project/projects.jsp
> +<% } /* if webpart */ %>
Isn't this change already pushed in a different PR?

2020-05-26 15:37 UTC, labkey-matthewb commented on api/src/org/labkey/api/module/MultiPortalFolderType.java
> +
I love deleting code, if everyone agrees.

2020-05-26 15:38 UTC, labkey-matthewb commented on api/src/org/labkey/api/view/Portal.java
> +    public static class WebPart implements Serializable, Factory<WebPart>
Well, I had a moment where I was contemplating all the different ways we create read-only objects.  Dual interfaces, Builders/Factories, lock() methods.  And decided not to contemplate too much.  Really I could rename WebPart -> WebPartBuilder, and the anonymous class -> WebPart, and this would be pretty vanilla.

2020-05-26 15:39 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +<% } /* if webpart */ %>
oops

2020-05-26 15:41 UTC, labkey-matthewb commented on api/src/org/labkey/api/view/Portal.java
> +    public static class WebPart implements Serializable, Factory<WebPart>
But more code churn that way.

2020-05-26 15:44 UTC, labkey-matthewb commented on core/src/org/labkey/core/project/projects.jsp
> +<% } /* if webpart */ %>
maybe I forked off that branch, hmmm

2020-05-27 16:39 UTC, labkey-matthewb commented on api/src/org/labkey/api/module/MultiPortalFolderType.java
> +
deleted

2020-05-27 16:40 UTC, labkey-matthewb commented on api/src/org/labkey/api/view/Portal.java
> +    public static class WebPart implements Serializable, Factory<WebPart>
leaving unless you feel strongly.

2020-05-27 17:56 UTC, labkey-adam approved these changes

2020-05-27 18:34 UTC, merged