Fb 38234 automation
LabKey/platform pull request #1222
Opened 2020-05-26 18:33 UTC by labkey-sweta

#### Rationale
1. Adding test coverage for setting dataset default view. ( Issue 38340)
2. Adding test coverage for setting default view for dataset with name and label. (Issue 40502) 

#### Related Pull Requests

#### Changes
New test class added in DailyA

2020-05-27 13:16 UTC, cnathe approved these changes
The test case coverage seems good to me. I made a couple small suggestions. Any reason to get someone from the test team to review as well?

2020-05-27 13:16 UTC, cnathe commented on study/test/src/org/labkey/test/tests/study/StudyDatasetDefaultView.java
> +        checker().verifyTrue("Not the correct default view", isElementPresent(Locator.tagWithText("span", gridName)));
Maybe also add checks for the column changes made to the saved custom view as well (i.e. those columns removed and added in the lines above).

2020-05-27 13:16 UTC, cnathe commented on study/test/src/org/labkey/test/tests/study/StudyDatasetDefaultView.java
> +        importFolderFromZip(TestFileUtils.getSampleData("studies/LabkeyDemoStudy.zip"));
I think there is a version of this `importFolderFromZip` helper that will not validate queries during import. This use case definitely doesn't need to do that query validation steps, so skipping that would speed things up.

2020-06-01 18:43 UTC, labkey-danield approved these changes
Conditional on the extra checks Cory suggested I think this looks ok.

2020-06-04 22:30 UTC, labkey-tchad requested changes

2020-06-04 22:30 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudyDatasetDefaultView.java
> +public class StudyDatasetDefaultView extends BaseWebDriverTest
Test class names should end with "Test"
```suggestion
public class StudyDatasetDefaultViewTest extends BaseWebDriverTest
```

2020-06-10 16:20 UTC, labkey-tchad approved these changes

2020-06-10 16:46 UTC, merged