Fb script processing 6620
LabKey/platform pull request #1224
Opened 2020-05-26 22:53 UTC by labkey-ankurj

#### Rationale
This PR updates the ExpGeneratorHelper to create an experiment run with necessary steps so that provenance service can be utilized to trace the input and output of each operation.

#### Related Pull Requests
*

2020-05-27 17:22 UTC, labkey-jeckels requested changes
Looking good. A handful of suggestions in the comments.

2020-05-27 17:22 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/ProvenanceRecordingParams.java
> +public class ProvenanceRecordingParams implements IsSerializable
IsSerializable is a GWT interface. We shouldn't be introducing new references. I suspect java.io.Serializable is what you want.

2020-05-27 17:22 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/ProvenanceRecordingParams.java
> +    private Map<String, Object> properties = Collections.emptyMap();
Please add comments to indicate what the Strings are intended to be here. LSIDs? GUIDs? Etc.

2020-05-27 17:22 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> + * Also, provides support to record provenance information across LabKey HTTP API calls. - May TBD, 2020
I'm generally not a big fan of logging dates in comments, since the source control history should capture that without the need to fill in TBD values. But if you want to retain, please just use "May 2020" or be sure to fill in a date

2020-05-27 17:22 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> +        return new Lsid(PROVENANCE_PROTOCOL_LSID);
Could we make the variable an Lsid instead of a String to avoid needing to create one every time this method is called?

2020-05-27 17:22 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> +    String startRecording(ViewContext context, JSONObject jsonObject) throws ValidationException;
Consider returning a GUID object instead of a String. It's great to have the JavaDoc indicating the value is a GUID, but having it strongly typed is even better.

2020-05-27 17:22 UTC, labkey-jeckels commented on api/src/org/labkey/api/pipeline/RecordedAction.java
> +    // Provenance map (list of from and to pairs)
Pairs of what - LSIDs? Can we use the Lsid class instead of a String?

2020-05-27 17:22 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        return null;
Generally, better to rethrow the exception instead of returning null. Is there an expected error case where we want to fail and return null?

2020-05-27 17:22 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +            if (log != null)
Consider making the Logger @NotNull, and changing callers to pass in a standard logger to route to labkey.log if we don't have a job or other more specific log file to write to.

2020-05-27 17:22 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +            if (svc != null && apiSaveRowsForm.getJsonObject().has("provenance"))
Can we introduce a no-op ProvenanceService implementation that's registered in the absence of the provenance module so that all callers don't have to do null checks?

2020-05-28 22:59 UTC, labkey-ankurj commented on api/src/org/labkey/api/exp/api/ProvenanceRecordingParams.java
> +public class ProvenanceRecordingParams implements IsSerializable
Replaced

2020-05-28 23:02 UTC, labkey-ankurj commented on api/src/org/labkey/api/exp/api/ProvenanceRecordingParams.java
> +    private Map<String, Object> properties = Collections.emptyMap();
done

2020-05-28 23:04 UTC, labkey-ankurj commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> + * Also, provides support to record provenance information across LabKey HTTP API calls. - May TBD, 2020
removed the date, not sure why I added it in the first place.

2020-05-28 23:08 UTC, labkey-ankurj commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> +        return new Lsid(PROVENANCE_PROTOCOL_LSID);
this method was not being used, removed. Need to append recording Id to this string to create final LSID, so will be leaving this as a String.

2020-05-28 23:09 UTC, labkey-ankurj commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> +    String startRecording(ViewContext context, JSONObject jsonObject) throws ValidationException;
done

2020-05-28 23:10 UTC, labkey-ankurj commented on api/src/org/labkey/api/pipeline/RecordedAction.java
> +    // Provenance map (list of from and to pairs)
updated the comment

2020-05-28 23:20 UTC, labkey-ankurj commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +            if (log != null)
Done

2020-05-29 00:01 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +            if (svc != null && apiSaveRowsForm.getJsonObject().has("provenance"))
Added

2020-05-29 00:09 UTC, labkey-ankurj commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        return null;
done

2020-05-30 21:43 UTC, labkey-jeckels requested changes
Based on our call yesterday, I suspect there are more changes coming here so I'll hold off on approving

2020-05-30 21:43 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> +    void addRecordingStep(HttpServletRequest request, String recordingId, RecordedAction action);
These recordingId values could be GUIDs too, like the return value from startRecording()

2020-05-30 21:43 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/DefaultProvenanceProvider.java
> +public class DefaultProvenanceProvider implements ProvenanceService
Add a comment that this is a no-op implementation.

2020-05-30 21:43 UTC, labkey-jeckels reviewed
One more suggestion

2020-06-01 22:27 UTC, labkey-ankurj commented on api/src/org/labkey/api/exp/api/DefaultProvenanceProvider.java
> +public class DefaultProvenanceProvider implements ProvenanceService
added

2020-06-01 22:27 UTC, labkey-ankurj commented on api/src/org/labkey/api/exp/api/ProvenanceService.java
> +    void addRecordingStep(HttpServletRequest request, String recordingId, RecordedAction action);
done

2020-06-02 15:26 UTC, labkey-jeckels approved these changes

2020-06-03 22:02 UTC, merged