TabBufferedReader, a special BufferedReader subclass that accommodates infer fields
LabKey/platform pull request #1263
Opened 2020-06-03 23:01 UTC by labkey-adam

#### Rationale
`TabLoader` uses `BufferedReader.mark(int)` to read data for inferring column data types, then `BufferedReader.reset()` to back up and actually import the data. `mark(int)` specifies the buffer size and `BufferedReader` allocates the entire buffer upfront and never resizes it, which restricts our ability to infer a large number of rows, since every import incurs the cost of a large buffer. `TabBufferedReader` addresses this limitation and provides more flexibility. It starts with a relatively small read-ahead buffer (currently 1M characters) and grows it as needed, the goal being to accommodate inferring and importing very large tables while using low memory footprint for smaller tables.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/1244
* https://github.com/LabKey/platform/pull/1257

2020-06-03 23:04 UTC, labkey-adam commented
Not a lot of new code, but this deserves some real scrutiny on the code review.

2020-06-04 00:02 UTC, labkey-matthewb requested changes
I think you can accomplish this without the reflection with clever use of the existing public methods.  The catch would seem to be that BufferedReader doesn't have any sort of getPosition() so you need to keep track of that (or cheat and reflect for that field).  See https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/ExtendedBufferedReader.java.html

2020-06-04 00:02 UTC, labkey-matthewb commented on api/src/org/labkey/api/reader/TabBufferedReader.java
> +    private boolean ensureBuffer()
Could this manipulation of internal field values be accomplished by using the public methods?  E.g. to grow the buffer
reset(); // get back to mark
mark(targetBufferSize); // growbuffer
skip(backToWhereWeWere); // continue on...

2020-06-04 00:02 UTC, labkey-matthewb commented on api/src/org/labkey/api/reader/TabBufferedReader.java
> +    public String readLine() throws IOException
Does this class need to override other read() methods?  Maybe they are safe, but first thought is that they should be overridden or throw Unsupported.

2020-06-04 00:12 UTC, labkey-adam commented on api/src/org/labkey/api/reader/TabBufferedReader.java
> +    public String readLine() throws IOException
It's not meant to be a general purpose replacement for BufferedReader, so yes, probably should. skip() as well.

2020-06-04 00:29 UTC, labkey-adam commented on api/src/org/labkey/api/reader/TabBufferedReader.java
> +    private boolean ensureBuffer()
This is exactly what my first attempt did. That grows the buffer (a bit less efficiently), but the problem is I don't see a way to reliably count characters (including all line terminators) without either reflection or duplicating a lot of BufferedReader. Once I'm using reflection to get the character count I might as well set the buffer size use reflection as well.

2020-06-04 00:40 UTC, labkey-adam commented
I don't see a way to count characters consumed inside of readLine() without reflection... but if you do, I'm all for it.

2020-06-04 00:55 UTC, labkey-matthewb commented on api/src/org/labkey/api/reader/TabBufferedReader.java
> +    private boolean ensureBuffer()
Yeah, that's why I mentioned ExtendedBufferedReader, it tracks position.

2020-06-04 02:00 UTC, labkey-adam commented on api/src/org/labkey/api/reader/TabBufferedReader.java
> +    private boolean ensureBuffer()
That class tracks position if you call read(), but not readLine(), which is what TabLoader uses. We could roll our own readLine and count characters, but there's a lot of stuff in there and of course it manipulates all the same private members.

2020-06-04 02:37 UTC, labkey-jeckels commented
Since Matt's already jumped in, I am not planning to do a separate review here. Let me know if I'd be useful to break a tie or do a full independent review.

2020-06-09 00:51 UTC, labkey-matthewb approved these changes

2020-06-09 00:59 UTC, merged