Issue 39840: Not prompting user about file overwrite when uploading multiple files
LabKey/platform pull request #1295
Opened 2020-06-09 22:42 UTC by XingY

#### Rationale
Overwrite has been set to true to silently overwrite when there is >1 files uploaded. This was probably due to tech difficulty in getting Ext.Msg box, which is a singleton, to show multiple instances at once.  Since user might be uploading a very large number of files with many many duplicates, we don't want to prompt file by file anyways. 

#### Related Pull Requests
* 

#### Changes
* change made to NOT set overwrite to true by default when uploading multiple files
* prompt for one or multiple files overwrite in a single dialog

2020-06-09 22:55 UTC, labkey-nicka requested changes

2020-06-09 22:55 UTC, labkey-nicka commented on filecontent/webapp/File/panel/Upload.js
> +                            msg += "</url>";
What is `</url>`? Did you mean `</ul>`?

2020-06-09 22:55 UTC, labkey-nicka commented on filecontent/webapp/File/panel/Upload.js
> +                            msg += "</url>";
Same about `</url>`.

2020-06-09 22:55 UTC, labkey-nicka commented on filecontent/webapp/File/panel/Upload.js
> +                                msg += "<li>" + f.name + "</li>"
I'm forgetting my `Ext4` but should this be:

```js
msg += "<li>" + Ext4.htmlEncode(f.name) + "</li>";
```

Same question for other HTML string concatenation in this change.

2020-06-09 22:55 UTC, labkey-nicka commented on filecontent/webapp/File/panel/Upload.js
> +                            else if (file.errorText === 'Already exists') {
nit: Basing the error processing of the error message is fragile. Is there a specific HTTP status that the server responds with in this case? I realize this was already being done for the "Drag-and-drop upload" but just thought I'd mention it.

2020-06-09 23:18 UTC, XingY commented on filecontent/webapp/File/panel/Upload.js
> +                            msg += "</url>";
yep..

2020-06-10 05:47 UTC, labkey-nicka approved these changes

2020-09-15 23:13 UTC, labkey-tchad commented
@XingY I'm sorry for sitting on this for so long. Can I merge `develop` into this branch or do we want to try to get it into 20.7?

2020-09-16 03:16 UTC, XingY commented
> @XingY I'm sorry for sitting on this for so long. Can I merge `develop` into this branch or do we want to try to get it into 20.7?

merge develop is probably fine. Doesn't sound like the client needed it urgently.

2021-06-17 20:45 UTC, merged