support for provenance in query apis
LabKey/platform pull request #1299
Opened 2020-06-11 19:49 UTC by labkey-klum

#### Rationale
We want to be able to pass in provenance related information to a subset of our query APIs (insert, update, delete) to allow them to participate in a provenance recording and contribute provenance mappings that will show up in the provenance run.

[master specification](https://docs.google.com/document/d/1AM7gm80JUq9iHpu529vNwPYA6KDl57oxY1zVMKlAMlU/edit#)

#### Related Pull Requests

#### Changes
- Moved the code responsible for handling provenance recording params into the BaseSaveRowsAction.

2020-06-15 16:27 UTC, labkey-ankurj requested changes
looks good, one comment.

2020-06-15 16:27 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +                            JSONArray jsonRows = json.getJSONArray("rows");
I guess this will throw exception if 'rows' is not an array.

2020-06-16 19:32 UTC, labkey-klum commented on query/src/org/labkey/query/controllers/QueryController.java
> +                            JSONArray jsonRows = json.getJSONArray("rows");
done

2020-06-17 15:56 UTC, labkey-ankurj approved these changes

2020-06-18 00:14 UTC, merged