Issue 40659: Security fixes for vulnerabilities found in security scan report
LabKey/platform pull request #1317
Opened 2020-06-18 01:16 UTC by labkey-ankurj

#### Rationale
This PR addresses the security concerns mentioned in this issue https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=40659

#### Related Pull Requests
* TBD

#### Changes
* Update jQuery versions
* mark email in cookie as secure
* rel="noopener" in site footer to avoid phishing attacks
* remove ext js index.html to avoid mixed content over http

2020-06-18 22:26 UTC, labkey-jeckels requested changes

2020-06-18 22:26 UTC, labkey-jeckels commented on core/src/org/labkey/core/login/LoginController.java
> +
As discussed, let's handle this in the JS code that is the only spot that deals with the cookie right now.

server/modules/platform/core/webapp/login.js

and only set it to be secure if the page is an "https://" URL

2020-06-18 22:29 UTC, labkey-ankurj commented on core/src/org/labkey/core/login/LoginController.java
> +
Done

2020-06-19 18:30 UTC, labkey-jeckels requested changes
Please also check for other places in the code where we create links with target="_blank". It should be safe to always add the new attribute, but it's only required when we target some external server (not a link to another page on the same server)  For example, I found one in server/modules/platform/core/src/org/labkey/core/admin/customizeEmail.jsp

We should also make our link rendering inject this in server/modules/platform/api/src/org/labkey/api/data/DataColumn.java, server/modules/platform/api/src/org/labkey/api/data/SimpleDisplayColumn.java, and server/modules/platform/api/src/org/labkey/api/data/DataRegion.java in their renderGridCellContents() methods.

2020-06-19 18:30 UTC, labkey-jeckels commented on api/webapp/clientapi/core/Utils.js
> +            if (name === "email" && window.location.href.startsWith("https")) {
To be extra cautious, do a .toLowerCase() here

2020-06-19 18:30 UTC, labkey-jeckels commented on core/resources/views/_footer.html
> +    <a href="http://labkey.com" target="_blank" rel="noopener">Powered by LabKey</a>
Let's make this https instead of http

2020-06-19 18:30 UTC, labkey-jeckels commented on core/resources/views/_footer.html
> +    <a href="http://labkey.com" target="_blank" rel="noopener">Powered by LabKey</a>
Also, looks like this should be "noopener noreferrer". https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

2020-06-19 19:41 UTC, labkey-ankurj commented
> Please also check for other places in the code where we create links with target="_blank". It should be safe to always add the new attribute, but it's only required when we target some external server (not a link to another page on the same server) For example, I found one in server/modules/platform/core/src/org/labkey/core/admin/customizeEmail.jsp
> 
> We should also make our link rendering inject this in server/modules/platform/api/src/org/labkey/api/data/DataColumn.java, server/modules/platform/api/src/org/labkey/api/data/SimpleDisplayColumn.java, and server/modules/platform/api/src/org/labkey/api/data/DataRegion.java in their renderGridCellContents() methods.

Aren't the urls in renderGridCellContents of these classes targeting the same server?

2020-06-19 20:02 UTC, labkey-jeckels commented
99% of the time, yes, but they can be external URLs too, like http://foo.com/path?id=${RowId}

2020-06-22 18:18 UTC, labkey-jeckels approved these changes
Three more tiny changes, but I'll make it as approved

2020-06-22 18:18 UTC, labkey-jeckels commented on api/webapp/clientapi/core/Utils.js
> +            if (name.toLowerCase() === "email" && window.location.href.startsWith("https")) {
I was intending for the lower casing to be on window.location.href, not the cookie name

2020-06-22 18:18 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/DataColumn.java
> +                out.write("\" rel=\"noopener noreferrer\"");
One more tweak - let's only do this when we have a target window

2020-06-22 18:18 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/SimpleDisplayColumn.java
> +            out.write("' rel='noopener noreferrer'");
Same here -  let's only do this when we have a target window

2020-06-22 23:41 UTC, merged