Issue 40415: Server JavaScript Console not displaying trigger messages fired by ETL
LabKey/platform pull request #1318
Opened 2020-06-18 15:31 UTC by labkey-martyp

#### Rationale
Update SessionAppender to store appender infos for cross thread access.  This is to allow trigger script console messages triggered from an ETL pipeline job to use the same appender info as the current view context.

#### Related Pull Requests
TBD

#### Changes
Add register mechanism to save appender infos to concurrent map.  Add functions to get appender info by key and to set the current thread's appender info to an already existing appender info.

2020-06-18 19:22 UTC, labkey-matthewb requested changes

2020-06-18 19:22 UTC, labkey-matthewb commented on api/src/org/labkey/api/util/SessionAppender.java
> +    private static final Map<String, AppenderInfo> appenderInfos = new ConcurrentCaseInsensitiveSortedMap<>();
Roaches check in, but they don't check out!

This needs to use some sort of WeakHashMap, or a SessionListener to remove AppendInfo that are associated with sessions that have gone away.

2020-06-19 14:27 UTC, labkey-martyp commented on api/src/org/labkey/api/util/SessionAppender.java
> +    private static final Map<String, AppenderInfo> appenderInfos = new ConcurrentCaseInsensitiveSortedMap<>();
Dang, yes forgot the cleanup on this.  I went with a ConcurrentReferenceMap which is essentially a concurrent WeakHashMap.

2020-06-19 16:37 UTC, labkey-matthewb requested changes

2020-06-19 16:37 UTC, labkey-matthewb commented on api/src/org/labkey/api/util/SessionAppender.java
> +    private static final Map<String, AppenderInfo> appenderInfos = new ConcurrentReferenceHashMap<>();
What a great class.  You should probably specify ReferenceType.WEAK, instead of the default ReferenceType.SOFT.

2020-06-19 16:42 UTC, labkey-matthewb commented on api/src/org/labkey/api/util/SessionAppender.java
> +    private static final Map<String, AppenderInfo> appenderInfos = new ConcurrentReferenceHashMap<>();
Also, probably worth a comment explaining how/when the cleanup should work.  e.g. References to the SessionAppender should go away when the session is destroyed allowing the ConcurrentReferenceHashMap to release the entry.

2020-06-22 14:09 UTC, labkey-martyp commented on api/src/org/labkey/api/util/SessionAppender.java
> +    private static final Map<String, AppenderInfo> appenderInfos = new ConcurrentReferenceHashMap<>();
Oh yeah, I missed that was a soft reference by default. Specified to WEAK reference and added a comment about garbage collection on it.

2020-06-22 16:12 UTC, labkey-matthewb approved these changes

2020-06-22 16:52 UTC, merged