Epic 5886 : ODBC for hosted clients
LabKey/platform pull request #1330
Opened 2020-06-23 01:33 UTC by labkey-bpatel

#### Rationale
Part of offering ODBC connectivity to our hosted customers is to give end-user access to the configured certificate.

#### Related Pull Requests
https://github.com/LabKey/connectors/pull/34

#### Changes
- Add External Tool View Service and Provider infrastructure
- Decouple APIKey view from SecurityController.ApiKeyAction to APIKeyProvider.
- Refactor ApiKeyAction to iterate through External Tool Providers.
- Decouple user navigation piece ('Done' button) from the individual view rendering.

2020-06-23 02:17 UTC, labkey-jeckels approved these changes
Let me know if you want further review, but otherwise one simple comment and don't forget the TODOs about JavaDocs

2020-06-23 02:17 UTC, labkey-jeckels commented on core/src/org/labkey/core/security/SecurityController.java
> +            //TODO: this is no longer shown, should this message be part of the view or silently just not display because user does not have the access?
Let's replace with a "Nothing enabled" page if somebody gets here but no providers are active for them

2020-06-23 08:40 UTC, labkey-bpatel commented on core/src/org/labkey/core/security/SecurityController.java
> +            //TODO: this is no longer shown, should this message be part of the view or silently just not display because user does not have the access?
Done!

2020-06-23 15:27 UTC, labkey-jeckels requested changes
Another set of suggestions, hopefully the last on this side of the PR

2020-06-23 15:27 UTC, labkey-jeckels commented on core/src/org/labkey/core/security/SecurityController.java
> +            if (view.isEmpty())
We should rename this action - it's no longer just for ApiKeys

2020-06-23 15:27 UTC, labkey-jeckels commented on core/src/org/labkey/core/security/nothingEnabled.jsp
> +Nothing enabled
Sorry, I didn't literally mean to just show "nothing enabled". Let's rephrase to be a bit more user-friendly. How about:

This server does not have any configurations enabled that show settings here. An administrator can configure tool access via the Admin Console.

2020-06-23 15:27 UTC, labkey-jeckels commented on api/src/org/labkey/api/view/PopupUserView.java
> +        return getContextContainer().hasPermission(user, ReadPermission.class);
Is this quite right? Seems like the current user will always have read permission on the current container if the page is being rendered, and if ODBC is off and API keys aren't enabled, they'll get the page that tells them nothing is available.

Seems like we should check to see if any views would be shown to the user, and if not, omit the menu item.

2020-06-23 22:35 UTC, labkey-bpatel commented on core/src/org/labkey/core/security/nothingEnabled.jsp
> +Nothing enabled
Haha yes, sorry i meant to ask you if we needed anything more user-friendly. Thanks for the text.

2020-06-23 23:07 UTC, labkey-bpatel commented on core/src/org/labkey/core/security/SecurityController.java
> +            if (view.isEmpty())
Yes, good point! Action now renamed.

2020-06-24 00:04 UTC, labkey-bpatel commented on api/src/org/labkey/api/view/PopupUserView.java
> +        return getContextContainer().hasPermission(user, ReadPermission.class);
Since all the readers get odbc view at minimum, not too clear what the check should be to omit the menu item altogether, (and if odbc is disabled then its just not configured and so will get nothingEnabled page). So not clear on what the criteria is to for a user not to get external tool provider views.

2020-06-24 00:11 UTC, labkey-jeckels commented on api/src/org/labkey/api/view/PopupUserView.java
> +        return getContextContainer().hasPermission(user, ReadPermission.class);
Not all deployments will have the Connectors module, and API keys aren't enabled by default.

There's no harm in showing them a blank page, of course, but it's a useless bit of menu clutter in those cases.

2020-06-24 01:55 UTC, labkey-bpatel commented on api/src/org/labkey/api/view/PopupUserView.java
> +        return getContextContainer().hasPermission(user, ReadPermission.class);
Done, let me know what you think!

2020-06-24 16:49 UTC, labkey-jeckels approved these changes
One more tiny tweak, but otherwise ready to merge so I'm approving the PR

2020-06-24 16:49 UTC, labkey-jeckels commented on core/src/org/labkey/core/security/SecurityController.java
> +        public ActionURL getExternalToolsViewURL(User user, @NotNull URLHelper returnURL)
Let's annotate this as @Nullable, and consider this set!

2020-06-30 21:53 UTC, merged