issue37736
LabKey/platform pull request #1335
Opened 2020-06-23 21:08 UTC by labkey-chrisj

#### Rationale
This adds a very quick test to address issue#37736, which provides coverage to ensure that the create project wizard highlights steps along the way

#### Related Pull Requests
(related pr in testAutomation)

#### Changes

2020-06-23 23:56 UTC, labkey-tchad requested changes
This doesn't cover the regression that spawned this test.

2020-06-23 23:56 UTC, labkey-tchad commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +@Category({Git.class})
This should go in the community `Daily` suite. The `Git` suite is for premium functionality

2020-06-23 23:56 UTC, labkey-tchad commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +        new BodyWebPart(getDriver(), "Messages");
You only get these webparts if the `wiki` and `announcements` modules are installed. We should avoid imposing unnecessary requirements to allow testing as wide a variety of servers as possible. Sample Manager trial doesn't have them for instance.

2020-06-23 23:56 UTC, labkey-tchad commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +        new BodyWebPart(getDriver(), "Subfolders");
Don't assume that the `BodyWebPart` constructor will actually find the webpart; it might get refactored to not do so at some point. Just grab the actual titles and verify that they contain what you want.
```suggestion
        assertThat("WebParts for collaboration folder type.", new PortalHelper().getWebPartTitles(), hasItem("Subfolders"))
```
_Sidenote: the thought of this is the sort of pattern is what makes me worry about helpers that return `null` or `-1` when something isn't found._

2020-06-23 23:56 UTC, labkey-tchad commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +                .clickFinish();
This doesn't cover the regression described in the [related issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=37736). The problem was cosmetic. This should go step by step and check that the correct step is highlighted and has the correct text.

2020-06-24 00:00 UTC, labkey-jeckels commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +@Category({Git.class})
@labkey-tchad  This is out of scope for this PR, but sounds like we should rename the Git suite sometime soon...

2020-06-24 00:27 UTC, labkey-chrisj commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +        new BodyWebPart(getDriver(), "Subfolders");
Huh.  Didn't realize getWebPartTitles() existed, thanks for pointing it out

2020-06-24 00:29 UTC, labkey-chrisj commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +                .clickFinish();
I was relying on the waitForPage methods in SetFolderPermissionsPage and SetInitialFolderSettingsPage to check that- and the former does- but only for synchronization purposes (it's been timing out without raising errors for a long time now).
I'm updating the pages with waitForPage() methods that will verify the active list item along the way, and raise errors if they aren't there (or more to the point, they won't sit there waiting to time out without treating that like a problem)

2020-06-24 00:30 UTC, labkey-chrisj commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +@Category({Git.class})
Okay, I just put it in platform because that's where the fix went.

2020-06-24 00:43 UTC, labkey-chrisj commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +                .clickFinish();
If you'd prefer, I can rip those checks out of the pages and put them in the test.

2020-06-24 04:21 UTC, labkey-tchad commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +                .clickFinish();
I vote to rip them out of the pages and put them in the test. There's no reason to have dozens of tests start failing if this regresses again.
I thought I'd seen tests pausing a bit too long on one of the wizard steps. Good to know that will be cleared up with this as well.

2020-06-24 05:56 UTC, labkey-tchad approved these changes

2020-06-24 15:32 UTC, labkey-chrisj commented on core/test/src/org/labkey/test/tests/ProjectWizardTest.java
> +                .clickFinish();
Okay, that's how this will go, then

2020-06-24 21:01 UTC, merged