Issue 40510: promote inputs to the run
LabKey/platform pull request #1343
Opened 2020-06-25 18:22 UTC by labkey-ankurj

#### Rationale
Experiment run can be created by provenance recording apis with inputs and outputs attached to the recording steps. This work promotes the inputs of a step that are not attached to the run and are not outputs of the previous step.

2020-06-25 19:54 UTC, labkey-jeckels requested changes

2020-06-25 19:54 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +                if (!runDataInputs.contains(dataFile.getURI().toString()) && !prevAction.getInputs().contains(dataFile))
This doesn't feel right. Isn't it a mismatch with LSID and URI?

2020-06-26 01:13 UTC, labkey-ankurj commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +                if (!runDataInputs.contains(dataFile.getURI().toString()) && !prevAction.getInputs().contains(dataFile))
yes, fixed it.

2020-06-26 23:49 UTC, labkey-jeckels requested changes

2020-06-26 23:49 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +        Collection<Map<String, Object>> containerData = new TableSelector(ExperimentService.get().getTinfoData(), Set.of(lsid, datafileurl)).getMapCollection();
This will pull in ALL exp.data rows, correct? On some servers that's hundreds of thousands or maybe even millions. And not all will have a DataFileURL, which means they would NPE in the forEach below. Can we filter to those in this container? Or that have a URL or LSID that matches the ones we're processing in this run?

2020-06-26 23:56 UTC, labkey-ankurj commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +        Collection<Map<String, Object>> containerData = new TableSelector(ExperimentService.get().getTinfoData(), Set.of(lsid, datafileurl)).getMapCollection();
would this filter work?
```
SimpleFilter filter = SimpleFilter.createContainerFilter(container);
filter.addCondition(FieldKey.fromParts(datafileurl), null, CompareType.NONBLANK);
```

2020-06-27 00:00 UTC, labkey-ankurj commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +        Collection<Map<String, Object>> containerData = new TableSelector(ExperimentService.get().getTinfoData(), Set.of(lsid, datafileurl)).getMapCollection();
Or that have a URL or LSID that matches the ones we're processing in this run? -- to create this filter is it okay to query multiple times?

2020-06-27 00:07 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +        Collection<Map<String, Object>> containerData = new TableSelector(ExperimentService.get().getTinfoData(), Set.of(lsid, datafileurl)).getMapCollection();
Your filter would definitely help, and I think still match the ones you need.

But I think it would be safe to do a series of queries for the individual rows that you need in this case. There should be a modest number of data or material objects attached to a given run, so it shouldn't be a real perf concern, and eliminates the concern about potentially pulling tons of rows into memory.

2020-06-27 00:54 UTC, labkey-jeckels requested changes

2020-06-27 00:54 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +                filter.addCondition(FieldKey.fromString(datafileurl), dataFile.getURI().toString(), CompareType.EQUAL);
It looks like you're accumulating filters here. The first time through the loop, it'll match, but all subsequent times won't match because you'll have DataFileURL = X AND DataFileURL = Y, which will never match any rows. If you push the filter creation inside the loop, it should be OK. And LSID should never be null, so that filter isn't strictly necessary.

2020-06-29 16:33 UTC, labkey-ankurj commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +                filter.addCondition(FieldKey.fromString(datafileurl), dataFile.getURI().toString(), CompareType.EQUAL);
I think the latest commit is fixed
![Screen Shot 2020-06-29 at 9 30 19 AM](https://user-images.githubusercontent.com/39965420/86031992-82bb7d80-b9eb-11ea-9557-ee28e46d25e5.png)

2020-06-29 16:39 UTC, labkey-jeckels approved these changes
One question to double-check

2020-06-29 16:39 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/pipeline/ExpGeneratorHelper.java
> +                filter.addCondition(FieldKey.fromString(datafileurl), dataFile.getURI().toString(), CompareType.EQUAL);
Step 3 isn't supposed to have any outputs? Probably OK, just not sure about the test case.

2020-06-29 16:40 UTC, labkey-ankurj commented
> One question to double-check

Yes, I did not add outputs in step 3.

2020-06-29 20:37 UTC, merged