Make participant list height dynamic
LabKey/platform pull request #1348
Opened 2020-06-27 00:04 UTC by RosalineP

#### Rationale
It was requested that the participant list right-hand display panel dynamically grow to fit its result contents, rather than a hard 470px.

#### Related Pull Requests
* N/A

#### Changes
* Remove height limitation of 470px

2020-06-29 14:58 UTC, cnathe reviewed
I don't know the full context of this change, but just an FYI that this change affects both the narrow "Participant List" webpart and the left/main "Participant List" webpart. Also note that if a study has a large number of subjects (say > 1000) this webpart will now grow vertically to fit ALL subjects on the screen. This could result in a very very tall page with a lot of white space.

2020-06-29 17:50 UTC, RosalineP commented
Good point on the fact this also applies to the webpart! I sent a message with more context on this issue to hopefully work something out.

2020-06-29 19:12 UTC, cnathe requested changes

2020-06-29 19:12 UTC, cnathe commented on study/src/org/labkey/study/view/subjects.jsp
> +    Boolean isParticipantsListPage = param != null && param.equals("study.PARTICIPANTS");
I recommend just using the constant from StudyFolderTabs.ParticipantsPage:
```suggestion
    boolean isParticipantsListPage = StudyFolderTabs.ParticipantsPage.PAGE_ID.equalsIgnoreCase(param);
```

2020-06-29 19:12 UTC, cnathe commented on study/src/org/labkey/study/view/subjects.jsp
> +                <div style="<%=conditionalStyling%>" id="<%= listDivId %>"></div>
I'd imagine that IntelliJ is complaining about this being "unsafe" (i.e. red squiggles):
```suggestion
                <div style="<%=h(conditionalStyling)%>" id="<%= listDivId %>"></div>
```

2020-07-01 18:19 UTC, RosalineP commented on study/src/org/labkey/study/view/subjects.jsp
> +                <div style="<%=conditionalStyling%>" id="<%= listDivId %>"></div>
Oddly not... 
![image](https://user-images.githubusercontent.com/18537731/86278088-a833bd00-bb8c-11ea-9d21-2f5fbd8b6abc.png)
Thank you for the reminder, though!

2020-07-01 18:57 UTC, cnathe approved these changes

2020-07-02 20:45 UTC, labkey-adam approved these changes

2020-07-07 20:38 UTC, merged