Fb validator reference
LabKey/platform pull request #1355
Opened 2020-06-30 20:10 UTC by labkey-matthewb

#### Rationale
Remove unnecessary table exp.validatorreference.  This m-m junction table has caused deadlocks and is unnecessary.  Also be consistent about always providing WHERE clauses to use the PK (container,propertyid,rowid)

2020-06-30 23:50 UTC, labkey-jeckels requested changes
Couple of schema nits

2020-06-30 23:50 UTC, labkey-jeckels commented on experiment/resources/schemas/dbscripts/sqlserver/exp-20.006-20.007.sql
> +    Expression   text,
I think we should be using NVARCHAR, and NVARCHAR(MAX) instead of TEXT

2020-06-30 23:50 UTC, labkey-jeckels commented on experiment/resources/schemas/dbscripts/sqlserver/exp-20.006-20.007.sql
> +    PropertyId   int not null constraint fk_pv_descriptor references exp.propertydescriptor,
Indices on Container and PropertyId?

2020-07-01 00:44 UTC, labkey-matthewb commented on experiment/resources/schemas/dbscripts/sqlserver/exp-20.006-20.007.sql
> +    PropertyId   int not null constraint fk_pv_descriptor references exp.propertydescriptor,
This is as it was previously. I was wondering if we really need the propertyid constraint, or should add an index.  container should be fine because of the PK.

2020-07-01 18:43 UTC, labkey-jeckels approved these changes

2020-07-01 18:43 UTC, labkey-jeckels commented on experiment/resources/schemas/dbscripts/sqlserver/exp-20.006-20.007.sql
> +    PropertyId   int not null constraint fk_pv_descriptor references exp.propertydescriptor,
My heuristic is that if it needs a FK, it probably needs an index too, but these will be small tables so no big deal. I think the NVARCHAR comment is relevant regardless (maybe you're already swapping that one)

2020-08-19 19:31 UTC, merged