Item 7490: Upgrade to Log4J 2 - Part 1
LabKey/platform pull request #1378
Opened 2020-07-08 23:15 UTC by labkey-ankurj

#### Rationale
This PR is the starting point towards the effort to upgrade our logging to log4j2. After the code review of this branch, we will not merge this branch in develop. For the next part of the work, a new branch will be created from this branch and pull request from the new branch to this branch will be created and code review for that story and merge it back. This will keep on happening until we are done and then this original branch will be merged to develop. Let me know if someone has suggestion for an easier approach.

#### Related Pull Requests
* TBD

#### Changes
Shorter version:
* ```org.apache.log4j.Logger.getLogger()``` --> ```org.apache.logging.log4j.LogManager.getLogger()```
* ```org.apache.log4j``` --> ```org.apache.logging.log4j```

2020-07-08 23:17 UTC, labkey-ankurj commented
The builds and teamcity tests will fail as the build.gradle which is in SVN will not be checked in until the work is complete.

2020-07-08 23:31 UTC, labkey-adam commented
In the past, I've added conditionals to the (svn-based) build.gradle file to keep it working with both develop and my branch. And then I remove the conditionals after I finally merge to develop. In my case, I was conditionalizing on the presence of the assay module, but you could conditionalize on something else: https://svn.mgt.labkey.host/stedi/trunk/server/build.gradle/?p=64176

2020-07-09 00:55 UTC, labkey-ankurj commented
> In the past, I've added conditionals to the (svn-based) build.gradle file to keep it working with both develop and my branch. And then I remove the conditionals after I finally merge to develop. In my case, I was conditionalizing on the presence of the assay module, but you could conditionalize on something else: https://svn.mgt.labkey.host/stedi/trunk/server/build.gradle/?p=64176

There is more to that, the gradle plugin needs to read the changed log4j.xml (which is also in SVN).

2020-07-09 13:37 UTC, labkey-susanh commented
> > In the past, I've added conditionals to the (svn-based) build.gradle file to keep it working with both develop and my branch. And then I remove the conditionals after I finally merge to develop. In my case, I was conditionalizing on the presence of the assay module, but you could conditionalize on something else: https://svn.mgt.labkey.host/stedi/trunk/server/build.gradle/?p=64176
> 
> There is more to that, the gradle plugin needs to read the changed log4j.xml (which is also in SVN).

We can make a short-term change to the plugin to pick up a different log4j.xml based on, say, the presence of some property if that makes things easier, but since you're having to change all the import paths for log4j, I'm not seeing a clear way to have both log4j options available based on some property or other without a lot of extra work.

2020-07-10 18:57 UTC, labkey-jeckels reviewed
I guess I'll hold the final approval until it's ready to merge?

2020-07-10 18:57 UTC, labkey-jeckels commented on core/src/org/labkey/core/CoreController.java
> +            for (int i=0; i < 4000; i++)
Do we get value from having this many threads? 4000 is quite a stress test. Just calling randomSentence() directly in the for loop seems like it would be fine

2020-07-10 18:57 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/MXBeanAppender.java
> +@Plugin(name = "SessionAppender", category = "Core", elementType = "appender", printObject = true)
Looks like name was copy/pasted, should probably be MXBeanAppender?

2020-07-10 18:57 UTC, labkey-jeckels commented on core/src/org/labkey/core/admin/AdminController.java
> +                // TODO - find replacement - maybe a ThreadLocal using a WeakHashMap of Event->EventId?
Is this on the list for the next story?

2020-07-28 00:47 UTC, labkey-martyp requested changes
Tested out both ETL and data entry methods for SessionAppender and they look good.

Not sure if you saw my comments here.  That eventIdMap in the SessionAppender is accessible by muliple threads so should be thread safe.
https://github.com/LabKey/platform/pull/1423

2020-07-28 00:50 UTC, labkey-martyp commented
Also tutorialModules repo has some build issues with these changes, not sure if that is coming in another round of updates

2020-07-28 00:54 UTC, labkey-ankurj commented
> Tested out both ETL and data entry methods for SessionAppender and they look good.
> 
> Not sure if you saw my comments here. That eventIdMap in the SessionAppender is accessible by muliple threads so should be thread safe.
> #1423

Here you go: https://github.com/LabKey/platform/pull/1378/commits/45f909b18c7dbf4a9e9dc01d3c1119dcebf07fd6. I pushed the changes in closed branch.

2020-07-28 00:54 UTC, labkey-ankurj commented
> Also tutorialModules repo has some build issues with these changes, not sure if that is coming in another round of updates

thanks for letting me know. I have not upgraded log4j in tutorialModules, will check it out as well.

2020-07-28 00:57 UTC, labkey-martyp approved these changes

2020-08-05 01:17 UTC, labkey-jeckels requested changes

2020-08-05 01:17 UTC, labkey-jeckels commented on api/src/org/labkey/api/pipeline/PipelineJob.java
> +            String formattedDate = new SimpleDateFormat("dd MMM yyyy HH:mm:ss,SSS").format(new Date());
Don't create a new date format for every invocation - use DateUtil.formatDateTime() which caches and uses a thread-safe implementation

2020-08-05 02:03 UTC, labkey-jeckels approved these changes

2020-08-05 19:54 UTC, merged