Item 7554: part 2 of log4jupgrade
LabKey/platform pull request #1423
Opened 2020-07-22 17:19 UTC by labkey-ankurj

#### Rationale
This is part two of log4j upgrade work, includes changes to custom appenders, event id handling for server javascript console and admin logging UI changes

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/1378

2020-07-22 17:43 UTC, labkey-jeckels requested changes

2020-07-22 17:43 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/SafeFileAppender.java
> +        if (logEvent.getLevel().compareTo(Level.DEBUG) == 0)
Can these use equals() instead of compareTo()?

And while we seldom use it, this is missing the TRACE level

2020-07-22 17:43 UTC, labkey-jeckels commented on core/src/org/labkey/core/admin/AdminController.java
> +            Map<LogEvent, String> events = SessionAppender.getLoggingEvents(getViewContext().getRequest());
@labkey-martyp if you haven't already looked at this, can you make sure that it doesn't break the ETL logging scenario that you recently worked on?

2020-07-22 21:56 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/SafeFileAppender.java
> +        if (logEvent.getLevel().compareTo(Level.DEBUG) == 0)
Should I add the trace level (It wasn't there earlier.)? Are there pipeline jobs that have the trace logging.

2020-07-22 22:00 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/SafeFileAppender.java
> +        if (logEvent.getLevel().compareTo(Level.DEBUG) == 0)
Here is old code in Pipeline.java
![Screen Shot 2020-07-22 at 3 00 18 PM](https://user-images.githubusercontent.com/39965420/88233234-22a3aa00-cc2c-11ea-86d4-3869fbaa03e7.png)

2020-07-22 22:51 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/SafeFileAppender.java
> +        if (logEvent.getLevel().compareTo(Level.DEBUG) == 0)
OK, but let's make the new code better than the old. :)

2020-07-22 22:52 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/SafeFileAppender.java
> +        if (logEvent.getLevel().compareTo(Level.DEBUG) == 0)
I doubt anyone's using trace now (since it doesn't work, apparently), but let's support it. I added trace level logging for some of the recent ODBC work, so I think there are legit use cases within our codebase

2020-07-22 22:55 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/SafeFileAppender.java
> +        if (logEvent.getLevel().compareTo(Level.DEBUG) == 0)
sounds good, added it.

2020-07-22 23:00 UTC, labkey-jeckels approved these changes
Looks good, but let's wait for Marty confirm on the JS console logging for the ETL scenario if you haven't already connected

2020-07-24 16:12 UTC, labkey-jeckels requested changes

2020-07-24 16:12 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/LoggerWriter.java
> +    void write(String message, @Nullable Throwable t);
dumpThreads() is only calling a single method, so I think this interface could much simpler:

void debug(String message)

or you call call it write() if that feels better. I don't expect we'll need to add other log levels in the future since it's such a targeted use case

2020-07-24 16:12 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/FileLoggerWriter.java
> +        NetworkDrive.exists(file);
Since we only have a single use case, I recommend having the constructor open the BufferedWriter, adding a close() method, and calling it after all of the write() calls are done. That will make it so that you don't have to keep opening and closing the file for every line that gets written

2020-07-24 16:23 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/LoggerWriter.java
> +    void write(String message, @Nullable Throwable t);
there is a call to DbScope.logCurrentConnectionState at DebugInfoDumper.dumpThreads (L282) which uses info, call to ConnectionWrapper.dumpOpenConnections at (L290) which uses debug and call to ConnectionWrapper.dumpLeaksForThread (L272) which uses error.

2020-07-24 16:56 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/LoggerWriter.java
> +    void write(String message, @Nullable Throwable t);
Indeed. I'm not sure that the debug/error split is all that compelling, but given the differentiation let's stick with your approach.

2020-07-24 20:10 UTC, labkey-jeckels approved these changes

2020-07-27 04:46 UTC, labkey-martyp requested changes
Sorry, my delay getting to this probably got your branches out of sync with develop.  I'm having difficulty getting this to build and looks like its not building on TC. Let me know if I can be any help fixing the build, but assume you can do it a lot quicker for this branch.

2020-07-27 04:46 UTC, labkey-martyp commented on api/src/org/labkey/api/util/SessionAppender.java
> +    private static ThreadLocal<WeakHashMap<LogEvent, String>> _eventIds = new ThreadLocal<>();
Is this being used?

2020-07-27 04:46 UTC, labkey-martyp commented on api/src/org/labkey/api/util/SessionAppender.java
> +        final Map<LogEvent, String> eventIdMap = new WeakHashMap<>();
I think this should probably be a ConcurrentReferenceHashMap.  These can be accessed from multiple threads, so that will at least make the map operations thread safe.  See appenderInfos implementation of that map type

2020-07-27 04:46 UTC, labkey-martyp commented on api/src/org/labkey/api/util/SessionAppender.java
> +                info.eventIdMap.remove(0);
This is something I should have fixed, but would probably be safer to override the put() function of that map with this check.

2020-07-27 04:46 UTC, labkey-martyp commented on api/src/org/labkey/api/util/SessionAppender.java
> +        final Map<LogEvent, String> eventIdMap = new WeakHashMap<>();
Possibly something like this?  Still not great to just randomly remove index(0) but not sure how to get the eldest entry without using a LinkedHashMap, which does not have a weak reference option.

```suggestion
        final Map<LogEvent, String> eventIdMap = new ConcurrentReferenceHashMap<>(16, ConcurrentReferenceHashMap.ReferenceType.WEAK)
        {
            @Override
            public String put(LogEvent key, String value)
            {
                // Safeguard against runaway size. ConcurrentReferenceHashMap does not have removeEldestEntry so have  
                // to randomly remove an entry
                if (size() > 1000)
                    remove(0);

                return super.put(key, value);
            }
        };
```

2020-07-27 04:46 UTC, labkey-martyp commented on api/src/org/labkey/api/util/SessionAppender.java
> +                info.eventIdMap.remove(0);
See suggestion above

2020-07-27 18:47 UTC, merged