add pipeline status details page test helper
LabKey/platform pull request #1431
Opened 2020-07-28 16:45 UTC by labkey-kevink

#### Rationale
- fix S3FileRootMigrationTest: support s3 cloud status files in StatusDetailsBean
- fix RedCapTest: find expected errors in log text

#### Related Pull Requests
*

2020-07-28 17:44 UTC, labkey-jeckels requested changes

2020-07-28 17:44 UTC, labkey-jeckels commented on pipeline/src/org/labkey/pipeline/status/FileDisplayColumn.java
> +        if (Files.exists(parent))
We need a variant of NetworkDrive.exists() that takes a Path, so that we do the mounting of the drive if required on Windows.

2020-07-28 19:00 UTC, labkey-kevink commented on pipeline/src/org/labkey/pipeline/status/FileDisplayColumn.java
> +        if (Files.exists(parent))
Done

2020-07-28 19:30 UTC, labkey-adam commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +            <pre class="labkey-log-text <%=h(logTextClass(record))%>"
I have a slight preference for making `logTextClass()` return HtmlString and then directly outputting that return value (pushing the encoding assertion to where the content is generated), but this is fine since we're all in the same JSP file.

2020-07-28 19:34 UTC, labkey-adam approved these changes
Josh should probably re-review the Path/ensure() changes, but looks good to me.

2020-07-29 00:09 UTC, labkey-jeckels approved these changes

2020-07-29 00:12 UTC, merged