Item 7629: Redesign of Error page
LabKey/platform pull request #1518
Opened 2020-08-26 22:03 UTC by labkey-ankurj

#### Rationale
This work is to update the current error page for LabKey server. We will address modern UI/UX patterns with error page content. This will improve the user experience in the events of errors by smoother transitions from the error page to a guided LabKey server page.

2020-08-27 00:02 UTC, labkey-ankurj commented on api/src/org/labkey/api/view/template/PageConfig.java
> +        Error;
note to self - remove Error

2020-08-27 00:03 UTC, labkey-ankurj commented on core/src/client/entryPoints.js
> +    // },
note to self - put these back

2020-09-03 14:46 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorType.tsx
> +    <>
Cory, I know you told me to just have string constants here but I thought of keeping them like this because of different pieces of text and links in some. Let me know if I should make a component for each of them and pass props or sth else.

2020-09-03 17:39 UTC, labkey-jeckels requested changes

2020-09-03 17:39 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +            renderer.setErrorType(ErrorRenderer.ErrorType.execution);
Similar to how we default to a particular responseStatus in handleException() and then update it for certain kinds of exceptions (NotFoundException sets it to a 404, UnauthorizedException sets it to SC_UNAUTHORIZED or SC_FORBIDDEN), choose the appropriate errorType as we go and then use it down here.

2020-09-04 19:06 UTC, cnathe requested changes
I reviewed the client side pieces of this PR. I'll defer on the server side stuff to Josh/Nick.

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +    <>
Yeah, if they have links and other non-text items in them, then leaving them as-is makes sense. It looks like the SUBHEADING constants are just text, so I would likely change those.

2020-09-04 19:06 UTC, cnathe commented on api/src/org/labkey/api/util/ErrorRenderer.java
> +    // TODO: ErrorPage use these in React app
Is this a TODO or just a comment saying that the React component uses them? Just curious what is the TODO here.

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +export class ErrorHandler extends React.Component<ErrorHandlerProps, ErrorHandlerState> {
use React.PureComponent

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +    loadBack = (): void => {
this function name confused me, what is the `load` part about? could it be renamed to something like `goBack` or `onBackClick`?

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +    loadViewDetails = (): void => {
same question here about the use of `load` in the function name, should this be named `onViewDetailsClick` or something along those lines?

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +            If you would like to file a <a href="#"> LabKey support ticket</a>, your unique reference code is:
I assume these hrefs will be filled in with the next story? If so, I'd add a TODO somewhere here about this.

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +);
After thinking about what we discussed the other day for these consts and looking at the enum below. What do you think about putting the headings and instructions into a single object? That way they could be accessed with a single line instead of a switch / ifelse. Something like this:
```
const ERROR_TYPE_INFO = {
   general: {heading: ..., instruction: ...},
   permission:  {heading: ..., instruction: ...},
   ...
};

ERROR_TYPE_INFO[errorType].heading
```

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +export const getImage = (errorType: ErrorType): ReactNode => {
If we went the route of putting the error type heading and instructions into a single object, I'd put the image string in there as well. Then all of these functions would be much simpler (i.e. `getImage`, `getSubHeading`, `getInstruction `).

```
export const getImage = (errorType: ErrorType): ReactNode => {
   const path = ERROR_TYPE_INFO[errorType].heading; // probably want to add a check to make sure errorType exists in the ERROR_TYPE_INFO
   return <img alt="LabKey Error" src={imageURL('_images', path)} />;
};
```

2020-09-04 19:06 UTC, cnathe commented on core/src/client/ErrorHandler/dev.tsx
> +}
@labkey-nicka Rosaline mentioned in her PR for the module editor case (which is also using the App.registerApp approach), that these lines weren't needed for the HMR to work. I haven't tried it, just an FYI.

2020-09-04 19:06 UTC, cnathe commented on core/src/client/components/ErrorTopSection.tsx
> +                <Row className="panel-body">
seems a bit odd to put the `panel-body` class on a `Row`. Should this be wrapped in a `Panel` or div and that class be applied there?

2020-09-04 19:06 UTC, cnathe commented on core/src/client/components/ErrorTopSection.tsx
> +                    <Col md={1} />
I'm curious why the `<Col md={1} />` on the left and right sides? Is that just to make the display area narrower?

2020-09-04 19:06 UTC, cnathe commented on core/src/client/entryPoints.js
> +        generateLib: true
could add a quick comment here saying where this lib is used:
```suggestion
        generateLib: true // used in errorView.jsp
```

2020-09-04 19:06 UTC, cnathe commented on core/src/client/entryPoints.js
> +        permission: 'admin',
I assume this permission isn't actually used in the `generateLib` case and can be removed. That permission is used in the views/*.xml files but this error page will have permissions controlled elsewhere.

2020-09-08 21:01 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/ErrorRenderer.java
> +    // TODO: ErrorPage use these in React app
That's a TODO, I am keeping the TODOs for this story consistent with format // TODO: ErrorPage so that they'd be searchable in next story. The todo here is to use/ remove these booleans from the old error view into new error page.

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +    loadBack = (): void => {
sure

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +    loadViewDetails = (): void => {
sure

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorType.tsx
> +);
Yes, I think this looks cleaner.

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorType.tsx
> +export const getImage = (errorType: ErrorType): ReactNode => {
done

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorType.tsx
> +            If you would like to file a <a href="#"> LabKey support ticket</a>, your unique reference code is:
added

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/components/ErrorTopSection.tsx
> +                <Row className="panel-body">
yes, done.

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/components/ErrorTopSection.tsx
> +                    <Col md={1} />
I guess I added because invision has a wider view, but after removing this it looks better. Thanks.

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/entryPoints.js
> +        permission: 'admin',
removed

2020-09-08 21:01 UTC, labkey-ankurj commented on core/src/client/entryPoints.js
> +        generateLib: true
added

2020-09-09 15:27 UTC, cnathe approved these changes
Approving React / client side related code changes.

2020-09-10 00:24 UTC, labkey-jeckels requested changes

2020-09-10 00:24 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +                    log.error("Global.handleException", e);
Seems like we should log exc too

2020-09-10 00:24 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +        else if (AppProps.getInstance().isExperimentalFeatureEnabled(AppProps.EXPERIMENTAL_ERROR_PAGE))
This method is already ridiculously long. Can you pull this out into a separate method that's called from here?

2020-09-10 00:24 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +        SearchService ss, Logger log, @Nullable ViewContext context, @Nullable PageConfig pageConfig)
It looks like pageConfig is only used to get the template, correct? If so, consider switching to take that as an argument since I'm not sure we want to carry all of the other config into the error page.

Also, did you see if you could call HttpView.hasCurrentView() and then HttpView.currentContext() instead of passing ViewContext here?

2020-09-10 23:09 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +        SearchService ss, Logger log, @Nullable ViewContext context, @Nullable PageConfig pageConfig)
PageConfig is used to get template and also to create the template. I think it is required here. 

On the ViewContext part, yes I am able to use HttpView.currentContext().

2020-09-10 23:09 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +        else if (AppProps.getInstance().isExperimentalFeatureEnabled(AppProps.EXPERIMENTAL_ERROR_PAGE))
sure

2020-09-10 23:09 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +                    log.error("Global.handleException", e);
OK

2020-09-11 01:02 UTC, labkey-jeckels approved these changes

2020-09-14 15:59 UTC, merged