7627: Module Editor Story 2
LabKey/platform pull request #1531
Opened 2020-08-31 06:40 UTC by RosalineP

#### Rationale
We surface links to the new Module Editor page in the UI.

#### Related Pull Requests
* https://github.com/LabKey/moduleEditor/pull/9

#### Changes
* Adds module editor link in Developer Links dropdown
* Adds module editor link from Known Modules page
* Resolves ModuleEditor permissions-related TODO

2020-08-31 13:22 UTC, cnathe commented
@RosalineP should the PR name be referring to "Story 3" instead of 2?

2020-09-02 15:33 UTC, cnathe requested changes

2020-09-02 15:33 UTC, cnathe commented on api/src/org/labkey/api/reports/report/ModuleReportDescriptor.java
> +            errors.add(new SimpleValidationError("You must possess ModuleEditorRole to edit module resources."));
I believe we usually leave the perm/role names out of these types of error messages and say something like "You do not have permissions to edit module resources on this server."

2020-09-02 15:33 UTC, cnathe commented on core/src/org/labkey/core/admin/AdminController.java
> +                String linkText = AppProps.getInstance().isDevMode() ? "Edit module" : "Update module";
It looks like the only place that is calling this `getModuleEditorLink` method is already doing the `isDevMode()` check so I think we can just set the linkText to "Edit module" here.

2020-09-02 15:33 UTC, cnathe commented on core/src/org/labkey/core/admin/AdminController.java
> +            return url;
```suggestion
            return ModuleEditorService.get().getModuleEditorURL(name);
```

2020-09-02 22:53 UTC, RosalineP commented on core/src/org/labkey/core/admin/AdminController.java
> +                String linkText = AppProps.getInstance().isDevMode() ? "Edit module" : "Update module";
Oop. Thank you for catching—the text is supposed to say 'Edit module' if LK is in dev mode, and 'Update module' otherwise, as per the spec. I've updated the code accordingly in the last push.

2020-09-03 13:28 UTC, cnathe requested changes
Still one question about the `Edit module` vs `Update module case`.

2020-09-03 13:28 UTC, cnathe commented on core/src/org/labkey/core/admin/AdminController.java
> +                String linkText = AppProps.getInstance().isDevMode() ? "Edit module" : "Update module";
So is the link target going to go to a different page / action than in the non-dev mode case? Or is it just the text of the link that changes? I assume the former, but from the code in this PR it looks like both will still just go to the module editor URL. Should the code that was removed below for the "Update Module" case be called to get the `getUpdateURL()`?

2020-09-04 21:34 UTC, RosalineP commented on core/src/org/labkey/core/admin/AdminController.java
> +                                !AppProps.getInstance().isDevMode() ? null : TD(cl("labkey-column-header"),""),    // edit actions
This was reordered because it looks peculiar when there are empty columns on either side of a generally populated column

2020-09-08 14:09 UTC, cnathe approved these changes

2020-09-08 16:36 UTC, merged