41280: Expose new permissions : DeleteUserPermission and UpdateUserPermission
LabKey/platform pull request #1532
Opened 2020-08-31 15:54 UTC by labkey-klum

#### Rationale
As a follow on to this [change](https://github.com/LabKey/platform/pull/1496), for completeness sake we build on the AddUserPermission and introduce
- DeleteUserPermission
- UpdateUserPermission

In addition, to help with external development of admin security roles, we've introduced a listener to allow the automatic addition of registered permissions to admin roles.

#### Related Pull Requests
https://github.com/LabKey/platform/pull/1496

#### Changes
- add new permissions
- update instances of UserManagementPermission to check for either DeleteUserPermission or UpdateUserPermission where appropriate
- assign new permissions to AppAdminRole
- add AdminRoleListener and RoleManager.addAdminRoleListener

2020-09-02 15:24 UTC, cnathe requested changes
In addition to comments added to the changed files, I found a user in UsersTable.java which we might want to update to use the specific add / delete users perm checks:

```
        if (schema.getUser().hasRootPermission(UserManagementPermission.class))
        {
            setDeleteURL(new DetailsURL(new ActionURL(UserController.DeleteUsersAction.class, schema.getContainer())));
            setInsertURL(new DetailsURL(new ActionURL(SecurityController.AddUsersAction.class, schema.getContainer())));
        }
```

Also, the `PipelineController.java` and `ShowGroupMambersAction.java` classes both look to have a `UserManagementPermissions` check that looks to be related to an add user case.

2020-09-02 15:24 UTC, cnathe commented on api/src/org/labkey/api/security/AuthenticationManager.java
> +        boolean isUserManager = userManager.hasRootPermission(UpdateUserPermission.class);
Very minor, but since we aren't using `UserManagementPermission` here anymore, might be worth changing the variable names: `userMangaer` -> `user`, `isUserManager` -> `canUpdateUser`

2020-09-02 15:24 UTC, cnathe commented on core/src/org/labkey/core/security/SecurityApiActions.java
> +    @RequiresPermission(UpdateUserPermission.class)
Looking at the `SecurityApiActions.TestCase` it looks like there are some asserts that will need to be updated for the `@RequiresPermission(UserManagementPermission.class)` changes.

2020-09-02 15:24 UTC, cnathe commented on core/src/org/labkey/core/security/SecurityController.java
> +    @RequiresPermission(UpdateUserPermission.class)
Just above this action, there is another related action `ShowResetEmailAction`, should the requires permission check there be updated to use `UpdateUserPermission` as well?

2020-09-02 15:24 UTC, cnathe commented on core/src/org/labkey/core/user/UserController.java
> +            boolean isUserManager = getUser().hasRootPermission(UpdateUserPermission.class);
Another minor case where it might be worth changing the variable name to `canUpdateUser`

2020-09-02 15:24 UTC, cnathe commented on core/src/org/labkey/core/user/UserController.java
>      public class DeleteUsersAction extends FormViewAction<UserIdForm>
There is another action in this controller which I think should be updated: `UpdateUsersStateApiAction`. It does both de/reactive changes and deletions, so should likely be changed to something like `@RequiresAllOf({UpdateUserPermission.class, DeleteUserPermission.class})`

2020-09-02 15:24 UTC, cnathe commented on core/src/org/labkey/core/user/changeEmail.jsp
> +    boolean isUserManager = getUser().hasRootPermission(UpdateUserPermission.class);
change `isUserManager` variable name?

2020-09-02 15:24 UTC, cnathe commented on core/src/org/labkey/core/user/changeEmail.jsp
> +<%@ page import="org.labkey.api.security.permissions.UpdateUserPermission" %>
can the `UserManagementPermission` import above be removed?

2020-09-02 17:25 UTC, labkey-adam commented
It's possible (though not likely, honestly) that the old permission (UserManagementPermission) is serialized for webpart permissions in the database and/or folder archives. If you want, you can address this by implementing getSerializationAliases(), e.g., on UpdateUserPermission. See DesignSampleTypePermission as a random example of this.

2020-09-03 18:17 UTC, labkey-klum commented on core/src/org/labkey/core/security/SecurityApiActions.java
> +    @RequiresPermission(UpdateUserPermission.class)
I agree that the method name is no longer accurate and could be changed to something like : assertForUserPermissions but the test still should pass since application admins will have all of the new permissions. Were you noticing something different?

2020-09-03 18:27 UTC, cnathe commented on core/src/org/labkey/core/security/SecurityApiActions.java
> +    @RequiresPermission(UpdateUserPermission.class)
Ah yes, that's right. I forgot how those assert checks worked. Looking at it closer, that makes sense.

2020-09-03 18:57 UTC, cnathe approved these changes

2020-09-08 15:29 UTC, merged