Issue 41150: ETL - Columns with spaces in name are being nulled out when not in src query
LabKey/platform pull request #1561
Opened 2020-09-14 02:45 UTC by labkey-martyp

#### Rationale
Columns with spaces in name are getting nulled out if not in source query of an ETL.  Currently comparing sql selector with column names when determining what columns not to update.  Need to compare names to names.

#### Changes
Update StatementUtils.createStatement, Base Table Insert section.  Store col and value sql fragments in map with column name as key so comparison of column names can be done when skipping updates to columns in _dontUpdateColumnNames.

2020-09-14 16:40 UTC, labkey-matthewb requested changes

2020-09-14 16:40 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/StatementUtils.java
> +        Map<String, SQLFragment> values = new HashMap<>();
It's not a good assumption that cols.values() and values.values() will return items in the same order.  I would consider changing "List<SQLFragment> cols"  to "List<ColumnInfo> cols" instead.  You could use LinkedHashMap<> but I don't really see the point in using the Map<>.

2020-09-14 17:12 UTC, labkey-martyp commented on api/src/org/labkey/api/data/StatementUtils.java
> +        Map<String, SQLFragment> values = new HashMap<>();
@labkey-matthewb 
I wasn't thinking order would matter here but I have seen pretty small changes in order make big changes in performance on queries, so that makes sense.

What is the suggestion here? "I would consider changing "List cols" to "List cols" instead."

Really the whole point of the map is just because we need the column name (not SQLFragment) to see if it exists in _dontUpdateColumnNames (line 840).  I could make a third list to hold column names but thought converting cols and values to maps would be a little more concrete than relying on indexes aligning across three lists.

2020-09-14 17:40 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/StatementUtils.java
> +        Map<String, SQLFragment> values = new HashMap<>();
Sorry, apparently angle brakets means something in markup (see comment source).  That was List of ColumnInfo instead of List of SQLFragment.  It's not a performance thing, but the order of column in the INSERT clause must match the order of columns in the SELECT clause.  I don't think you're really using the Map functionality you're just tracking both the "name" and the "selectnam", you could just carry around the ColumnInfo which also tracks the "name" and "selectname".

2020-09-14 19:40 UTC, labkey-martyp commented on api/src/org/labkey/api/data/StatementUtils.java
> +        Map<String, SQLFragment> values = new HashMap<>();
Got it. Good call. Updated to use List<ColumnInfo>

2020-09-15 16:39 UTC, labkey-matthewb requested changes

2020-09-15 16:39 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/StatementUtils.java
> +                FieldKey fk = new FieldKey(null, colSql.getSQL());
I think this can now be `fk = col.getFieldKey()` which is much better than the original code!

2020-09-15 17:15 UTC, labkey-matthewb approved these changes
Nice cleanup, thanks Marty.

2020-09-15 21:31 UTC, merged