7857: Apply moduleEditor feedback
LabKey/platform pull request #1576
Opened 2020-09-18 01:04 UTC by RosalineP

#### Rationale
On Known Modules page, 'Edit Module' link should only be shown if moduleEditor is not included in the build, or if the relevant module is not editable.

#### Related Pull Requests
* 

#### Changes
* Add helper function to DefaultModule
* Add checks for moduleEditor's existence and module validity before displaying 'Edit Module' link

2020-09-18 01:19 UTC, RosalineP commented on core/src/org/labkey/core/admin/AdminController.java
> +                                    boolean modIsValid = (module instanceof DefaultModule) && ((DefaultModule) module).isValidSourceDirectory();
@labkey-matthewb 
This looked like the correct checks to invoke based off of your comments on the ModuleEditor spec regarding when to allow editing of module resources. Happy to make any fixes if I've misapprehended anything or if there are additional gates to include when determining if a module is editable or not!

2020-09-18 17:25 UTC, labkey-matthewb requested changes

2020-09-18 17:25 UTC, labkey-matthewb commented on core/src/org/labkey/core/admin/AdminController.java
> +                                    boolean modIsValid = (module instanceof DefaultModule) && ((DefaultModule) module).isValidSourceDirectory();
This logic shouldn't be scattered around the product, it should be centralized in ModuleEditorService.  Presumably null != ModuleService.getModuleEditorURL() should be accurate.

2020-09-21 20:00 UTC, RosalineP commented on core/src/org/labkey/core/admin/AdminController.java
> +                                    boolean modIsValid = (module instanceof DefaultModule) && ((DefaultModule) module).isValidSourceDirectory();
Hopefully addressed as per offline gChat convo.

2020-09-21 20:07 UTC, labkey-matthewb requested changes

2020-09-21 20:07 UTC, labkey-matthewb commented on core/src/org/labkey/core/admin/AdminController.java
> +                                    boolean modIsValid = (module instanceof DefaultModule) && ((DefaultModule) module).isValidSourceDirectory();
Doesn't address the original comment however.  Presumably getModuleEditorURL() is correctly determining if this module can be edited and what the URL should be.  Why second guess that code???  Just check != null.

2020-09-21 21:53 UTC, RosalineP commented on core/src/org/labkey/core/admin/AdminController.java
> +                                    boolean modIsValid = (module instanceof DefaultModule) && ((DefaultModule) module).isValidSourceDirectory();
Ah, the intention of the `isValidSourceDirectory()` check goes back to a comment you made on the ModuleEditor spec (under the 'Open questions' section) regarding when to allow editing of module resources—you mention that we should allow editing if we have a valid source directory, and to take a look at logic implemented in `computeResourceDirectory()` for that. I thought that this was what you were referring to when you mention in the Issue opened that if a module isn't editable, the link to the ModuleEditor shouldn't appear.

2020-09-24 19:56 UTC, labkey-matthewb approved these changes

2020-09-24 23:45 UTC, merged