Item 7767: View details section of ErrorPage Redesign - Story 2
LabKey/platform pull request #1589
Opened 2020-09-22 22:07 UTC by labkey-ankurj

#### Rationale
This is the continued work of error page redesign.

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/346

#### Changes
* View details section on Error Page

2020-09-24 20:04 UTC, cnathe requested changes
Just some quick comments. I'll do a more thorough code review after manual testing.

2020-09-24 20:04 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +        this.setState({ showDetails: !showDetails });
You'll want to use the state at the time of the callback.
```suggestion
        this.setState((state) => ({ showDetails: !state.showDetails }));
```

2020-09-24 20:04 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +                                <button className="btn btn-info error-backButton" onClick={this.onBackClick}>
I know the mockups had this as the bootstrap blue "info" button, but we should stick to our standard button classes and let our core scss (which will hopefully remove some of the bootstrap overrides in the future).
```suggestion
                                <button className="btn btn-primary error-backButton" onClick={this.onBackClick}>
```

2020-09-24 20:04 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +            issue.
Does anyone know if this text has been reviewed by the support team? Looking at [this page](https://www.labkey.org/home/Support/project-begin.view?), it looks like the response time of community forum posts is "as time allows". Ankur, if you haven't chatted with the support team and reviewed these pages with them yet, I'm happy to do so.

2020-09-24 20:04 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +                    href="https://www.labkey.org/Support%20Tickets/wiki-edit.view?"
wiki-edit.view? that can't be the right place to send them, is it? I would expect any of the support related links would just go to this URL: https://www.labkey.org/home/Support/project-begin.view?

2020-09-24 20:36 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorType.tsx
> +            issue.
I asked the services team around the wording of config exception in the specs, but haven't heard back. Yes, it'd be great if you don't mind chatting with the team. Thanks.

2020-09-24 20:41 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorType.tsx
> +                    href="https://www.labkey.org/Support%20Tickets/wiki-edit.view?"
I found that link in the specs to linked to filing a ticket. I can update if that is not correct.

2020-09-24 22:30 UTC, labkey-jeckels commented on core/src/client/ErrorHandler/ErrorType.tsx
> +                    href="https://www.labkey.org/Support%20Tickets/wiki-edit.view?"
It's definitely not the right spot. I just send an invite for a meeting next week to get this and other text finalized.

2020-09-28 19:48 UTC, cnathe requested changes

2020-09-28 19:48 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.spec.tsx
> +        expect(wrapper.find('.error-details-container')).toHaveLength(0);
is there some header text / element  that we can check based on the `errorType`? Just checking that `error-details-container` isn't visible until after the state change is more of a check of the view details button and not the error type differences.

2020-09-28 19:48 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.spec.tsx
> +        expect(question.text().startsWith('What went wrong?')).toBeTruthy();
any way we can also check for the `message` from the ErrorDetails context somewhere in this test case too?

2020-09-28 19:48 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.spec.tsx
> +            errorType: ErrorType.configuration,
similar comment as above, this test case is the same as the above one in what things it is checking for even though the `errorType` is different. It would be good to check more about the error type changes in these cases if possible.

2020-09-28 19:48 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +        const viewDetailsBtnText = !showDetails ? this._hideDetails : this._viewDetails;
I would probably just move this if/else logic to the button text display instead of stashing it in state. We already have the `showDetails` state variable we can use for that button text display.

2020-09-28 19:48 UTC, cnathe commented on core/src/org/labkey/core/webdav/DavController.java
> +import org.labkey.api.util.*;
was this change to the `*` import intentional or just something that IntelliJ did for you?

2020-09-28 19:48 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +        {getServerContext().impersonatingUser !== undefined && (
It would be good to get some jest tests for the various different displays here for the permissions error with and without the impersonate user.

2020-09-28 20:49 UTC, labkey-nicka commented
@labkey-ankurj I've closed the related `@labkey/components` PR so this branch can just update to the latest version of that package (which might result in no diff from develop).

2020-09-28 21:22 UTC, labkey-nicka requested changes
I'd like to discuss the different usages of `ErrorView` and see if we can consolidate them so that the implementation that is specific to the view isn't the callers responsibility.

2020-09-28 21:22 UTC, labkey-nicka commented on core/src/org/labkey/core/webdav/DavController.java
> +            ErrorRenderer renderer = ExceptionUtil.getErrorRenderer(HttpServletResponse.SC_BAD_REQUEST, message, x, getViewContext().getRequest(), false, false);
I'm curious why we switch to error view here? The `sendMessage` function is intended to handle how the error response is configured. We don't want to return an HTML view when the response is requested as JSON.

2020-09-28 21:22 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                ErrorRenderer renderer = ExceptionUtil.getErrorRenderer(HttpServletResponse.SC_BAD_REQUEST, "Failed to convert to Excel - invalid input", e, getViewContext().getRequest(), false, fals
Expecting JSON?

2020-09-28 21:22 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                ErrorRenderer renderer = ExceptionUtil.getErrorRenderer(HttpServletResponse.SC_BAD_REQUEST, "Failed to convert to table - invalid input", e, getViewContext().getRequest(), false, fals
Expecting JSON?

2020-09-29 17:44 UTC, labkey-ankurj commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +    public static void renderErrorView(ViewContext context, PageConfig pageConfig, ErrorRenderer.ErrorType errorType, int responseStatus, String message, @Nullable Throwable ex, boolean isPart, boole
@labkey-nicka added this method

2020-09-29 17:44 UTC, labkey-ankurj commented on core/src/org/labkey/core/webdav/DavController.java
> +                    else if (CONTENT_TYPE_HTML.equals(getRequest().getHeader("Content-Type)")) ||
@labkey-nicka Let me know if this looks right. I tried to test through the URL link that you showed yesterday and it renders the error page in browser since the content type is text/html but returns json when apt content type is passed in the request. 
![Screen Shot 2020-09-29 at 10 43 03 AM](https://user-images.githubusercontent.com/39965420/94596223-b3a48c00-0240-11eb-8c8e-f6daedfa31be.png)

2020-09-29 19:26 UTC, labkey-nicka requested changes

2020-09-29 19:26 UTC, labkey-nicka commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +    public static void renderErrorView(ViewContext context, PageConfig pageConfig, ErrorRenderer.ErrorType errorType, int responseStatus, String message, @Nullable Throwable ex, boolean isPart, boole
Very nice!

2020-09-29 19:26 UTC, labkey-nicka commented on core/src/org/labkey/core/webdav/DavController.java
> +                    else if (CONTENT_TYPE_HTML.equals(getRequest().getHeader("Content-Type)")) ||
Yes, this is now appropriately scoped and looks to still respond with JSON.

It is now assuming that the response code is 404 (not found) but then returning a status of 400 (bad request). What happens if a different type of error occurs? If is a 404 shouldn't we respond as such?

2020-09-29 19:26 UTC, labkey-nicka commented on core/src/org/labkey/core/webdav/DavController.java
> +                            return sendError(status, message);
This could cause an infinite loop as this is calling the same method. I believe this should call `super.sendError(status.code, message);` and not return.

2020-09-29 21:25 UTC, labkey-ankurj commented on core/src/org/labkey/core/webdav/DavController.java
> +                    else if (CONTENT_TYPE_HTML.equals(getRequest().getHeader("Content-Type)")) ||
updated the status code here, but error type here I think should always be not found as this is being utilized only for not found pages.

2020-09-29 21:25 UTC, labkey-ankurj commented on core/src/org/labkey/core/webdav/DavController.java
> +                            return sendError(status, message);
updated. thanks.

2020-09-29 22:01 UTC, labkey-ankurj commented on core/src/org/labkey/core/webdav/DavController.java
> +import org.labkey.api.util.*;
this was intellij.. ran the optimize imports.

2020-10-01 13:46 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorHandler.spec.tsx
> +        expect(wrapper.find('.error-details-container')).toHaveLength(0);
Added a text check for the sub heading in the top section and text check in details section.

2020-10-01 13:46 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorHandler.spec.tsx
> +        expect(question.text().startsWith('What went wrong?')).toBeTruthy();
done

2020-10-01 13:46 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorHandler.spec.tsx
> +            errorType: ErrorType.configuration,
Added a text check for the sub heading in the top section and text check in details section.

2020-10-01 13:47 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorHandler.tsx
> +        const viewDetailsBtnText = !showDetails ? this._hideDetails : this._viewDetails;
done

2020-10-01 13:47 UTC, labkey-ankurj commented on core/src/client/ErrorHandler/ErrorType.tsx
> +        {getServerContext().impersonatingUser !== undefined && (
Not sure how to impersonate in jest tests, do you have any pointers to existing example?

2020-10-01 17:14 UTC, labkey-nicka reviewed
Looks good to me. Only a couple nit items. I'll let @cnathe approve the PR once he's reviewed again.

2020-10-01 17:14 UTC, labkey-nicka commented on api/src/org/labkey/api/view/template/errorView.jsp
> +        LABKEY.App.__app__.isDOMContentLoaded = true;
@labkey-ankurj Can you open a ticket to me about this. It's fine to leave this "as-is" in this PR but the app loader should correctly identify when the DOM is loaded so you don't have to touch it's "private" state.

2020-10-01 17:14 UTC, labkey-nicka commented on api/src/org/labkey/api/view/template/errorView.jsp
> +    LABKEY.requiresCss(<%=q("/core/css/" + PageFlowUtil.resolveThemeName(getContainer()) + ".css")%>);
nit: I might further update this comment to state why the CSS is being pulled in here rather than in the client dependencies for the JSP. Something like:

```
This error page may be invoked without the themes having been loaded for this container. We load the theme artifact for this container here to ensure the correct theme is loaded as this cannot be resolved during "addClientDependencies()" for this view.

2020-10-01 17:15 UTC, labkey-nicka approved these changes

2020-10-01 17:58 UTC, cnathe commented on core/src/client/ErrorHandler/ErrorType.tsx
> +        {getServerContext().impersonatingUser !== undefined && (
If it is just a matter of setting some specific context on the LABKEY object for a certain test case (i.e. the LABKEY.impersonatingUser in this case), then we have an example of that in labkey-ui-components which might work here:
labkey-ui-components/packages/components/src/internal/app/utils.spec.ts

2020-10-01 17:58 UTC, cnathe approved these changes

2020-10-01 22:42 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/ExceptionUtil.java
> +            if (ex instanceof ConfigurationException && e instanceof NullPointerException)
Can we do a more direct check if JSPs are ready to render? What's null that's causing this exception?

2020-10-09 18:05 UTC, merged