41472: Copied to study assay results column names can change
LabKey/platform pull request #1605
Opened 2020-09-28 23:31 UTC by labkey-klum

#### Rationale
This change fixes issue [41472](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=41472). While this change does alter the generated copied to study column names, it only does so for the previously broken case where a study name consisted entirely of numbers. This scenario resulted in unstable column names when multiple copied to study names were added that only consisted of numbers in the name.

2020-09-29 01:22 UTC, labkey-jeckels requested changes

2020-09-29 01:22 UTC, labkey-jeckels commented on api/src/org/labkey/api/assay/AssayProtocolSchema.java
> +                if (sanitizeName(assayDataset.getStudy().getContainer().getName()).isEmpty())
Why do we look at the container name in the if check but then use the study label when generating the column name?

2020-09-29 03:04 UTC, labkey-klum commented on api/src/org/labkey/api/assay/AssayProtocolSchema.java
> +                if (sanitizeName(assayDataset.getStudy().getContainer().getName()).isEmpty())
I was attempting to constrain the column name changes to only the case where the entire study folder name consisted of numbers but a study folder name of 123FooBar would still create a column name of : copied_to_FooBar_Study which would be the same as prior to this change.

2020-09-29 04:58 UTC, labkey-jeckels commented on api/src/org/labkey/api/assay/AssayProtocolSchema.java
> +                if (sanitizeName(assayDataset.getStudy().getContainer().getName()).isEmpty())
Yes, that makes sense, but the container name doesn't necessarily match the study's label. You could have a container name that doesn't start with a number, but a study label that does. Wouldn't you want to check the same string in the if() statement as you're sanitizing?

2020-09-29 16:48 UTC, labkey-klum commented on api/src/org/labkey/api/assay/AssayProtocolSchema.java
> +                if (sanitizeName(assayDataset.getStudy().getContainer().getName()).isEmpty())
good point, line 848 could be replaced with : `if (sanitizeName(studyName).isEmpty())`

2020-09-30 00:12 UTC, labkey-jeckels commented on api/src/org/labkey/api/assay/AssayProtocolSchema.java
> +                if (sanitizeName(assayDataset.getStudy().getContainer().getName()).isEmpty())
I assume this update is in your queue, @labkey-klum? I can approve when it's pushed.

2020-09-30 01:03 UTC, labkey-jeckels approved these changes

2020-09-30 02:24 UTC, merged