Item 7882: Add support for discovery of data involved in transactions through detailed audit logging
LabKey/platform pull request #1621
Opened 2020-10-08 23:27 UTC by labkey-susanh

#### Rationale
Within LKSM, we want to enable users to work with the samples and sources that have just been imported, either via a file import or import within a grid.  Currently, this is possible when importing from a grid because the records created from using the `insertRows` operation are returned in the api response.  When importing from a file, only a count of the rows is returned (which is reasonable).  Here we add in an ability to find the data items that were inserted or updated during an upload operation by way of a new audit event type, which is created when the transaction begins and contains a unique transactionId that can then be stored in other audit logs as a reference.  

* [Issue 39594](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39594)

#### Related Pull Requests
* 

#### Changes
* Add TransactionAuditProvider, Domain and EventType
* Add transactionID field to QueryUpdateEvents, SampleTimelineEvents, and SampleTypeEvents
* Add method to QueryService for retrieving audit records given a transactionId
* Add action in AuditController for retrieving data ids based on a transaction id (for sources and samples only at this point)
* Convert type of rowId in AuditTypeEvent from int to long to support use of DbSequence as a rowId

2020-10-09 16:13 UTC, labkey-jeckels requested changes
One request and one question.

2020-10-09 16:13 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/AbstractQueryUpdateService.java
> +        transaction.addCommitTask(() -> AuditLogService.get().addEvent(user, auditEvent), DbScope.CommitTaskOption.POSTCOMMIT);
I'd make this PRECOMMIT instead so that it gets committed in the same transaction as everything else.

2020-10-09 16:13 UTC, labkey-jeckels commented on audit/src/org/labkey/audit/AuditController.java
> +                TableSelector selector = new TableSelector(ExperimentService.get().getTinfoData(), Collections.singleton("RowId"), filter, null);
Think we should sort the IDs?

2020-10-09 16:25 UTC, labkey-susanh commented on audit/src/org/labkey/audit/AuditController.java
> +                TableSelector selector = new TableSelector(ExperimentService.get().getTinfoData(), Collections.singleton("RowId"), filter, null);
Could do.  It's not at all necessary for my current use case, though.

2020-10-09 16:26 UTC, labkey-susanh commented on api/src/org/labkey/api/query/AbstractQueryUpdateService.java
> +        transaction.addCommitTask(() -> AuditLogService.get().addEvent(user, auditEvent), DbScope.CommitTaskOption.POSTCOMMIT);
Done.

2020-10-09 16:52 UTC, labkey-jeckels approved these changes

2020-10-09 17:48 UTC, XingY requested changes

2020-10-09 17:48 UTC, XingY commented on api/src/org/labkey/api/query/AbstractQueryImportAction.java
> +            // Check first if the audit behavior has been defined for the table either in code or through XML.
This logic seems problematic to me. audit behavior is set code, then override by action, and then override by xml. If the code set audit to Summary, but XML set audit to NONE, we should respects XML's NONE and ignore action's audit setting.

2020-10-09 17:48 UTC, XingY commented on audit/src/org/labkey/audit/AuditController.java
> +    public static class GetTransactionRowIdsAction extends ReadOnlyApiAction<AuditTransactionForm>
Should this action be moved to samplemanagement instead? The function seems very much tied to samplemanager and its client util selectIdsFromTransactionId is in samplemanagement only (maybe I missed some other usages).

2020-10-09 17:48 UTC, XingY commented on query/src/org/labkey/query/controllers/QueryController.java
> +    public static class ReplaceSelectedAction extends MutatingApiAction<SetCheckForm>
Is the shared component ComponentWithQueryModels replaceSelections wired up to this new action?

2020-10-09 18:03 UTC, labkey-susanh commented on api/src/org/labkey/api/query/AbstractQueryImportAction.java
> +            // Check first if the audit behavior has been defined for the table either in code or through XML.
I think that is the effect here since the logic for getting it from the table will defer to the XML setting unless I'm misreading.

2020-10-09 18:05 UTC, labkey-susanh commented on audit/src/org/labkey/audit/AuditController.java
> +    public static class GetTransactionRowIdsAction extends ReadOnlyApiAction<AuditTransactionForm>
I've put it here anticipating that Biologics will also want to use this when they turn on detailed audit logging for samples and because the event types in question are both defined in platform modules.  We will likely move the `selectIdsFromTransactionId` from sampleManagement into ui-components when the time comes.

2020-10-09 18:05 UTC, labkey-susanh commented on query/src/org/labkey/query/controllers/QueryController.java
> +    public static class ReplaceSelectedAction extends MutatingApiAction<SetCheckForm>
Yes.

2020-10-09 20:42 UTC, XingY commented on query/src/org/labkey/query/controllers/QueryController.java
> +    public static class ReplaceSelectedAction extends MutatingApiAction<SetCheckForm>
hmm, I'm still seeing clearSelections followed by setSelections for replaceSelections in withQueryModels.tsx

2020-10-09 20:45 UTC, XingY commented on api/src/org/labkey/api/query/AbstractQueryImportAction.java
> +            // Check first if the audit behavior has been defined for the table either in code or through XML.
The problematic check is behaviorType == AuditBehaviorType.NONE . if XML set to NONE, then we should treat it as NONE, instead of setting it to action's auditBehavior

2020-10-09 20:58 UTC, labkey-susanh commented on query/src/org/labkey/query/controllers/QueryController.java
> +    public static class ReplaceSelectedAction extends MutatingApiAction<SetCheckForm>
Ahhh!  Sorry.  I did not change QueryModels.  I shall do so.

2020-10-12 21:45 UTC, XingY requested changes

2020-10-12 21:45 UTC, XingY commented on api/src/org/labkey/api/data/TableInfo.java
> +     *  - the value supplied by this table's implementation (returned if not NONE or overrideValue is null)
I'm not understanding the order of precedence here. My understanding is that XML > param override > table implementation. If override has the lowest precedence, then it doesn't sound like it can override anything. If xml is null, table is summary, param is detailed, then the winner should be detailed. But based on this logic, summary would win.

2020-10-12 22:39 UTC, labkey-susanh commented on api/src/org/labkey/api/data/TableInfo.java
> +     *  - the value supplied by this table's implementation (returned if not NONE or overrideValue is null)
Ah yes.  'tis fixed.

2020-10-12 22:51 UTC, XingY approved these changes

2020-10-14 02:13 UTC, merged