fix for experimental feature "No Question Marks in URLs"
LabKey/platform pull request #1624
Opened 2020-10-09 19:42 UTC by labkey-matthewb

#### Rationale
bug fix

2020-10-09 22:05 UTC, labkey-kevink requested changes

2020-10-09 22:05 UTC, labkey-kevink commented on study/src/org/labkey/study/view/subjects.jsp
> +    String subjectUrlString = subjectUrl.toString();
Instead of using string concatenation on the client-side, we can use URL objects.  I'll send you a patch.

2020-10-10 00:31 UTC, labkey-adam commented on study/src/org/labkey/study/view/subjects.jsp
> +    String subjectUrlString = subjectUrl.toString();
👍

2020-10-10 00:42 UTC, labkey-matthewb commented on study/src/org/labkey/study/view/subjects.jsp
> +    String subjectUrlString = subjectUrl.toString();
I'll be out for a week, feel free to commit to branch!

2020-10-11 06:00 UTC, labkey-kevink approved these changes

2020-10-11 14:27 UTC, labkey-adam approved these changes

2020-10-12 19:00 UTC, merged