40909: Lookup field doesn't resolve when bulk importing into a sampleset
LabKey/platform pull request #1638
Opened 2020-10-19 22:08 UTC by labkey-klum

#### Rationale
We allow FK imports on int columns by alternate key column but not for string columns, for example dataset ptid to lsid translations. This change enables that if the raw FK value does not resolve to the target table.

tracking [issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=40909)

#### Changes
- For datasets, mark the subject ID column as unique so it can be used as an alternate key
- RemapPostConvertColumn will attempt to resolve lookups by alternate key for string columns if the raw value did not match

2020-10-19 22:38 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/SimpleTranslator.java
> +                if (fk != null && Objects.equals(o, value) && String.class.equals(_toCol.getJavaObjectClass()))
getJdbcType().isText()

2020-10-19 22:50 UTC, labkey-matthewb requested changes

2020-10-19 22:50 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/SimpleTranslator.java
> +                    {
I think _remapper is doing a lot of work to cache lookups.  This is not and TableSelector.getObject() is really expensive.  Wouldn't it make more sense to have a flag on RemapPostConvert to also lookup by PK first, then by AK?  Just like it has a flag called _includeTitleColumn?

2020-10-23 00:21 UTC, labkey-matthewb requested changes

2020-10-23 00:21 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/SimpleTranslator.java
> +                    ts = createSelector(pkCol, pkCol);
Looks good.  Won't this do a full table select for every miss when _allowBulkLoads == true?  Should we remember if we've done a full select so as to only select once here?

2020-10-23 01:08 UTC, labkey-klum commented on api/src/org/labkey/api/dataiterator/SimpleTranslator.java
> +                    ts = createSelector(pkCol, pkCol);
Good catch, fixed [here](https://github.com/LabKey/platform/pull/1638/commits/6e67cdec440ad044d4581484ed59cad34ff3046c).

2020-10-26 16:41 UTC, labkey-matthewb approved these changes

2020-10-26 17:59 UTC, merged