Announcements: Expose API endpoints
LabKey/platform pull request #1644
Opened 2020-10-21 17:45 UTC by labkey-nicka

#### Rationale
In our applications we've decided to leverage Announcements to support the commenting architecture. This PR allows us to use API endpoints to perform CRUD operations on announcements.

* [Specification](https://docs.google.com/document/d/13kchO4S4OgmWjAswXS35YrATU9j7Ko7i-1weG8WxOic/edit)

#### Related Pull Requests
* TBD

#### Changes
* Validate `AnnouncementModel` upon insert and update in `AnnouncementManager`. This was formerly done in the form validation of `AnnouncementForm`. This means that all inserts/updates from the UI, API endpoints, or the Query Update Service will run through the same validation. This validation will throw `RuntimeValidationException` if validation fails.
* Title validation address issue [#41611](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=41611).
* Renamed `DeleteThreadAction` to `DeleteAction`. Implemented new `DeleteThreadAction` as an API endpoint.
* Update `AnnouncementModel`, `HtmlString`, and `User` models to be serializable by Jackson.
* Address issue [#41616](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=41616) by not allowing for "owners" to update/delete announcements -- solely dependent on container permissions.

2020-10-21 23:13 UTC, labkey-tchad commented
BVTs ain't happy.

2020-10-21 23:35 UTC, labkey-adam requested changes
Owner permissions need to be adjusted for the Delete and Update cases, to match issue #41616 (and wiki & issue behavior). To update, user must have update OR must be the owner & have read & insert permissions. To delete, user must have delete OR must be the owner & have read & insert permission... plus must be able to delete all the responses (which we're already checking). NormalMessageBoardPermissions needs to mimic what BaseWikiPermissions is doing.

2020-10-21 23:39 UTC, labkey-nicka commented
> BVTs ain't happy.

@labkey-tchad Seem unrelated to anything here, but yes, of course we'll have them clear before merging.

2020-10-21 23:40 UTC, labkey-nicka commented
> Owner permissions need to be adjusted for the Delete and Update cases, to match issue #41616 (and wiki & issue behavior). To update, user must have update OR must be the owner & have read & insert permissions. To delete, user must have delete OR must be the owner & have read & insert permission... plus must be able to delete all the responses (which we're already checking). NormalMessageBoardPermissions needs to mimic what BaseWikiPermissions is doing.

Sorry, I clearly over trivialized this. I can make this more nuanced behavior update.

2020-10-22 18:11 UTC, labkey-klum approved these changes

2020-10-22 18:48 UTC, labkey-adam approved these changes
Thanks, looks good

2020-10-23 04:10 UTC, merged