Issue 40081: Fix Mothership test failing on sql server because of date coming as string "null"
LabKey/platform pull request #1702
Opened 2020-11-10 15:39 UTC by labkey-ankurj

#### Rationale
Check for date as "null" string on configure mothership page.

2020-11-10 17:02 UTC, labkey-jeckels requested changes

2020-11-10 17:02 UTC, labkey-jeckels commented on mothership/src/org/labkey/mothership/MothershipManager.java
> +        return  null == buildDate || "null".equals(buildDate) ? null : new Date(DateUtil.parseDateTime(c, buildDate));
Let's avoid storing the string "null" instead. Looks like it's being introduced by the String.valueOf() in setCurrentBuildDate(). I recommend checking that value for null, and using DateUtil.formatDateTime() instead.

2020-11-10 17:39 UTC, labkey-adam commented on mothership/src/org/labkey/mothership/MothershipManager.java
> +        return  null == buildDate || "null".equals(buildDate) ? null : new Date(DateUtil.parseDateTime(c, buildDate));
Since we're storing a date as a string and expecting to parse it later, please use `formatDateTimeISO8601(Date)` in `setCurrentBuildDate()` and `parseISODateTime(String)` in `getCurrentBuildDate()` (or `parseDateTime(String)` if we need to parse non-ISO formats for backward compatibility purposes). The container-based variants should only be used for displaying results in human readable form, not for serializing dates that need to be parsed. Folder display formats can be lossy and there's no guarantee that we'll be able to parse the results.

2020-11-11 19:22 UTC, labkey-ankurj commented on mothership/src/org/labkey/mothership/MothershipManager.java
> +        return  null == buildDate || "null".equals(buildDate) ? null : new Date(DateUtil.parseDateTime(c, buildDate));
@labkey-jeckels the initial (when landing on configure mothership page for the first time) "null" string value of property CURRENT_BUILD_DATE_PROP  is not coming from String.valueOf() in setCurrentBuildDate(). Also, looks like it only happens on sql server.

2020-11-11 21:32 UTC, labkey-jeckels approved these changes

2020-11-11 21:42 UTC, labkey-adam approved these changes

2020-11-11 22:00 UTC, merged