Issue 41908: ETL columns with special characters (including Benchling WH columns)
LabKey/platform pull request #1743
Opened 2020-11-29 23:27 UTC by labkey-martyp

#### Rationale
ETLing columns with non-alphanumeric characters like $ in the column name, does not correctly bind the parameter values.  The StatementUtils creation uses the select column name and the ResultSetDataIterator uses only the alias, causing parameter values on a SQL statement to not be filled in correctly.  This PR copies over select column metadata into the ResultSetDataIterator columnInfos, if provided.  This is used in StatementDataIterator.init() to match result set values with sql statement parameters.

Verified on PG and MSSQL and ran nearly all major automated tests to ensure no issues.

#### Changes
- In ResultSetDataIterator constructor pass in optional SelectColumns list to pass on metadata to ResultSetDataIterator column infos.  Match on column name or alias.

2020-11-30 19:04 UTC, labkey-jeckels reviewed
This approach looks OK, but a couple of questions:

1. The ResultSet that's passed here will actually be a Results object which already has info about the ColumnInfos. We could consider using that instead of adding another argument.
2. Why create a new BaseColumnInfo instead of just using the selectCol that you've matched?

It would be great to get @labkey-matthewb 's review too.

2020-11-30 20:00 UTC, labkey-martyp commented
> This approach looks OK, but a couple of questions:
> 
> 1. The ResultSet that's passed here will actually be a Results object which already has info about the ColumnInfos. We could consider using that instead of adding another argument.
> 2. Why create a new BaseColumnInfo instead of just using the selectCol that you've matched?
> 
> It would be great to get @labkey-matthewb 's review too.

Thanks for taking a look @labkey-jeckels 
1. The ResultSet does have columnInfos with it, however when you get the list of columnInfos using ResultSet.getMetaData it only returns columnInfos with the alias as the name.  The underlying actual column name is not accessible.  Those columnInfos are limited in other ways in their metadata, also missing things like parentTable which might have helped here.  PgResultSetMetaData has getBaseColumnName() which works to get the actual column name, but I can't find an equivalent function for sql server.
2. We can use the existing select columnInfos if you think that's appropriate.  They are a child type of BaseColumnInfo (RelationColumnInfo).  I was just trying to be consistent with the BaseColumnInfo type.  Also trying to create the new ColumnInfos free and clear of changes to the passed in SelectCols columnInfos, should they change elsewhere.

2020-11-30 20:09 UTC, labkey-jeckels commented
@labkey-martyp for the approach that I'm proposing with #1 you'd have to check if it's an instanceof Results and then you could call getFieldMap().values() to get the Collection<ColumnInfo>.

And I think that all of ColumnInfos are hopefully immutable based on the work that Matt's done previously, so you shouldn't need to be defensive and make your own copy.

2020-11-30 20:19 UTC, labkey-martyp commented
> @labkey-martyp for the approach that I'm proposing with #1 you'd have to check if it's an instanceof Results and then you could call getFieldMap().values() to get the Collection.
> 
> And I think that all of ColumnInfos are hopefully immutable based on the work that Matt's done previously, so you shouldn't need to be defensive and make your own copy.

@labkey-jeckels I see what you're saying.  I'll check that out.

2020-11-30 21:08 UTC, labkey-matthewb commented
Note that Results has a getColumn(index) method, which might be easier to use.  You wouldn't have to match the ColumnInfo to the right column in the ResultSet.

2020-12-01 22:08 UTC, labkey-matthewb requested changes

2020-12-01 22:08 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/QueryDataIteratorBuilder.java
> +            return new ResultSetDataIterator(rs, context, selectCols);
qs.select() returns a Results (not a ResultSet).  Results already have the correct ColumnInfo associated with each column in the result.

2020-12-01 22:08 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/ResultSetDataIterator.java
> +                    for (ColumnInfo col : ((Results) rs).getFieldMap().values())
Doesn't ((Results)rs).getColumn(i) work?

2020-12-01 22:49 UTC, labkey-martyp commented on api/src/org/labkey/api/dataiterator/QueryDataIteratorBuilder.java
> +            return new ResultSetDataIterator(rs, context, selectCols);
Yes using the Results columnInfos looks like the way to go.  This should be updated now to not pass in the selectCols.

2020-12-01 22:51 UTC, labkey-martyp commented on api/src/org/labkey/api/dataiterator/ResultSetDataIterator.java
> +                    for (ColumnInfo col : ((Results) rs).getFieldMap().values())
The indexes don't match up very well. Example below.  Results has an extra _rowNumber columnInfo in its columnInfoList, but that's not in its fieldMap or in the ResultSet metadata.  The ResultSet metadata has the container columnInfo which Results does not have.  However sometimes the container is in the Results object.  I can probably piece something together something using indexes and offsets, but it seemed the more reliable way was just to match on name/alias.  Or I can look into making Results columnInfo indexes more closely match the ResultSet metadata columns.

![image](https://user-images.githubusercontent.com/10213376/100805506-9c6e5000-33e3-11eb-85a1-e2f0bb5adf10.png)

2020-12-01 23:36 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/ResultSetDataIterator.java
> +                    for (ColumnInfo col : ((Results) rs).getFieldMap().values())
Remember that the ResultSet api's are 1-based.  I see (xKey,field1,field2) in the same order on both sides.  It would be really, really broken if those didn't match.

It seems that we don't have the columnInfo's for the "suggested columns" on the query side (I should probably look into that).  Interestingly , that means that this extra column (container) was not explicitly specified by the user in the query, and should probably not participate in the ETL!  QueryService.get().selectResults() has a parameter "strictColumnList" that does not pull in extra columns.

2020-12-03 02:47 UTC, labkey-martyp commented on api/src/org/labkey/api/dataiterator/ResultSetDataIterator.java
> +                    for (ColumnInfo col : ((Results) rs).getFieldMap().values())
@labkey-matthewb Whose idea was it to make ResultSets 1-based?  Ok I updated to do direct access of the columnInfo with Results.getColumn().  All appears to be working now. Running tests on TC

I didn't do anything with strictColumnList but can file a follow up issue if container columnInfo shouldn't be there.  I was just running ETLListTest.testMergeEtl to test.

2020-12-03 04:55 UTC, labkey-matthewb approved these changes

2020-12-03 15:13 UTC, merged