Pipeline log display not showing some logs on ERROR
LabKey/platform pull request #1749
Opened 2020-12-02 19:30 UTC by labkey-martyp

#### Rationale
The pipeline log display is checking the log file right after executing the job.  There is a race condition between displaying the error and the logger writing the logs to file.  This PR adds a time check to start the log rechecking process if the job has completed in the last minute.

#### Changes
- Add a check if the pipeline job modified time is within one minute of the current time.  If so, go into the pipeline log updating code.

2020-12-02 21:39 UTC, labkey-jeckels requested changes

2020-12-02 21:39 UTC, labkey-jeckels commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +    LocalDateTime modifiedTime = LocalDateTime.parse(status.modified,
Can we change the bean to store the Date object, and format it when we display it, instead of converting to String and then back to a date?

2020-12-02 21:51 UTC, labkey-martyp commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +    LocalDateTime modifiedTime = LocalDateTime.parse(status.modified,
Yeah I wasn't sure how the Date would serialize or if it was much savings to do that since the Date will have to be formatted in both Java and JS, depending on the view/api called.

2020-12-03 09:00 UTC, labkey-kevink requested changes

2020-12-03 09:00 UTC, labkey-kevink commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +    LocalDateTime modifiedTime = LocalDateTime.parse(status.modified,
Yes, using Date objects in the `StatusDetailsBean` is a good option, but you'd need to format it the client as you pointed out.  Alternatively, since this check of the modified field is only used on the initial render, you could add the `modified` field or a method to the `StatusController.DetailsBean`

2020-12-03 17:41 UTC, labkey-martyp commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +    LocalDateTime modifiedTime = LocalDateTime.parse(status.modified,
Good call.  Added modified to DetailsBean to just be passed to the view for initial render.

2020-12-03 18:32 UTC, labkey-jeckels approved these changes

2020-12-05 02:04 UTC, labkey-kevink approved these changes
Looks good

2020-12-05 17:06 UTC, merged