8012: Field Editor Row Selection
LabKey/platform pull request #1780
Opened 2020-12-11 19:45 UTC by RosalineP

#### Rationale
Update component version to support field row selection. 

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/413

#### Changes
* Update package versions

2020-12-15 16:45 UTC, cnathe requested changes

2020-12-15 16:45 UTC, cnathe commented on core/package.json
> +    "@labkey/api": "1.1.1",
I don't think we want to revert the @labkey/api version here back down to 1.1.1. I assume this was just a bad merge, right?

2021-01-06 17:16 UTC, RosalineP commented on core/package.json
> +    "@labkey/api": "1.1.1",
Oh, yup! Fixed

2021-01-13 18:48 UTC, cnathe approved these changes

2021-01-15 01:05 UTC, merged