Issue 22302: Merge user-defined and built-in queries in schema browser
LabKey/platform pull request #1786
Opened 2020-12-14 19:59 UTC by labkey-jeckels

#### Rationale
Users often don't pick up on the fact that we split queries and tables in the schema browser. And even if they understand that, they don't necessarily know which type a given entry is. Thus, in schemas with many dozens of tables and queries, it's often frustrating to find the one you want.

#### Changes
* Flatten the queries and tables so that they're direct children of their parent schema
* Show child schema list in the schema details panel
* Use icons to distinguish between tables, module-defined queries, and user-defined queries

2020-12-14 20:43 UTC, labkey-nicka requested changes

2020-12-14 20:43 UTC, labkey-nicka commented on query/src/org/labkey/query/controllers/GetSchemaQueryTreeAction.java
> +    protected void addQueryToList(SchemaKey schemaName, String qname, String label, String description, boolean hidden, Map<String, JSONObject> list, boolean table, boolean moduleSupplied)
nit: These new parameters `table` and `moduleSupplied` are unused.

2020-12-14 20:43 UTC, labkey-nicka commented on query/src/org/labkey/query/controllers/GetSchemaQueryTreeAction.java
> +import java.util.Collections;
nit: Unused import.

2020-12-14 20:43 UTC, labkey-nicka commented on query/webapp/query/browser/Browser.js
> +            if (selectInTree) {
Consider doing this in the `expand()` callback so it is guaranteed to be after the node has been expanded.

```js
schemaNode.expand(false, function(node) {
    if (Ext4.isFunction(callback)) {
        callback.call((scope || this), true, node);
    }

    if (selectInTree) {
        tree.getSelectionModel().select(node, false, true);
    }
});
```

2020-12-14 20:43 UTC, labkey-nicka commented on query/webapp/query/browser/Tree.js
> +                        return LABKEY.ActionURL.getContextPath() + '/reports/' + (rec.raw.table ? 'grid.gif' : (rec.raw.moduleSupplied ? 'grid-sql.png' : 'grid-sql-editable.png' )); }},
I'm not seeing these icons as I'd expect. I think this is due to those unused properties above not being handed down to the client.

2020-12-14 20:47 UTC, labkey-nicka commented on query/webapp/query/browser/view/QueryDetails.js
> +                html: 'LabKey SQL query' + (queryDetails.moduleName ? ' defined in ' + Ext4.htmlEncode(queryDetails.moduleName) + ' module' : '')
nit: Should this use the new `moduleSupplied` property instead of if the `moduleName` has a value or vice versa? Seems like overlapping logic.

2020-12-14 23:09 UTC, labkey-jeckels commented on query/webapp/query/browser/Browser.js
> +            if (selectInTree) {
Done

2020-12-14 23:09 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/GetSchemaQueryTreeAction.java
> +    protected void addQueryToList(SchemaKey schemaName, String qname, String label, String description, boolean hidden, Map<String, JSONObject> list, boolean table, boolean moduleSupplied)
Simplified to one new parameter - table - and re-introduced the code that sends it to the client

2020-12-14 23:10 UTC, labkey-jeckels commented on query/webapp/query/browser/view/QueryDetails.js
> +                html: 'LabKey SQL query' + (queryDetails.moduleName ? ' defined in ' + Ext4.htmlEncode(queryDetails.moduleName) + ' module' : '')
I removed the moduleSupplied property, and can keep relying on the preexisting moduleName property

2020-12-15 01:25 UTC, labkey-kevink commented on query/webapp/query/browser/view/QueryDetails.js
> +        if (queryDetails.isUserDefined) {
Can you check the behavior with linked schemas that expose a table and query in the source container and also has a custom sql query defined in the target (linked schema) container?

2020-12-15 23:12 UTC, labkey-nicka approved these changes

2020-12-16 00:04 UTC, merged