Use JSONB data type for metrics in mothership reporting
LabKey/platform pull request #1798
Opened 2020-12-17 01:38 UTC by labkey-jeckels

#### Rationale
Servers report a variety of metrics via JSON. We can make much better use of them by leveraging Postgres's JSON data type

#### Changes
* Allow pass-through for Postgres JSON operators and functions
* Drop SQL Server support for the mothership module, as we have no production deployments there
* Add queries that expose the JSON data in a relational-DB-like model for ease of reporting

2020-12-17 01:41 UTC, labkey-jeckels commented
@labkey-matthewb I'd appreciate your review of the JSON pass-through approach. Possible areas of concern:

Is there a better, relatively low effort way to pass through to the Postgres JSON operators?

Should we immediately do this passthrough more centrally in Query so that it's available in all Postgres instances instead of just the few ones that have the Mothership module?

Do want to capture the data type more directly in JdbcType or other enum-like metadata?

Do we want to invest in SQL Server JSON support now? There's overlap in functionality but it's far from a 1:1 simple mapping.

2020-12-17 05:07 UTC, labkey-matthewb requested changes

2020-12-17 05:07 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +        if (MothershipManager.get().getSchema().getSqlDialect().isPostgreSQL())
You can omit this check if you pass in the PostgresDialect as the last argument to registerPassthroughMethod().  Then it will work for external postgres schemas regardless of the primary database type.

2020-12-17 05:07 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +        if (MothershipManager.get().getSchema().getSqlDialect().isPostgreSQL())
Is there a reason to limit this to servers that have the mothership module?  Obviously these are global functions once they are registered.

2020-12-17 05:07 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +                    SQLFragment transformedOperator = new SQLFragment(operatorRawString.substring(1, operatorRawString.length() - 1));
SQL injection

2020-12-17 05:07 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +                    SQLFragment transformedOperator = new SQLFragment(operatorRawString.substring(1, operatorRawString.length() - 1));
Verify that this is indeed an expected operator

2020-12-17 05:07 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +            // Pretend that the JSON operators are a function instead so that we don't need them to be fully supported
Probably wouldn't be that hard to update SqlBase.g to accept these operators and just translate it on the spot.  E.g. 
The parser could translate```a #>> b``` into ```json_op(a, '#>>', b)```

2020-12-17 20:50 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +                    return new SQLFragment(arguments[0]).append(transformedOperator).append(arguments[2]);
need to rap arguments[0] and arguments[2] in parens "(" and ")".  Precedence of "," in function argument list is different than precedence of the transformedOperator.

2020-12-17 20:57 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +                    if (!rawOperator.getParams().isEmpty() || !operatorRawString.startsWith("'") || !operatorRawString.endsWith("'"))
see Method.validate() so that this is a handled/displayed error.

2020-12-17 23:08 UTC, labkey-jeckels commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +        if (MothershipManager.get().getSchema().getSqlDialect().isPostgreSQL())
This limits our exposure while we experiment as very few distributions include it

2020-12-17 23:08 UTC, labkey-jeckels commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +                    SQLFragment transformedOperator = new SQLFragment(operatorRawString.substring(1, operatorRawString.length() - 1));
Added

2020-12-17 23:09 UTC, labkey-jeckels commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +                    return new SQLFragment(arguments[0]).append(transformedOperator).append(arguments[2]);
Done

2020-12-17 23:10 UTC, labkey-jeckels commented on mothership/src/org/labkey/mothership/MothershipModule.java
> +                    if (!rawOperator.getParams().isEmpty() || !operatorRawString.startsWith("'") || !operatorRawString.endsWith("'"))
Method (and QNode, etc) isn't part of the query module's API so it's not available here. I changed to throw a QueryParseException instead, which is a little better but still gets reported poorly. When we promote this to more general usage we can register in Query and improve this.

2020-12-18 00:06 UTC, labkey-matthewb approved these changes

2020-12-18 01:09 UTC, labkey-jeckels commented
@labkey-tchad I just pushed a change to mark the Mothership tests as Postgres only. Can you adjust the GitHub and/or TeamCity settings to stop triggering them on SQL Server too?

2020-12-18 04:31 UTC, merged