Dataclass import/export support
LabKey/platform pull request #1828
Opened 2020-12-24 21:38 UTC by labkey-klum

#### Rationale
In this PR, we are adding support to export and import data classes through the folder archive framework. This will be added to the previously new support for sample types, so the archive data type has been updated to : 'Sample Types and Data Classes'.

#### Changes
- To be consistent with sample types, the data class definition and properties will be handled through the XAR framework
- Derivation protocol runs which involve data inputs/outputs were already being handled in the XAR
- Round trip support for data class special fields : flag, alias, MV indicators, and attachments
- Some refactoring of the query update service and attachment data iterator were required to use with data classes

2020-12-25 07:26 UTC, labkey-kevink requested changes
Looks good, but don't rely on the tsv export file name.

2020-12-25 07:26 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/XarReader.java
> +                dataClass.setSampleType(sampleType.getRowId());
Should we warn if the SampleType can't be found?

2020-12-25 07:26 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
>      private static final String DEFAULT_DIRECTORY = "sample-types";
These constants are duplicates of the ones in `SampleTypeAndDataClassFolderWriter`

2020-12-25 07:26 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
> +                                qus.loadRows(ctx.getUser(), ctx.getContainer(), loader, context, null);
Check `errors` to see if any errors occurred during import.

2020-12-25 07:26 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
> +                        dataClassDataFiles.put(file, FileUtil.getBaseName(file.substring(SampleTypeAndDataClassFolderWriter.DATA_CLASS_PREFIX.length())));
When we write the tsv, the file name is cleaned using `FIleUtil.makeLegalName` so it may not match the actual table name if it contains fun characters.  You could import tsv files for the sample types and data classes listed in the xar xml or something?

2020-12-28 19:41 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/XarReader.java
> +                dataClass.setSampleType(sampleType.getRowId());
done https://github.com/LabKey/platform/pull/1828/commits/af072efb6e0b917f3edf833180f452f70a736e36

2020-12-28 19:41 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
>      private static final String DEFAULT_DIRECTORY = "sample-types";
fixed https://github.com/LabKey/platform/pull/1828/commits/af072efb6e0b917f3edf833180f452f70a736e36

2020-12-28 19:41 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
> +                                qus.loadRows(ctx.getUser(), ctx.getContainer(), loader, context, null);
https://github.com/LabKey/platform/pull/1828/commits/af072efb6e0b917f3edf833180f452f70a736e36

2020-12-28 19:42 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
> +                        dataClassDataFiles.put(file, FileUtil.getBaseName(file.substring(SampleTypeAndDataClassFolderWriter.DATA_CLASS_PREFIX.length())));
good catch, followed your suggestion to use the names of the sample types and data classes loaded in the XAR, added this case to the test plan. https://github.com/LabKey/platform/pull/1828/commits/af072efb6e0b917f3edf833180f452f70a736e36

2020-12-29 00:39 UTC, labkey-kevink approved these changes

2020-12-29 04:16 UTC, merged