Enable merge option for datasets (phase 1)
LabKey/platform pull request #1834
Opened 2020-12-29 01:32 UTC by labkey-ians

#### Rationale
Spec: https://docs.google.com/document/d/110fl8qRIk1o9lEgFq8RKFWNW5vo_cYCiWkE1doFq214/
Enable the Merge option for bulk updating Datasets

TODO: (Phase 2) Improve Audit Logging

#### Changes
* Enabled UI option for the Dataset bulk insert page and form
* Passed importOption and auditLogBehavior parameters through to the DataIterator context
* Added a DetailedAuditLogDataIterator to the DI queue

2020-12-29 02:08 UTC, labkey-ians commented
One thing I just noticed is the Created date field's value is getting changed on the update instead of the Modified field. I'll need to look and see how to correct it.

2020-12-29 15:39 UTC, labkey-susanh requested changes

2020-12-29 15:39 UTC, labkey-susanh commented on study/src/org/labkey/study/model/DatasetDefinition.java
> +                //REVIEW: I'm guessing this is a terrible idea for multiple reasons, but seems to work...
This is certainly where we take the performance hit, but it is akin to how we handle the detailed audit logging for samples as well and is, I believe, the best we can do without more significant changes.  What reasons were you seeing other than performance for this to be a bad idea?

2020-12-29 15:39 UTC, labkey-susanh commented on study/src/org/labkey/study/model/DatasetDefinition.java
> +        DataIteratorBuilder dib = in;
The extra variable here doesn't seem necessary.

2020-12-29 15:39 UTC, labkey-susanh commented on study/src/org/labkey/study/model/DatasetDefinition.java
> +            if (auditAction == QueryService.AuditAction.MERGE)
We want to do the detailed logging only when the audit behavior is DETAILED.

2020-12-31 19:14 UTC, labkey-ians commented
Split into two PRs:
1) for enabling the merge option https://github.com/LabKey/platform/pull/1839
2) Adding the audit logging https://github.com/LabKey/platform/pull/1840

2020-12-31 19:14 UTC, closed without merging