New Assay Type Select Page
LabKey/platform pull request #1841
Opened 2021-01-01 22:00 UTC by labkey-martyp

#### Rationale
Create a new React page to replace the current "Choose Assay Type" page.  Uses @labkey/components AssayPicker which will be used in LKB as well.  New NPM entry point for this page. React page handles XAR upload here in Platform as this will not be used in LKB. Update actions to load the UI and handle XAR submission. 

#### Related Pull Requests
- https://github.com/LabKey/labkey-ui-components/pull/425

#### Changes
- Add action in AssayController to get list of available assay providers, list of possible containers and the default container. Reuses code from prior implementation just no longer a FormViewAction.
- Add action in ExperimentController to upload the XAR. This reuses XAR upload from previous FormViewAction implementation.
- Add NPM entry point
- Add AssayTypeSelect component to wrap AssayPicker and navigate or upload XAR on submit
- Remove unused actions and jsps

2021-01-04 15:14 UTC, cnathe requested changes

2021-01-04 15:14 UTC, cnathe commented on assay/src/client/entryPoints.js
> +        permission: 'insert',
The action where this new entryPoint is used, i.e. ChooseAssayTypeAction, requires DesignAssayPermission. Since that is the main usage of this entryPoint, I'd suggest that if we leave this generated view in place we raise this to "admin" permissions here. As it stands now, a user in the Author group can get to the assay-assayTypeSelect.view URL action/view successfully but it isn't really functional.

2021-01-04 15:14 UTC, cnathe commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.tsx
> +        if (isFileUpload && xar) {
if `isFileUpload` is true but we don't have a `xar`, this would go to the else statement and redirect. Is that desired? Not sure the user would actually be able to get to this `onSubmit` function in that case.

2021-01-04 15:14 UTC, cnathe commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.scss
> +  margin-top: 25px;
was this extra top spacing in the mockups? it looks a little excessive to me

2021-01-04 15:14 UTC, cnathe commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.tsx
> +                        selectedTab={tab}
Since this component will be used in LKS and LKB, I guess I was expecting that the `AssayPicker` itself would be the one maintaining the state of the selected inputs within the component. Was the reason for needing to put this state in this wrapped component because of the XAR import? I was imagining that all of that state and import action would be within ui-components and then this wrapper would just be how the LKS one passes in the props about allowing XAR import and handling navigation after success or on cancel.

As a comparison, the AssayDesigner.tsx wrapper in this module uses the AssayDesignerPanels in this way (i.e. all of the state and logic about the assay designer is in the shared component and then this wrapper is just for what to do onCancel and onComplete).

2021-01-04 15:14 UTC, cnathe commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.tsx
> +export function uploadXarFile(
Does this function need to be exported? It looks to only be used here in this component.

2021-01-04 15:14 UTC, cnathe commented on assay/src/client/entryPoints.js
> +        permission: 'insert',
Also, another option (though likely overkill here) would be to do what the AssayDesigner.tsx does. It checks the user permissions via an API call and then shows an insufficient permissions Alert (line 207) where applicable.

2021-01-04 15:14 UTC, cnathe commented on assay/src/org/labkey/assay/AssayController.java
> +        public Object execute(Object o, BindException errors) throws Exception
should the return type here be something  like `ApiResponse` or `ApiSimpleResponse`?

2021-01-04 15:14 UTC, cnathe commented on assay/src/org/labkey/assay/AssayController.java
> +            response.put("providers", jsonProvider);
Do we need to iterate through the providers here to convert them to `JSONObject`? I would have expected that just doing the following would be sufficient: `response.put(getProviders)`.

2021-01-06 01:50 UTC, labkey-martyp commented on assay/src/org/labkey/assay/AssayController.java
> +            response.put("providers", jsonProvider);
Was having some issues with Jackson marshalling, but got it working.  Removed this manual creation of JSONObjects

2021-01-06 01:50 UTC, labkey-martyp commented on assay/src/org/labkey/assay/AssayController.java
> +        public Object execute(Object o, BindException errors) throws Exception
Fixed

2021-01-06 01:50 UTC, labkey-martyp commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.tsx
> +export function uploadXarFile(
No, fixed

2021-01-06 01:50 UTC, labkey-martyp commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.tsx
> +                        selectedTab={tab}
As we discussed, the AssayPicker is maintaining state (so it can be reused in LKB) and passing up selection data to this parent component.  Refactored per your suggestion to use a single onChange handler and passing up a model of selections.

2021-01-06 01:50 UTC, labkey-martyp commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.scss
> +  margin-top: 25px;
The goal was to make the top margin on this page match the top margin of the Assay Designer for continuity when this page navigates to that page

2021-01-06 01:50 UTC, labkey-martyp commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.tsx
> +        if (isFileUpload && xar) {
This was refactored

2021-01-06 01:50 UTC, labkey-martyp commented on assay/src/client/entryPoints.js
> +        permission: 'insert',
As we discussed, updated @labkey/build to allow permissionClasses in entry points.  Added DesignAssayPermission class as a permissionClass.

2021-01-06 14:28 UTC, cnathe approved these changes

2021-01-06 14:28 UTC, cnathe commented on assay/src/client/AssayTypeSelect/AssayTypeSelect.tsx
> +        setAssayPickerSelection(model);
do we want to add the dirty state check/handling in this component wrapper?

2021-01-13 02:02 UTC, merged