Regression coverage for Files in Datasets disappear after editing the…
LabKey/platform pull request #1926
Opened 2021-01-25 06:25 UTC by labkey-sweta

#### Rationale
Automation Test
https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=42309

#### Related Pull Requests
https://github.com/LabKey/testAutomation/pull/607

#### Changes
study/test/src/org/labkey/test/tests/study/StudyDatasetFileFieldTest.java

2021-01-25 17:26 UTC, labkey-tchad requested changes

2021-01-25 17:26 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudyDatasetFileFieldTest.java
> +        checker().verifyEquals("Incorrect file name ", " datasetdata\\xml_sample.xml", table.getDataAsText(0, "fileField"));
This looks like a Windows file path and I suspect that it will fail on Linux or MacOS.

2021-01-25 17:26 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudyDatasetFileFieldTest.java
> +        setFormElement(Locator.name("quf_textField"), "Welcome..!");
The issue mentions that there should be a thumbnail or link to the existing file on the update row page. We should check for that here.

2021-01-25 17:46 UTC, labkey-klum commented on study/test/src/org/labkey/test/tests/study/StudyDatasetFileFieldTest.java
> +        setFormElement(Locator.name("quf_textField"), "Welcome..!");
Yes, that would be a good check, I would consider a different file from xml, since it will just render as a download link and not as an inline image with a popup.

2021-01-29 08:24 UTC, labkey-sweta commented on study/test/src/org/labkey/test/tests/study/StudyDatasetFileFieldTest.java
> +        setFormElement(Locator.name("quf_textField"), "Welcome..!");
Changed the Verification

2021-01-29 18:16 UTC, labkey-tchad requested changes

2021-01-29 18:16 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudyDatasetFileFieldTest.java
> +        setFormElement(Locator.name("quf_textField"), "Welcome..!");
I was suggesting that this should verify the download link and thumbnail on the update page before submitting. I think the file would need to be an image of some kind to actually have a thumbnail.

2021-02-05 17:35 UTC, labkey-tchad approved these changes

2021-02-05 17:51 UTC, merged