Issue 41458: Custom date-time fields show diffs with no changes on update
LabKey/platform pull request #1971
Opened 2021-02-08 20:31 UTC by labkey-ankurj

#### Rationale
This fixes the issue in change summary of issue tracker that displays the custom date-time field diff when there are no changes.

2021-02-08 22:26 UTC, labkey-adam requested changes
This doesn't look right... oldValue could be anything, an Integer or String or whatever. This code seems to be converting random objects to Strings, parsing the result as a date, and formatting back as a date.

I believe the correct approach is to NOT convert oldValue and newValue to Strings. `_appendCustomColumnChange()`, `_appendColumnChange()`, and `_appendChange()` should all take these as `Object` parameters. Then do a null-safe equals check on these objects (e.g., `Objects.equals()`) and only then invoke special formatting on any date objects.

2021-02-08 22:48 UTC, labkey-ankurj commented
want to make sure that oldValues and newValues were getting converted to string before this change and we want to change the approach.

2021-02-08 23:05 UTC, labkey-adam commented
This problem is caused by converting these values to String too early. My suggestion is to compare Object values and convert to Strings only if the object values differ; the String values should be used only for rendering purposes. Let me know if you want to discuss.

2021-02-09 02:26 UTC, labkey-adam commented on issues/src/org/labkey/issue/actions/ChangeSummary.java
> +            String toStr = to instanceof Date ? DateUtil.formatDate(container, (Date) to) : String.valueOf(to);
`from` and `to` can be `null` now, right? `String.valueOf(null)` returns the String "null", which I'm sure we don't want. I think you want to set `fromStr` and `toStr` to either `null` or `""` in the null case.

2021-02-09 02:27 UTC, labkey-adam reviewed
Looks much better. Just the one comment about null handling in `_appendChange()`. Or let me know if I've misunderstood something there.

2021-02-09 22:14 UTC, labkey-adam approved these changes

2021-02-09 22:15 UTC, merged