Item 8417: Support for changing lineColor in trendline plots
LabKey/platform pull request #2002
Opened 2021-02-16 22:49 UTC by labkey-ankurj

#### Rationale
Support to add a new property in trend line graphs to provide the line color.

#### Related Pull Requests
* https://github.com/LabKey/targetedms/pull/337

#### Changes
* new lineColor prop in LABKEY.vis.TrendingLinePlotType

2021-02-17 16:11 UTC, cnathe requested changes

2021-02-17 16:11 UTC, cnathe commented on internal/webapp/vis/src/plot.js
> + * @param {String} [config.properties.lineColor] (Optional) The data property name for the color to be used for the trend line connecting data points.
The description here mentions that this is a "data property name for the color", is that right? I think it should just say "The color to be used...".

2021-02-17 16:11 UTC, cnathe commented on internal/webapp/vis/src/plot.js
> +                        pathLayerConfig.aes.color = config.properties.lineColor;
I tested this on the Demo LabKey Plots page by making changes to the `leveyJenningsPlot` case in the /vis/demo/demo_scripts.js file, and it looks like the color I define for the `lineColor` isn't showing in the plot. For exmaple, if I change the properties to the following:
```
        showTrendLine: true,
        groupBy: 'colorlabel',
        lineColor: 'red',
        color: 'colorlabel',
        colorRange: ['red', 'blue', 'green', 'brown'],
```
I do see that the line color doesn't match the different group colors of the points, but the line is not red. It seems that the main thing here that is preventing the different line colors is just that we aren't going into the `else` block below.

2021-02-23 03:01 UTC, labkey-ankurj commented on internal/webapp/vis/src/plot.js
> +                        pathLayerConfig.aes.color = config.properties.lineColor;
yeah I guess the color black that I was trying was coming from default color in geom.js. fixed now.

2021-02-23 03:01 UTC, labkey-ankurj commented on internal/webapp/vis/src/plot.js
> + * @param {String} [config.properties.lineColor] (Optional) The data property name for the color to be used for the trend line connecting data points.
done

2021-02-23 15:32 UTC, cnathe approved these changes

2021-03-08 17:17 UTC, closed without merging