batch select existing records
LabKey/platform pull request #2004
Opened 2021-02-17 21:24 UTC by labkey-matthewb

#### Rationale
For performance we want to be able to batch selecting existing records for detailed audit logging.
However, sampletypes depends on the behavior of SampleTypeUpdateServiceDI.getRows().  So provide a use QUS.getRows() option (not fast).

2021-02-18 16:22 UTC, labkey-susanh requested changes

2021-02-18 16:22 UTC, labkey-susanh commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +                List<Map<String, Object>> list = qus.getRows(user, c, List.of(keys));
Hmm.  Not sure if this is going to do the trick because this method sets addInputs to false.  We need to have that true.

2021-02-18 16:22 UTC, labkey-susanh commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +                existingRecords.put((Integer)_delegate.get(0), existing);
Why is it that this version can't fetch multiple rows?  Does the SQL to get the key values not work here?

2021-02-18 16:22 UTC, labkey-susanh commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +            _delegate.next();
That's a bit crafty :-).

2021-02-18 17:04 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +                existingRecords.put((Integer)_delegate.get(0), existing);
I should have added a comment.  Even though getRows() looks like a bulk API, the implementations all just loop row-by-row.

2021-02-18 17:05 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +                List<Map<String, Object>> list = qus.getRows(user, c, List.of(keys));
Thanks

2021-02-18 17:06 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +                List<Map<String, Object>> list = qus.getRows(user, c, List.of(keys));
Not part of the QUS interface of course...

2021-02-18 18:02 UTC, labkey-susanh reviewed
This seems good to me, but there's still a failing test for SM Lineage that will need some further investigation.

2021-02-19 18:57 UTC, labkey-susanh approved these changes

2021-02-19 21:29 UTC, merged