Issue 42519: fix insert api for Submitter role
LabKey/platform pull request #2031
Opened 2021-02-25 00:56 UTC by labkey-ankurj

#### Rationale
Submitter role claims that the users may submit new information, but may not read or change anything. When a submitter (not reader) tries to insert information through Query.insertRows, the user is not successful because of ReadPermission check. This change allows the user to insert into a folder when the user is only submitter and not reader.

2021-02-25 02:49 UTC, labkey-jeckels requested changes
I don't think we want to modify getRows() like this. Can we check in the code that's calling getRows() instead? It looks like we might need to pull hasPermission() into the QueryUpdateService interface.

Have you already tested this with a number of roles and no permissions to see that it produces the expected results?

2021-02-26 01:26 UTC, labkey-jeckels approved these changes
Looks good. With the use of @RequiresAnyOf this feels like a much safer change.

2021-02-26 01:27 UTC, labkey-jeckels commented
Please address the test failure before merging though.

2021-02-26 01:27 UTC, labkey-ankurj commented
seems like I have to modify the failing test looking checking permissions

2021-02-26 22:35 UTC, labkey-jeckels commented on api/src/org/labkey/api/security/permissions/AbstractActionPermissionTest.java
> +            if (!submitterAllowed)
Can you make this verify that submitter has access, instead of just skipping the check that it has no access?

2021-02-26 22:59 UTC, labkey-ankurj commented on api/src/org/labkey/api/security/permissions/AbstractActionPermissionTest.java
> +            if (!submitterAllowed)
I think https://github.com/LabKey/platform/pull/2031/files#diff-98586cebe484870a914a05d55618a046b47349818c6cf16811f81dab2cf1365cR7031 is doing that. let me know if I am misunderstanding

2021-02-26 23:03 UTC, labkey-jeckels commented on api/src/org/labkey/api/security/permissions/AbstractActionPermissionTest.java
> +            if (!submitterAllowed)
Which file are you looking at? That just links to the whole PR for me.

I'm looking right here, where it does a check if submitterAllowed is false, but doesn't actually verify that the submitter has access when it submitterAllowed is true

2021-02-26 23:05 UTC, labkey-ankurj commented on api/src/org/labkey/api/security/permissions/AbstractActionPermissionTest.java
> +            if (!submitterAllowed)
new addition in QueryController.java L7031

2021-02-26 23:06 UTC, labkey-ankurj commented on api/src/org/labkey/api/security/permissions/AbstractActionPermissionTest.java
> +            if (!submitterAllowed)
Are you saying that I check for insertPermission for submitter?

2021-02-26 23:10 UTC, labkey-jeckels requested changes

2021-02-26 23:10 UTC, labkey-jeckels commented on api/src/org/labkey/api/security/permissions/AbstractActionPermissionTest.java
> +            if (!submitterAllowed)
I think it's as simple as adding an else that calls assertPermission(_c, action, _users.get(SUBMITTER_EMAIL)), so that the call from QueryController.java L7031 actually validates the submitter permission instead of just skipping over it

2021-02-26 23:19 UTC, labkey-jeckels approved these changes
Lovely

2021-02-27 01:04 UTC, labkey-jeckels approved these changes

2021-02-27 04:41 UTC, merged