Issue40946: Updates to secure message board options
LabKey/platform pull request #2036
Opened 2021-02-25 23:39 UTC by RosalineP

#### Rationale
Allow for a third secure message board option that allows for secure message boards to send contents of emails.
Migrate previous `secure = false` option to 'secureOff', previous `secure = true` option to 'secure without emails', and retain default message board setting as 'secureOff'. 
A message board that is 'secure without emails' will notify that a message board update has occurred without including body content, while 'secure with emails' will notify and include body content.

#### Related Pull Requests
* n/a

#### Changes
* Toggle boolean 'secure' property to corresponding default string using upgrade scripts
* Bump announcement version number
* Update wording and options on announcements-customize page

2021-02-25 23:41 UTC, RosalineP commented
Notes from sync with Josh: 
Due to the simplicity of the new string secure setting, I opted to not make it a enum, and just clarify using the string values.

Existing integration tests check whether or not various roles can various actions such as view, update, delete. Since there's no test that currently toggles and verifies the Security setting—and no tests checking email content—I think auto tests on this should be deferred.

Either PR would be appreciated depending on who gets the bandwidth, thank you! 👍

2021-02-26 00:13 UTC, RosalineP commented
Looking at test outages that popped up with the upgrade script push....

2021-02-26 00:18 UTC, labkey-jeckels requested changes

2021-02-26 00:18 UTC, labkey-jeckels commented on internal/src/org/labkey/api/announcements/DiscussionService.java
> +            return ("secureWithoutEmail").equals(_secure) || ("secureWithEmail").equals(_secure);
Since these strings are reused can they be constants and also referenced from the JSP?

2021-02-26 00:18 UTC, labkey-jeckels commented on announcements/resources/schemas/dbscripts/sqlserver/comm-21.000-21.001.sql
> +    set IN (SELECT set FROM prop.propertysets WHERE category = 'messageBoardSettings');
Haven't looked at the test failures, but given your comment I'm guessing you need to double-quote "SET" as it's a reserved word and I remember one of the DBs being picky

```suggestion
    "set" IN (SELECT "set" FROM prop.propertysets WHERE category = 'messageBoardSettings');
```

2021-02-26 00:43 UTC, RosalineP commented on announcements/resources/schemas/dbscripts/sqlserver/comm-21.000-21.001.sql
> +    set IN (SELECT set FROM prop.propertysets WHERE category = 'messageBoardSettings');
Though the outages are only on sqlserver, tested this out and added quotes to both upgrade scripts for consistency 👍

2021-02-26 00:43 UTC, RosalineP commented on internal/src/org/labkey/api/announcements/DiscussionService.java
> +            return ("secureWithoutEmail").equals(_secure) || ("secureWithEmail").equals(_secure);
Done! 👍

2021-02-26 01:02 UTC, labkey-jeckels requested changes
As discussed separately, it's legal syntax in the full UPDATE statement but it's not working the way you want
SELECT 'set' FROM prop.propertysets WHERE category = 'messageBoardSettings'
will return the value 'set' as a string, not the value of the "set" column

2021-02-26 01:24 UTC, labkey-jeckels approved these changes

2021-02-26 02:26 UTC, merged