Item 8516: Create aliquot using API
LabKey/platform pull request #2042
Opened 2021-02-26 22:34 UTC by XingY

#### Rationale
Aliquots are distinguished from the existing "derivatives". An aliquot or subaliquot is generated from a single parent sample or aliquot of the same sample type, and can have its own additional properties, in addition to the inherited sample's properties. This PR adds some preliminary work to support aliquots for LKSM. 

#### Related Pull Requests
* 

#### Changes
* new "Sample Aliquot" experimental flag
* add new PropertyDescriptor "DerivationDataScope" to support tagging Aliquot specific” fields
* add RootMaterialLSID and AliquotedFromLSID to exp.material
  * RootMaterialLSID is used to fetch sample metadata for aliquots and subaliquots
  * AliquotedFromLSID stores the aliquots direct parent for convenience
* fetch aliquot field values using a self join on provisioned material table in ExpMaterialImpl.getFromSql 
* update DerivationDataIterator to also handle aliquot creation, using a new "Sample Aliquot Protocol"
** customize samples/aliquot insert and update with new UpdateMaterialQueryRowAction and InsertMaterialQueryRowAction

2021-03-01 22:41 UTC, labkey-susanh requested changes

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/resources/schemas/dbscripts/sqlserver/exp-20.012-20.013.sql
> +GO
Is this necessary if it's the last line in the file?

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +        final List<String> _aliquotLsids; // check if lsid is aliquot with absent "AliquotedFrom", for merge
This comment is confusing to me.  I think it's partially a naming issue (see below), but maybe the comment could be updated to something like "used to check if ...". or "LSIDs present without AliquotFrom field.  Used for validation."

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            _aliquotParentCol = aliquotParentCol;
Looks like the local `aliquotParentCol` variable is not necessary.

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    _aliquotLsids.add(lsid);
Am I reading this correctly that if there isn't an `AliquotedFrom` column then the lsid is added to the `aliquotLsids`?  That seems the opposite of what I would expect, but I think it's just a naming thing.  `aliquotLsids` are really samlpeLsids that will be checked to determine if they are aliquots or not, right?  Maybe just call this `sampleLsids`?

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +    static List<ExpMaterialImpl> getAliquots(List<String> lsids)
Looks like this is only ever used to check for absence or presence or aliquots.  Can you use the `exists()` method on `TableSelector` instead?  It should be more efficient.

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                throw new ValidationException("Aliquots are present but 'AliquotedFrom' column is missing.");
This behavior is a little different than for other fields where the absence of a column means we don't want to change the current value in the database.  Does it need it be?

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                if ("ChildOnly".equalsIgnoreCase(propertyColumn.getDerivationDataScope()))
Maybe add constants for "ChildOnly" and its partner?

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +                LOG.warn("Aliquot specific field update has been skipped for a sample.");
```suggestion
                LOG.warn("Aliquot-specific field update has been skipped for a sample.");
```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            throw new IllegalArgumentException("Protocol has the wrong number of steps for a simple protocol, it should have three");
```suggestion
            throw new IllegalArgumentException("Protocol has the wrong number of steps for a simple protocol; it should have three.");
```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                    if ((countA % MAX_RUNS_IN_BATCH) == 0)
I'm unclear on the needs for batches since we're sort of moving away from using them.  It seems right that we would have separate batches for aliquots than for derivatives.  Thoughts on this @labkey-kevink?

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            new SqlSelector(pa.getSchema(), new SQLFragment("SELECT Lsid, RowId FROM " + pa /* + (pa.getSqlDialect().isSqlServer() ? " WITH (UPDLOCK, HOLDLOCK)" : "") */ + " ")
Is the `WITH (UPDLOCK ...` meant to be commented out still?

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +    private static final String INVALID_ALIQUOT_PROPERTY = "An aliquot specific property [%1$s] value has been ignored for a non-aliquot sample.";
```suggestion
    private static final String INVALID_ALIQUOT_PROPERTY = "An aliquot-specific property [%1$s] value has been ignored for a non-aliquot sample.";

```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                String message = "Aliquot parent '" + aliquotedFrom + "' not found";
```suggestion
                String message = "Aliquot parent '" + aliquotedFrom + "' not found.";

```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                            String message = "Sample derivation parent input not allowed for aliquot";
```suggestion
                            String message = "Sample derivation parent input is not allowed for aliquots.";

```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                            String message = "Sample derivation parent input not allowed for aliquot";
```suggestion
                            String message = "Sample derivation parent input is not allowed for aliquots.";

```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                                String message = "Sample derivation output not allowed for aliquot";
```suggestion
                                String message = "Sample derivation output is not allowed for aliquots.";

```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                            throw new ValidationException("Aliquot parent cannot be updated");
```suggestion
                            throw new ValidationException(Strring.format("Aliquot parents cannot be updated.  Change parent value from %s to %s.",currentMaterial.getAliquotedFromLSID(), aliquotParent.getLSID()));
```
This should help a user find the offending row in the input.

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                        throw new ValidationException("Unable to find aliquot parent for " + runItem.getName());
```suggestion
                        throw new ValidationException("Unable to find aliquot parent for " + runItem.getName() + ".");

```

2021-03-01 22:41 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                        throw new ValidationException("Invalid parents for aliquot: " + runItem.getName());
```suggestion
                        throw new ValidationException("Invalid parents for aliquot " + runItem.getName() + ".");

```

2021-03-02 19:49 UTC, XingY commented on experiment/resources/schemas/dbscripts/sqlserver/exp-20.012-20.013.sql
> +GO
I assume it's helpful in the roll up script. But I added it here because @mbellew added a 'GO' to exp-20.010-20.011

2021-03-02 19:54 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            _aliquotParentCol = aliquotParentCol;
The problem is _aliquotParentCol is a final fields that cannot be updated. So a temp var is used to process intermediate value.

2021-03-02 20:57 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                throw new ValidationException("Aliquots are present but 'AliquotedFrom' column is missing.");
It doesn't needs to be. But for reasons listed in comment, it might not be so horrible to make it required. Also it would require a big change to StatementUtil to prepare a customized update/insert statement for samples. Maybe something to consider for future when we got compliants?

2021-03-03 00:09 UTC, labkey-adam commented on experiment/resources/schemas/dbscripts/sqlserver/exp-20.012-20.013.sql
> +GO
Fine to include it, thanks @XingY . When we eventually roll up scripts, we do test and add GO statements if required. So not critical either way.

2021-03-03 01:31 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            _aliquotParentCol = aliquotParentCol;
Got it.  Thanks.

2021-03-03 01:31 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                throw new ValidationException("Aliquots are present but 'AliquotedFrom' column is missing.");
Isn't the hasAliquots method already querying for the LSID?  Granted, it's now doing an exists query instead of retrieving the materials so will be more efficient.  

Sorry if I'm being dense here, but why would the customized insert/update statement be needed?  Do you mean in the case that we don't have the AliquotedFrom value so we would somehow need to know which fields to update and which to discard?  Yes, that would be ugly.

2021-03-03 01:31 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            new SqlSelector(pa.getSchema(), new SQLFragment("SELECT Lsid, RowId FROM " + pa /* + (pa.getSqlDialect().isSqlServer() ? " WITH (UPDLOCK, HOLDLOCK)" : "") */ + " ")
Still need this commented out part of the SQLFragment?

2021-03-03 18:06 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                throw new ValidationException("Aliquots are present but 'AliquotedFrom' column is missing.");
Yes, the check is for differentiating meta vs aliquots fields. Insert/update into the material & properties table are already done by this point. And for merge without 'aliquotedFrom' column, the update might have wrongly updated meta/aliquot fields. This check is meant as a workaround after the update to fail the transaction. It does check for hasAliquots, but like I said, this is way past the actual update/insert. 

To properly update aliquot/meta fields, a custom StatementUtil will be needed at an earlier step. But if it's purely sql based, log warning for bad records wouldn't be possible.

Alternatively, we can add a FixDerivationDataFieldDataIterator, which identifies (find all merged sample with any aliquot-specific field populated, and aliquots with meta field populated) and fix(re-update) aliquot vs meta fields for merge without 'aliquotedFrom' case.

2021-03-03 18:09 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                throw new ValidationException("Aliquots are present but 'AliquotedFrom' column is missing.");
Got it.  Thanks for the clarification.  Definitely a different kind of merge we're doing here.  We may want to revisit this at some point if this special treatment from the user becomes problematic, but I think we're good for now.

2021-03-03 18:09 UTC, labkey-susanh approved these changes

2021-03-03 18:13 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            new SqlSelector(pa.getSchema(), new SQLFragment("SELECT Lsid, RowId FROM " + pa /* + (pa.getSqlDialect().isSqlServer() ? " WITH (UPDLOCK, HOLDLOCK)" : "") */ + " ")
This was copied from Matt's code, removed.

2021-03-03 20:21 UTC, merged