Issue 41827: Exp schema very slow (and sometimes non-responsive) to lookup to or open the schema browser
LabKey/platform pull request #2043
Opened 2021-02-26 23:15 UTC by XingY

#### Rationale
per code reviews from https://github.com/LabKey/platform/pull/2035 , we will move the expensive ensureFileData call from constructor to getFromSQL. 

#### Related Pull Requests
* 

#### Changes
* move ensureFileData to getFromSQL

2021-02-26 23:19 UTC, labkey-jeckels requested changes
Since getFromSQL() is overloaded, I think it's better to override the two-argument version. The base class's single-argument version calls the two-argument variant, so that would make sure this get hit both ways.

2021-02-26 23:47 UTC, labkey-jeckels approved these changes
Thanks Xing!

2021-02-26 23:55 UTC, labkey-kevink approved these changes

2021-03-22 23:53 UTC, labkey-jeckels commented
Did this change get lost? Is it ready to merge?

2021-03-23 17:38 UTC, XingY commented
> Did this change get lost? Is it ready to merge?

Was waiting on @labkey-tchad to do some regression testing. Or do you think it's safe to merge without?

2021-03-26 19:08 UTC, labkey-tchad commented
> > Did this change get lost? Is it ready to merge?
> 
> Was waiting on @labkey-tchad to do some regression testing. Or do you think it's safe to merge without?

Sorry. I missed this. I'll verify against 21.3. We'll need a [new PR](https://github.com/LabKey/platform/compare/21.3_fb_issue41827?expand=1) if we want this fix included in 21.3.1.

2021-03-26 19:41 UTC, labkey-jeckels commented
Fixing for a 21.3 maintenance release sounds good.

2021-04-02 18:21 UTC, closed without merging

2021-04-02 18:21 UTC, XingY commented
https://github.com/LabKey/platform/pull/2128