Improvements for MxN Panorama reproducibility reports - plotting functions and error reporting
LabKey/platform pull request #2076
Opened 2021-03-08 05:42 UTC by labkey-jeckels

#### Rationale
Panorama is leveraging our visualizations and needs more click and rendering options

#### Changes
* Support a new 'sequential' point arrangement that orders the scatter plot deterministically (unlike jittering) and based on the input data ordering
* Support clickFn on box plots
* Show error when an AJAX details tooltip fails to load

2021-03-08 20:32 UTC, labkey-ankurj requested changes

2021-03-08 20:32 UTC, labkey-ankurj commented on internal/webapp/vis/src/internal/D3Renderer.js
> +        if (geom.xScale.scaleType === 'discrete' && (geom.position === 'jitter' || geom.position === 'sequential')) {
seems like strings 'discrete', 'jitter' and 'sequential' can me made as constants.

2021-03-08 22:23 UTC, labkey-jeckels commented on internal/webapp/vis/src/internal/D3Renderer.js
> +        if (geom.xScale.scaleType === 'discrete' && (geom.position === 'jitter' || geom.position === 'sequential')) {
Indeed they can, as could many other strings that aren't constants in this file. I made constants for the position and scaleType values but don't want to revamp everything as part of this change.

2021-03-08 23:17 UTC, cnathe approved these changes
Looks good. I did some quick local testing using our index.html and demo_data code in /platform/internal/webapp/vis/demo/ folder.

2021-03-09 00:31 UTC, labkey-ankurj approved these changes

2021-03-09 00:38 UTC, merged