8591: Link to Study UI Elements
LabKey/platform pull request #2098
Opened 2021-03-16 20:49 UTC by RosalineP

#### Rationale
For Sample Type designer on LKS, add the form 'Auto-Link Data to Study' dropdown element to 'Properties' panel, and support full roundtrip of this new attribute.

#### Related Pull Requests
* 

#### Changes
* Bump ui-components version to pull in Sample Type designer UI changes
* Add 'AutoLinkTargetContainerId' column to 'exp.MaterialSource' table to hold new 'Auto-Link Data to Study' attribute data 
* Roundtrip new 'Auto-Link Data to Study' attribute data on creation and update of Sample Types
* Surface 'Link To Study' button in
    - Sample Types webpart
    - showSampleType view (experiment-showSampleType.view?rowId=`N`)
* Surface 'Link To Study History' button in Sample Type properties panel

2021-03-16 21:20 UTC, RosalineP commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeImpl.java
> +    public void setAutoLinkTargetContainerId(String autoLinkTargetContainerId)
Thought we might want to leave this intentionally not public in the `ExpSampleType` interface, similar to `setMetricUnit()` above at line 312?

2021-03-16 21:20 UTC, RosalineP commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeTableImpl.java
> +        addColumn(ExpSampleTypeTable.Column.AutoLinkTargetContainerId).setHidden(true);
Assuming this should also be a hidden column

2021-03-16 21:22 UTC, RosalineP commented on experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
> +                                              String nameExpression, @Nullable TemplateInfo templateInfo, @Nullable Map<String, String> importAliases, @Nullable String labelColor, @Nullable String me
Would it be a good idea to check whether `autoLinkTargetContainerId` is valid for the current container around line 655, here? (Following the pattern of the other checks-and-throws within the function)

2021-03-16 23:05 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeImpl.java
> +    public void setAutoLinkTargetContainerId(String autoLinkTargetContainerId)
That sounds reasonable, as the interface looks immutable (no setters)

2021-03-16 23:06 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeTableImpl.java
> +        addColumn(ExpSampleTypeTable.Column.AutoLinkTargetContainerId).setHidden(true);
yep

2021-03-16 23:07 UTC, RosalineP commented on experiment/resources/schemas/exp.xml
> +      <column columnName="AutoLinkTargetContainerId"/>
Noticed that `DatabaseDiagnosticsTest.databaseCheckTest` was running red due to `ERROR: Inconsistency in Schema exp
ERROR: Table "materialsource", column "autolinktargetcontainerid" missing from XML`. Checked out some examples and updated expTypes.xsd and exp.xml accordingly

2021-03-17 16:35 UTC, labkey-klum commented on experiment/resources/schemas/dbscripts/postgresql/exp-21.002-21.003.sql
> +ALTER TABLE exp.MaterialSource ADD COLUMN AutoLinkTargetContainerId VARCHAR(50) NULL;
If this field in the DB is truly a container ID we should model it as type: ENTITYID which is defined in core-0.00-18.30.sql as VARCHAR(36). Just so we are consistent across our data models on container fields.

2021-03-17 16:37 UTC, labkey-klum commented on experiment/resources/schemas/exp.xml
> +      <column columnName="AutoLinkTargetContainerId"/>
expTypes.xsd is used in the XAR import/export for sample types. I assume you didn't add any code yet to support the new property but maybe add a note in the spec for one of the future stories.

2021-03-17 16:59 UTC, labkey-klum requested changes
We should discuss how we represent the autoLinkTarget in our data models and interfaces. I think I'm more in favor of using Container objects instead of IDs on the database serialization/deserialization boundary and other than in the JSON serialization for the DomainKind.createDomain, it would be preferable to return container objects.

2021-03-17 19:27 UTC, RosalineP commented on experiment/resources/schemas/dbscripts/postgresql/exp-21.002-21.003.sql
> +ALTER TABLE exp.MaterialSource ADD COLUMN AutoLinkTargetContainerId VARCHAR(50) NULL;
Updated type length constraint accordingly!

2021-03-17 20:12 UTC, RosalineP commented on experiment/resources/schemas/exp.xml
> +      <column columnName="AutoLinkTargetContainerId"/>
Note added to spec!

2021-03-18 02:25 UTC, RosalineP commented on experiment/src/org/labkey/experiment/api/MaterialSource.java
> +    public void setAutoLinkTargetContainerId(Container autoLinkTargetContainerId)
Would have been nice to rename these `getAutoLinkTargetContainer` and `setAutoLinkTargetContainer` since we're using Containers instead of Strings now, but renaming seems to break alignment with the SampleTypeDomainKindProperties bean

2021-03-19 00:36 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/api/MaterialSource.java
> +    public void setAutoLinkTargetContainerId(Container autoLinkTargetContainerId)
I don't think I'm following this completely. Can you give an example or point me to the code where there is an implicit need to keep these methods aligned?

2021-03-19 18:41 UTC, RosalineP commented on experiment/src/org/labkey/experiment/api/MaterialSource.java
> +    public void setAutoLinkTargetContainerId(Container autoLinkTargetContainerId)
(Updated in patch as of 0ddf377)

2021-03-19 19:16 UTC, labkey-klum approved these changes

2021-03-22 16:34 UTC, merged