support PHI columns for DataClass and SampleType
LabKey/platform pull request #2109
Opened 2021-03-18 14:47 UTC by labkey-kevink

#### Rationale
Teach DataClass and SampleType to respect PHI settings on columns similar to Lists.  Import/insert/update/delete URLs and permission depend on a user having PHI access to all columns on the table.

Introduce `PhiTransformedColumnInfo` marker interface for columns that have been transformed by PHI rules.  Query details API and DataRegion uses this to indicate which columns have been transformed due to PHI settings.  Query metadata indicates PHI transformed columns with a new `phiTransformed` property.  When PHI rules omit columns from a table, a DataRegion message is added to the grid to indicate one or more columns have been removed.

To allow an admin page within Biologics to change the folder's compliance settings, add the ability to change the settings in the ComplianceService along with a permissions check.

#### Related Pull Requests
* https://github.com/LabKey/compliance/pull/105

#### Changes
* DataClass and SampleType respect PHI rules
* Add `phiTransformed` property to query metadata for PHI transformed columns
* Add DataRegion message for PHI omitted columns
* Add ComplianceService methods to get and set compliance folder settings

2021-03-30 00:32 UTC, labkey-adam requested changes

2021-03-30 00:32 UTC, labkey-adam commented on api/src/org/labkey/api/data/QueryLogging.java
> +//            throw new IllegalStateException("This QueryLogging instance is read-only: " + _debugName);
Uncomment like above? Or delete?

2021-03-30 00:32 UTC, labkey-adam commented on experiment/src/org/labkey/experiment/api/LineageTreeDisplayColumn.java
> +//        out.write("</ul>");
Remove?

2021-03-31 03:06 UTC, labkey-kevink commented on api/src/org/labkey/api/data/QueryLogging.java
> +//            throw new IllegalStateException("This QueryLogging instance is read-only: " + _debugName);
I'd like to uncomment, but we are currently relying on the behavior.  Added a comment to the Issue for tracking.

2021-04-06 14:38 UTC, labkey-adam commented
Looks like it needs a merge

2021-04-06 14:38 UTC, labkey-adam approved these changes

2021-04-07 06:16 UTC, merged