Item 8638: aliquot grids
LabKey/platform pull request #2130
Opened 2021-03-26 22:23 UTC by XingY

#### Rationale
A "isAliquot" column is now added to the samples grid to provide indication if a sample is an aliquot. Additionally, modifications to lineage query and graph are done to better support aliquot vs derivative differentiation. 

#### Related Pull Requests
* 

#### Changes
* add "IsAliquot" query column to samples grid
* add "materialLineageType" to lineage node response
* support lineage filter option by MaterialRunType
* fix broken lineage query when a seed has no child

2021-03-27 04:05 UTC, labkey-kevink requested changes
Let's support filtering by other protocol LSIDs as well.

2021-03-27 04:05 UTC, labkey-kevink commented on api/src/org/labkey/api/exp/api/ExpLineage.java
> +            if (node instanceof ExpMaterial)
Can you add this to ExperimentJSONConverter instead?  I'd like to keep all the serialization there if possible.

2021-03-27 04:05 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                if (excludeAliquotation || excludeDerivation)
I'd prefer not making this limited to these two types of runs.  We've had requests to filter the lineage by assay run protocol.

2021-03-27 04:05 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/api/ExperimentRunGraph2.jsp
> +  String materialRunType = StringUtils.defaultString(bean.getMaterialRunType(), "ALL");
See other comment about including/excluding other protocols by LSID.

2021-03-29 14:05 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                        "(CASE WHEN RootMaterialLSID IS NULL THEN ? ELSE ? END)").add(false).add(true), JdbcType.BOOLEAN);
Is the parameterization here necessary since the values being used are constants?

2021-04-02 18:07 UTC, labkey-susanh approved these changes
Just one comment on error message wording.

2021-04-02 18:07 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/api/ExpLineage.java
> +import org.springframework.util.StringUtils;
Is this import used?

2021-04-02 18:07 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                            String message = "Data input is not allowed for aliquots";
Is this the message users see in the UI?  I wonder if we can be more informative so they will know which field in their data is problematic by including the name of the column. Something like "${parentColName} is not allowed for aliquots."  ("Data input" just sounds like we don't allow any kind of data.)

2021-04-02 18:26 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                        "(CASE WHEN RootMaterialLSID IS NULL THEN ? ELSE ? END)").add(false).add(true), JdbcType.BOOLEAN);
turns out it's best to use parameterization due to sql dialect handling. Sql uses bit but postgres uses boolean type.

2021-04-02 22:20 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                            String message = parentColName + " is not allowed for aliquots";
if the parentColName is aliased in the import via a parent alias this might not match up to the user's import name. 
```suggestion
                            String message = "Sample derivation inputs are not allowed for aliquots.";
```

Or maybe a string constant to match with line 396.

2021-04-05 19:21 UTC, XingY commented
> Let's support filtering by other protocol LSIDs as well.

@kevinkrouse Kevin, can you please review this PR again so merge can be unblocked? Thanks.

2021-04-05 22:28 UTC, labkey-kevink approved these changes

2021-04-05 23:15 UTC, merged