Remove default sample type upgrade code
LabKey/platform pull request #2140
Opened 2021-03-30 19:46 UTC by labkey-adam

#### Rationale
Earliest upgrade is now 19.1, which means the `deleteDefaultSampleType()` code that was added in 19.1 no longer needs to run. At this point, no installation (whether new or upgraded) will have a default sample type.

2021-03-30 21:58 UTC, labkey-kevink requested changes
There are a few usages of `SampleTypeService.getDefaultSampleTypeLsid` that should be removed -- especially the `ExperimentServiceImpl.createExpMaterials` one that could save new samples into the default sample type.

2021-03-30 21:58 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/ExperimentModule.java
>          ExperimentUpgradeCode.upgradeMaterialSource(null);
I know it's not a part of this change, but can we move `upgradeMaterialSource` into an upgrade script?  Or at least add a note about when we can remove it?  I think for 22.3?

2021-03-30 22:31 UTC, labkey-adam commented on experiment/src/org/labkey/experiment/ExperimentModule.java
>          ExperimentUpgradeCode.upgradeMaterialSource(null);
https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=40714

2021-03-30 22:34 UTC, labkey-adam commented
Oops... I didn't see your other comment, @labkey-kevink  -- I'll need to look at that

2021-04-07 08:53 UTC, labkey-kevink approved these changes
As we discussed, we'll remove the other usages of the getDefaultSampleTypeMaterialLsidPrefix in a separate PR.

2021-04-08 01:52 UTC, merged