Issue42885: Provide for parameter substitution in authentication configuration fields
LabKey/platform pull request #2168
Opened 2021-04-06 23:20 UTC by RosalineP

#### Rationale
The motivating change desired is to allow the ACS URL setting within SAML auth config modals to dynamically update the hardcoded url '/labkey/saml-validate.view?configuration=configurationId'. We want to replace 'configurationId' with the id value saved on the SAML auth config in question.

We opted for a more general and reusable approach that allows for customization of <FixedHtml/>s through parameter substitution. Upon detecting the parameter substitution pattern ('${someVariable}') we attempt to replace it with the passed dynamic variable value 'someVariable' existing on 'authConfig'. If we cannot, we replace the pattern with the text 'someVariable' itself.

#### Related Pull Requests
* n/a (currently)

#### Changes
* Lint
* Supply 'authConfig' prop to <DynamicFields/>
* Support <FixedHtml/> parameter substitution
* Update snapshot

2021-04-07 05:32 UTC, labkey-adam commented
Probably best for Alan to review... seems like some changes aren't directly related to parameter substitution, but probably fine changes to take.

2021-04-07 17:38 UTC, labkey-adam commented on core/src/client/components/DynamicFields.tsx
> +                replacementVar ? replacementVar.toString() : matchedString
HTML encode replacement value?

2021-04-08 23:06 UTC, RosalineP commented on core/src/client/components/DynamicFields.tsx
> +                replacementVar ? replacementVar.toString() : matchedString
Addressed! 
Note: JS built-in `encodeURI ()` encodes all special characters except `, / ? : @ & = + $ #`

2021-04-09 00:52 UTC, labkey-adam requested changes

2021-04-09 00:52 UTC, labkey-adam commented on core/src/client/components/DynamicFields.tsx
> +            return encodeURI(authConfig[value] ? authConfig[value].toString() : value);
encodeURI is not HTML encoding. One extreme test: give your configuration a description like `SAML Configuration <script>alert("hello");</script>` and include ${description} in a FixedHtml field. I didn't see an alert, but the <script> tag and everything after it are being output into the page without any encoding. Instead, you should see all the text, just like you do on the main auth config page.

2021-04-09 00:52 UTC, labkey-adam commented on core/src/client/components/DynamicFields.tsx
> +        const stringTemplatedHtml = html.replace(/\${(.*?)}/g, (match, value) => {
Did you test this with a bunch of different replacements? For me, it's still only working on the first one. Perhaps you need `replaceAll()`?

2021-04-09 18:18 UTC, RosalineP commented on core/src/client/components/DynamicFields.tsx
> +        const stringTemplatedHtml = html.replace(/\${(.*?)}/g, (match, value) => {
(Adam reported as resolved)

2021-04-09 18:19 UTC, RosalineP commented on core/src/client/components/DynamicFields.tsx
> +            return encodeURI(authConfig[value] ? authConfig[value].toString() : value);
Found and used  LK JS API fn `encodeHtml()` 👍

2021-04-09 19:01 UTC, cnathe approved these changes

2021-04-09 19:01 UTC, cnathe commented on core/src/client/components/DynamicFields.tsx
> +            return Utils.encodeHtml(authConfig[value] ? authConfig[value].toString() : value);
Is it possible for `authConfig[value]` to be zero here? If so, that would go to the else block. Do you instead want the check to be `authConfig[value] !== undefined && authConfig[value] !== null ? authConfig[value].toString() : value`?

2021-04-09 19:21 UTC, RosalineP commented on core/src/client/components/DynamicFields.tsx
> +            return Utils.encodeHtml(authConfig[value] ? authConfig[value].toString() : value);
Done!

2021-04-09 19:41 UTC, labkey-adam approved these changes

2021-04-09 19:41 UTC, labkey-adam commented
I've performed manual testing locally... good to go!

2021-04-09 19:44 UTC, merged