Add concept picker and Ontology filters to data region filter dialog
LabKey/platform pull request #2205
Opened 2021-04-21 18:18 UTC by labkey-ians

#### Rationale
Item #8670 - https://docs.google.com/document/d/1QmHYktA4uNPxiSeid1kX2TakE2E0QPU4ZBkuSwTNeZI/edit?usp=sharing
Ontology, data region column filtering

#### Related Pull Requests
* TBD

#### Changes
* Add app entry point to inject ontology React elements into FilterDialog
* Some additional logic in FilterDialog.js to enable ontology specific filters

2021-04-22 16:32 UTC, cnathe requested changes

2021-04-22 16:32 UTC, cnathe commented on core/src/client/ConceptFilter/ConceptFilterView.scss
> +}
Not sure where this goes, but in quick manual testing I noticed that the ontology search results menu that pops down from the search input hides the right hand side of the menu behind the edge of the filter dialog. maybe we just need to fix the width of that search menu in this filter dialog case?

2021-04-22 16:32 UTC, cnathe commented on core/src/client/ConceptFilter/ConceptFilterView.tsx
> +    } = context;
```suggestion
    const {
        initFilterValue,
        initFilter,
        onFilterChange,
        ontologyId,
        subscribeFilterValue,
        unsubscribeFilterValue,
        subscribeFilterTypeChanged,
        unsubscribeFilterTypeChanged,
        loadListener,
    } = props.context;
```

2021-04-22 16:32 UTC, cnathe commented on core/src/client/ConceptFilter/ConceptFilterView.tsx
> +    const [collapsed, setHidden] = useState<boolean>(true);
any reason you used the name `setHidden` here instead of `setCollapsed` to match the variable name?

2021-04-22 16:32 UTC, cnathe commented on core/src/client/ConceptFilter/ConceptFilterView.tsx
> +    },[setFilter, subscribeFilterValue, unsubscribeFilterValue]);
should this be `[setFilter,  subscribeFilterTypeChanged, unsubscribeFilterTypeChanged]`?

2021-04-22 16:32 UTC, cnathe commented on search/src/org/labkey/search/SearchController.java
> +//            new AdminAction(getPageConfig()).setViewContext(getViewContext()).addNavTrail(root);
was this change intentional or something you were testing?

2021-04-22 16:32 UTC, cnathe commented on api/webapp/clientapi/ext3/FilterDialog.js
> +    CONCEPT_CODE_CONCEPT_URI: 'http://www.labkey.org/types#conceptCode',
looks like this `CONCEPT_CODE_CONCEPT_URI` const is defined in a couple places in this file. Is it possible to just make it a top level global variable in the file?

2021-04-22 16:32 UTC, cnathe commented on api/webapp/clientapi/ext3/FilterDialog.js
> +//TODO may be appropriate to move the one off stuff to this then switch based on conceptURI property.
Yeah, I was wondering about something like this as well. It would be great if it was possible to define this ConceptFilter dialog version and have all relevant code only there and not have to intertwine it with the original FilterDialog code above. With this TODO here, did you give that a try or was that just an idea after the implementation was done?

2021-04-26 18:42 UTC, labkey-ians commented on search/src/org/labkey/search/SearchController.java
> +//            new AdminAction(getPageConfig()).setViewContext(getViewContext()).addNavTrail(root);
carryover from an Issue investigation. Reverted.

2021-04-26 23:51 UTC, labkey-ians commented on core/src/client/ConceptFilter/ConceptFilterView.scss
> +}
removed. And adjusted the search panel via the components css

2021-04-26 23:51 UTC, labkey-ians commented on core/src/client/ConceptFilter/ConceptFilterView.tsx
> +    } = context;
fixed

2021-04-26 23:51 UTC, labkey-ians commented on core/src/client/ConceptFilter/ConceptFilterView.tsx
> +    const [collapsed, setHidden] = useState<boolean>(true);
nope, fixed.

2021-04-26 23:51 UTC, labkey-ians commented on core/src/client/ConceptFilter/ConceptFilterView.tsx
> +    },[setFilter, subscribeFilterValue, unsubscribeFilterValue]);
yes. fixed.

2021-04-26 23:53 UTC, labkey-ians commented on api/webapp/clientapi/ext3/FilterDialog.js
> +//TODO may be appropriate to move the one off stuff to this then switch based on conceptURI property.
Updated to use this.

2021-04-27 20:16 UTC, labkey-ians commented on api/webapp/clientapi/ext3/FilterDialog.js
> +    CONCEPT_CODE_CONCEPT_URI: 'http://www.labkey.org/types#conceptCode',
done.

2021-04-28 15:14 UTC, cnathe approved these changes

2021-04-28 15:14 UTC, cnathe commented on core/src/client/ConceptFilter/ConceptFilterView.scss
> +//}
remove commented out code?

2021-04-28 15:14 UTC, cnathe commented on api/webapp/clientapi/ext3/FilterDialog.js
> +Ext.reg('filter-view-conceptfilter', LABKEY.FilterDialog.View.ConceptFilter);
I really like this implementation with the separate LABKEY.FilterDialog.View.ConceptFilter. Nice job with the necessary refactors in the default filter panels so that you had the necessary functions to subclass / override.

2021-05-01 20:48 UTC, merged