Update StudyPublishTest to verify non-zero records in published datasets
LabKey/platform pull request #2207
Opened 2021-04-21 23:39 UTC by labkey-chrisj

#### Rationale
Issue [25892 ](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=25892)calls for verification that published datasets receive non-zero records, this adds verification that published datasets get at least one

#### Related Pull Requests
n/a

#### Changes

2021-04-22 00:10 UTC, labkey-tchad requested changes
This should verify that the published study has participants as well. The original regression mentions that they were missing as well: https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=25883

2021-04-22 21:46 UTC, labkey-chrisj commented
in this context, ensuring values in the MouseID column validates participants, right?

2021-04-22 23:26 UTC, labkey-tchad requested changes

2021-04-22 23:26 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudyPublishTest.java
> +                    dataTable.getColumnDataAsText("Mouse Id"), allOf(notNullValue()));
This doesn't work as you expect. `allOf` combines multiple matchers; it doesn't apply a matcher to each member of a collection. This will just verify that `getColumnDataAsText` returns a non-null value (which it always does).
I think you want `not(hasItem(""))`; I don't think `getColumnDataAsText` returns null values for empty cells.

2021-04-23 16:24 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudyPublishTest.java
> +                "ETL Definitions",
Is this a fix for a test failure? I don't think "ETL Definitions" will show up in community suites.

2021-04-23 17:23 UTC, labkey-chrisj commented on study/test/src/org/labkey/test/tests/study/StudyPublishTest.java
> +                "ETL Definitions",
ok, that explains it.

2021-04-23 17:55 UTC, labkey-tchad approved these changes

2021-04-23 19:15 UTC, merged