Item 8789: Initial implementation for client side metric counts
LabKey/platform pull request #2209
Opened 2021-04-23 20:20 UTC by cnathe

#### Rationale

#### Related Pull Requests
* 

#### Changes
*

2021-04-26 15:57 UTC, labkey-susanh reviewed
These changes seem fine to me, but I wonder if we will always want all of these metrics to appear under the Core module? At the moment, of course, it's a small set of metrics, but it could get somewhat unwieldy, and using separate keys for the applications could make for easier querying.  We are already providing the application name when submitting the metric, so we could change the structure of the metric to have another layer under the Core.clientSideMetricCounts, or each module with an application could register with the manager (if it moved to an API package) and get its own clentSideMetricCounts.  An argument for leaving it with Core is that we might want to gather the same count across multiple modules (if a UI component is shared, for example), but that seems like the data might get a bit muddier.

2021-04-26 16:42 UTC, labkey-jeckels requested changes

2021-04-26 16:42 UTC, labkey-jeckels commented on core/src/org/labkey/core/metrics/ClientSideMetricManager.java
> +    public Integer increment(String metricName)
This can return int instead of Integer.

2021-04-26 16:42 UTC, labkey-jeckels commented on core/src/org/labkey/core/metrics/ClientSideMetricManager.java
> +        if (!METRIC_COUNTS.containsKey(metricName))
Suggest using an AtomicInteger instead. It'll be thread safe, and will let you do something like:

return METRIC_COUNTS.computeIfAbsent(metricName, s -> new AtomicInteger(0)).incrementAndGet();

2021-04-26 16:42 UTC, labkey-jeckels commented on core/src/org/labkey/core/metrics/ClientSideMetricManager.java
> +    private static final Map<String, Integer> METRIC_COUNTS = new HashMap<>();
Multiple HTTP requests may be accessing this concurrently, so this should be synchronized in some way. Swapping in ConcurrentHashMap should be enough. It doesn't support null for keys or values, but that's fine for this scenario.

2021-04-26 16:44 UTC, labkey-jeckels commented
Cory, I know we talked about possible approaches for a nested JSON tree for these metrics or a flat namespace, but if you're receiving the metric API request with two separate strings I'd vote for reflecting that in the JSON structure that's submitted.

2021-04-26 19:59 UTC, cnathe commented on core/src/org/labkey/core/metrics/ClientSideMetricManager.java
> +    public Integer increment(String metricName)
done

2021-04-26 22:00 UTC, cnathe commented on core/src/org/labkey/core/metrics/ClientSideMetricManager.java
> +        if (!METRIC_COUNTS.containsKey(metricName))
done

2021-04-26 22:00 UTC, cnathe commented on core/src/org/labkey/core/metrics/ClientSideMetricManager.java
> +    private static final Map<String, Integer> METRIC_COUNTS = new HashMap<>();
done

2021-04-26 23:38 UTC, labkey-jeckels approved these changes

2021-04-27 18:19 UTC, labkey-susanh approved these changes

2021-04-28 13:56 UTC, merged