Item 8709: Add support for Sample Picklists Definition CRUD
LabKey/platform pull request #2243
Opened 2021-05-07 15:22 UTC by labkey-susanh

#### Rationale
We are building support for user-defined picklists of samples within Sample Manager and eventually within Biologics as well. These lists are built on top of our list implementation, but using a new domain kind with some properties specific to picklists. 
We add a new permission class `ManagePicklistsPermission` because we want to enable Editors in the application to be able to create picklists without having permission to create lists in general.

Users should be able to see all public picklists and their own private picklists.  Administrators should be able to see and delete  their own lists as well as public picklists.  Within LKS, users with DesignListPermission can update picklist domains just as other domains, but Editors cannot.

Picklists can be imported and exported, along with other lists, but, just as other lists with references to sampleIds, are generally not portable between containers.

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/522
* https://github.com/LabKey/inventory/pull/234
* https://github.com/LabKey/sampleManagement/pull/565

#### Changes
* Add new 'category' field for list metadata table to distinguish regular lists from public picklists from private picklists
* Add new permission class for managing picklists and assign it to editors and administrators
* Update DeleteListDefinitionAction to allow for passing in multiple listIds to be deleted
* Update methods for getting lists to allow for showing only public or owned picklists as appropriate.

2021-05-10 18:35 UTC, cnathe requested changes

2021-05-10 18:35 UTC, cnathe commented on api/src/org/labkey/api/exp/list/ListService.java
> +    ListDefinition createList(Container container, String name, ListDefinition.KeyType keyType, @Nullable TemplateInfo templateInfo, ListDefinition.@Nullable Category category);
What is the `ListDefinition.@Nullable` for the category param? I think that might be a copy-paste error.

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/ListModule.java
> +                metric.put("privatePicklistCount", new SqlSelector(dbSchema, "SELECT COUNT(*) FROM exp.list WHERE category ='" + ListDefinition.Category.PrivatePicklist.toString() + "'").getObject(Lo
Should these use `?` for the category = ...?

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/controllers/ListController.java
> +                                                    getContainer().hasPermission(getUser(), AdminPermission.class)
Shouldn't this just be a check for if the user has `DesignListPermission` on the container? i.e. `getContainer().hasPermission(getUser(), DesignListPermission.class)`. Or what is the need for the site level admin permissions check?

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/model/ListDomainKind.java
> +    public static Lsid generateDomainURI(String name, Container c, KeyType keyType, ListDefinition.@Nullable Category category)
Ok maybe the other usage wasn't a typo. How is `ListDefinition.@Nullable` different from `@Nullable`?

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/model/ListManagerTable.java
> +        MutableColumnInfo sharingCol = addWrapColumn("Sharing", _rootTable.getColumn(FieldKey.fromParts("Category")));
I guess I would have expected this to be an AliasedColumn, but this seems to work

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/model/ListManagerTable.java
> +        listIdCol.setHidden(true);
was the previous way this `ListId` column was being `setHidden` not working? I don't see any downstream usages of `listIdCol`.

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/model/ListManagerTable.java
> +        MutableColumnInfo countCol = addWrapColumn("ItemCount", _rootTable.getColumn(FieldKey.fromParts("ListID")));
again I would have expected this to be an AliasedColumn

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/view/ListsWebPart.java
> +        Map<String, ListDefinition> lists = ListService.get().getLists(model.getContainer(), model.getUser(), false);
Does the `false` here mean that we don't want to show any picklists in the narrow lists webpart? Just curious.

2021-05-10 18:35 UTC, cnathe commented on list/src/org/labkey/list/view/listsWebPart.jsp
> +    Map<String, ListDefinition> lists = ListService.get().getLists(c, getUser(), false);
Same question as above, does the `false` here mean we don't include any pick lists?

2021-05-11 13:47 UTC, cnathe approved these changes

2021-05-13 15:38 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/list/ListService.java
> +    ListDefinition createList(Container container, String name, ListDefinition.KeyType keyType, @Nullable TemplateInfo templateInfo, ListDefinition.@Nullable Category category);
It's IntelliJ being super intelligent.  Same as `@Nullable ListDefinition.Category`.

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/ListModule.java
> +                metric.put("privatePicklistCount", new SqlSelector(dbSchema, "SELECT COUNT(*) FROM exp.list WHERE category ='" + ListDefinition.Category.PrivatePicklist.toString() + "'").getObject(Lo
I guess it might be safer for portability, but string concatenation seems OK here.

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/controllers/ListController.java
> +                                                    getContainer().hasPermission(getUser(), AdminPermission.class)
The intent is that public picklists should be able to be deleted by any admin.  DesignListPermission is given to non-admins (e.g., AssayDesigners), so that didn't seem appropriate.  Perhaps there's some overkill in these permission checks.

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/model/ListDomainKind.java
> +    public static Lsid generateDomainURI(String name, Container c, KeyType keyType, ListDefinition.@Nullable Category category)
It's not.  The annotations are really just for IntelliJ and it did this weird syntax when I added a `@Nullable` parameter to this method.

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/model/ListManagerTable.java
> +        listIdCol.setHidden(true);
It was working fine.  This was just some initial modifications during my implementation iteration. Reverted.

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/model/ListManagerTable.java
> +        MutableColumnInfo sharingCol = addWrapColumn("Sharing", _rootTable.getColumn(FieldKey.fromParts("Category")));
`addWrapColumn` creates an `AliasedColumn` under the covers.

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/view/ListsWebPart.java
> +        Map<String, ListDefinition> lists = ListService.get().getLists(model.getContainer(), model.getUser(), false);
It means we shouldn't show ALL lists, only those the user has access to (public and own picklists and regular lists).

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/view/listsWebPart.jsp
> +    Map<String, ListDefinition> lists = ListService.get().getLists(c, getUser(), false);
Same answer as above. :-)

2021-05-13 15:38 UTC, labkey-susanh commented on list/src/org/labkey/list/model/ListManagerTable.java
> +        MutableColumnInfo countCol = addWrapColumn("ItemCount", _rootTable.getColumn(FieldKey.fromParts("ListID")));
Yup, it's an aliased column.

2021-05-13 15:52 UTC, merged