Item #8853: Ontology, Form insert and update
LabKey/platform pull request #2295
Opened 2021-05-26 20:36 UTC by labkey-ians

#### Rationale
Item #8853: Ontology, Form insert and update

#### Related Pull Requests
* https://github.com/LabKey/ontology/pull/43

#### Changes
* Adds the ConceptSubtree DomainProperty so we can apply a specific ontology hierarchy path to a field

2021-05-27 15:08 UTC, cnathe requested changes
I reviewed the changes and made a few comments, but @labkey-matthewb I think it would be good if you took a look at the changes for `OntologyManager.java` and the related classes. I am not familiar with that code.

2021-05-27 15:08 UTC, cnathe commented on api/src/org/labkey/api/data/ColumnRenderPropertiesImpl.java
> +    public void setSourceOntology(String sourceOntology)
I noticed that several of these ontology related setters don't have the `assert _checkLocked();` like the others. Not likely part of this PR, but is that intentional for any reason that you know of? or should they be added?

2021-05-27 15:08 UTC, cnathe commented on api/src/org/labkey/api/exp/OntologyManager.java
> +/*        TableInfo t = get();
There is a lot of commented out code left here. Is that to be removed at this point?

2021-05-27 15:08 UTC, cnathe commented on experiment/resources/schemas/dbscripts/sqlserver/exp-21.004-21.005.sql
> +--ALTER TABLE exp.PropertyDescriptor ADD ConceptSubtree NVARCHAR(MAX) NULL;
I assume we do want to support this in sql server. Is there a reason this is commented out?

2021-05-27 15:56 UTC, cnathe commented
> I reviewed the changes and made a few comments, but @labkey-matthewb I think it would be good if you took a look at the changes for `OntologyManager.java` and the related classes. I am not familiar with that code.

Looking at the commits, maybe you were the one that made those changes @labkey-matthewb. Is that correct?

2021-05-27 17:09 UTC, labkey-matthewb approved these changes

2021-05-27 17:31 UTC, cnathe approved these changes

2021-06-02 00:19 UTC, labkey-ians commented on api/src/org/labkey/api/exp/OntologyManager.java
>      static final String parameters = "propertyuri,name,description,rangeuri,concepturi,label," +
@mbellew There are some fields that are no longer being included in the insert statement. Should the be added here?

2021-06-02 00:20 UTC, labkey-ians commented on api/src/org/labkey/api/exp/OntologyManager.java
>      static final String parameters = "propertyuri,name,description,rangeuri,concepturi,label," +
facetingbehaviortype,
phi,
redactedText,
excludefromshifting,
mvindicatorstoragecolumnname,
defaultscale,

2021-06-02 00:39 UTC, labkey-matthewb commented on api/src/org/labkey/api/exp/OntologyManager.java
>      static final String parameters = "propertyuri,name,description,rangeuri,concepturi,label," +
This was an attempt to make the code _more_ consistent instead of repeating the columns in three places.  I didn't realize that insertPropertyIfNotExists() handled more columns than insertPropertyDescriptors().  I can't imagine that's intentional.  I assume that's genetic drift?

2021-06-09 22:29 UTC, merged