Issue43219: Move "System Default Domain" to Authentication page
LabKey/platform pull request #2327
Opened 2021-06-07 22:41 UTC by RosalineP

#### Rationale
The second property on the "Site Settings" page is called "System default domain (default domain for user log in)". This is really an authentication property and should be on the Authentication configuration page. Moving it there would make it more discoverable.

#### Related Pull Requests
* 

#### Changes
* Refactor calls of `AppProps.getDefaultDomain()` to use `AuthenticationManager.getDefaultDomain()`
* Create `AuthenticationManager.getDefaultDomain()`
* Refactor calls of `WriteableAppProps.setDefaultDomain()` to `AuthenticationManager.setDefaultDomain()`
* Create `AuthenticationManager.setDefaultDomain()`
* Add deferred Java upgrade code that reads the old property value and saves it to the new property set
* Update front-end

2021-06-07 22:44 UTC, RosalineP commented on api/src/org/labkey/api/security/AuthenticationManager.java
> +                boolean vIsBoolean = v instanceof Boolean;
Not very neat but my shot at wrapping the save into saveAuthSettings(). Alternatively, I could pull out saving the string into a separate function?

2021-06-07 22:46 UTC, RosalineP commented on api/src/org/labkey/api/settings/AppPropsImpl.java
> -                    case DEFAULT_DOMAIN_PROP -> writeable.setDefaultDomain(prop.getValue());
Is this still needed in this location, actually, since it's still a 'site setting' that gets populated here?

2021-06-07 22:48 UTC, RosalineP commented on core/src/client/components/GlobalSettings.tsx
> +                        <div> Default domain for user log in.</div>
Note to Adam: Please check in the UI that the tooltip helptext looks good to you

2021-06-07 22:49 UTC, RosalineP commented on core/src/org/labkey/core/CoreUpgradeCode.java
> +    public Map<String, String> getProperties(Container c)
I aggressively moved all necessary calls to help functions into the method—let me know if this is not what you meant when we talked about this!

2021-06-07 22:52 UTC, RosalineP commented
@labkey-adam 
I checked around and it looks like the other core executeJavaUpgradeCodes don't bump a value in `getSchemaVersion()` within `CoreModule` as is done with general upgrade scripts for other modules. Is the core module a special case?

2021-06-09 00:22 UTC, labkey-alan approved these changes
From a frontend perspective it looks good, though there is a setState call that should probably be changed to compute state via the state object passed to setState just to be safe.

2021-06-09 00:22 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        const newState = { ...this.state.globalSettings, [id]: value };
This should be computed inside the this.setState call below and should reference `prevState` instead of `this.state` when doing so, that way you are guaranteed to be calculating state on the most up to date state.

2021-06-09 20:04 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        const newState = { ...this.state.globalSettings, [id]: value };
Oops, thanks for the catch. Done!

2021-06-15 22:49 UTC, labkey-adam requested changes

2021-06-15 22:49 UTC, labkey-adam commented on api/src/org/labkey/api/security/AuthenticationManager.java
> +                boolean vIsBoolean = v instanceof Boolean;
Eh, I wouldn't worry about it... seems fine to me

2021-06-15 22:49 UTC, labkey-adam commented on api/src/org/labkey/api/settings/AppPropsImpl.java
> -                    case DEFAULT_DOMAIN_PROP -> writeable.setDefaultDomain(prop.getValue());
Good catch. Our syseng team is likely setting this property on hosted instances, so we need to coordinate with them. We need to email them know that, as of 21.7, there's a new way to set the default domain via startup properties (and we should verify that it works). It would be nice if this code would remain backward compatible for a while... it should accept the old property name but call the new AuthenticationManager setter AND log a warning stating its going away and listing the correct approach.

2021-06-15 22:49 UTC, labkey-adam commented on core/src/org/labkey/core/CoreUpgradeCode.java
> +    public Map<String, String> getProperties(Container c)
Since this is an `@DeferredUpgrade`, it's safe to call into `AppPropsImpl`... but you'd have to make lookupStringValue() `public`. Oh, and AppPropsImpl isn't public. Here's my suggestion (not tested, but should work):

```
        String defaultDomain = (new AbstractWriteableSettingsGroup(){
            @Override
            protected String getGroupName()
            {
                return "site settings";
            }

            @Override
            protected String getType()
            {
                return null;
            }

            private String getDefaultDomain()
            {
                return lookupStringValue(SITE_CONFIG_NAME, "");
            }
        }).getDefaultDomain();
```

2021-06-15 22:49 UTC, labkey-adam commented on core/src/org/labkey/core/admin/customizeSite.jsp
> +    <td colspan=2>Set base server url (<%=bean.helpLink%>)</td>
```suggestion
    <td colspan=2>URL settings (<%=bean.helpLink%>)</td>

```

2021-06-15 23:15 UTC, labkey-adam commented on core/src/client/components/GlobalSettings.tsx
> +                        <div> Default domain for user log in.</div>
```suggestion
                        <div> Default domain for user sign in.</div>
```

2021-06-16 18:47 UTC, RosalineP commented on core/src/org/labkey/core/CoreUpgradeCode.java
> +    public Map<String, String> getProperties(Container c)
Done!

2021-06-16 23:25 UTC, RosalineP commented on api/src/org/labkey/api/settings/AppPropsImpl.java
> -                    case DEFAULT_DOMAIN_PROP -> writeable.setDefaultDomain(prop.getValue());
Done!

2021-06-16 23:26 UTC, RosalineP commented
Misclicked and accidentally re-requested from Alan; feel free to ignore that.

2021-06-17 00:14 UTC, labkey-adam requested changes
A bit of cleanup...

2021-06-17 00:14 UTC, labkey-adam commented on api/src/org/labkey/api/settings/AppPropsImpl.java
> +                        LOG.warn("DEFAULT_DOMAIN_PROP here will be deprecated in 21.11 in favor of using DEFAULT_DOMAIN in AuthenticationManager.populateSettingsWithStartupProps()");
```suggestion
                        LOG.warn("Support for the \"SiteSettings.defaultDomain\" startup property will be removed shortly; use \"Authentication.DefaultDomain\" instead.");

```

2021-06-17 00:14 UTC, labkey-adam commented on core/src/org/labkey/core/login/LoginController.java
>                              WriteableAppProps appProps = AppProps.getWriteableInstance();
No need to touch appProps... remove this line

2021-06-17 00:14 UTC, labkey-adam commented on core/src/org/labkey/core/login/LoginController.java
>                              appProps.save(null);
...and remove this line

2021-06-17 19:02 UTC, RosalineP commented on core/src/org/labkey/core/login/LoginController.java
>                              WriteableAppProps appProps = AppProps.getWriteableInstance();
Done!

2021-06-17 19:02 UTC, RosalineP commented on core/src/org/labkey/core/login/LoginController.java
>                              appProps.save(null);
Done!

2021-06-17 20:00 UTC, labkey-adam approved these changes

2021-06-18 20:10 UTC, merged