Announcements - DiscussionSrcTypeProvider
LabKey/platform pull request #2362
Opened 2021-06-17 23:08 UTC by labkey-alan

#### Rationale
We need a way for Biologics/ELN to override the thread URLs for discussions when generating email notifications. We want the URLs in the notifications to point to a specific page in Biologics. This PR adds a new interface DiscussionSrcTypeProvider, and some methods for modules to register instances of these classes that are associated with an entity type. When creating a thread you can now set the discussionSrcEntityType (for labbook it sets it to "notebook") and if any modules have registered a DiscussionSrcTypeProvider for that type we will use that class instance to generate URLs.

#### Related Pull Requests
* TBD

#### Changes
* Add upgrade scripts to add DiscussionSrcEntityType column to the announcements table
* Add discussionSrcEntityType to AnnouncementModel
* Add DiscussionSrcTypeProvider interface
* Add getDiscussionSrcTypeProvider and registerDiscussionSrcTypeProvider to AnnouncementService

2021-06-17 23:43 UTC, labkey-adam requested changes
Minor change: HashMap -> ConcurrentHashMap

2021-06-17 23:43 UTC, labkey-adam commented on announcements/src/org/labkey/announcements/api/AnnouncementServiceImpl.java
> +        _discussionSrcTypeProviders = new HashMap<>();
Technically, should be a `ConcurrentHashMap`. I would just initialize _discussionSrcTypeProviders above and make it final.

2021-06-17 23:43 UTC, labkey-adam commented on experiment/package-lock.json
> +      "resolved": "http://artifactory.labkey.com/artifactory/api/npm/libs-client/@labkey/api/-/@labkey/api-1.5.0.tgz",
??

2021-06-17 23:43 UTC, labkey-adam commented on pipeline/package-lock.json
> +      "resolved": "http://artifactory.labkey.com/artifactory/api/npm/libs-client/@labkey/api/-/@labkey/api-1.5.0.tgz",
??

2021-06-21 20:16 UTC, labkey-alan commented on experiment/package-lock.json
> +      "resolved": "http://artifactory.labkey.com/artifactory/api/npm/libs-client/@labkey/api/-/@labkey/api-1.5.0.tgz",
I must have misread the diff when this change popped up, looks like we may be having issues with Artifactory again, I'll revert this.

2021-06-21 20:48 UTC, labkey-alan commented on announcements/src/org/labkey/announcements/api/AnnouncementServiceImpl.java
> +        _discussionSrcTypeProviders = new HashMap<>();
Fixed.

2021-06-22 17:16 UTC, labkey-nicka approved these changes

2021-06-22 20:54 UTC, labkey-adam commented on api/src/org/labkey/api/announcements/api/AnnouncementService.java
> +import javax.validation.constraints.Null;
I don't think we use this anywhere else... typically we annotate `org.jetbrains.annotations.Nullable`

2021-06-22 20:55 UTC, labkey-adam approved these changes

2021-06-22 20:55 UTC, labkey-adam commented on api/src/org/labkey/api/announcements/api/AnnouncementService.java
> +import javax.validation.constraints.Null;
Not sure if this behaves in the same way

2021-06-22 21:30 UTC, labkey-alan commented on api/src/org/labkey/api/announcements/api/AnnouncementService.java
> +import javax.validation.constraints.Null;
Ugh, Intellij auto-completed this for me and I did not notice. Fixed.

2021-06-22 22:58 UTC, merged