Issue 43261:  Convert workflow priority and status lists to enum tables
LabKey/platform pull request #2389
Opened 2021-06-23 23:40 UTC by XingY

#### Rationale
Sample manager workflow uses container scoped lists to reference certain job and task properties. We don't have a way to mark those special list as 'system' lists and they might get edited or deleted by users with edit permissions. Switching the implementation to enum tables will help prevent such errors.  

#### Related Pull Requests
* 

#### Changes
* add exp.WorkflowTaskStatus and exp.WorkflowJobPriority enum tables

2021-06-23 23:41 UTC, XingY commented
@labkey-susanh I don't think those tables need to live in exp. They probably suit SampleManagementSchema better. What do you think?

2021-06-24 00:29 UTC, labkey-susanh requested changes

2021-06-24 00:29 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/query/WorkflowTaskStatusEnumTableInfo.java
> +    public static final String WORKFLOW_JOB_PRIORITY_TABLE_NAME = "WorkflowJobPriority";
It's strange to me that the priority table and enum live in this class.  I think I would move them into their own class or just in the Schema class itself, and yes, I think these may be better suited to the SampleManager schema.

2021-06-24 13:50 UTC, XingY commented
Moved code to sampleManagement, closing PR

2021-06-24 13:50 UTC, closed without merging