Fb dataset notifications 9061
LabKey/platform pull request #2424
Opened 2021-07-02 19:42 UTC by labkey-klum

#### Rationale
We want to expand the options available when configuring notifications for report and dataset changes in a study. With this change we now support selection on a per dataset basis which will be mutually exclusive from the other previous options:
- All
- By category

In addition the notification sent out will contain a link (for datasets) to the audit changes that occurred for that notification. 

#### Related Documents
- [Specification](https://docs.google.com/document/d/1_7mF64TIT5b5x28RSw3S1G8xrmj_avaJyrWGDi481Dk/edit)

#### Changes
- Add a new option to the notification config UI to set on a per dataset basis
- Refactor the Ext4 code to be more consistent with other components that we have written in Ext4. Extend the panel class instead of acting like a factory class.
- Update the email template and formatting (styles were not included properly)
- Simplify the HTML generation of the report and notification email template grid. Switch from HTML generation in java to rendering using a JSP.
- Add an audit link to the manage datasets page
- Collect metrics for the number of notification configurations on the server

2021-07-02 19:44 UTC, labkey-klum commented on study/src/org/labkey/study/controllers/DatasetController.java
> +    @RequiresPermission(CanSeeAuditLogPermission.class)
Checked with Susan, no reason that this view should be restricted to admin only.

2021-07-08 00:17 UTC, labkey-adam requested changes
Just a couple suggestions to consider

2021-07-08 00:17 UTC, labkey-adam commented on query/src/org/labkey/query/reports/view/ReportAndDatasetChangeDigestEmailTemplate.java
> +            ViewContext context = ViewContext.getMockViewContext(User.getSearchUser(), c, new ActionURL(), true);
Can you use a `JspTemplate` here instead?

2021-07-08 00:17 UTC, labkey-adam commented on query/src/org/labkey/query/reports/view/manageNotifications.jsp
> +            datasets : <%=HtmlString.unsafe(jsonMapper.writeValueAsString(form.getDatasets()))%>,
I think you could use `<%=toJsonArray()%>` or `<%=toJsonObject()%>` here. More succinct and their output is already marked `SafeToRender`.

2021-07-08 00:19 UTC, labkey-adam commented
Did you want to target `release21.7-SNAPSHOT`?

2021-07-08 20:55 UTC, labkey-klum commented on query/src/org/labkey/query/reports/view/manageNotifications.jsp
> +            datasets : <%=HtmlString.unsafe(jsonMapper.writeValueAsString(form.getDatasets()))%>,
👍

2021-07-08 20:55 UTC, labkey-klum commented on query/src/org/labkey/query/reports/view/ReportAndDatasetChangeDigestEmailTemplate.java
> +            ViewContext context = ViewContext.getMockViewContext(User.getSearchUser(), c, new ActionURL(), true);
ah right, for the life of me I couldn't remember the name of that class.

2021-07-10 15:49 UTC, labkey-adam requested changes
Simplify `JspTemplate` handling

2021-07-10 15:49 UTC, labkey-adam commented on query/src/org/labkey/query/reports/view/ReportAndDatasetChangeDigestEmailTemplate.java
> +            JspTemplate<NotificationBean> view = new JspTemplate<>("/org/labkey/query/reports/view/reportAndDatasetList.jsp", bean);
```suggestion
            return new JspTemplate<>("/org/labkey/query/reports/view/reportAndDatasetList.jsp", bean).render();

```

2021-07-10 15:49 UTC, labkey-adam commented on query/src/org/labkey/query/reports/view/ReportAndDatasetChangeDigestEmailTemplate.java
> +            JspTemplate<NotificationBean> view = new JspTemplate<>("/org/labkey/query/reports/view/reportAndDatasetList.jsp", bean);
You don't need the `MockViewContext`, etc. -- `JspTemplate.render()` will handle it for you

2021-07-19 20:35 UTC, labkey-adam approved these changes

2021-07-20 16:39 UTC, merged