Item 8788: Find samples using sample Ids or barcodes
LabKey/platform pull request #2444
Opened 2021-07-12 14:19 UTC by labkey-susanh

#### Rationale
When scanning barcodes or coming to the application with a set of known ids, users want to be able to find these samples quickly and act on them in bulk. To support this, we need to provide a way to search for samples across all types for Sample Ids and search for barcodes in all of the Unique ID fields for all sample types.  The sample IDs (which are the names of the samples, not their rowIds) are not unique across sample types.  The Unique IDs are globally unique but any sample type may have more than one (or none) such fields.  Furthermore, it is important that the ids provided are handled in the order in which they are provided so that if scanning the samples to be put into a freezer, they are assigned to spots in the storage box in the order provided.  For this, we require an ordering column attached to our session query used to select the various samples.

#### Related Pull Requests
* 

#### Changes
* Add `ExpMaterialUniqueIdUnionTableInfo` virtual table for gathering together all data from the 
* Add index for UniqueId columns in sample types
* Add `SaveOrderedSamplesQueryAction` to `ExperimentController`

2021-07-12 18:28 UTC, labkey-matthewb requested changes

2021-07-12 18:28 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExpMaterialUniqueIdUnionTableInfo.java
> +public class ExpMaterialUniqueIdUnionTableInfo extends VirtualTable
This doesn't really need to be TableInfo at all, it's just a helper class with one method getSql().

2021-07-12 18:28 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                    sampleIdValuesSql.append("'").append(id.substring(SAMPLE_ID_PREFIX.length())).append("'");
DialectStringHandler.quoteStringLiteral()

2021-07-12 18:28 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                    uniqueIdValuesSql.append("'").append(id.substring(UNIQUE_ID_PREFIX.length())).append("'");
DialectStringHandler.quoteStringLiteral()

2021-07-12 18:28 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/property/DomainImpl.java
> +            idx.second.stream().filter(col -> !col.isUniqueIdField()).forEach(uniqueIndexCols::add);
comments?  Got lost on what's happening here.

2021-07-12 18:28 UTC, labkey-matthewb commented on internal/src/org/labkey/experiment/api/SampleTypeDomainKind.java
> +        domain.getProperties().stream().filter(DomainProperty::isUniqueIdField).forEach(prop -> {
If we index on (prop,"RowId") then query engine should be able to execute the select directly using the index w/o touching the base table.  Once the engine finds a matching row in the index for "INNER JOIN exp.materials M ON _ordered_ids_.column2 = M.Name", it can do the "SELECT M.RowId" with the index entry it has in hand.

2021-07-13 16:59 UTC, labkey-susanh commented on internal/src/org/labkey/experiment/api/SampleTypeDomainKind.java
> +        domain.getProperties().stream().filter(DomainProperty::isUniqueIdField).forEach(prop -> {
So, are you suggesting adding "RowId" as one of the columns?  Since these uniqueId values are, in fact, unique independent of the rowId, I thought it redundant, but you seem to be saying adding that column will be a hint at even more efficient behavior, right?

2021-07-13 16:59 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpMaterialUniqueIdUnionTableInfo.java
> +public class ExpMaterialUniqueIdUnionTableInfo extends VirtualTable
Ah, good thought.  That will be better.

2021-07-13 16:59 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/property/DomainImpl.java
> +            idx.second.stream().filter(col -> !col.isUniqueIdField()).forEach(uniqueIndexCols::add);
Done.

2021-07-13 16:59 UTC, labkey-susanh commented on internal/src/org/labkey/experiment/api/SampleTypeDomainKind.java
> +        domain.getProperties().stream().filter(DomainProperty::isUniqueIdField).forEach(prop -> {
Hmm.  Well, that didn't work, but maybe I've misunderstood the intent. "RowId" isn't a column on the sample type provisioned table, only on the exp.materials table.  I could use "lsid" here together with `prop.name()`.  Would that achieve the same thing @labkey-matthewb?

2021-07-14 20:04 UTC, labkey-matthewb approved these changes

2021-07-14 20:31 UTC, merged

2022-12-15 18:13 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                    sampleIdValuesSql.append("'").append(id.substring(SAMPLE_ID_PREFIX.length())).append("'");
We're generating LabKey SQL here so this should use `LabKeySql.quoteString()`.

2022-12-15 18:13 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                    uniqueIdValuesSql.append("'").append(id.substring(UNIQUE_ID_PREFIX.length())).append("'");
We're generating LabKey SQL here so this should use `LabKeySql.quoteString()`.