Dataset change Email Notification Automation test
LabKey/platform pull request #2506
Opened 2021-08-02 05:57 UTC by labkey-sweta

#### Rationale
Dataset change email notifications automation test

#### Related Pull Requests
* 

#### Changes
study/test/src/org/labkey/test/tests/study/StudyDatasetChangeEmailNotificationTest.java

2021-08-02 17:27 UTC, labkey-klum commented on study/test/src/org/labkey/test/tests/study/StudyDatasetChangeEmailNotificationTest.java
> +            refresh();
you may want to limit this to a certain number of refreshes to avoid an infinite loop on an error.

2021-08-02 17:54 UTC, labkey-klum requested changes
See comments about capping the number of times you refresh the mail record page. Another approach would be to hit the daily digest API at the end of `doCreateSteps` which should reset the notifications so you don't have to account for that initial email from creation, you could also clear out the mail records at that start of each test by unchecking the `Record email messages sent` checkbox on the webpart, that way you are only looking for a single email in each test.

2021-08-03 21:17 UTC, labkey-sweta commented
> Record email messages sent

Updated the test.

2021-08-05 16:19 UTC, labkey-klum approved these changes
if we fail to send an email then the code at line : 179 will just loop continuously, not great but I guess the test will time out at the 3 minute mark?

2021-08-05 16:21 UTC, merged

2021-08-05 17:07 UTC, labkey-sweta commented
> if we fail to send an email then the code at line : 179 will just loop continuously, not great but I guess the test will time out at the 3 minute mark?

Yes, test will timeout.