Issue 43647: SM: creating aliquots for a sample type with a required field gives an error
LabKey/platform pull request #2524
Opened 2021-08-05 23:48 UTC by XingY

#### Rationale
RequiredValidator fails import/creation for aliquots when the sample type has require fields. This PR modifies the import so that aliquots can bypass the required field validator

#### Related Pull Requests
* 

#### Changes
*  skip RequiredValidation for sample fields that are required, if the sample is an aliquot

2021-08-06 20:32 UTC, labkey-susanh requested changes

2021-08-06 20:32 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            }
Do we need both string and number to account for "123" and 123 as row Ids?

2021-08-06 20:32 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +        DataIteratorBuilder dib = new ExpDataIterators.ExpMaterialDataIteratorBuilder(getQueryTable(), data, container, user);
I think you also need this block from `super.createImportDIB`:
```
        if (_enableExistingRecordsDataIterator)
        {
            // some tables need to generate PK's, so they need to add ExistingRecordDataIterator in persistRows() (after generating PK, before inserting)
            dib = ExistingRecordDataIterator.createBuilder(dib, getQueryTable(), getSelectKeys(context));
        }
```

2021-08-06 21:43 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            }
No, we support "123" as SampleID, aliquotedFrom is always sampleId, not rowId

2021-08-06 21:44 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +        DataIteratorBuilder dib = new ExpDataIterators.ExpMaterialDataIteratorBuilder(getQueryTable(), data, container, user);
I don't think so, SampleTypeUpdateServiceID is the subclass that specifically disable this, see
`// we do this in ExpMaterialTableImpl.persistRows() via ExpDataIterators.PersistDataIteratorBuilder
        _enableExistingRecordsDataIterator = false;`

2021-08-09 13:58 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            }
Got it.  Thanks.

2021-08-09 13:59 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +        DataIteratorBuilder dib = new ExpDataIterators.ExpMaterialDataIteratorBuilder(getQueryTable(), data, container, user);
Ah ha.

2021-08-09 13:59 UTC, labkey-susanh approved these changes

2021-08-09 20:08 UTC, merged