25741: Support for trigger scripts on UI bulk insert
LabKey/platform pull request #2530
Opened 2021-08-09 20:52 UTC by labkey-klum

#### Rationale
- https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=25741

Also represents an opportunity to clean up some of the variety of legacy code paths which insert data into datasets so that they are funneled through the QUS in order to get more of a uniform behavior.
 
#### Changes
- User `BatchValidationException` instead of `List<String>` for errors
- Refactor `DatasetDefinition.importDatasetData` to go through the `QueryUpdateService` to load data.
- Consolidate code in `StudyManager.importDatasetData` to go through common code paths and push more options into `DataIteratorContext`

2021-08-10 21:15 UTC, labkey-matthewb requested changes
I'm really happy we're continuing the conversion to QUS!

2021-08-10 21:15 UTC, labkey-matthewb commented on study/src/org/labkey/study/assay/StudyPublishManager.java
> +            if (!targetContainer.hasPermission(user, AdminPermission.class) && targetContainer.hasPermission(user, InsertPermission.class))
targetContainer.hasPermissions(Set.of(...))

2021-08-10 21:15 UTC, labkey-matthewb commented on study/src/org/labkey/study/assay/StudyPublishManager.java
> +                Set<Role> contextualRoles = new HashSet<>(user.getStandardContextualRoles());
Set.of(user.getStandardContextualRoles(),RoleManager.getRole(FolderAdminRole.class)) is shorter

2021-08-10 21:15 UTC, labkey-matthewb commented on study/src/org/labkey/study/model/StudyManager.java
> +        options.put(DatasetUpdateService.Config.ForUpdate, Boolean.valueOf(false));
why not Boolean.FALSE?  (several usages in patch)

2021-08-10 21:15 UTC, labkey-matthewb commented on study/src/org/labkey/study/query/DatasetUpdateService.java
> +        ForUpdate               // expected: Boolean
Should we add an new value to the InsertOption enum so we don't need a similar looking ForUpdate?

2021-08-11 00:49 UTC, labkey-klum commented on study/src/org/labkey/study/assay/StudyPublishManager.java
> +            if (!targetContainer.hasPermission(user, AdminPermission.class) && targetContainer.hasPermission(user, InsertPermission.class))
can't really use that since the check is if you can insert but aren't already an admin.

2021-08-11 00:51 UTC, labkey-klum commented on study/src/org/labkey/study/assay/StudyPublishManager.java
> +                Set<Role> contextualRoles = new HashSet<>(user.getStandardContextualRoles());
Hmmm, this didn't seem to work since the first param is `Set<Role>` and the second is `Role`, it ends up returning `Set<Object>`

2021-08-11 00:51 UTC, labkey-klum commented on study/src/org/labkey/study/model/StudyManager.java
> +        options.put(DatasetUpdateService.Config.ForUpdate, Boolean.valueOf(false));
sounds good, done

2021-08-11 01:00 UTC, labkey-klum commented on study/src/org/labkey/study/query/DatasetUpdateService.java
> +        ForUpdate               // expected: Boolean
I generally like that idea although looking closer at when we use that flag doesn't map very cleanly to any of the existing `InsertOption` enums. We set it to both true or false for either INSERT or IMPORT and maybe it's wrong in it's current state. 

Looking at `DatasetDataIteratorBuilder:145` it appears to be used to control whether we allow a managed key to be imported. Maybe just renaming this Enum to make it clearer is the better route since it doesn't appear to be related to an insert option.

2021-08-11 17:30 UTC, labkey-matthewb approved these changes

2021-08-25 16:15 UTC, merged