Enable import for Folder/Study archives when paired with the cloud module
LabKey/platform pull request #2541
Opened 2021-08-12 01:14 UTC by labkey-ians

#### Rationale
Item #9160 - [Labkey R&D-EI - Reload Study from S3 root via Folder Management UI](https://docs.google.com/document/d/1Fe9tyqIdvMTyu7gFYm4PJrfFMXMf1oQbpVXXdvRzqn8/)

#### Related Pull Requests
* Cloud: TBD
* DataIntegration: TBD

#### Changes
* Refactors to replace some usages of File with nio.Path
  * Deprecated several API methods in preference for Path based versions
  * Fixed some typos & NPEs along the way
* Added cloud service task to download study archive files
  * Adjusted context and root Job properties to account for cloud --> temp directory path change during processing

2021-08-18 21:17 UTC, labkey-klum commented on api/src/org/labkey/api/admin/FolderImportContext.java
> +//    // Assume file was referenced in folder.xml file   // TODO: Context should hold onto the root -- shouldn't have to pass it in
is there a reason to keep this code around?

2021-08-18 21:33 UTC, labkey-klum commented on api/src/org/labkey/api/pipeline/PathSerialization.java
>          public Path deserialize(JsonParser parser, DeserializationContext context) throws IOException
add a `Nullable` annotation?

2021-08-18 21:34 UTC, labkey-klum commented on api/src/org/labkey/api/pipeline/PathSerialization.java
> +                return Path.of(str); //TODO this will cause issues...
would it be better to throw then?

2021-08-18 21:52 UTC, labkey-klum commented on api/src/org/labkey/api/pipeline/PipelineProvider.java
> +        return true;
Are we really saying that all providers now support cloud storage? Wouldn't it be safer to keep this unchanged and just override.

2021-08-18 22:00 UTC, labkey-klum commented on api/src/org/labkey/api/study/StudyService.java
> +    default boolean runStudyImportJob(Container c, User user, @Nullable ActionURL url, File studyXml, String originalFilename, BindException errors, PipeRoot pipelineRoot, ImportOptions options)
Is there any code that references this method?

2021-08-18 22:01 UTC, labkey-klum commented on api/src/org/labkey/api/util/FileType.java
> +//    public static List<FileType> findTypes(@NotNull List<FileType> types, @NotNull List<File> files)
delete?

2021-08-18 23:06 UTC, labkey-klum commented on study/src/org/labkey/study/pipeline/StudyReloadSourceJob.java
> +    public void downloadCloudArchive(Path studyXml, BindException errors)
This method is nearly identical to the version in `StudyImportJob`, we should try to consolidate otherwise it will probably bite us down the road.

2021-08-18 23:14 UTC, labkey-klum commented on study/src/org/labkey/study/importer/StudyImportInitialTask.java
> +        if (isCloudRoot)
`StudyFolderImporter` also checks whether the study dir has a cloud scheme. Should we do the same here?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/admin/InvalidFileException.java
> +    @Deprecated // prefer the Path version
Would we want to have this forward to the Path version?
```
this(root.toPath(), file.toPath(), t);
```

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/pipeline/PathSerialization.java
> +//            return Path.of(URI.create(str));
remove commented code?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/pipeline/PathSerialization.java
> +                }
All of these TODOs make me wonder if this does work.  If it works in limited cases, do we need or have some corresponding documentation?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/pipeline/PipeRoot.java
> +    //TODO implement this properly
Properly?  Do we know what that means here?  Something to do now?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/pipeline/PipelineJob.java
> +        throw new PipelineJobException("Unable to update working root. Updates not supported by job");
```suggestion
        throw new PipelineJobException("Unable to update working root. Updates not supported by job.");

```

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/pipeline/PipelineJob.java
> +        if (null != _localDirectory & isDone())
when is this "finallyCleanUp" called when the job is not done?  Is this protection against an error case?  Or a case when nothing happened in the first place?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/pipeline/file/FileAnalysisJobSupport.java
> +        //TODO This needs implementation in derived classes...
Is this to be done in this PR?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/writer/FileSystemFile.java
> +            //TODO do more...
More?  What did you have in mind?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/writer/FileSystemFile.java
> +            //TODO should do more here...
Do more?  Is there some way to recover?

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/writer/FileSystemFile.java
> +            //TODO do more here...
Same comment here.  Let's either remove this TODO or make the comment more meaningful or do whatever "more" is in this case.

2021-08-18 23:59 UTC, labkey-susanh commented on api/src/org/labkey/api/writer/PrintWriters.java
> +            // TODO Retain old behavior
What is the old behavior that needs to be retained?  I'm guessing we don't want to change the behavior.

2021-08-18 23:59 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpDataTableImpl.java
> +                    excel.write(f.getOutputStream("excel.xlsx")); //TODO should this outputStream be closed?
Closing the stream seems a good idea unless that happens elsewhere.

2021-08-18 23:59 UTC, labkey-susanh commented on pipeline/src/org/labkey/pipeline/PipelineDirectoryImpl.java
> +import java.util.stream.Stream;
Needed?

2021-08-18 23:59 UTC, labkey-susanh commented on pipeline/src/org/labkey/pipeline/api/PipeRootImpl.java
> +    //TODO why do we have both of these? 1
Are both referenced?

2021-08-18 23:59 UTC, labkey-susanh commented on pipeline/src/org/labkey/pipeline/api/PipelineManager.java
> +        return importDir.toAbsolutePath().resolve(xmlFileName);
Can `xmlFileName` be null?

2021-08-18 23:59 UTC, labkey-susanh commented on pipeline/src/org/labkey/pipeline/importer/FolderImportTask.java
> +        return job.getPipeRoot().isCloudRoot(); //TODO should this check to target file's protocol?
I don't know the answer to the TODO question.  Is there a way to do that check here?  How would we have `isCloudRoot` return true but the protocol is not as expected?

2021-08-18 23:59 UTC, labkey-susanh commented on study/api-src/org/labkey/api/specimen/pipeline/AbstractSpecimenTask.java
> +//        }
Remove?

2021-08-18 23:59 UTC, labkey-susanh commented on study/src/org/labkey/study/importer/StudyImportJob.java
> +                    Path importRoot = CloudStoreService.get().copyExpandedStudyArchiveLocally(studyXml, _ctx.getXml(), _ctx.getRoot().getLocation(), getPipeRoot(), _ctx.getLoggerGetter().getLogger(),
Probably a naive question at this stage, but is there a chance that the study in the cloud is going to be too big to copy locally?

2021-08-18 23:59 UTC, labkey-susanh commented on study/src/org/labkey/study/importer/StudyImporterFactory.java
> +                //TODO unify with other download location
Is this to be done now?

2021-08-18 23:59 UTC, labkey-susanh commented on study/src/org/labkey/study/importer/StudyImporterFactory.java
> +//                new StudyImportContext(user, c, studyDoc, ctx.getDataTypes(), ctx.getLoggerGetter(), studyDir);
remove?

2021-08-18 23:59 UTC, labkey-susanh commented on study/src/org/labkey/study/importer/StudyReload.java
> +            if (!study.hasPermission(user, UpdatePermission.class))  //TODO double check required permission
The permission seems correct to me, but you could verify by impersonating an editor and seeing if reload is available.

2021-08-18 23:59 UTC, labkey-susanh commented on study/src/org/labkey/study/importer/StudyReload.java
> +                    studyXml = root.resolveRelativePath("study.xml");  //TODO this is likely wrong...
Do we know what the right answer is or why it is likely wrong?  Would be worth adding a comment about why it seems wrong, at least.

2021-08-19 00:19 UTC, labkey-klum commented on pipeline/src/org/labkey/pipeline/importer/FolderImportTask.java
> +            Path importRoot = CloudStoreService.get().downloadFolderArchive(job);
I'm confused by the abstraction of the code which handles the downloading of bits from a cloud store. In this case we are interfacing directly with the `CloudStoreService` to download the archive. In the study import and reload cases the pipeline jobs which implement `StudyJobSupport.downloadCloudArchive` are called on to handle the download. Is there a reason why the pipeline job in the folder import case can't do the same thing?

Additionally the code in `CloudFolderImporter` and `CloudStudyImporter` could be pushed together as they already share some duplicate code. It seems like the only distinction is one downloads a folder archive and the other downloads an expanded archive?

2021-08-19 00:31 UTC, labkey-klum commented on pipeline/src/org/labkey/pipeline/importer/FolderImportTask.java
> +            Path importRoot = CloudStoreService.get().downloadFolderArchive(job);
If we did push more of this code into the pipeline job then `updateWorkingRoot` could be handled inside of the job as part of the download operation. Then we don't need to add the method to the abstract base since it seems like calling this method only makes sense in the context of downloading into a temp location (the study pipeline jobs seem to be doing this in `generateImportContext`).

2021-08-19 00:35 UTC, labkey-klum requested changes
It would be nice to clean up the abstraction of the code which invokes and implements the downloading of either a compressed or expanded study or folder archive.

2021-08-21 00:26 UTC, labkey-ians commented on api/src/org/labkey/api/admin/FolderImportContext.java
> +//    // Assume file was referenced in folder.xml file   // TODO: Context should hold onto the root -- shouldn't have to pass it in
removed

2021-08-21 00:26 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/PathSerialization.java
>          public Path deserialize(JsonParser parser, DeserializationContext context) throws IOException
added

2021-08-21 00:27 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/PathSerialization.java
> +                return Path.of(str); //TODO this will cause issues...
If the string path isn't viable it will cause an exception, the existing message is fairly clear (at least as clear as I would make it) rather than catch and rethrow, I think it makes sense to leave it as is and let the parser throw if needed.

2021-08-21 00:27 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/PipelineProvider.java
> +        return true;
switched

2021-08-21 00:27 UTC, labkey-ians commented on api/src/org/labkey/api/study/StudyService.java
> +    default boolean runStudyImportJob(Container c, User user, @Nullable ActionURL url, File studyXml, String originalFilename, BindException errors, PipeRoot pipelineRoot, ImportOptions options)
I'm a little concerned an external reference may exist, but I removed the method for now.

2021-08-21 00:27 UTC, labkey-ians commented on api/src/org/labkey/api/util/FileType.java
> +//    public static List<FileType> findTypes(@NotNull List<FileType> types, @NotNull List<File> files)
deleted

2021-08-21 00:27 UTC, labkey-ians commented on study/src/org/labkey/study/pipeline/StudyReloadSourceJob.java
> +    public void downloadCloudArchive(Path studyXml, BindException errors)
consolidated

2021-08-21 00:27 UTC, labkey-ians commented on study/src/org/labkey/study/importer/StudyImportInitialTask.java
> +        if (isCloudRoot)
yes, I think...

2021-08-21 00:28 UTC, labkey-ians commented on api/src/org/labkey/api/admin/InvalidFileException.java
> +    @Deprecated // prefer the Path version
fixed

2021-08-21 00:28 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/PathSerialization.java
> +//            return Path.of(URI.create(str));
removed

2021-08-21 00:28 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/PipeRoot.java
> +    //TODO implement this properly
this TODO is a left over implementation thought.

I think using the implemented getRootNioPath will work correctly and gives the Root Impl the authority of how to relativize the Path.

2021-08-21 00:28 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/PipelineJob.java
> +        throw new PipelineJobException("Unable to update working root. Updates not supported by job");
added

2021-08-21 00:30 UTC, labkey-ians commented on study/src/org/labkey/study/importer/StudyImportJob.java
> +                    Path importRoot = CloudStoreService.get().copyExpandedStudyArchiveLocally(studyXml, _ctx.getXml(), _ctx.getRoot().getLocation(), getPipeRoot(), _ctx.getLoggerGetter().getLogger(),
Absolutely it is possible. Currently jClouds would be the generator of the Exception on the download attempt. We don't currently check for size constraints but we probably should. I think this might be worth breaking out as a bug to follow up with after the main story is solidified. We also dont do this for the TargetedMS imports AFICT

2021-08-21 00:31 UTC, labkey-ians commented on study/src/org/labkey/study/importer/StudyImporterFactory.java
> +//                new StudyImportContext(user, c, studyDoc, ctx.getDataTypes(), ctx.getLoggerGetter(), studyDir);
removed

2021-08-21 00:31 UTC, labkey-ians commented on study/src/org/labkey/study/importer/StudyReload.java
> +                    studyXml = root.resolveRelativePath("study.xml");  //TODO this is likely wrong...
The thought was that I was using the incorrect resolution method, but I think it is actually correct. Looking at the previous method AFICT they resolve the same.

2021-08-21 00:37 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/PipelineJob.java
> +        if (null != _localDirectory & isDone())
This is protection against an error case -- specifically when there is an error and there are notifications to clean up. See line ~1813 where this method is called. The method references the log file, but if this method executes before that then the log file has moved--so it causes a secondary FileNotFoundException.

2021-08-23 23:02 UTC, labkey-ians commented on api/src/org/labkey/api/writer/FileSystemFile.java
> +            //TODO do more here...
Was thinking some additional logging, but there isn't an obvious logger available.

Removed

2021-08-23 23:02 UTC, labkey-ians commented on api/src/org/labkey/api/writer/FileSystemFile.java
> +            //TODO should do more here...
Was thinking some additional logging, but there isn't an obvious logger available.

Removed.

2021-08-23 23:02 UTC, labkey-ians commented on api/src/org/labkey/api/writer/FileSystemFile.java
> +            //TODO do more...
Was thinking some additional logging, but there isn't an obvious logger available.

Removed.

2021-08-23 23:34 UTC, labkey-ians commented on api/src/org/labkey/api/writer/PrintWriters.java
> +            // TODO Retain old behavior
It was just throwing, removed TODO, and move try block to Path method to catch the new IOException.

2021-08-24 00:49 UTC, labkey-ians commented on api/src/org/labkey/api/pipeline/file/FileAnalysisJobSupport.java
> +        //TODO This needs implementation in derived classes...
Short answer is no. Some of these are complicated, and also not part of LabKey's managed code

2021-08-24 00:49 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/ExpDataTableImpl.java
> +                    excel.write(f.getOutputStream("excel.xlsx")); //TODO should this outputStream be closed?
done.

2021-08-24 00:49 UTC, labkey-ians commented on pipeline/src/org/labkey/pipeline/PipelineDirectoryImpl.java
> +import java.util.stream.Stream;
removed

2021-08-24 00:50 UTC, labkey-ians commented on pipeline/src/org/labkey/pipeline/api/PipeRootImpl.java
> +    //TODO why do we have both of these? 1
not any more...

2021-08-24 00:50 UTC, labkey-ians commented on pipeline/src/org/labkey/pipeline/api/PipelineManager.java
> +        return importDir.toAbsolutePath().resolve(xmlFileName);
Not as far as I can tell, I trace it back to static strings from PipelineController:~1319

2021-08-24 00:52 UTC, labkey-ians commented on pipeline/src/org/labkey/pipeline/importer/FolderImportTask.java
> +        return job.getPipeRoot().isCloudRoot(); //TODO should this check to target file's protocol?
Consolidated to use the FileUtil to check URI protocol.  (My thought was if we ever allowed GCS) I think by using the helper method here we can ensure that that would be the case.

2021-08-24 00:52 UTC, labkey-ians commented on study/api-src/org/labkey/api/specimen/pipeline/AbstractSpecimenTask.java
> +//        }
done.

2021-08-24 00:53 UTC, labkey-ians commented on study/src/org/labkey/study/importer/StudyImporterFactory.java
> +                //TODO unify with other download location
done.

2021-08-24 00:53 UTC, labkey-ians commented on study/src/org/labkey/study/importer/StudyReload.java
> +            if (!study.hasPermission(user, UpdatePermission.class))  //TODO double check required permission
verified.

2021-08-24 23:51 UTC, labkey-jeckels reviewed
Smaller suggestions.

Also, there aren't a lot of places here where we check if CloudStoreService.get() == null, but eventually we'll probably want a dummy implementation that lets us avoid doing null checks everywhere, throwing UnsupportedOperationExceptions or no-opping as appropriate.

2021-08-24 23:51 UTC, labkey-jeckels commented on pipeline/src/org/labkey/pipeline/api/PipelineManager.java
> +        if ("study.xml".equals(xmlFileName) && archiveFile.getFileName().toString().endsWith(".folder.zip"))
Case sensitivity

2021-08-24 23:51 UTC, labkey-jeckels commented on pipeline/src/org/labkey/pipeline/api/PipelineManager.java
> +        if (archiveFile.getFileName().toString().endsWith(".zip"))
Case sensititivity

2021-08-24 23:51 UTC, labkey-jeckels commented on study/api-src/org/labkey/api/specimen/pipeline/AbstractSpecimenTask.java
> +                        specimenArchive = ARCHIVE_FILE_TYPE.getFile(inputFile.getParent().toFile(), transformer.getFileType().getBaseName(inputFile));
Won't this blow up if it's S3-backed?

2021-08-24 23:51 UTC, labkey-jeckels commented on study/api-src/org/labkey/api/specimen/pipeline/AbstractSpecimenTask.java
> +                                    log.error("Unable to delete file: " + p);
Include exception here like a few lines lower?

2021-08-24 23:51 UTC, labkey-jeckels commented on study/src/org/labkey/study/importer/StudyImportProvider.java
> +            return pathString.endsWith("study.xml") || pathString.endsWith(".study.zip") || pathString.endsWith(".folder.zip");
Case sensitivity

2021-08-26 03:32 UTC, Sigmonia commented on pipeline/src/org/labkey/pipeline/api/PipelineManager.java
> +        if ("study.xml".equals(xmlFileName) && archiveFile.getFileName().toString().endsWith(".folder.zip"))
fixed

2021-08-26 03:32 UTC, Sigmonia commented on pipeline/src/org/labkey/pipeline/api/PipelineManager.java
> +        if (archiveFile.getFileName().toString().endsWith(".zip"))
fixed

2021-08-26 03:33 UTC, Sigmonia commented on study/api-src/org/labkey/api/specimen/pipeline/AbstractSpecimenTask.java
> +                        specimenArchive = ARCHIVE_FILE_TYPE.getFile(inputFile.getParent().toFile(), transformer.getFileType().getBaseName(inputFile));
Made a change here to use nio.Path

2021-08-26 03:47 UTC, Sigmonia commented on study/api-src/org/labkey/api/specimen/pipeline/AbstractSpecimenTask.java
> +                                    log.error("Unable to delete file: " + p);
Adjusted to use FileUtil.dirDelete

2021-08-26 03:47 UTC, Sigmonia commented on study/src/org/labkey/study/importer/StudyImportProvider.java
> +            return pathString.endsWith("study.xml") || pathString.endsWith(".study.zip") || pathString.endsWith(".folder.zip");
fixed

2021-08-26 19:55 UTC, Sigmonia commented on pipeline/src/org/labkey/pipeline/importer/FolderImportTask.java
> +            Path importRoot = CloudStoreService.get().downloadFolderArchive(job);
So I did unify the download code into the `CloudArchiveImportSupport` which is in turn implemented by the jobs. This is also where the updateWorkingRoot method is now implemented. I think this allows us to isolate the cloud support to those jobs that implement that job supporter.

2021-09-01 21:58 UTC, labkey-klum approved these changes

2021-09-08 19:35 UTC, merged