Issue 43818: Indicate uninterruptible upgrade script state with a "lockfile"
LabKey/platform pull request #2594
Opened 2021-09-02 00:07 UTC by labkey-jeckels

#### Rationale
Some upgrade steps can be missed if Tomcat is shut down in the midst of the upgrade process. We want to avoid this and catch potential problems up front. We're doing that through a lock file that automation can monitor to easily understand the server's status, and the server will refuse to continue if it detects that a previous upgrade attempt was interrupted.

#### Changes
* Write a labkeyUpgradeLockFile to the deployment root (sibling file to the ./modules directory)
* Refuse to start up if a labkeyUpgradeLockFile already exists
* Delete labkeyUpgradeLockFile when startup is incomplete

### Notes
* This makes the critical section larger than may be strictly required for many startups but should be guaranteed to handle all upgrades, deferred and not
* This does NOT currently monitor pipeline jobs that may get queued to import or migrate data

2021-09-02 15:14 UTC, labkey-stuartm approved these changes

2021-09-02 20:54 UTC, labkey-adam requested changes

2021-09-02 20:54 UTC, labkey-adam commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        lockFile.delete();
In most cases, upgrade is not complete at this point. The rest of the message is usually "modules are being upgraded and initialized in the background".

I think the bottom of `afterUpgrade()` is closer to the right place. Need to verify that this gets called in all cases (including non-upgrade startup).

2021-09-08 00:59 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        lockFile.delete();
You're correct - I was misunderstanding the threading behavior. afterUpgrade() appears to be called in all startups in my testing.

Note that this change may be annoying on dev machines as it takes a while to get that far into the startup process. If so, we could pull it back by checking if we have any deferred upgrades, or perhaps even if there are any version changes, and delete the lock file much earlier if there won't be any upgrade work to do.

2021-09-08 01:50 UTC, labkey-adam commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        lockFile.delete();
So the dev machine annoyance is the fact that restarting before an upgrade is complete means a ConfigurationException and need to manually delete the lock file? We could tone down the warning in dev mode... e.g., log a loud warning but delete the file and continue upgrade.

2021-09-08 16:23 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        lockFile.delete();
I also thought about that approach but hadn't implemented it. Assuming other devs have similar build/restart patterns as me, it seems worth special casing. Update pushed.

2021-09-08 16:47 UTC, curiositycasualty commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        lockFile.delete();
Would it make sense, or be possible to conceal this behind a feature flag we could use to keep this disabled for dev scenarios?

2021-09-08 17:37 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        lockFile.delete();
@curiositycasualty I pushed a change that logs a warning when you're running in dev mode (an existing flag) but doesn't halt the startup process as it does in production mode.

2021-09-08 20:16 UTC, labkey-adam commented on api/src/org/labkey/api/module/ModuleLoader.java
> +        lockFile.delete();
Dev mode seems best to me since we want to make a fuss about interrupted upgrades on all production servers, including those that don't use our automation (and hence don't use any special feature flags).

2021-09-08 20:42 UTC, labkey-adam approved these changes
Couple minor suggestions

2021-09-08 20:42 UTC, labkey-adam commented on api/src/org/labkey/api/module/ModuleLoader.java
> +            writer.write("LabKey instance beginning initialization at " + new Date());
We try not to output `Date.toString()`...
```suggestion
            writer.write("LabKey instance beginning initialization at " + DateUtil.formatDateTimeISO8601(new Date()));

```

2021-09-08 20:42 UTC, labkey-adam commented on api/src/org/labkey/api/module/ModuleLoader.java
> +                throw new ConfigurationException("Lock file " + FileUtil.getAbsoluteCaseSensitiveFile(result) + " already exists - a previous upgrade attempt may have left the server in an indetermin
```suggestion
                throw new ConfigurationException("Lock file " + FileUtil.getAbsoluteCaseSensitiveFile(result) + " already exists - a previous upgrade attempt may have left the server in an indeterminate state. Proceed with extreme caution as the database may not be properly upgraded. To continue, delete the file and restart Tomcat.");

```

2021-09-09 03:56 UTC, merged