Link to Study Dataset Category Assignment: Sample Types
LabKey/platform pull request #2596
Opened 2021-09-02 16:50 UTC by RosalineP

#### Rationale
It is desired that we add functionality to be able to categorize the dataset resulting from a link to study at the sample type design level, for the auto-link case. For the manual link to study case, the dataset category assignment can now happen at the initial 'publishStart' page.
This functionality was initially implemented for Assay link to study, and these changes will allow for functionality parity on Sample Types.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/2540
* https://github.com/LabKey/labkey-ui-components/pull/622

#### Changes
* Support roundtrip of new sample type property, 'AutoLinkCategory'
* Add call to ensureViewCategory() upon automatic or manual link to study cases to generate or locate dataset category
* Slightly update publishChooseStudy.jsp wording
* Reorder where 'Auto Link Target Container' appears on `showSampleType` view of sample type within Sample Type Properties

2021-09-02 17:48 UTC, RosalineP commented on api/src/org/labkey/api/study/publish/publishChooseStudy.jsp
> +            String autoLinkCategoryTip = "Specify the desired category for the Dataset that will be created (or appended to) in the target study when rows are linked. " +
It was a little bit of a cheat to just change 'Assay Dataset' to 'Dataset' in order to be generic to both link to study types. 
The alternative is to pass a way to tell whether we're coming from an assay or a sample type, or to use the existing values passed to figure it out. I was a fan of just changing the text to 'Dataset' because I think that that's still clear and informative, but I'm open to other thoughts!

2021-09-02 18:00 UTC, RosalineP commented on api/src/org/labkey/api/study/publish/StudyPublishService.java
>                            Pair<Dataset.PublishSource, Integer> publishSource,
Note that the publishData() starting on line 87 (only difference in signature is that it doesn't include the 'targetContainer' param) has only one usage. I waffled on whether to change that usage to the publishData() with the 'targetContainer' param set to null, and delete the function signature. I ultimately thought I'd leave it as-is to make it a little clearer that Category setting in link-to-study is not supported in (what seems to be) Vaccine Study Design study generation

2021-09-02 18:26 UTC, labkey-klum commented on api/src/org/labkey/api/study/publish/StudyPublishService.java
>                            Pair<Dataset.PublishSource, Integer> publishSource,
sounds right, good call.

2021-09-02 18:31 UTC, labkey-klum commented on api/src/org/labkey/api/study/publish/publishChooseStudy.jsp
> +            String autoLinkCategoryTip = "Specify the desired category for the Dataset that will be created (or appended to) in the target study when rows are linked. " +
This is a reasonable change, we can always revisit if users find it unclear but I'm guessing this will be sufficient.

2021-09-02 18:33 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
> +                                              @Nullable Container autoLinkTargetContainer, @Nullable String autoLinkCategory)
lol so many parameters, at some point we might consider moving to a builder pattern.

2021-09-02 18:49 UTC, labkey-klum requested changes
Just wanted to verify that the new property is round-tripped in folder export. It looks like schema changes were made to the xsd but I didn't notice any changes to `XarReader` or `XarExporter`.

2021-09-02 19:22 UTC, RosalineP commented
> Just wanted to verify that the new property is round-tripped in folder export. It looks like schema changes were made to the xsd but I didn't notice any changes to `XarReader` or `XarExporter`.

Oop, I missed that because it wasn't in my tasks. I've implemented it as of the last commit e83c627!

2021-09-02 19:49 UTC, labkey-klum approved these changes

2021-09-09 17:09 UTC, merged

2021-09-09 20:41 UTC, XingY commented on experiment/resources/schemas/dbscripts/sqlserver/exp-21.010-21.011.sql
> +ALTER TABLE exp.MaterialSource ADD AutoLinkCategory VARCHAR(200) NULL;
@labkey-adam Should we stick with NVARCHAR for sqlserver, or does it not matter?

2021-09-09 21:40 UTC, labkey-adam commented on experiment/resources/schemas/dbscripts/sqlserver/exp-21.010-21.011.sql
> +ALTER TABLE exp.MaterialSource ADD AutoLinkCategory VARCHAR(200) NULL;
Yes, I would stick with NVARCHAR