Issue 43853: Update GetContainersAction to add container user permissions check before adding results to response
LabKey/platform pull request #2611
Opened 2021-09-09 19:35 UTC by cnathe

#### Rationale
https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=43853

#### Changes
* Add check that user has read access to a container before adding info to the response object

2021-09-09 21:08 UTC, labkey-jeckels requested changes

2021-09-09 21:08 UTC, labkey-jeckels commented on core/src/org/labkey/core/portal/ProjectController.java
> +                    if (c != null && c.hasPermission(user, ReadPermission.class)) // 43853
We should at least consider the desired behavior when a user has no access to the project but has read permission to a subfolder.

getContainerJSON() calls to getVisibleChildren() which does this kind of filtering and recursion. Do we need to pop this up a level?

2021-09-13 14:09 UTC, cnathe commented on core/src/org/labkey/core/portal/ProjectController.java
> +                    if (c != null && c.hasPermission(user, ReadPermission.class)) // 43853
Good point. I updated this PR so that they check for if the user has container read perm is done within the getContainerJSON. This should account for the scenario you mentioned of the user having perm to a child container but not the parent / requested container.

2021-09-13 16:54 UTC, labkey-jeckels approved these changes

2021-09-13 21:02 UTC, merged