Time out when acquiring locks during transaction setup instead of deadlocking
LabKey/platform pull request #2650
Opened 2021-09-29 00:18 UTC by labkey-jeckels

#### Rationale
Deadlocking the server is really bad. Similar to how we switched to timing out with an exception when DB connections aren't available from the pool, we can time out when trying to acquire (most) lock objects passed to DbScope.ensureTransaction()

#### Changes
* Time out after 2 minutes of failing to get a lock
* Unwind already acquired locks when one fails
* New test coverage
* Enable test that now seems to pass
* More descriptions for loggers

2021-09-29 17:46 UTC, labkey-adam requested changes
Looks like a connection leak in `testLockException()`

2021-09-29 21:13 UTC, labkey-jeckels commented
@labkey-adam Indeed. Fixed with my latest commit. I'll kick off the dailies to make sure this doesn't introduce other subtle problems.

2021-09-29 21:14 UTC, labkey-jeckels commented
https://teamcity.labkey.org/buildConfiguration/LabkeyTrunk_DailyPostgres_2/1553901

2021-09-29 23:43 UTC, labkey-adam approved these changes

2021-09-30 01:07 UTC, labkey-jeckels commented
@labkey-adam I've made a number of followup changes here but they're not as exciting as the original change. Up to you if you want to review again. I'll merge tomorrow if I don't hear objections.

2021-09-30 04:14 UTC, labkey-adam commented
Seem fine to me

2021-09-30 16:03 UTC, merged