Unique names for data classes and sample types
LabKey/platform pull request #2682
Opened 2021-10-11 21:27 UTC by labkey-klum

#### Rationale
For this [story ](https://docs.google.com/document/d/1N6xfULI198pbU7xYdijYi4jmEg8n1a9s5PcPc5Tb4w0/edit) we want to support an administrative ability to set an optional prefix for data classes and sample types on a per container basis. 

We also will want to give administrators the ability to disable manually inserting/updating a name for sample types and data classes. This should make is so the name field is removed from all insert/update forms for LKS, LKB, LKSM and raise an error if a name comes in through an API endpoint.

#### Related Pull Requests
- https://github.com/LabKey/sampleManagement/pull/723
- https://github.com/LabKey/labkey-ui-components/pull/652
- https://github.com/LabKey/biologics/pull/1023

#### Changes
- Define a `NameExpressionOptionService` with a default NoOp implementation. An actual implementation will be provided in the `SampleManagementModule`
- If users are not allowed to manually insert names
  - Remove the name field for insert/update views
  - Add validation in the name expression `DataIterator` to fail if detected
  - Disallow removing the name expression from the domain editors
  - For samples, if the `UpdateExisting` option is specified, fail only if a specified name doesn't exist in the database

2021-10-12 13:49 UTC, cnathe commented
@labkey-klum I'm not sure if it was part of this story or not, but Rosaline and I were talking about some changes in the Field editor related to this container prefix and the per sample type naming pattern. She was demoing the container prefix part to me and mentioned that if the sample type had a naming pattern and then the container prefix was updated, then that updated prefix would override and change the per sample type naming pattern. Is this as expected? For example, if my sample type had a naming pattern of "PREFIX-Blood-${genId}" and the container prefix was changed to "PRX", I would not have expected the sample type naming pattern to then be set to "PRX". I would see it being updated to "PRX-Blood-${genId}". Just wanted to check in on this. Thanks.

2021-10-13 19:40 UTC, labkey-susanh approved these changes

2021-10-13 19:40 UTC, labkey-susanh commented on api/src/org/labkey/api/dataiterator/NameExpressionDataIterator.java
> +                    getErrors().addRowError(new ValidationException("Manual entry of names has been disabled for this folder. Only naming pattern generated names are allowed."));
```suggestion
                    getErrors().addRowError(new ValidationException("Manual entry of names has been disabled for this folder. Only naming-pattern-generated names are allowed."));
```
Or, if you're anti-hyphen, "Only names generated by naming patterns are allowed."

2021-10-13 19:40 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/api/NameExpressionOptionService.java
> +     * Returns whether user specified names for samples and dataclasses are permitted for this folder.
```suggestion
     * Returns whether user-specified names for samples and dataclasses are permitted for this folder.
```

2021-10-13 19:40 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/api/NameExpressionOptionService.java
> +     * Set whether user specified names for samples and dataclasses are allowed for this folder. If set to false
```suggestion
     * Set whether user-specified names for samples and dataclasses are allowed for this folder. If set to false
```

2021-10-13 19:40 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
> +                // shut off this field in insert and update views if user specified names are not allowed
```suggestion
                // shut off this field in insert and update views if user-specified names are not allowed
```

2021-10-13 19:40 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/api/NameExpressionOptionService.java
> +            return null;
Should this return `nameExpression`?

2021-10-13 19:40 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                                addRowError("Manual entry of names has been disabled for this folder. Only naming pattern generated names (or existing names) are allowed.");
```suggestion
                                addRowError("Manual entry of names has been disabled for this folder. Only naming-pattern- generated names (or existing names) are allowed.");

```

2021-10-13 19:40 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                            addRowError("Manual entry of names has been disabled for this folder. Only naming pattern generated names are allowed.");
```suggestion
                            addRowError("Manual entry of names has been disabled for this folder. Only naming-pattern-generated names are allowed.");

```

2021-10-13 19:40 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
> +                            if (!rowExists(currNameObj.toString()))
This seems like the sort of thing the ExistingRecordDataIterator was designed for, but I don't think it's in the mix here. This stashed set of names is probably sufficient, even if there's an outside chance the name won't be in the selected set.

2021-10-13 22:55 UTC, labkey-klum commented on api/src/org/labkey/api/exp/api/NameExpressionOptionService.java
> +            return null;
yes good catch

2021-10-15 13:38 UTC, labkey-susanh requested changes

2021-10-15 13:38 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
> +            aliquotNameExpression = svc.createPrefixedExpression(c, aliquotNameExpression, true);
I'm not sure the applying of prefixes should happen only when we don't allow user-specified names.  It seems like these settings are meant to be independent of each other.

2021-10-15 16:58 UTC, labkey-klum commented on experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
> +            aliquotNameExpression = svc.createPrefixedExpression(c, aliquotNameExpression, true);
This is true, I've split it out from that conditional

2021-10-15 17:00 UTC, labkey-susanh approved these changes

2021-10-19 06:38 UTC, merged