log row values when exception during script execution
LabKey/platform pull request #2704
Opened 2021-10-20 05:17 UTC by ankurjuneja

#### Rationale
Log the row values when there is an exception during server side trigger script execution. 

#### Related Pull Requests
* https://github.com/LabKey/ehrModules/pull/256

2021-10-21 21:51 UTC, labkey-jeckels requested changes

2021-10-21 21:51 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/triggers/ScriptTrigger.java
> +            throw UnexpectedException.wrap(e, "Script execution failed for row with values: " + Arrays.toString(args));
I like this approach, but we can do better when including the arguments into the error.

First, the init and complete functions will pass a single argument (the toString() of the TableInfo.TriggerType). Second, beforeUpdate and afterUpdate will pass both the new and old row maps and it won't be clear which is which.

I think we should pass a Function argument to _invokeTableScript() that knows how to render the args to the error message in a more descriptive way. init and complete don't have anything to include, and the insert/update/delete variants can include the row maps.

2021-11-03 22:44 UTC, labkey-adam approved these changes

2021-11-04 14:01 UTC, ankurjuneja commented
@labkey-jeckels thanks for looking into this, github is not letting me merge until you approve the requested chnages.

2021-11-04 15:03 UTC, labkey-jeckels approved these changes
I merged release21.7-SNAPSHOT into the ehrModules FB with the same name so that we can get the test results prior to merging.

I'm not sure that the ehrModules change will be that valuable with this new, centralized logging, but it shouldn't do any harm either so I approved it too.

2021-11-04 19:00 UTC, merged