Item 9574: Store aliquot count and total amount data in exp.materials table
LabKey/platform pull request #2715
Opened 2021-10-25 14:57 UTC by XingY

#### Rationale
Aliquot rollup columns (counts and volume) are computed columns which resulted in slow query time for large sample sets. This set of PRs implements the change to store the calculated rollup values in exp.material table, so they don't have to be computed at query time. 

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/2715
* https://github.com/LabKey/labkey-ui-components/pull/656
* https://github.com/LabKey/inventory/pull/326
* https://github.com/LabKey/sampleManagement/pull/729
* https://github.com/LabKey/biologics/pull/1032

#### Changes
* add rollup fields to exp.material table
* wire up rollup recompute on sampletype update, sample insert/delete
* fix Issue 44039: SM: Cannot import a LKSM project if the project contains sub-aliquots

2021-10-25 23:08 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/XarReader.java
> +                // create derivation and aliquot protocol using shared folder
Is the shared folder where these normally reside?

2021-10-25 23:08 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/Material.java
> +    //rollup columns
```suggestion
    // aliquot rollup columns
```

2021-10-25 23:08 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +                    aliquotParents.add((String) map.get("RootMaterialLSID"));
Seems like we might want a constant for this `RootMaterialLSID` field.  We use it a lot.

2021-10-25 23:27 UTC, XingY commented on experiment/src/org/labkey/experiment/XarReader.java
> +                // create derivation and aliquot protocol using shared folder
Yes, importing folders containing derivatives or aliquots would fail if those protocols don't reside on shared folder. A repro would be to import from an archive containing derivatives/aliquots into a clean DB. Then subsequent import using a different import archive would fail. In that case, a upgrade/fix script to set the protocols to shared folder is needed to fix those dbs.

2021-10-27 22:04 UTC, labkey-matthewb requested changes

2021-10-27 22:04 UTC, labkey-matthewb commented on experiment/resources/schemas/dbscripts/postgresql/exp-21.016-21.017.sql
> +                                                   );
Simpler to do lsid IN ()?
WHERE lsid IN (SELECT rootMaterialLsid FROM exp.material)

2021-10-27 22:04 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                ret.setUserEditable(false);
Is is possible to set these properties in exp.xml?

2021-10-27 22:04 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                    sampleTypeAliquotParents.get(sampleType).add(material.getRootMaterialLSID());
I think you can do this:
  sampleTypeAliquotParents.computeIfAbsent(sampleType, (k) -> new HashSet<>()).add(material.getRootMaterialLSID());

or look at org.apache.commons.collections.map.MultiValueMap

2021-10-27 22:04 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                        InventoryService.get().recomputeSamplesRollup(parentSampleIds, parentSampleType, container);
Since you ae grouping by SampleType, I assume that means that exp.material by itself does not have all the information required by recomputeSamplesRollup().  It would be interesting to figure out if we could make this self contained.  (I haven't read that code yet)

2021-10-27 22:04 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
>          else
super.deleteRows() will call deleteRow().  Does that need to be updated?

2021-10-27 22:04 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            ExperimentServiceImpl.get().deleteMaterialByRowIds(user, container, ids, true, _sampleType, false, false);
That probably should have been migrated to SampleTypeServiceImpl.  oops.

2021-10-28 19:06 UTC, XingY commented on experiment/resources/schemas/dbscripts/postgresql/exp-21.016-21.017.sql
> +                                                   );
good call, updated

2021-10-28 19:06 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                ret.setUserEditable(false);
yes, I did not know that

2021-10-28 19:07 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                        InventoryService.get().recomputeSamplesRollup(parentSampleIds, parentSampleType, container);
It's mainly to save a query to sample type for the configured sample type unit. Refactored

2021-10-28 19:07 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
>          else
It's handled in deleteMaterialByRowIds

2021-10-29 02:03 UTC, labkey-susanh approved these changes

2021-10-29 02:03 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                sql.add(true);
Does this need to be the True for the SQL dialect?

2021-10-29 16:48 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                sql.add(true);
I think if you use append then need to use dialect.getBooleanTRUE(), but with add it's not needed? I'm not sure, but the test plan called out sql server testing and they seem to pass

2021-10-29 18:00 UTC, labkey-matthewb approved these changes

2021-10-30 18:11 UTC, merged