StudyQuerySchema contextual role
LabKey/platform pull request #2725
Opened 2021-10-28 17:04 UTC by labkey-matthewb

#### Rationale
The study schema currently enforces non-readability of datasets by failing DatasetDefinition.getTableInfo().  If we want to allow control of readability by other means (other than just the study security configuration), we need to allow for the TableInfo to be checked for permissions later (e.g.  UserSchema.getTable()).

A side effect of the current implementation is that many tables did not correctly implement canRead() as they simply would never be returned to the user if canRead()==false.

This change generalizes how we elevate permissions in the StudySchema to use contextual roles and also correctly implements canRead() for tables in the study schema.

#### Related Pull Requests
* 

#### Changes
* StudyQuerySchema can take a contextual role in its constructor (replaces mustCheckPermissions flag)
* Study tables consistently implement canRead()
* The study schema is now responsible for hiding tables w/o read permission.

2021-10-29 16:35 UTC, labkey-adam commented
Build failing in `nircEHRModules` (newer repo) due to `canReadSchema()`: "attempting to assign weaker access privileges; was public"

2021-10-29 19:30 UTC, labkey-adam commented
@labkey-matthewb Bunch of "use DatasetTableImpl.hasPermission()" exceptions in the BVT-EHR runs

2021-10-29 22:55 UTC, labkey-adam requested changes
Everything reviewed and seems very close. Please review comments and get EHR, etc. tests in reasonable shape and I'll approve.

2021-10-29 22:55 UTC, labkey-adam commented on api/src/org/labkey/api/data/DataRegion.java
> +            TableInfo tinfoMain = getTable();
Why pull this up? Is it doing a required permissions check or something?

2021-10-29 22:55 UTC, labkey-adam commented on api/src/org/labkey/api/data/DataRegion.java
> +                Collection<Map<String, Object>> maps = new TableSelector(tinfoMain, selectKeyMap.values(), new PkFilter(getTable(), viewForm.getPkVals()), null).getMapCollection();
```suggestion
                Collection<Map<String, Object>> maps = new TableSelector(tinfoMain, selectKeyMap.values(), new PkFilter(tinfoMain, viewForm.getPkVals()), null).getMapCollection();
```

2021-10-29 22:55 UTC, labkey-adam commented on study/src/org/labkey/study/query/StudyQuerySchema.java
> +        if (null != ModuleLoader.getInstance().getModule("Specimen"))
You can check `null != SpecimenService.get()` instead

2021-11-01 16:33 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/DataRegion.java
> +            TableInfo tinfoMain = getTable();
I think that was an intermediate change before I switched this.hasPermission()

2021-11-02 00:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/DataRegion.java
> +            TableInfo tinfoMain = getTable();
changed in 21.11_fb_readerrole

2021-11-02 00:23 UTC, closed without merging