44112: Gather more metrics on study
LabKey/platform pull request #2742
Opened 2021-11-02 16:37 UTC by labkey-klum

#### Rationale
Add additional study metrics per this [issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=44112).

#### Changes
Additional metrics for:
- Number of studies with REDCap or CDISC repositories configured
- Number of studies created via Publish study
- Number of datasets of the following: demographics, "regular", and third key (split into managed third key vs user provided)
- Number of datasets created from assays
- Number of datasets created from samples
- Number of studies where alternate participant IDs and aliases are configured
- Number of studies where Study products are configured
- Number of studies where Treatments are configured
- Number of studies where Assay Schedule are configured

2021-11-02 16:41 UTC, labkey-klum commented on study/src/org/labkey/study/StudyModule.java
> +                metric.put("alternateParticipantIdCount", new SqlSelector(StudySchema.getInstance().getSchema(), sql).getObject(Long.class));
I wasn't 100% sure on the behavior of the alternate participant ID but it seems like we have to look at both the participant and study tables. If a prefix is configured the `participant.alternateId` field is not populated until an export occurs but if an alias map is uploaded then it is populated immediately.

2021-11-02 18:41 UTC, labkey-klum commented on study/src/org/labkey/study/StudyModule.java
> +
These tables are provisioned so can't execute direct SQL to get the counts.

2021-11-03 00:00 UTC, labkey-adam commented on study/src/org/labkey/study/StudyModule.java
> +
This might not have been on the list, but shouldn't we count the "ancillary" studies as well?

2021-11-03 00:00 UTC, labkey-adam commented on study/src/org/labkey/study/StudyModule.java
> +                metric.put("alternateParticipantIdCount", new SqlSelector(StudySchema.getInstance().getSchema(), sql).getObject(Long.class));
On my machine, the second condition (AlternateIdPrefix IS NOT NULL) captures a lot more containers than the first. I think that's because the alias map and prefix are copied in the publish process, so every published study has them whereas only source studies have AlternateIds in the Participants table. You might check with Hannah, but I think it'd be best to separate these into distinct metrics to avoid confusion.

2021-11-03 00:00 UTC, labkey-adam requested changes
A couple suggestions... not strictly required, but worth considering

2021-11-04 17:55 UTC, labkey-klum commented on study/src/org/labkey/study/StudyModule.java
> +                metric.put("alternateParticipantIdCount", new SqlSelector(StudySchema.getInstance().getSchema(), sql).getObject(Long.class));
Spoke to Hannah, and she does want to track both (but separately)

https://github.com/LabKey/platform/pull/2742/commits/d637eddabde2dbe37684ddd9aa242760d51e5662

2021-11-04 17:55 UTC, labkey-klum commented on study/src/org/labkey/study/StudyModule.java
> +
Yes, agreed https://github.com/LabKey/platform/pull/2742/commits/d637eddabde2dbe37684ddd9aa242760d51e5662

2021-11-04 22:59 UTC, labkey-adam approved these changes

2021-11-05 23:18 UTC, merged