Issue 44434: Add admin action for adjusting timestamps for Created and Modified fields.
LabKey/platform pull request #2837
Opened 2021-12-08 19:13 UTC by labkey-susanh

#### Rationale
System-created timestamp values are created using the server's timestamp.  When we adjust the timezone for the server to correspond to the client's usual timezone, existing timestamps remain in the original timezone.  This action provides a way to adjust these system-created timestamp values so they line up with the adjusted server timestamp.

#### Changes
* Add `AdjustSystemTimestampAction` to `AdminController`

2021-12-08 19:46 UTC, labkey-matthewb commented on core/src/org/labkey/core/admin/AdminController.java
> +                    sql.append(String.format("SET %s = %s + interval '%d hour';\n", fieldName, fieldName, delta));
just FYI, {fn timestampadd(SQL_TSI_HOUR, delta, field)} is cross database.  That is how we implement this in LabKey SQL.
https://docs.oracle.com/javadb/10.8.3.0/ref/rrefjdbc88908.html

2021-12-08 19:51 UTC, labkey-matthewb commented on core/src/org/labkey/core/admin/AdminController.java
> +        private void updateField(TableInfo tInfo, String fieldName, int delta)
Collection<String> fieldNames?

2021-12-08 19:52 UTC, labkey-matthewb commented on core/src/org/labkey/core/admin/AdminController.java
> +            if (col != null)
&& col.getJdbcType() == JdbcType.TIMESTAMP

2021-12-08 19:59 UTC, labkey-matthewb requested changes
1) Maybe expand what we consider built-in date columns .e.g Modified, Created, lastIndexed, diModified, diCreated, _ts, etc. (I don't think we need to tackle this but things like "opened", "resolved", and "closed" get interesting, you could imagine asking tableinfo/module what are your built-in timestamp columns?).  This can be one off, but BuiltInColumnTypes is a possible place to consolidate default adjudication of column 'types'.
2) I think on UPDATE per table would be nice

2021-12-09 14:41 UTC, labkey-susanh commented on core/src/org/labkey/core/admin/AdminController.java
> +        private void updateField(TableInfo tInfo, String fieldName, int delta)
Done.

2021-12-09 14:41 UTC, labkey-susanh commented on core/src/org/labkey/core/admin/AdminController.java
> +                    sql.append(String.format("SET %s = %s + interval '%d hour';\n", fieldName, fieldName, delta));
Done.

2021-12-09 14:41 UTC, labkey-susanh commented on core/src/org/labkey/core/admin/AdminController.java
> +            if (col != null)
Done.

2021-12-10 18:06 UTC, labkey-matthewb approved these changes

2021-12-10 21:23 UTC, merged