Add Sample Type scannable option
LabKey/platform pull request #2845
Opened 2021-12-09 20:14 UTC by labkey-ians

#### Rationale
spec: https://docs.google.com/document/d/1wKe6bg2vnJmoa7DA1r43QeO-rt1Wd-2w3yIZen30Neg/edit#

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/685

#### Changes
* Item #9633: Add scannable option to SampleType text fields for LabKey apps
  * Added scannable option to domain descriptor
  * Added scannable option to folder/domain export
  * Added scannableColumnCount metric to ExperimentModule
  * Bumped various components package versions

2021-12-10 16:34 UTC, cnathe requested changes

2021-12-10 16:34 UTC, cnathe commented on api/schemas/expTypes.xsd
> +			<xs:element name="Scannable" type="boolean" minOccurs="0" maxOccurs="1" />
should we add the description / documentation info here as well?

2021-12-10 16:34 UTC, cnathe commented on api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyDescriptor.java
> +    private BooleanProperty scannable = new BooleanProperty(false);
should this file also have an update in the `public GWTPropertyDescriptor(GWTPropertyDescriptor s)` constructor for this new property?

2021-12-10 16:34 UTC, cnathe commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +        {//TODO why are we doing this? most of the props are the same in both methods
is this a TODO you were still going to look into for this PR?

2021-12-10 16:34 UTC, cnathe commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +        setScannable(col.isScannable());
looks like this file should also have updates in the `loadFromXml()` method

2021-12-10 16:34 UTC, cnathe commented on api/src/org/labkey/api/data/ColumnRenderProperties.java
> +     * Field value can be used as a barcode, similar to UniqueId type -- w/o requirement of being unique.
you mentioned "w/o requirement of being unique" in the comment here. is the other part that this property allows for the case of "user defined IDs"?

2021-12-10 16:34 UTC, cnathe commented on api/src/org/labkey/api/data/JsonWriter.java
> +        props.put("scannable", scannable);
are both of these needed? it looks like some of the boolean props are duplicated in this way and some are not. The comment about the duplicated ones indicates that it is for backwards compatibility, which shouldn't be needed here.

2021-12-10 16:34 UTC, cnathe commented on api/src/org/labkey/api/data/TableInfoWriter.java
> +            columnXml.setScannable(column.isScannable());
the comment about this if statement should be updated since this is more then just the scale column prop now.

2021-12-10 16:34 UTC, cnathe commented on experiment/resources/schemas/exp.xml
> +      <column columnName="scannable" />
it probably doesn't matter, but any reason this new prop is lowercase and the others are uppercase?

2021-12-10 16:34 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
> +        edit().setScannable(scannable);
some of the other boolean properties in this class have a check to make sure the value is changing before calling the `edit()...` method. see things like setHidden, setShownInDetailsView, setRecommendedVariable. should we do the same here?

2021-12-10 16:34 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
> +        setScannable(propSrc.isScannable());
this comment isn't related to this file, but should there also be changes for the new "scannable" property in the `DomainImpl.java` class? It looks like that file is related to audit diff info / comments.

2021-12-10 16:34 UTC, cnathe commented on internal/src/org/labkey/api/exp/property/DomainUtil.java
> +        gwtProp.setScannable(prop.isScannable());
looks like there are a couple more places to add changes for this new property in this file: `getPropertyDescriptor(ColumnType columnXml)` and `_copyProperties`. I was just looking for places where the "recommendedVariable" property is used for comparison.

2021-12-10 16:34 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
> +        setScannable(propSrc.isScannable());
also unrelated to this file, but do we need changes for the new property in the `MetadataTableJSON.java` class as well?

2021-12-10 16:34 UTC, cnathe commented on experiment/resources/schemas/dbscripts/sqlserver/exp-21.018-21.019.sql
> +ALTER TABLE exp.PropertyDescriptor ADD Scannable BIT DEFAULT 0;
the postgres file above has `NOT NULL`, should this as well? i.e. `BIT NOT NULL DEFAULT 0`

2021-12-11 01:33 UTC, labkey-ians commented on api/schemas/expTypes.xsd
> +			<xs:element name="Scannable" type="boolean" minOccurs="0" maxOccurs="1" />
added

2021-12-11 01:33 UTC, labkey-ians commented on api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyDescriptor.java
> +    private BooleanProperty scannable = new BooleanProperty(false);
added

2021-12-11 01:33 UTC, labkey-ians commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +        {//TODO why are we doing this? most of the props are the same in both methods
Not as part of this PR, it was just note that this should probably be adjusted. Don't mind doing it, but I would separate it as I don't want it to confound any issues that may crop-up.

2021-12-11 01:33 UTC, labkey-ians commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +        setScannable(col.isScannable());
added

2021-12-11 01:33 UTC, labkey-ians commented on api/src/org/labkey/api/data/JsonWriter.java
> +        props.put("scannable", scannable);
dupe removed, and field moved to lower block to match comment

2021-12-11 01:33 UTC, labkey-ians commented on api/src/org/labkey/api/data/TableInfoWriter.java
> +            columnXml.setScannable(column.isScannable());
done

2021-12-11 01:33 UTC, labkey-ians commented on experiment/resources/schemas/exp.xml
> +      <column columnName="scannable" />
fixed

2021-12-11 01:33 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
> +        edit().setScannable(scannable);
fixed

2021-12-11 01:33 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
> +        setScannable(propSrc.isScannable());
yes, and yes
added

2021-12-11 01:34 UTC, labkey-ians commented on internal/src/org/labkey/api/exp/property/DomainUtil.java
> +        gwtProp.setScannable(prop.isScannable());
fixed

2021-12-11 01:34 UTC, labkey-ians commented on experiment/resources/schemas/dbscripts/sqlserver/exp-21.018-21.019.sql
> +ALTER TABLE exp.PropertyDescriptor ADD Scannable BIT DEFAULT 0;
updated

2021-12-13 14:15 UTC, cnathe approved these changes

2021-12-13 14:15 UTC, cnathe commented on api/schemas/expTypes.xsd
> +						When true, includes field values as part Barcode searches.
```suggestion
						When true, include field values as part of Barcode searches.

```

2021-12-17 17:36 UTC, merged