ELN: Email Notification Improvements
LabKey/platform pull request #2857
Opened 2021-12-14 03:21 UTC by RosalineP

#### Rationale
We would like to update the email subject lines on emails sent when commenting on a Notebook to be more informative. Additionally, we would like to update who receives emails in various circumstances when commenting on a Notebook: users should generally not receive emails for comments they have just posted, and notebook authors should generally receive emails when their notebook receives a comment.

#### Related Pull Requests
* 

#### Changes
* When we know we are in a Notebook thread, 
    * Send notebook authors an email if their Email Notification Settings are set to 'my conversations', and a user comments in their notebook
    * Do not send a user an email if their Email Notification Settings are set to 'my conversations', and they have just made the most recent comment
* Add 'message subject' member that can overwrite the default email subject

2021-12-14 03:26 UTC, RosalineP commented on announcements/src/org/labkey/announcements/model/AnnouncementManager.java
> +                    if (EmailOption.MESSAGES_MINE.getValue() == pref && u.isActive())
Maybe I should add a short explanatory comment, "// Skip if user is inactive"? This is something we do in other places in the code to avoid giving users an opportunity to spam others who are not actually legitimate users.

2021-12-15 20:38 UTC, labkey-alan commented on announcements/src/org/labkey/announcements/model/AnnouncementManager.java
> +                    if (EmailOption.MESSAGES_MINE.getValue() == pref && u.isActive())
Can't hurt.

2021-12-15 20:59 UTC, labkey-alan requested changes
Overall looks good, I did leave some feedback that should be addressed though.

2021-12-15 20:59 UTC, labkey-alan commented on announcements/src/org/labkey/announcements/model/AnnouncementManager.java
> +                if (EmailOption.MESSAGES_MINE.getValue() == createdByPref)
I would add a comment that explains what we're doing here. Can be brief "Only email users that..." or "Don't email users that..."

2021-12-15 20:59 UTC, labkey-alan commented on announcements/src/org/labkey/announcements/model/AnnouncementManager.java
> +                if (notificationBean.messageSubject != null)
Instead of doing this null check here I would have it setup in the constructor to have the messageSubject default to the code below. That way we can move most of the logic out of this and just return `notificationBean.messageSubject` which is similar to what we do for the other replacements.

2021-12-15 20:59 UTC, labkey-alan commented on api/src/org/labkey/api/announcements/api/DiscussionSrcTypeProvider.java
> +    default Set<User> getNotebookAuthors(Container container, User user, String discussionSrcIdentifier)
This should not be called `getNotebookAuthors`, as we don't want the concept of Notebooks leaking into other modules. Instead this should be called `getRecipients`. We need to support the same email scenarios for Workflow and it wouldn't make sense to have Workflow implement `getNotebookAuthors`.

2021-12-16 21:45 UTC, RosalineP commented on announcements/src/org/labkey/announcements/model/AnnouncementManager.java
> +                if (notificationBean.messageSubject != null)
Like so?

2021-12-16 21:58 UTC, labkey-alan approved these changes
Approved, but I did point out one minor thing that should be addressed so we don't accidentally have null subjects.

2021-12-16 21:58 UTC, labkey-alan commented on announcements/src/org/labkey/announcements/model/AnnouncementManager.java
> +                this.messageSubject = StringUtils.trimToEmpty(isResponse ? "RE: " + parent.getTitle() : a.getTitle());
I don't think we want the default case in an else block, because getEmailSubject can return null. We have two options, I'm fine with either:

1. Initialize the value with the default before the if block above with the default value here. Then, only override the value if the typeProvide returns a non-null value.
2. Convert this else into a new, and separate, if block that checks `if (this.messageSubject == null)`

2021-12-17 18:21 UTC, merged