Issue 44511: Ability to change a field's data type to known safe alternatives
LabKey/platform pull request #2930
Opened 2022-01-11 01:11 UTC by labkey-jeckels

#### Rationale
Users sometimes change their mind on the appropriate data type for a field. There are a number of transitions that we know will be safe, including changing an integer to a double or non-strings into strings.

#### Changes
* New StorageProvisioner support for changing a column's type
* Gate the allowed transitions via before/after type checks in DomainPropertyImpl
* Handle non-provisioned tables via updates to exp.ObjectProperty as well
* Preserve formatting for boolean values but not other types at this point
* Misc small code cleanup

2022-01-19 20:26 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/dialect/PostgreSql91Dialect.java
>          sb.append( String.format("ALTER TABLE %s.%s ", change.getSchemaName(), change.getTableName()));
makeTableIdentifier()?

2022-01-19 21:17 UTC, labkey-matthewb requested changes

2022-01-19 21:17 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/dialect/PostgreSql91Dialect.java
> +                dbType = getSqlTypeName(column.getJdbcType()) + "(" + column.getPrecision() + ", " + column.getSize() + ")";
getScale()?

2022-01-19 21:17 UTC, labkey-matthewb commented on bigiron/src/org/labkey/bigiron/mssql/BaseMicrosoftSqlServerDialect.java
> +                        column.getName(),
I'm surprised there's not more escaping of column names?  Maybe we always know column names don't have special chars at this level?

2022-01-19 21:17 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
> +        SQLFragment sql = new SQLFragment("UPDATE ").append(schemaTable).append(" SET ").
This deserves a comment.  updateBoolean only works on strings?  Does this mean we use strings today to store booleans in exp.objectproperty, but the string value is not stored consistently?

2022-01-19 23:57 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/dialect/PostgreSql91Dialect.java
> +                dbType = getSqlTypeName(column.getJdbcType()) + "(" + column.getPrecision() + ", " + column.getSize() + ")";
No such thing! But I think I should use our hardcoded default of (15,4) instead. I extracted a constant.

2022-01-20 00:19 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/dialect/PostgreSql91Dialect.java
>          sb.append( String.format("ALTER TABLE %s.%s ", change.getSchemaName(), change.getTableName()));
Swapped

2022-01-20 00:21 UTC, labkey-jeckels commented on bigiron/src/org/labkey/bigiron/mssql/BaseMicrosoftSqlServerDialect.java
> +                        column.getName(),
I reused existing code that was there for resizing VARCHAR fields but did some extra testing.

This works in almost all cases because of the brackets. But not if you have a closing bracket. Switched to makeLegalIdentifer()

2022-01-20 00:21 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
> +        SQLFragment sql = new SQLFragment("UPDATE ").append(schemaTable).append(" SET ").
Comments added. Let me know if you think I should revise further.

2022-01-21 19:32 UTC, labkey-matthewb approved these changes

2022-01-21 19:38 UTC, merged