Issue 44557: Optimize queries within Panorama QC folders for faster plot rendering
LabKey/platform pull request #2960
Opened 2022-01-19 19:26 UTC by labkey-jeckels

#### Rationale
Fast pages are good. QC folders in Panorama are slower than we want, and there are some platform changes to help improve the SQL we run.

Also, on my dev machine where I have many notifications queued up (4000+) every page render was taking 200ms to stream them all back into Java objects when all we cared about was the count.

#### Changes
* Make LazyForeignKey even lazier, meaning it's less likely to initialize the full FK
* Offer the execution plan for queries that have a CTE
* Expose a QueryService method to turn LabKey SQL into minimal TableInfos to be embedded in other, larger SQL queries

2022-01-19 20:06 UTC, labkey-matthewb requested changes

2022-01-19 20:06 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/Table.java
> +                // First non-comment line must start with SELECT or WITH (for a CTE)
Presence of WITH is does not mean that the whole query is a SELECT.  I would like to see this augmented to scan through and make sure that in addition a line starting with SELECT, that there is no line starting with "UPDATE", "DELETE" or "INSERT".  Having a SQLFragment version might make for more accurate/easier parsing, since the CTE's get broken out separately from the 'main' SQL statement.

2022-01-19 20:06 UTC, labkey-matthewb commented on api/src/org/labkey/api/admin/notification/NotificationService.java
> +    long getNotificationCountByUser(Container container, int notifyUserId, boolean unreadOnly);
👍

2022-01-20 00:37 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/Table.java
> +                // First non-comment line must start with SELECT or WITH (for a CTE)
I will revert this change. I was focused on whether we show a link to get the execution plan in the Admin Console's Queries section where it's OK to be a little sloppy. However, the other usage in PostgresSql91Dialect is much more important to be sure, and without doing a full parse we be as confident (there's no guarantee that UPDATE or DELETE would be at the beginning of a line, for example)

2022-01-22 07:12 UTC, labkey-matthewb approved these changes

2022-01-22 16:46 UTC, merged