Stream documents to be indexed
LabKey/platform pull request #2992
Opened 2022-01-28 03:10 UTC by labkey-matthewb

#### Rationale
We currently buffer the tika converted documents in memory (the text version of whatever file is being indexed).  These files can be very large.  This change allows for these files to overflow to disk to limit the indexers demands on the java heap.

#### Related Pull Requests
* 

#### Changes
*

2022-01-31 18:58 UTC, labkey-adam requested changes
Couple suggestions for Couple suggestions for `TempTextFileWrapper`

2022-01-31 18:58 UTC, labkey-adam commented on api/src/org/labkey/api/util/FileUtil.java
> +            if (null == _charBuffer)
Why not do this allocation in `TempTextFileWrapper(int)`, passing the `charBuffer` to `TempTextFileWrapper(CharBuffer)`?

2022-01-31 18:58 UTC, labkey-adam commented on api/src/org/labkey/api/util/FileUtil.java
> +        ByteBuffer _byteBuffer = null;
`@Nullable`

2022-01-31 18:58 UTC, labkey-adam commented on api/src/org/labkey/api/util/FileUtil.java
> +//        int _maxPosition = 0;
Remove?

2022-01-31 18:58 UTC, labkey-adam commented on api/src/org/labkey/api/util/FileUtil.java
> +//                        _maxPosition = Math.max(_maxPosition, _charBuffer.position());
remove?

2022-01-31 18:58 UTC, labkey-adam commented on api/src/org/labkey/api/util/FileUtil.java
> +        CharBuffer _charBuffer = null;
Could be `final` if initialized in the first constructor

2022-02-01 20:55 UTC, labkey-matthewb commented on api/src/org/labkey/api/util/FileUtil.java
> +            if (null == _charBuffer)
Moving the _charBuffer allocation is makes sense, but I want to make sure the caller only asks for the Writer/Reader once.  I don't want the interface to look like might be more than one writer (or reader) that separately track position.  Using null as a marker is simple.

2022-02-02 00:10 UTC, labkey-adam approved these changes

2022-02-02 01:02 UTC, merged