Item 9923: Add new storage role permissions classes
LabKey/platform pull request #2993
Opened 2022-01-28 15:17 UTC by labkey-susanh

#### Rationale
We are adding new roles and permissions specific to storage. These roles are not meant to be available to Admins by default.  The Storage Editors need to be able to manage picklists and jobs, but not assay data, samples or data classes. They are also allowed to update the status of samples when they are being discarded from storage (A later story will probably allow this more broadly.). The updating of sample status for stored samples is handled through an action in the `InventoryController`.  Here we add the permission class.

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/723 (and related)

#### Changes
* Add `SampleWorkflowJobPermission` and `UpdateSampleStatusPermission`
* Allow workflow runs to be created, updated, and deleted for users with `SampleWorkflowJobPermission`.

2022-01-28 20:41 UTC, XingY requested changes

2022-01-28 20:41 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpRunImpl.java
> +    @Override
Should the check also be done in this class's "public void delete(User user)" method?

2022-01-28 20:41 UTC, XingY commented on api/src/org/labkey/api/exp/api/ExpRun.java
I don't see permission check updates in ExpRunTableImpl.RunTableUpdateService. Is the idea that workflow actions will be done exclusively through LKSM actions rather than query API?

2022-01-28 20:41 UTC, XingY commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                throw new UnauthorizedException("You do not have permission to delete "
" in this container." instead of " runs in this container", with an extra "runs"

2022-01-31 01:47 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpRunImpl.java
> +    @Override
Good call.  Done.

2022-01-31 01:47 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                throw new UnauthorizedException("You do not have permission to delete "
Done. Thanks.

2022-01-31 01:47 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/api/ExpRun.java
The ExperimentListener implementation in SM should do the checking we need since the UpdateService calls `run.save` when then invokes the listeners.

2022-01-31 18:00 UTC, XingY approved these changes

2022-02-01 03:03 UTC, merged