Issue 38175: Correcting relative paths in extracted zip directories
LabKey/platform pull request #300
Opened 2019-08-07 17:36 UTC by labkey-ankurj

2019-08-07 18:07 UTC, labkey-jeckels requested changes

2019-08-07 18:07 UTC, labkey-jeckels commented on internal/webapp/internal/ZipLoad/ZipLoad.js
> +                    fileZipPath += '/' + filePath[index+1];
Can change this to filePath[++index] and remove the following line

2019-08-07 18:07 UTC, labkey-jeckels commented on internal/webapp/internal/ZipLoad/ZipLoad.js
> +        var fileZipPath = '';
Please add logging and fallback to the file name if the directory never matches in the for() loop below.

2019-08-07 18:24 UTC, labkey-ankurj commented on internal/webapp/internal/ZipLoad/ZipLoad.js
> +                    fileZipPath += '/' + filePath[index+1];
Done.

2019-08-07 18:25 UTC, labkey-ankurj commented on internal/webapp/internal/ZipLoad/ZipLoad.js
> +        var fileZipPath = '';
Done

2019-08-07 18:28 UTC, labkey-jeckels approved these changes
Looks great, thanks.

2019-08-09 19:03 UTC, labkey-jony commented
Client stated in ticket that the fix worked. They're expecting it to be rolled into 19.2

2020-01-23 22:55 UTC, closed without merging