DomainKind and SimpleTableDomainKind pass through User props
LabKey/platform pull request #3014
Opened 2022-02-03 19:00 UTC by labkey-martyp

#### Rationale
In order for SimpleTable (extensible table) domains to be updated in startup scripts in EHR, we cannot rely on getting the user from HTTPView context. This passes through user in a couple spots to be used instead of HTTPView context.

#### Related Pull Requests
* TBD

#### Changes
* Add getReservedPropertyNames with user parameter to DomainKind
* Update SimpleTableDomainKind to use passed in User (when available) for getTable and getReservedPropertyNames
* Update DomainUtil.validateProperties to pass through user

2022-02-03 22:27 UTC, ankurjuneja approved these changes

2022-02-03 23:12 UTC, labkey-jeckels requested changes

2022-02-03 23:12 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +    public Set<String> getReservedPropertyNames(Domain domain, User user)
I know you took this approach because it's a pain to refactor existing code but this bound to cause us headaches going forward. How do callers know when they should pass in a user? And implementers that need the user have to implement both (but will always fail when you call the one without a user)?

2022-02-04 01:08 UTC, labkey-jeckels requested changes
You may be in the process of fixing these up, but it seems like many or hopefully all it should be easy to pipe in the real user.

2022-02-04 01:08 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        Set<String> reservedNames = kind.getReservedPropertyNames(domain, null);
```suggestion
        Set<String> reservedNames = kind.getReservedPropertyNames(domain, u);
```

2022-02-04 01:08 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
> +        Set<String> reservedNames = kind.getReservedPropertyNames(domain, null);
```suggestion
        Set<String> reservedNames = kind.getReservedPropertyNames(domain, u);

```

2022-02-04 01:08 UTC, labkey-jeckels commented on internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
> +                Set<String> reservedNames = getReservedPropertyNames(newDomain, null);
```suggestion
                Set<String> reservedNames = getReservedPropertyNames(newDomain, user);
```

2022-02-04 01:08 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/pipeline/SampleReloadTask.java
> +                    Set<String> reservedProps = domainKind.getReservedPropertyNames(null, null);
```suggestion
                    Set<String> reservedProps = domainKind.getReservedPropertyNames(null, job.getUser());
```

2022-02-04 01:08 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +            Set<String> reservedNames = domainKind == null ? Collections.emptySet() : domainKind.getReservedPropertyNames(null, null);
```suggestion
            Set<String> reservedNames = domainKind == null ? Collections.emptySet() : domainKind.getReservedPropertyNames(null, getUser());

```

2022-02-04 01:08 UTC, labkey-jeckels commented on internal/src/org/labkey/experiment/api/SampleTypeDomainKind.java
> +        Set<String> reservedNames = new CaseInsensitiveHashSet(this.getReservedPropertyNames(stDomain, null));
```suggestion
        Set<String> reservedNames = new CaseInsensitiveHashSet(this.getReservedPropertyNames(stDomain, user));

```

2022-02-04 18:27 UTC, labkey-martyp commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +    public Set<String> getReservedPropertyNames(Domain domain, User user)
Ok added user to that function param and updated all the LK modules that are overriding/calling that function.

2022-02-04 18:31 UTC, labkey-jeckels approved these changes
One more possible caller to update. Your call if it's feasible enough.

2022-02-04 18:31 UTC, labkey-jeckels commented on assay/src/org/labkey/assay/AssayImportServiceImpl.java
> +                Set<String> reservedNames = domain.getDomainKind().getReservedPropertyNames(domain, null);
Is it feasible to pipe the user into this call?

2022-02-04 19:39 UTC, merged