lineage sql
LabKey/platform pull request #3016
Opened 2022-02-04 21:33 UTC by labkey-matthewb

#### Rationale
Implement new LabKey SQL functionality "IN expDescendantsOf ()" and "IN expAncestorsOf ()" to efficiently support lineage filters required the new sample finder feature.

#### Related Pull Requests
* 

#### Changes
*

2022-02-19 23:53 UTC, XingY requested changes
Columns selection in ExpMaterialTableImpl needs some changes.

2022-02-19 23:53 UTC, XingY commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +                setConceptURI(xmlCol.getConceptURI());
can use conceptURI directly here

2022-02-19 23:53 UTC, XingY commented on api/src/org/labkey/api/exp/api/ExpLineageOptions.java
> +     * NOTE: that also means that there is no implicit container filter on the result.  The
The lack of container filtering should make supporting sample finder in a subfolder setup easier.

2022-02-19 23:53 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +            // don't need to generate SQL for columns that aren't selected
Is it true that a column is needed only if it's in the select? A query might not select RowId as a returned result, but uses rowId as a join condition to another table, or use it in the where filter. 

Ideally, LabKey would able to determine that selectedColumns should also include those dependency columns. But I have seen in testing that the absent of "RowId" is causing faceted filtering on any of those inventory columns added to samples grid to fail (Freeze/Thaw Count, StorageStatus, etc). Minimally "RowId" should probably be added to the wrappedFieldKeys set. But conservatively, we might want to continue to select all columns

2022-02-19 23:53 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +            new FieldKey(null, "objectid"),
add RowId?

2022-02-19 23:53 UTC, XingY commented on query/src/org/labkey/query/sql/QInLineage.java
> +        var LHS = ((QExpr) getFirstChild());
LHS short for? (I'm guess left hand side but I might be way off... )

2022-02-19 23:53 UTC, XingY commented on query/src/org/labkey/query/QueryServiceImpl.java
> +            if (null != fk.getParent() || !StringUtils.startsWithIgnoreCase(value, "SELECT "))
Can consider allowing (Select ...). I see that the parentheses are added below, but doesn't hurt to double parentheses

2022-02-22 20:27 UTC, labkey-matthewb commented on query/src/org/labkey/query/sql/QInLineage.java
> +        var LHS = ((QExpr) getFirstChild());
yes, left-hand side.

2022-02-22 21:02 UTC, labkey-matthewb commented on query/src/org/labkey/query/QueryServiceImpl.java
> +            if (null != fk.getParent() || !StringUtils.startsWithIgnoreCase(value, "SELECT "))
I tried to make this work, but I think it's tricky.  I can check that the value starts and ends with parens.  I can't really check that they are matched parens though.

`(select col from table) AND (1=1)`

I could probably do something, but I don't want to think about it right now.

2022-02-22 21:07 UTC, XingY commented on query/src/org/labkey/query/QueryServiceImpl.java
> +            if (null != fk.getParent() || !StringUtils.startsWithIgnoreCase(value, "SELECT "))
agree this is nice to have, but not important and can definitely do without for now.

2022-02-23 00:13 UTC, XingY approved these changes

2022-02-23 00:16 UTC, merged