Help user understand why a clipboard copy failed
LabKey/platform pull request #3037
Opened 2022-02-11 17:23 UTC by labkey-jeckels

#### Rationale
navigator.clipboard APIs require HTTPS (or localhost, which makes this harder to test). While all servers should be using HTTPS, we can do better by giving feedback to the user

#### Changes
* Detect failure and show helpful text

2022-02-11 17:37 UTC, labkey-jeckels commented
I checked and the other places we're doing clipboard functionality we're not using navigator.clipboard, at least not directly. In some places we're doing the deprecated document.execCommand('copy') and in other places we're using clipboard.js. I was tempted to consolidate but ultimately decided to not venture out that far

2022-02-11 17:41 UTC, labkey-martyp approved these changes

2022-02-11 18:09 UTC, labkey-susanh requested changes
One request, but this is certainly an improvement.

2022-02-11 18:09 UTC, labkey-susanh commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +                    });
There should probably also be a `.catch` block attached after the then. I'm not sure if the same messaging would still be appropriate there (Maybe just "Copy failed. Please check the logs."), but at least logging the error would be helpful. 
```
navigator.clipboard.writeText(logDataEl.innerText).then( 
...
).catch(error -> {
   console.error(error)
   e.target.innerHTML = "Copy failed. So sorry, but have a nice day.";
});
```

2022-02-14 14:33 UTC, labkey-susanh approved these changes

2022-02-14 14:33 UTC, labkey-susanh commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +                        e.target.innerText = "Copy failed: " + error;
It seems likely this error message is going to be something fairly incomprehensible to the average user, but it should be a rare occurrence, so I leave it to you to decide whether to remove it or not since the error will get logged.

2022-02-14 17:00 UTC, labkey-jeckels commented on pipeline/src/org/labkey/pipeline/status/details.jsp
> +                        e.target.innerText = "Copy failed: " + error;
Since it'll be logged to a place that a user is even less likely to find and relay to us, I'm OK keeping it as-is. I suppose I log it as a client exception to mothership. But since it seems unlikely to happen, I'm going to merge.

2022-02-14 17:00 UTC, merged