44544: Sample type dataset definitions should be locked similar to assays
LabKey/platform pull request #3098
Opened 2022-02-26 00:02 UTC by labkey-klum

#### Rationale
In 21.7 we added the ability to link sample type data to studies. The dataset designer restricts what properties are editable for linked source type datasets (additional key fields, name, etc). However this was only happening for assays and not sample types.

#### Related Pull Requests
- https://github.com/LabKey/labkey-ui-components/pull/749

#### Changes
- generalize `DatasetDomainKindProperties` so that it uses : `sourceName`, `sourceUrl`, and `sourceType` to pass down to the client
- update the description for linked source datasets to work for both assays and sample types

2022-02-28 15:57 UTC, cnathe requested changes

2022-02-28 15:57 UTC, cnathe commented on core/package.json
> +    "@labkey/components": "2.137.4-fb-issue-44544.0",
Related to the email thread we had, I assume you aren't seeing the local changes from this alpha package because I am not seeing the related package-lock.json file changes. You can cd into the /server/modules/platform/core dir and then run `npm install --legacy-peer-deps` to get that package-lock.json file updated and then commit that change as well.

2022-03-01 00:06 UTC, labkey-klum commented on core/package.json
> +    "@labkey/components": "2.137.4-fb-issue-44544.0",
done: https://github.com/LabKey/platform/pull/3098/commits/e2a2f060397f18ee7dbc827283415ebc6e976b04

strangely, I was seeing the changes locally even without this change.

2022-03-01 02:18 UTC, cnathe approved these changes

2022-03-01 21:41 UTC, closed without merging