Issue44305: Wiki attachments don't appear in the same order in imported folders
LabKey/platform pull request #3110
Opened 2022-03-02 23:46 UTC by RosalineP

#### Rationale
Previously, files attached to wiki pages don't appear in the same order when the folder is exported and reimported to another folder. 

#### Related Pull Requests
* N/A

#### Changes
* Add attr to wiki.xsd to keep track of file attachment order
* Sort incoming attachments based on above attr

2022-03-02 23:59 UTC, labkey-jeckels requested changes

2022-03-02 23:59 UTC, labkey-jeckels commented on wiki/schemas/wiki.xsd
> +                <xsd:documentation>The order in which this page's attachments should appear</xsd:documentation>
Useful to mention that this is a semi-colon separated list of file names.

2022-03-02 23:59 UTC, labkey-jeckels commented on wiki/src/org/labkey/wiki/export/WikiImporterFactory.java
> +            Map<String, Integer> attachmentOrderMap = List.of(attachmentOrder.split(";")).stream().collect(Collectors.toMap(i -> i, i -> inc.getAndIncrement()));
Won't this NPE when attachmentOrder is null?

2022-03-03 00:48 UTC, RosalineP commented on wiki/schemas/wiki.xsd
> +                <xsd:documentation>The order in which this page's attachments should appear</xsd:documentation>
Updated

2022-03-03 00:51 UTC, RosalineP commented on wiki/src/org/labkey/wiki/export/WikiImporterFactory.java
> +            Map<String, Integer> attachmentOrderMap = List.of(attachmentOrder.split(";")).stream().collect(Collectors.toMap(i -> i, i -> inc.getAndIncrement()));
Oops, yes, thank you. Added a nullcheck. I wasn't sure how to exercise the null case, however—the comment in WikiImporterFactory, line 131, says that its call to `importWiki` happens when there are wiki subdirectories that weren't present in the XML metadata, and while I tested with wiki subdirectories I wasn't sure how to test with wiki subdirectories that don't appear in the XML metadata.

2022-03-03 01:07 UTC, labkey-jeckels commented on wiki/src/org/labkey/wiki/export/WikiImporterFactory.java
> +            Map<String, Integer> attachmentOrderMap = List.of(attachmentOrder.split(";")).stream().collect(Collectors.toMap(i -> i, i -> inc.getAndIncrement()));
A couple of testing ideas:

1. Import a folder archive that has wiki attachments doesn't have the new attribute set. This could be done on a server that doesn't have your change yet, or by manually editing the XML prior to import.
2. Set a breakpoint on in this method and use the debugger to set the attachmentOrder variable to null before it uses it.

2022-03-03 01:08 UTC, labkey-jeckels approved these changes

2022-03-03 19:31 UTC, RosalineP commented on wiki/src/org/labkey/wiki/export/WikiImporterFactory.java
> +            Map<String, Integer> attachmentOrderMap = List.of(attachmentOrder.split(";")).stream().collect(Collectors.toMap(i -> i, i -> inc.getAndIncrement()));
Tested locally using method 2 👍

2022-03-03 19:31 UTC, merged