Throw exception when lsid is not found in table selector list
LabKey/platform pull request #3227
Opened 2022-04-06 17:07 UTC by ankurjuneja

#### Rationale
EHR billing tables have extensible columns and when those table rows are updated, the existing values for extensible columns get lost when lsid is not found in table selector.

#### Related Pull Requests
* https://github.com/LabKey/tnprc_billing/pull/153

2022-04-06 17:27 UTC, labkey-jeckels requested changes

2022-04-06 17:27 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/DefaultQueryUpdateService.java
> +                throw new NotFoundException("LSID value not found in table - " + table.getName());
NotFoundException is useful when the client set us a request for something that doesn't exist. We don't log it as an error because it was a bogus request.

IllegalStateException is a better fit here, as this represents something that shouldn't happen. It'll get logged and be more likely to be noticed with test failures.

2022-04-06 17:30 UTC, ankurjuneja commented on api/src/org/labkey/api/query/DefaultQueryUpdateService.java
> +                throw new NotFoundException("LSID value not found in table - " + table.getName());
makes sense. changed.

2022-04-07 17:50 UTC, labkey-jeckels approved these changes
I know you're still tracking down test failures but the fact that this change exposed those problems is a good confirmation of the approach.

2022-04-07 17:50 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/DefaultQueryUpdateService.java
> +import org.labkey.api.view.NotFoundException;
This can be trimmed now.

2022-04-08 23:32 UTC, merged