Issue 45033: Missing / can't set folder descriptions (comments)
LabKey/platform pull request #3272
Opened 2022-04-20 23:10 UTC by XingY

#### Rationale
Folder dataFileUrl are saved without trailing slash. But canonicalURL for folders do end with /. Change made to query for dataFileUrl with and then without ending /. 

#### Related Pull Requests
* 

#### Changes
* query data using dataFileUrl with and then without ending /.
* update file browser "comment"label to "description".

2022-04-20 23:11 UTC, XingY commented
@josheckels Perhaps we should stop stripping off trailing "/" in ExpDataImpl.setDataFileURI?

2022-04-21 22:36 UTC, labkey-jeckels requested changes
These trailing slashes are such a pain. I'd prefer to strip them off before doing the query instead of double-querying. 

One of the biggest headaches is that you get a different path depending on if the directory exists or not. If it exists, you get a trailing slash. If it doesn't, no trailing slash. Thus, it depends on the current state of the file system.

Additionally, we want to store them consistently in the DB. Thus, at upgrade time we'd have to figure out whether a given path in the DB is a directory or not, which of course we can only infer based on what's currently available on the file system.

2022-04-27 14:13 UTC, XingY commented
> These trailing slashes are such a pain. I'd prefer to strip them off before doing the query instead of double-querying.
> 
> One of the biggest headaches is that you get a different path depending on if the directory exists or not. If it exists, you get a trailing slash. If it doesn't, no trailing slash. Thus, it depends on the current state of the file system.
> 
> Additionally, we want to store them consistently in the DB. Thus, at upgrade time we'd have to figure out whether a given path in the DB is a directory or not, which of course we can only infer based on what's currently available on the file system.

Thanks for the details on the trailing slash. Given the inconsistence, probably leaving the stripping behavior as is makes most sense. I've updated implementation to strip off before querying.

2022-04-27 16:03 UTC, labkey-jeckels approved these changes

2022-04-27 16:03 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        String dataFielUrl = canonicalURL;
Typo - should be dataFileUrl, not dataFielUrl

2022-05-23 18:11 UTC, merged