Export multi-tabbed grids to excel
LabKey/platform pull request #3273
Opened 2022-04-20 23:32 UTC by labkey-ians

#### Rationale
Item #10158: Multi-sheet export to Excel workbooks of multi-tab grids

#### Related Pull Requests
* TBD

#### Changes
* Added ExportTabsXlsxAction
* refactor ExcelWriter to simplify configuration

2022-04-22 18:38 UTC, labkey-matthewb commented on query/src/org/labkey/query/controllers/QueryController.java
> +    public static class ExportTabsXLSXAction extends ReadOnlyApiAction<ExportTabsForm>
I might nitpick about the name.  The "Tab"s bit is SM UI thing.  There are other uses that certainly have nothing to do with tabs.

2022-04-22 18:45 UTC, labkey-matthewb requested changes
This seems like a pretty practical solution (e.g. more limited view specification than the full QueryForm).  I don't love the api Name.  Would love to see even a simple Junit smoke test.

2022-04-22 18:52 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/ExcelWriter.java
>      public void write(HttpServletResponse response)
With the refactor these write() methods are getting pretty overloaded/ambiguous.  Maybe rename with long descriptive names?  Like renderSheetAndWrite() etc?

2022-04-28 19:12 UTC, labkey-ians commented on api/src/org/labkey/api/data/ExcelWriter.java
>      public void write(HttpServletResponse response)
done, kept deprecated method as it is used in several other repos

2022-04-28 21:38 UTC, labkey-matthewb requested changes
Looks good.  I would still like to see one simple junit test with MockRequest and maybe two sheets (maybe just query core schema tables)

2022-04-28 21:38 UTC, labkey-matthewb commented on query/src/org/labkey/query/controllers/QueryController.java
> +                    props.put(key, ((JSONArray) entry.getValue()).getString(0));
check length()==1?  (or at least length() > 0)

2022-05-03 18:59 UTC, labkey-matthewb approved these changes

2022-05-04 18:44 UTC, merged