Export script minor improvements
LabKey/platform pull request #3387
Opened 2022-05-26 17:27 UTC by labkey-adam

#### Rationale
Export script is a little behind the times

#### Changes
* Update exported Java code comments to match reality
* Adjust referrer parameter on help link
* Require CSRF token on export script
* Adjust loadLibrary.api to expand only resolved libraries

2022-05-26 22:56 UTC, labkey-adam commented
@labkey-nicka this includes the loadLibrary change we discussed. Please review that at a minimum.

2022-05-26 23:33 UTC, labkey-nicka approved these changes

2022-05-26 23:33 UTC, labkey-nicka commented on api/src/org/labkey/api/action/QueryViewAction.java
> +            CSRFUtil.validate(getViewContext());
Seems like a bit of a specific place to have to have this validation. Isn't this already being done? If not, should it be done for other export types? I'm coming out of left field on this one so take it for what its worth.

2022-05-26 23:33 UTC, labkey-nicka commented on query/src/org/labkey/query/controllers/QueryController.java
> +                    throw new IllegalArgumentException("'containerFilter' parameter is not a valid org.labkey.api.data.ContainerFilter.Type enum constant");
nit: Consider resolving the package path of the class rather than hard coding it.

2022-05-26 23:33 UTC, labkey-nicka commented on bigiron/src/org/labkey/bigiron/mysql/MySql80Dialect.java
> +    protected String getExplainPrefix()
Ah yes, the MySql updates related to exporting scripts ... 😜

2022-05-26 23:49 UTC, labkey-adam commented on query/src/org/labkey/query/controllers/QueryController.java
> +                    throw new IllegalArgumentException("'containerFilter' parameter is not a valid org.labkey.api.data.ContainerFilter.Type enum constant");
Okay... previous message (from Java) included the package, but I agree it's unnecessary for a user message

2022-05-26 23:54 UTC, labkey-adam commented on api/src/org/labkey/api/action/QueryViewAction.java
> +            CSRFUtil.validate(getViewContext());
Yes, it is specific to the export script case. Export options are GETs with no CSRF, in general, because it's not a mutating action. I'm adding the requirement here because scanners complain about our echoing of parameter values, even though we're clearly responding with plain text. My hope is a CSRF requirement will appease the scanners.

2022-05-26 23:57 UTC, labkey-jeckels commented on api/src/org/labkey/api/action/QueryViewAction.java
> +            CSRFUtil.validate(getViewContext());
We could also set the HTTP header to get the browser to download the file instead of rendering it directly as plain text.

2022-05-27 00:05 UTC, labkey-jeckels requested changes

2022-05-27 00:05 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/QueryView.java
> +                    url.addParameter(CSRFUtil.csrfName, CSRFUtil.getExpectedToken(getViewContext()));
Are we OK transmitting CSRF as a GET parameter? It's more visible and leakier than POST and I've found guidance that recommends against it. https://brightsec.com/blog/csrf-token/

2022-05-27 00:05 UTC, labkey-adam commented on bigiron/src/org/labkey/bigiron/mysql/MySql80Dialect.java
> +    protected String getExplainPrefix()
Yeah, well...

2022-05-27 00:11 UTC, labkey-adam commented on api/src/org/labkey/api/query/QueryView.java
> +                    url.addParameter(CSRFUtil.csrfName, CSRFUtil.getExpectedToken(getViewContext()));
Hoping @labkey-matthewb weighs in on that. I'd prefer a header, but I don't see how we could do that without major changes to the panel JSP. Might be a little easier to switch to POST, and of course we POST the token all the time.

2022-05-27 00:17 UTC, labkey-adam commented on api/src/org/labkey/api/action/QueryViewAction.java
> +            CSRFUtil.validate(getViewContext());
See other comment. I believe validate() needs to stay at this chokepoint regardless of the approach we use to convey the token, since many QueryViewAction subclasses render the export script results.

2022-05-27 01:12 UTC, labkey-adam commented on api/src/org/labkey/api/query/QueryView.java
> +                    url.addParameter(CSRFUtil.csrfName, CSRFUtil.getExpectedToken(getViewContext()));
Switched to POST

2022-05-27 01:52 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/QueryView.java
> +                    url.addParameter(CSRFUtil.csrfName, CSRFUtil.getExpectedToken(getViewContext()));
Shouldn't this parameter get dropped then?

2022-05-27 02:30 UTC, labkey-adam commented on api/src/org/labkey/api/query/QueryView.java
> +                    url.addParameter(CSRFUtil.csrfName, CSRFUtil.getExpectedToken(getViewContext()));
Picky picky

2022-05-27 15:45 UTC, labkey-jeckels approved these changes

2022-05-27 18:52 UTC, merged