Issue 37040: Test Microsoft JDBC driver for SQL Server
LabKey/platform pull request #3440
Opened 2022-06-13 22:27 UTC by labkey-jeckels

#### Rationale
The official Microsoft JDBC driver has some nice capabilities beyond jTDS, including higher availability.

#### Changes
* Pull in MS driver as a dependency

2022-06-21 23:11 UTC, labkey-matthewb requested changes

2022-06-21 23:11 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/dialect/StatementWrapper.java
> +            Object transformedValue = _conn.getScope().getSqlDialect().translateJdbcParameterValue(_conn.getScope(), x);
I don't know if this is a problem, but this is the innerest loop of import.  It may be worth optimizing this a little.  At least cache DbScope and SqlDialect on the StatementWrapper.  I might go so far as to actually cache a java.lang.Function translateTimestamp (w/o typechecking) and java.lang.Function translateObject (w/ type checking).

2022-06-21 23:11 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/dialect/StatementWrapper.java
> +            Object transformedValue = _conn.getScope().getSqlDialect().translateJdbcParameterValue(_conn.getScope(), x);
Another strategy might be to make the dialect a factory of StatementWrapper.  Then StatementWrapper could be subclassed w/ special behavior and even less indirection.

2022-06-21 23:11 UTC, labkey-matthewb commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServer2016Dialect.java
> +    public Object translateJdbcParameterValue(DbScope scope, Object value)
One problem is that we don't know the _target_ type.  If the target type is DATETIME2, we want even higher precision than this (e.g. important for incremental ETL).  I don't think we use DATETIME2, but I know Alan was considering it, and external databases might.  Should we format with enough digits to handle the DATETIME2 case even though it is not necessary for DATETIME?

2022-06-22 01:04 UTC, labkey-jeckels commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServer2016Dialect.java
> +    public Object translateJdbcParameterValue(DbScope scope, Object value)
Switched to use Timestamp.toString() which includes the nanos

2022-06-22 01:05 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/dialect/StatementWrapper.java
> +            Object transformedValue = _conn.getScope().getSqlDialect().translateJdbcParameterValue(_conn.getScope(), x);
Good thinking, and this was already supported on SqlDialect but I missed it when creating the first approach. Refactored.

2022-06-22 17:16 UTC, labkey-matthewb approved these changes

2022-06-23 23:21 UTC, merged