Issue 45006: Provide link to lookup table/query in field designer
LabKey/platform pull request #3458
Opened 2022-06-17 21:12 UTC by RosalineP

#### Rationale
Usability improvement garnered by turning the lookup text display on a domain designer field into a direct link to the query.

#### Related Pull Requests
* 

#### Changes
* Bump version

2022-06-17 21:13 UTC, RosalineP commented
@cnathe 
I'm a little stale on the deal with current frontend package updates—should I update, for good measure, other repos as well with this change?

2022-06-20 14:31 UTC, cnathe commented
> @cnathe I'm a little stale on the deal with current frontend package updates—should I update, for good measure, other repos as well with this change?

@RosalineP In this case since the field editor is used in the LKB and LKSM app UI, I would suggest that you bump the @labkey/components version for those two via the `biologics/package.json` and the `sampleManagement/package.json` so that TeamCity runs those suites to check for regressions.

2022-06-20 14:32 UTC, cnathe requested changes

2022-06-20 14:32 UTC, cnathe commented on core/package-lock.json
> -      "dev": true,
hmmm...did you run the npm install command with the legacy peer deps flag (i.e. `npm install --legacy-peer-deps`)? I would not have expected this many line changes to the package-lock.json file with just a components package bump.

2022-06-20 19:53 UTC, RosalineP commented on core/package-lock.json
> -      "dev": true,
Ah, I think I didn't! The package-lock is looking better now.

Branches also opened on LKB and LKSM!

2022-06-20 20:01 UTC, cnathe approved these changes

2022-06-21 21:58 UTC, merged