Avoid complex query recursion
LabKey/platform pull request #3462
Opened 2022-06-20 21:13 UTC by labkey-matthewb

#### Rationale
Avoid stack overflow in cases of 'complex' query recursion.  Most simple cases are already handled.

#### Related Pull Requests
* 

#### Changes
*

2022-06-20 21:53 UTC, labkey-jeckels requested changes

2022-06-20 21:53 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/Query.java
> +    ThreadLocal<AtomicInteger> resolveDepth = new ThreadLocal<>(){
Shouldn't this be static, perhaps final and private too?

2022-06-21 15:27 UTC, labkey-matthewb commented on query/src/org/labkey/query/sql/Query.java
> +    ThreadLocal<AtomicInteger> resolveDepth = new ThreadLocal<>(){
seems like a good idea

2022-06-21 16:16 UTC, labkey-jeckels approved these changes

2022-06-21 18:31 UTC, merged