Issue 43374: Some characters in file names cause a problem when creating exp.data rows in FileImporter
LabKey/platform pull request #3654
Opened 2022-08-31 23:05 UTC by labkey-bpatel

#### Rationale
Issue [43374](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=43374): Some characters in file names cause a problem when creating exp.data rows in FileImporter

#### Related Pull Requests
* 

#### Changes
* Refactor encode special characters ("+" and "%") in container paths - push this encoding into FilesWebPart._getRootPath()
* Compensate for this encoding in Browser.js, Upload.js, Webdav.js for the actions to work as expected in the Files webpart

2022-08-31 23:47 UTC, labkey-jeckels requested changes

2022-08-31 23:47 UTC, labkey-jeckels commented on filecontent/webapp/File/system/Webdav.js
> +            var contextBaseURL = this.getContextBaseURL().replaceAll("%25", "%").replaceAll("%2B", "+");
There are a half dozen or so lines with this same decoding. Can you create a shared code chunk in case we discover another problematic character in the future?

2022-08-31 23:47 UTC, labkey-jeckels commented on filecontent/webapp/File/system/Webdav.js
> +            var contextBaseURL = this.getContextBaseURL().replaceAll("%25", "%").replaceAll("%2B", "+");
And add comments that point back and forth between the Java and JS code that needs to be kept in sync, too.

2022-09-01 00:48 UTC, labkey-bpatel commented on filecontent/webapp/File/system/Webdav.js
> +            var contextBaseURL = this.getContextBaseURL().replaceAll("%25", "%").replaceAll("%2B", "+");
done!

2022-09-01 01:12 UTC, labkey-jeckels approved these changes

2022-09-01 01:12 UTC, labkey-jeckels commented on api/src/org/labkey/api/files/view/FilesWebPart.java
> +        // This fix requires decoding these characters so that they don't get encoded twice - see getURLWithCharsReplaced() in Webdav.js and its usages.
I find this comment confusing, since the line it's attached to is encoding, not decoding.
```suggestion
        // Need to centrally encode characters that are special in URIs but not in most file systems. See getURLWithCharsReplaced() in Webdav.js for special client-side handling of these characters.

```

2022-09-07 08:42 UTC, merged