Issue 45368: Attachment fields containing field names with spaces doesn't show attachment
LabKey/platform pull request #3684
Opened 2022-09-16 00:28 UTC by labkey-bpatel

#### Rationale
Issue [45368](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=45368): Attachment fields containing field names with spaces doesn't show attachment 

#### Related Pull Requests
* 

#### Changes
* Get column alias when the name (for attachment column with spaces) is not present in the statement parameter

2022-09-16 00:35 UTC, labkey-jeckels reviewed
@labkey-matthewb this seems OK to me but would appreciate your quick glance too

2022-09-21 00:19 UTC, labkey-matthewb requested changes

2022-09-21 00:19 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/StatementDataIterator.java
> +                if (to == null)
Before making this change, I'm curious why this column wasn't correctly matched in DataIteratorUtil.matchColumns().  What is different about this case?

2022-09-21 06:47 UTC, labkey-bpatel commented on api/src/org/labkey/api/dataiterator/StatementDataIterator.java
> +                if (to == null)
It matches in DataIteratoUtil.matchColumns(). 
However, the stmt map here doesn't contain the field with spaces (ex. 'attach field 1'), it contains the field with underscores instead (ex 'attach_field_1').

It isn't clear exactly where the column name with underscores get set - putting a breakpoint in StatementDataIterator ctor (line 105), did not give any clues - it is called from TableInsertDataIterator (line 147), but it doesn't pass in the value for ParameterMapStatement argument. Maybe i am missing something obvious. Your insight is appreciated.

2022-09-21 15:38 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/StatementDataIterator.java
> +                if (to == null)
I see.  I have a suspicion about this.  The SQL and ParameterMapStatement are generated in StatementUtils.createStatement().  That code uses UpdateableTableInfo.remapSchemaColumns() to handle the case where a column name in the user schema is different than the column name in the underlying database schema.  That could be the failure point.

2022-09-22 07:28 UTC, labkey-bpatel commented on api/src/org/labkey/api/dataiterator/StatementDataIterator.java
> +                if (to == null)
Thanks for the insight.

Looks like StatementUtils.createStatement() calls createParameter() (~line 743) to create, well, a Parameter, during which it ends up calling BaseColumnInfo.jdbcRsNameFromName(), which replaces spaces with underscores.  It now makes sense _why_ Statement parameter contains field with underscores instead of the actual col with spaces.

ListTable.remapSchemaColumns() returns an empty map, btw.

2022-09-22 21:45 UTC, labkey-bpatel commented on api/src/org/labkey/api/dataiterator/StatementDataIterator.java
> +                if (to == null)
I've reverted this change

2022-10-19 20:13 UTC, closed without merging