Fix url passing to query webpart ajax call
LabKey/platform pull request #3686
Opened 2022-09-16 16:24 UTC by ankurjuneja

#### Rationale
Labkey Querywebpart api does not filter pound symbol which is often used in the urls and sends it as a parameter value back to the server when updating the grid on container filters.

#### Related Pull Requests
* 

#### Changes
* strip off everything after a pound for a query parameter

2022-09-16 20:29 UTC, labkey-jeckels requested changes

2022-09-16 20:29 UTC, labkey-jeckels commented on api/webapp/clientapi/dom/DataRegion.js
> +                    var poundIdx = pair.indexOf('#');
I think we should strip this earlier - right after we do the ? handling. There's no need to check each parameter separately.

2022-09-19 16:44 UTC, ankurjuneja commented on api/webapp/clientapi/dom/DataRegion.js
> +                    var poundIdx = pair.indexOf('#');
done

2022-09-19 16:49 UTC, labkey-jeckels approved these changes

2022-09-19 16:49 UTC, labkey-jeckels commented on api/webapp/clientapi/dom/DataRegion.js
> +            if (qStringWithoutPound.length > 1) {
I'm surprised this works - `qStringWithoutPound` is defined inside the scope of the if() body. But then again JS scoping is weird. I'd simplify ever so slightly and just reassign `qString`. We don't have a `qStringAfterQuestion`, for example.

2022-09-28 13:13 UTC, merged