Sample Finder, Assay results as filter
LabKey/platform pull request #3722
Opened 2022-09-27 16:40 UTC by XingY

#### Rationale
In order to support finding samples based on their assay data properties, a new compare type COLUMN_IN is added to allow constructing "sampleId IN (select sampleId from assayresult where...)" using filter type. Another new compare type COLUMN_NOT_IN is also added to support finding samples that don't have assay result "sampleId NOT IN (select sampleId from assayresult)"

#### Related Pull Requests
* 

#### Changes
*

2022-09-27 22:29 UTC, labkey-matthewb requested changes

2022-09-27 22:29 UTC, labkey-matthewb commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        SqlDialect dialect = querySchema.getDbSchema().getSqlDialect();
This looks good to me.  My only comment would be to consider not breaking up the "value" into parts.  Just using SQL to do this makes the feature more general.  E.g. instead of ~columnin=columnA,schemaB,tableC,D=E  you could simply do ~columnin=SELECT columnA From schmeaB.tableC WHERE D=E

2022-09-27 22:38 UTC, XingY commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        SqlDialect dialect = querySchema.getDbSchema().getSqlDialect();
I needed the schemaName to get the QuerySchema/UserSchema and the selectColumn to select from the the fromSql. 

Are you suggesting to parse "SELECT xx FROM schema.table .." and extract those information from the parsed string?

2022-09-27 23:13 UTC, labkey-matthewb commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        SqlDialect dialect = querySchema.getDbSchema().getSqlDialect();
You can use the UserSchema for the primary table (e.g.  tinfo.getUserSchema() in buildFilter()).  The schema and table in the SELECT will be resolved relative to that.  

For the column, I guess you'd use t.getColumns().get(0).getValueSql("_").

2022-09-27 23:16 UTC, labkey-matthewb commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        SqlDialect dialect = querySchema.getDbSchema().getSqlDialect();
It is a bit annoying that the schema is not passed around explicitly.  But note that even in addUrlFilters it is usually available indirectly via selectColumns.get(0).getParentTable().getUserSchema().

2022-09-27 23:16 UTC, labkey-ians approved these changes

2022-09-27 23:16 UTC, Sigmonia commented on query/src/org/labkey/query/QueryServiceImpl.java
> +            throw new NotFoundException("Incorrect number of arguments provided");
nit: `NotFoundException` seems to apply more to a resource reference (e.g., 404 error) vs a missing/malformed parameter or argument

```suggestion
            throw new IllegalArgumentException("Incorrect number of arguments provided");
```

2022-09-27 23:16 UTC, Sigmonia commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        qd = qs.createQueryDef(user, container, userSchema, GUID.makeGUID().replace("-", ""));
Need the separate initialization?
```suggestion
        QueryDefinition qd = qs.createQueryDef(user, container, userSchema, GUID.makeGUID().replace("-", ""));
```

2022-09-27 23:16 UTC, Sigmonia commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        //TODO qd.setContainerFilter();
TODO still needed? or addressed after this story?

2022-09-27 23:16 UTC, Sigmonia commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        TableInfo t = qd.getTable(userSchema, qerrors, true, true);
do we need to check the `qerrors`? or switch to inline?

2022-09-27 23:16 UTC, Sigmonia commented on query/src/org/labkey/query/QueryServiceImpl.java
> +                .append(")")
nit: extend the chain?
```suggestion
        SQLFragment sql = new SQLFragment()
                .append("(")
                .append(colFrag)
                .append(")")
```

2022-09-27 23:16 UTC, labkey-ians commented on query/src/org/labkey/query/QueryServiceImpl.java
> +                    Set<String> params = parseParams(value, getValueSeparator());
Style/nit: call parameter validation here? though I guess having it right before usage in the sql generation method also makes sense--a little torn.

2022-09-27 23:16 UTC, labkey-ians commented on query/src/org/labkey/query/QueryServiceImpl.java
> +                    Set<String> params = parseParams(value, getValueSeparator());
same as above

2022-09-27 23:29 UTC, XingY commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        //TODO qd.setContainerFilter();
Yes, this will be addressed as part of cross folder assay story

2022-09-28 17:01 UTC, XingY commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        SqlDialect dialect = querySchema.getDbSchema().getSqlDialect();
Thanks for the suggestions. This works great.

2022-09-28 17:49 UTC, labkey-matthewb commented on query/src/org/labkey/query/QueryServiceImpl.java
> +        ColumnInfo col = columnMap.get(fieldKey);
I can't remember the difference in usage between columnMap and selectColumns and if/when they can be null/empty.  I wonder if we can assert that col is not null and then use "col" instead of "selectColumns.get(0)"?

2022-09-28 17:50 UTC, labkey-matthewb approved these changes

2022-09-30 17:51 UTC, merged