Allow saveRows to use an array of commands where each can supply containerPath
LabKey/platform pull request #3881
Opened 2022-11-29 19:58 UTC by bbimber

@labkey-jeckels Would it be possible to make a clone of this branch on the LK repo if you're willing to entertain this?

The rationale is that saveRows is a client API that lets the user submit an array of commands as a transaction. This PR augments each command object so it can supply containerPath, which would override the top-level containerPath. I added an integration test to test the basic usage. The broad use-case is to let the client submit a transacted list of commands that span containers.

2022-11-29 23:35 UTC, labkey-nicka commented
I like this.

2022-11-29 23:43 UTC, bbimber commented
@labkey-nicka: when I submit a PR to the LK fork TeamCity doesnt pick up on it. Would you be able to make a clone of 22.11_fb_saverows on the Labkey/platform repo, so TeamCity recognizes this and runs the tests?

2022-11-30 01:17 UTC, labkey-jeckels requested changes

2022-11-30 01:17 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +        public void testCrossFolderSaveRows() throws Exception
I'd like to have another test case that validates the command fails and gets rolled back when the user doesn't have permission to the target container in a second command

2022-11-30 01:19 UTC, labkey-jeckels commented
@bbimber FB copy created: https://github.com/LabKey/platform/tree/22.11_fb_saverows

I can merge updates with additional test coverage if you add them

2022-11-30 01:38 UTC, bbimber commented on query/src/org/labkey/query/controllers/QueryController.java
> +        public void testCrossFolderSaveRows() throws Exception
ok

2022-11-30 02:32 UTC, bbimber commented
@labkey-jeckels test just added

2022-11-30 17:49 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +        public void testCrossFolderSaveRows() throws Exception
Thanks for the test addition. Initial review looks good. I've pulled it into the LK repo to let TeamCity validate it.

2022-11-30 19:14 UTC, bbimber commented
@labkey-jeckels, thoughts on interpreting the results of these? The EHR tests all have a pre-existing WNPRC_EHR Test failure. 
 BVT-A has a bunch of DomainDesigner failures:

https://teamcity.labkey.org/buildConfiguration/LabKey_2211Release_Community_BvtASqlserver/2143836?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&expandBuildChangesSection=true

I dont see any reason these should be related to this change, but the last release22.11-SNAPSHOT BVT-A did pass: https://teamcity.labkey.org/buildConfiguration/LabKey_2211Release_Community_BvtAPostgres?mode=builds

2022-11-30 19:27 UTC, bbimber commented
@labkey-jeckels, actually i see the issue. can you please merge my last commit into the labkey side of the fork? i think this will fix the issue. prior to this change, when no containerPath was provided, it was interpreting this as empty string, not null, and this ended up converting to the root container. Obviously not desired and now fixed.

2022-12-01 02:15 UTC, labkey-jeckels commented
Update merged. The Postgres BVT-A passed and the SQLServer failure seems unrelated and a problem with FirefoxDriver. I queued a new build to confirm.

2022-12-01 13:49 UTC, bbimber commented
@labkey-jeckels: looks like the BVTs passed now

2022-12-01 21:52 UTC, labkey-jeckels approved these changes

2022-12-01 21:52 UTC, merged

2022-12-01 22:18 UTC, bbimber commented
Thanks @labkey-jeckels

2022-12-06 02:07 UTC, bbimber commented
@labkey-jeckels: I found a subtle problem with this. As-is, the JS trigger script layer initializes itself and it assumes the effective container is the ViewContext's container. In effect:

- core/resources/scripts/labkey/init.js is called by the ScriptTrigger._try
- This calls PageFlowUtil.jsInitObject()
- @labkey-adam apparently already noted the problem (see line 2260). Even if the TableInfo is using a different container, this code always defaults back to the view container.

I've been poking around this code for a bit and dont see an obvious way to fix that. We could add new properties in ScriptTrigger ~ line 250. However, labkey.js calls init.js using require(), and JS modules called via require() dont seem to have access to the scriptContext the java code injects. I'm seeing if we could pass context into the modules from require(), but no luck yet.

Are you aware of a way to force context into the JS scripts that might help here? Thanks for any ideas. I'm going to keep looking into this as well.

2022-12-06 20:46 UTC, bbimber commented
See solutions in #3902