Issue 46465: Fix behavior of grid actions when using a filtered set of selections
LabKey/platform pull request #3908
Opened 2022-12-07 20:56 UTC by labkey-susanh

#### Rationale
When a user selects items on a grid and then filters the grid so only a subset of the items is shown, the expectation is that any actions performed will use the selections shown in the filtered grid. For many actions, however, we pick up the original set of selections for performing actions. This PR modifies the behavior in these cases to use a snapshot selection in order to get at the filtered items.

#### Related Pull Requests
- https://github.com/LabKey/sampleManagement/pull/1444
- https://github.com/LabKey/biologics/pull/1778
- https://github.com/LabKey/labkey-ui-components/pull/1046
- https://github.com/LabKey/inventory/pull/637

#### Changes
* When exporting, we want to obey filters as well as selection key if present
* Allow for use of snapshot selections when getting operation confirmation data

2022-12-07 23:09 UTC, cnathe requested changes

2022-12-07 23:09 UTC, cnathe commented on api/src/org/labkey/api/data/RenderContext.java
> +            filter.addUrlFilters(url, name, displayColumns, user, container);
this line is the same as the else statement. could this instead just be moved outside of the if/else?

2022-12-07 23:09 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                selectedIds = DataRegionSelection.getSelectedIntegers(getViewContext(), getDataRegionSelectionKey(), clear);
looks like this type of code block is repeated 3 times in this PR. any way to refactor it to be shared or add a static util helper somewhere in this class?

2022-12-08 20:38 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                selectedIds = DataRegionSelection.getSelectedIntegers(getViewContext(), getDataRegionSelectionKey(), clear);
Created a new form that does this override for two of the three cases. The third case, because it has to handle picklists, still has its own override.

2022-12-08 20:38 UTC, labkey-susanh commented on api/src/org/labkey/api/data/RenderContext.java
> +            filter.addUrlFilters(url, name, displayColumns, user, container);
Sure. Simpler.

2022-12-08 20:47 UTC, cnathe approved these changes

2022-12-14 00:36 UTC, merged