Issue 46830: Decouple SampleNameGenCounter from the ContextListener logger
LabKey/platform pull request #3911
Opened 2022-12-08 22:13 UTC by XingY

#### Rationale
DbSequence.Preallocate allow reserving a batch of ids from a sequence to avoid excess DB actions for certain tasks. Those Preallocated sequence gets added to ContextListener and will be cleaned up during server shut down. The withCounter naming syntax uses DBSequence to get the count of a unique string value. Preallocates are used and put in a local cache to allow efficient name generation that uses withCounter. For Preallocates used by withCounter, we should properly clean them up after the name generation task is done, instead of relying on ContextListener to clean them up.

#### Related Pull Requests
* 

#### Changes
* move counterSequence cache from CounterExpressionPart to State
* explicitly clean up counterSequences and remove them from ContextListener on State.close

2022-12-08 22:52 UTC, labkey-matthewb requested changes

2022-12-08 22:52 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        ((DbSequence.Preallocate) seq).shutdownPre();
This really belongs in DbSequence.  Maybe seq.sync().  I don't think we really need to call done().

Maybe like this?

        public synchronized void sync()
        {
            if (null != _lastReservedValue && _currentValue != _lastReservedValue)
            {
                DbSequenceManager.setSequenceValue(this, _currentValue);
                _lastReservedValue = _currentValue;
            }
        }

2022-12-08 22:52 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +                    if (seq instanceof DbSequence.Preallocate)
Instead of using instanceof implement base method (see below) which noops .

2022-12-08 22:52 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        counterSeq = DbSequenceManager.getPreallocatingSequence(_container, _counterSeqPrefix + prefix);
Sorry, I'm not that familiar with NameGenerator.  This is a permanent counter and can't be implemented with an in memory counter?  Are we generating permanent counters on the fly based on user entered name expressions?

2022-12-08 23:06 UTC, XingY commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        ((DbSequence.Preallocate) seq).shutdownPre();
I need to call done() to remove this sequence from ContextListener.shutdownListeners. If not, user will get a log entry about this sequence when server shuts down.

2022-12-08 23:13 UTC, XingY commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        counterSeq = DbSequenceManager.getPreallocatingSequence(_container, _counterSeqPrefix + prefix);
Those are permanent counters based on name expression. It cannot be in memory counter because we need to how how many times a substring occurred not just in this run, but in all previous actions.

2022-12-08 23:17 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        ((DbSequence.Preallocate) seq).shutdownPre();
We could also change the shutdownStarted() to just call sync() so that it noops.  What is causing logging???  

Is having a lot of ContextListeners causing a problem?  It's odd that we have one per sequence, instead of one static listener for DbSequence.

2022-12-08 23:29 UTC, XingY commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        ((DbSequence.Preallocate) seq).shutdownPre();
Each opened Preallocate gets added to ContextListener._shutdownListeners. I believe the intention is do call the sync so that preallocated but unused sequence gets reset. Each shutdownListener would log a "Calling xx shutdownPre()" entry in the log. If there are lots of Preallocate on the server, the shut down process takes a long time to clean up those preallocated, and the large number of log entries pollutes the sever log file. 

There are really 2 problems.
1.  Preallocate are almost never synced and have to rely on _shutdownListeners to clean up / sync.
2. One _shutdownListener per Preallocate, which causes excessive logging. 

For the 1st problem, this PR try to address ones caused by withCounter usage. Because withCount is used for Aliquot naming pattern, the number of those sequences can be huge. There are other usages of Preallocate in the app that lingers until server gets shut down, but hopefully there won't be as many of those. 
For the 2nd problem, I agree a single listener for all sequences sounds a good way to go.

2022-12-08 23:33 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        ((DbSequence.Preallocate) seq).shutdownPre();
I'll look at turning this into one listener.  That should fix a lot of sins.

2022-12-09 00:05 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        ((DbSequence.Preallocate) seq).shutdownPre();
OK, I got rid of all the listeners.  That should help.  I think we can just change NameGenerator to use sync() and not worry about the listeners now.

2022-12-09 00:20 UTC, XingY commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        ((DbSequence.Preallocate) seq).shutdownPre();
Great! This looks much better now. I've adjusted NameGenerator accordingly.

2022-12-09 00:31 UTC, labkey-matthewb approved these changes

2022-12-12 14:51 UTC, labkey-susanh approved these changes

2022-12-13 18:54 UTC, merged