SQL Server: improve support for unicode characters
LabKey/platform pull request #3922
Opened 2022-12-13 23:09 UTC by labkey-nicka

#### Rationale
This adds support for unicode characters for SQL Server by prefixing string literals `N'string'`.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/3890

#### Changes
* Introduce `stringValue()` to `StandardDialectStringHandler`.
* Override `stringValue()` with new implementation `MicrosoftSqlServerStringHandler`.
* Utilize `dialect.getStringHandler().substituteParameters()` to process "sourceKey" filter parameter in experiment lineage.

2022-12-13 23:50 UTC, labkey-matthewb requested changes

2022-12-13 23:50 UTC, labkey-matthewb commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServerStringHandler.java
> +    protected String stringValue(String value)
Why not override quoteStringLiteral() and use super.quoteStringLiteral()?  This seems round about.

2022-12-13 23:50 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                    select = select.replace("$SOURCEKEY$", dialect.getStringHandler().substituteParameters(options.getSourceKeySQL()));
This should just be dialect.getStringHandler().quoteStringLiteral(optinos.getSourceKey())
This is very circuitous...
If we need to generalize this in the future (e.g. to support IN or other expressions ) then this whole thing will need to be reworked.  We use substituteParameters() for debug logging and the like, I don't think we use it for production SQL.

2022-12-14 00:23 UTC, labkey-nicka commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServerStringHandler.java
> +    protected String stringValue(String value)
Agreed. Much better. Fixed.

2022-12-14 00:27 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                    select = select.replace("$SOURCEKEY$", dialect.getStringHandler().substituteParameters(options.getSourceKeySQL()));
> This should just be dialect.getStringHandler().quoteStringLiteral(optinos.getSourceKey()) This is very circuitous... 

Agreed. Fixed.

> If we need to generalize this in the future (e.g. to support IN or other expressions ) then this whole thing will need to be reworked. We use substituteParameters() for debug logging and the like, I don't think we use it for production SQL.

It is not apparent at all from seeing this method that it is intended for debug logging and the like. If it is not intended for production then we should at minimum make a note and at most make it throw an exception in production environments.

2022-12-14 00:30 UTC, labkey-matthewb approved these changes

2022-12-14 21:04 UTC, merged