Handle update and clarify merge - samples and dataclasses
LabKey/platform pull request #3949
Opened 2022-12-23 18:38 UTC by XingY

#### Rationale

#### Related Pull Requests
* 

#### Changes
*

2022-12-30 19:11 UTC, labkey-matthewb commented
I may be wrong, but the only place I see that we can make use of ImportOption.UPDATE is via AbstractQueryImportAction (and subclasses).  Is there a plan for API support?  We can do that as part of another story, but it would be odd to support in the UI but not in the API.

2022-12-30 19:12 UTC, labkey-matthewb commented
It would be great to have a junit test for InsertOption.UPDATE generically, and the SM special cases.

2022-12-30 20:00 UTC, labkey-matthewb requested changes

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +            if (option.mergeRows || option.updateOnly)
I think it's good to encapsulate the sematics of checks like this into the enum itself.  E.g. option.mayUpdateRows()

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/NoNewRecordValidationDataIterator.java
> +            qus.verifyExistingRows(user, c, new ArrayList<>(keysMap.values()));
This seems very expensive.  Like the code we removed from detailed audit logging.  Why not use ExistingRecordDataIterator and getExistingRecord()?

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/StatementUtils.java
> +                sqlfUpdate.append(new SQLFragment(keys.values().iterator().next().getSelectName()));
Maybe we should throw here?  The caller could be given the chance to skip this iterator or rethrow a meaninful error.

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/StatementUtils.java
> +                sqlfUpdate.append(new SQLFragment(keys.values().iterator().next().getSelectName()));
I don't know the vocabulary stuff very well, but will this allow an update to add a vocabulary property?

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/RecordValidationDataIterator.java
> +        if (qus.hasExistingRowsInOtherContainers(c, keysMap))
Again this is very expensive.  Are we doing all this work just to report "there is a record in the another container" instead of  "record is not found".  It seems like we should only  select existing records in the current container, and when/if we find a missing record _THEN_ choose whether we want to do the work to distinguish "not found" from "found in another container"?  Maybe I'm missing something.

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +        _verifyExisting = option.updateOnly;
This really breaks encapsulation (ExistingRecordDataIterator knowing about the implementation requirements of particualar tables), also instanceof here is fragile.  These flags should be either passed into createBuilder() or maybe stashed as properties in the DataIteratorContext.

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/TriggerDataBuilderHelper.java
> +            else if (context.getInsertOption().mergeRows && !_target.supportMerge())
This really needs to be updated to supportsInsertOption(InsertOption option).  See https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=42788

2022-12-30 20:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/query/QueryService.java
> +        }
I think it's better to either a) add getAuditAction() to the enum (preferred) or b) enumerate all the values and throw in the default case (see See pattern in AbstractQueryImportAction._execute()) .  Otherwise, we things can get missed.

2022-12-30 20:00 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
>  import org.labkey.api.data.dialect.SqlDialect;
comment?

2022-12-30 20:06 UTC, XingY commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +        _verifyExisting = option.updateOnly;
I initially had it passed in to createBuilder, but the case that would be broken is TriggerDataBuilderHelper, as it doesn't know the params to pass in. I can look into having them on DataIteratorContext

2022-12-30 21:00 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
> +                throw new QueryUpdateServiceException("Row not found for " + absentName);
Will there always be only one? If not, any reason not to report on all missing names?

2022-12-30 21:00 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +        filter.addCondition(FieldKey.fromParts("Container"), container);
I'm a little unclear on this, but if the Name exists but from a different container (e.g., it's in the parent container), are we meant to allow that update?  It seems like that is being handled elsewhere, which is probably as it should be since the error message is more specific.  Maybe it's worth a comment here?

2023-01-02 23:45 UTC, XingY commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +            if (option.mergeRows || option.updateOnly)
done

2023-01-02 23:46 UTC, XingY commented on api/src/org/labkey/api/dataiterator/NoNewRecordValidationDataIterator.java
> +            qus.verifyExistingRows(user, c, new ArrayList<>(keysMap.values()));
I've got rid of this iterator and switched to use ExistingRecordDataIterator

2023-01-02 23:46 UTC, XingY commented on api/src/org/labkey/api/data/StatementUtils.java
> +                sqlfUpdate.append(new SQLFragment(keys.values().iterator().next().getSelectName()));
done

2023-01-02 23:51 UTC, XingY commented on api/src/org/labkey/api/dataiterator/RecordValidationDataIterator.java
> +        if (qus.hasExistingRowsInOtherContainers(c, keysMap))
I've got rid of this iterator in favor of using ExistingRecordDataIterator.

We don't want to update/merge a record that exist in a different folder. Apart from user expectation, using update statement on tables without checking their folder context can be dangerous. Because samples and data consist of 2 tables, exp.material/data and the provisioned. While exp.material/data has a container column, their provisioned table do not. An update on cross folder item would skip exp table, but would update the provisioned.

2023-01-02 23:51 UTC, XingY commented on api/src/org/labkey/api/dataiterator/ExistingRecordDataIterator.java
> +        _verifyExisting = option.updateOnly;
changes made to stashe in the DataIteratorContext.

2023-01-02 23:52 UTC, XingY commented on api/src/org/labkey/api/dataiterator/TriggerDataBuilderHelper.java
> +            else if (context.getInsertOption().mergeRows && !_target.supportMerge())
done

2023-01-02 23:52 UTC, XingY commented on api/src/org/labkey/api/query/QueryService.java
> +        }
done

2023-01-02 23:52 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
> +                throw new QueryUpdateServiceException("Row not found for " + absentName);
This function is now removed as part of the refactoring to use ExistingRecordDataIterator for checking cross folder / existence of data.

2023-01-02 23:52 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +        filter.addCondition(FieldKey.fromParts("Container"), container);
This function is now removed as part of the refactoring to use ExistingRecordDataIterator for checking cross folder / existence of data.

2023-01-02 23:53 UTC, XingY commented on api/src/org/labkey/api/data/StatementUtils.java
> +                sqlfUpdate.append(new SQLFragment(keys.values().iterator().next().getSelectName()));
Good reminder. I've added vocabulary properties handling as part of the follow up story.

2023-01-03 21:46 UTC, XingY commented
> It would be great to have a junit test for InsertOption.UPDATE generically, and the SM special cases.

Junit tests added for samples, dataclass and list:
https://github.com/LabKey/platform/pull/3949/commits/8ca7b14fa949073260b0c4d34a310d6fc5fea5b0

For LKSM use cases, I did add junit test that uses detailed logging. The other piece that I'm not able to simulate is the "Projects" feature (the check for cross folder data), since it's based on site configuration. I'll defer that to integration test.

2023-01-03 21:53 UTC, XingY commented
> I may be wrong, but the only place I see that we can make use of ImportOption.UPDATE is via AbstractQueryImportAction (and subclasses). Is there a plan for API support? We can do that as part of another story, but it would be odd to support in the UI but not in the API.

By API, do you mean the updateRows api? Or some import api? If the former, there is a follow up story to use data iterators to do bulk updates.

2023-01-04 16:11 UTC, labkey-susanh reviewed
This seems fine to me, but I'll defer to Matt for final review.

2023-01-04 16:11 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeTestCase.jsp
> +    // AliquotedFrom is supplied but doesn't match the current aliquot status / parents should get ignored
Ignored? Wouldn't this be an error? Or is AliquotedFrom always ignored now for update.

2023-01-04 16:11 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +                throw new QueryUpdateServiceException("TODO");
TODO.

2023-01-04 16:11 UTC, labkey-susanh commented on study/src/org/labkey/study/query/DatasetTableImpl.java
> +            removeDisallowedInsertOption(QueryUpdateService.InsertOption.MERGE);
The double-negative aspect of this `removeDisallowed` gives me pause. I might have chosen to setDisallowed or setAllowed, but that's mainly a style thing.

2023-01-04 20:42 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +                throw new QueryUpdateServiceException("TODO");
actually this is no longer needed. removed.

2023-01-04 20:43 UTC, XingY commented on study/src/org/labkey/study/query/DatasetTableImpl.java
> +            removeDisallowedInsertOption(QueryUpdateService.InsertOption.MERGE);
renamed

2023-01-04 20:45 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeTestCase.jsp
> +    // AliquotedFrom is supplied but doesn't match the current aliquot status / parents should get ignored
I'm torn between error out and ignore as well... I've made the UI update to let user know that AliquotedFrom cannot be updated during file preview step. We can iterate on this behavior in the future.

2023-01-05 20:29 UTC, labkey-matthewb approved these changes

2023-01-05 20:29 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/AbstractTableInfo.java
> +    public boolean supportInsertOption(QueryUpdateService.InsertOption option)
I think SimpleTable supports MERGE by default (this is sometimes a problem).
We could leave it this way by default, and try to track down the cases where we actually _want_ MERGE to work, but there might be a lot of usages.

2023-01-05 20:29 UTC, labkey-matthewb commented on api/src/org/labkey/api/query/AbstractQueryUpdateService.java
> +        @Test
Maybe we could add this to  _insertRowsUsingDIB?  Might cause a bunch of errors initially, but would force consistency.

    if (!_queryTable.supportsInsertOption(context.getInsertOption()))
        throw new IllegalStateException();

2023-01-05 20:29 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/TableInfo.java
> +        return true;
Hmm, should probably return false if getUpdateService() is null, but we don't have a cheap way to know that....  Maybe switch default in the future...

2023-01-06 18:01 UTC, merged