Issue 46949: Sample timeline detail links aren't shown for subfolder samples when parent is in project level
LabKey/platform pull request #3969
Opened 2022-12-30 20:22 UTC by XingY

#### Rationale
Issue [46949](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=46949): Sample timeline detail links aren't shown for subfolder samples when parent is in project level 
Sample timeline needs to be able to find renamed entity with its legacy name at a specific time point. The utils for finding those entities currently don't work in cross folder scenarios. 

#### Related Pull Requests
* 

#### Changes
* support containerFilter for getEffectiveSampleType, getEffectiveSample, getEffectiveDataClass and getEffectiveData utils

2023-01-02 14:36 UTC, labkey-susanh approved these changes

2023-01-02 14:36 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeImpl.java
> +        SimpleFilter filter = new SimpleFilter(FieldKey.fromParts("ObjectId"), objectId);
I suppose the container filter is not really needed here since the objectId is globally unique.

2023-01-02 14:36 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeImpl.java
> +    private SimpleFilter getContainerFilterClause(Container c, @Nullable ContainerFilter cf)
This seems like it might belong with SimpleFilter, and I'm surprised there isn't such a think already.

2023-01-02 18:19 UTC, labkey-nicka requested changes

2023-01-02 18:19 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeImpl.java
> +        if (cf != null)
Rather than composing the filter here I'd recommend using `ContainerFilter.createFilterClause()`. The main reason is that all container filters may not operate in the same way so we don't want to presume an IN clause, etc. The usage would be something like this:

```java
public ExpMaterialImpl getSample(Container c, String name, @Nullable ContainerFilter cf)
{
    SimpleFilter filter = new SimpleFilter(FieldKey.fromParts("CpasType"), getLSID());
    filter.addCondition(FieldKey.fromParts("Name"), name);
    if (cf != null)
        filter.addCondition(cf.createFilterClause(ExperimentServiceImpl.get().getExpSchema(), FieldKey.fromParts("Container")));

    Material material = new TableSelector(ExperimentServiceImpl.get().getTinfoMaterial(), filter, null).getObject(Material.class);
    if (material == null)
        return null;
    return new ExpMaterialImpl(material);
}
```

And then you can just delete this entire `SimpleFilter getContainerFilterClause(Container c, @Nullable ContainerFilter cf)` method.

2023-01-02 18:19 UTC, labkey-nicka commented on api/src/org/labkey/api/data/Container.java
> +    public ContainerFilter getProjectDataContainerFilter(User user)
Please rectify this with `BiologicsManager.getContainerFilter()`. I would also recommend using the `create()` pattern.

```java
@Nullable
public static ContainerFilter getContainerFilter(@NotNull Container c, User user)
{
    if (!c.isProductProjectsEnabled() || c.isRoot() || ContainerManager.getSharedContainer().equals(c))
        return null;

    if (c.isProject())
        return ContainerFilter.Type.CurrentAndSubfoldersPlusShared.create(c, user);
    return ContainerFilter.Type.CurrentPlusProjectAndShared.create(c, user);
}
```

2023-01-02 18:20 UTC, labkey-nicka commented on api/src/org/labkey/api/data/Container.java
> +    public ContainerFilter getProjectDataContainerFilter(User user)
Also, consider renaming to `getProductProjectsDataContainerFilter`.

2023-01-25 00:30 UTC, XingY commented on api/src/org/labkey/api/data/Container.java
> +    public ContainerFilter getProjectDataContainerFilter(User user)
done

2023-01-25 00:30 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpSampleTypeImpl.java
> +        if (cf != null)
done

2023-01-27 18:25 UTC, labkey-nicka approved these changes

2023-01-29 19:39 UTC, merged