Let the warnings pass through when loading Query Definition
LabKey/platform pull request #4003
Opened 2023-01-10 08:33 UTC by labkey-bpatel

#### Rationale
Fix for WNPRC test failure "Error on line 4: Query or table not found: ehr_billing_public.aliases"
![image](https://user-images.githubusercontent.com/10765266/211497804-c2a9b36c-91b7-4517-af47-abf12b89d371.png)

These failures are unveiled as a result of recent change that added a check for presence of errors; however, in the above case, there are warnings generated while loading Query Definition for the linked table (ehr_billing_public.aliases) and are not actual errors.

#### Changes
* Add isError() check to ensure there are indeed any errors, and let the warnings pass through

2023-01-10 19:02 UTC, labkey-jeckels requested changes

2023-01-10 19:02 UTC, labkey-jeckels commented on query/src/org/labkey/query/QueryDefinitionImpl.java
> +                if (null == table || (null != errors && !errors.isEmpty() && errors.stream().anyMatch(error -> error instanceof QueryParseException && ((QueryParseException)error).isError())))
This is subtly different from the similar check here: https://github.com/LabKey/platform/blob/6fb3151a624541e6b2f7133b6527e2415bf191b5/query/src/org/labkey/query/LinkedSchema.java#L345

The other code checks to see if it's explicitly tagged as a warning. This checks if it's an error. If there's some other variant of QueryException in the list, it will continue through.

I haven't tested but I think this will be a more consistent approach:

```suggestion
                if (null == table || (null != errors && !errors.isEmpty() && !errors.stream().allMatch(error -> error instanceof QueryParseException && ((QueryParseException)error).isWarning())))

```

2023-01-10 20:28 UTC, labkey-bpatel commented on query/src/org/labkey/query/QueryDefinitionImpl.java
> +                if (null == table || (null != errors && !errors.isEmpty() && errors.stream().anyMatch(error -> error instanceof QueryParseException && ((QueryParseException)error).isError())))
Thanks, Josh! That is exactly what i had initially, and it works, then changed it to check for error instead.

2023-01-10 20:29 UTC, labkey-bpatel commented on query/src/org/labkey/query/QueryDefinitionImpl.java
> +                if (null == table || (null != errors && !errors.isEmpty() && errors.stream().anyMatch(error -> error instanceof QueryParseException && ((QueryParseException)error).isError())))
Thanks, Josh! That is exactly what i had initially, and it works, then changed it to check for error instead.

2023-01-10 20:32 UTC, labkey-bpatel commented on query/src/org/labkey/query/QueryDefinitionImpl.java
> +                if (null == table || (null != errors && !errors.isEmpty() && errors.stream().anyMatch(error -> error instanceof QueryParseException && ((QueryParseException)error).isError())))
Thanks, Josh! That is exactly what i had initially, and it works, then changed it to check for error instead.

2023-01-10 20:46 UTC, labkey-jeckels approved these changes
The change looks fine to me but let's check with @labkey-klum and @labkey-tchad to confirm this will get merged into develop. I can't quite remember what happens automatically vs via special request.

2023-01-10 21:39 UTC, labkey-tchad commented
> The change looks fine to me but let's check with @labkey-klum and @labkey-tchad to confirm this will get merged into develop. I can't quite remember what happens automatically vs via special request.

23.1-SNAPSHOT will get merged forward tomorrow and then again next Wednesday when we release 23.1.0

2023-01-10 22:34 UTC, labkey-jeckels commented
Thanks @labkey-tchad. I'll go ahead and merge now so it gets included tomorrow.

2023-01-10 22:35 UTC, merged

2023-01-12 18:12 UTC, labkey-jeckels commented
@labkey-bpatel the tests are failing in 22.11 so we should backport this. @labkey-tchad can we safely cherry-pick merge this into 22.11?