Here is another idea for taming robot indexers
LabKey/platform pull request #4016
Opened 2023-01-12 04:33 UTC by labkey-matthewb

#### Rationale
use rel=canonical to help ignore containerFilter variations

#### Related Pull Requests
* 

#### Changes
*

2023-01-13 17:47 UTC, labkey-jeckels requested changes

2023-01-13 17:47 UTC, labkey-jeckels commented on api/src/org/labkey/api/action/PermissionCheckableAction.java
> +            if (this instanceof BaseViewAction<?> viewaction)
Do we expect this to be common? Won't crawlers always be guests?

Note there are a number of unit test failures when there's not a full HTTP request in progress: https://teamcity.labkey.org/buildConfiguration/LabkeyTrunk_BvtBPostgres/2225932?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

2023-01-13 17:47 UTC, labkey-jeckels commented on api/src/org/labkey/api/view/template/PageConfig.java
> +            if (pair.getKey().endsWith(CONTAINER_FILTER_NAME))
```suggestion
            // Strip container filters from the URL to prevent crawlers from over-indexing a URL with different parameter values
            if (pair.getKey().endsWith(CONTAINER_FILTER_NAME))

```

2023-01-17 18:29 UTC, labkey-matthewb commented on api/src/org/labkey/api/action/PermissionCheckableAction.java
> +            if (this instanceof BaseViewAction<?> viewaction)
I was thinking about how we might use annotations as hints (or explicitly).  I agree this is not functional...

2025-01-17 19:53 UTC, closed without merging