Issue 46951: clear domain cache early in process of updating the domain
LabKey/platform pull request #4039
Opened 2023-01-19 15:16 UTC by labkey-susanh

#### Rationale
When in the process of updating a domain, if the domain cache is cleared too late it can happen that the tableInfo and the domain get out of sync, resulting in an incomplete/incorrect domain for fields that have been added.  Here we add a sometimes-redundant call to clear the domain cache early in the process of updating the domain so this mismatch doesn't happen.

#### Changes
* Clear the domain cache held by `OntologyManager` earlier

2023-01-19 18:32 UTC, labkey-matthewb requested changes

2023-01-19 18:32 UTC, labkey-matthewb commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +                // Issue 46951: be sure the domain is invalidated early in the process of updating so we don't get
I think we can be more surgical than this.   However, I think we have a basic problem that the DbSchema cache of TableInfo is not a DatabaseCache (not transaction aware).  I think we need to change that first for schemas with provisioned tables.  Then we can fix the order of invalidating objects here.

2023-01-19 18:53 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +                // Issue 46951: be sure the domain is invalidated early in the process of updating so we don't get
This sounds like more surgery than I have training for so am going to need some more pointers, unless you or @labkey-adam is interested in taking this on 😄. Do you mean converting the `DbSchemaCache._cache` to be a DatabaseCache? Does the SchemaTableInfoCache also need to get updated?

2023-01-27 18:49 UTC, labkey-susanh commented
Closing in favor of the more surgical approach here https://github.com/LabKey/platform/pull/4045

2023-01-27 18:49 UTC, closed without merging