Compliance logging refactor
LabKey/platform pull request #4112
Opened 2023-02-13 21:52 UTC by labkey-matthewb

#### Rationale
The query compiler now participates in generating ColumnLogging objects. 

#### Related Pull Requests
* 

#### Changes
*

2023-02-22 20:07 UTC, labkey-jeckels commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                    entryList.add(null);
I'm not understanding why we add nulls to the List and then filter them out when converting to a LinkedHashSet. Couldn't we just add the non-null values to the LinkedHashSet directly?

2023-02-22 20:07 UTC, labkey-jeckels commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                return _i < _row.size();
Is this correct? Seems like the remaining entries might all be `DOES_NOT_CONTAINKEY`

2023-02-22 20:07 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/ColumnLogging.java
> +    @Nullable
Can these commented variables be deleted? As it stands now, the `@Nullable` applies to `_shouldLogName` which doesn't make sense for a `boolean` to be nullable

2023-02-22 20:07 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/ColumnLogging.java
> +//                uniqueColumnKey, _columnScopeKey,
Many places that create ColumnLogging objects have these constructor args commented out. Are they useful to retain?

2023-02-22 20:07 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/ColumnLogging.java
> +        throw new UnsupportedOperationException();
Should we just not implement `Comparable`?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/QueryServiceImpl.java
> +    public SelectBuilder getSelectBuilder(TableInfo table)
Seems like a factory method - rename to `createSelectBuilder`?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/AbstractQueryRelation.java
> +    private static final Logger _log = LogManager.getLogger(QuerySelect.class);
```suggestion
    private static final Logger _log = LogManager.getLogger(AbstractQueryRelation.class);
```

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/AbstractQueryRelation.java
> +        PHI getPHI()
Should this be an abstract method to ensure that all subclasses think about what they should return?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QAggregate.java
> +        REGR_INTERCEPT(false, false)            // TODO: Should this be true?
`false` seems OK to me. It's possible that the intercept happens to be a value in the input data, but won't normally be

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QQuery.java
> +        AbstractQueryRelation.RelationColumn col = relation.getFirstColumn();
Is there always just a single column in this case? Is this enforced somewhere?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/Query.java
> +    /* Whenever a RelationColumn with a new unique name is created, add it should be added to this map */
```suggestion
    /* Whenever a RelationColumn with a new unique name is created, it should be added to this map */
```

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QueryLookupWrapper.java
> +    class PassThroughColumn extends QLWColumn
I'm having a hard time understanding the difference between `PassThroughColumn` and `QueryLookupColumn`. Maybe a comment on both?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QueryPivot.java
> +        public void afterConstruct()
Useless override

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QuerySelect.java
> +            protected void afterInitializeColumns()
Useless override

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QuerySelect.java
> +        ColumnLogging getColumnLogging()
Useless override

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QuerySelectView.java
> +                    // Use UnexpectedException to be consistent I guess??
Use `UnexpectedException` or `UnauthorizedException`?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QueryUnion.java
> +    /* Hopefully we can evantually avoid doing all this work when column logging is not enabled, so do this as late as possible.
```suggestion
    /* Hopefully we can eventually avoid doing all this work when column logging is not enabled, so do this as late as possible.

```

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QueryUnion.java
> +        QueryTableInfo fakeTableInfo = new QueryTableInfo(this, "UNION")
We also have one of these in QueryLookupWrapper. Worth sharing?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QueryUnion.java
> +                col._columnLogging = new ColumnLogging(this.getSchema().getSchemaName(), "UNION", col.getFieldKey(), shouldLog, dataLoggingColumns, "TODO", sqap);
`TODO`?

2023-02-22 20:07 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QueryUnion.java
> +        public ColumnLogging getColumnLogging()
Useless override

2023-02-22 20:59 UTC, labkey-matthewb commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                    entryList.add(null);
We want the order of entrySet() and iterator() and values() to match.  The order we're trying to be consistent with is array index order.
This loop is iterating the keys, but they are not in any order, so we stash them in an array so we can match the keys to the values.  This does raise the idea of making the FindMap be a LinkedHashMap, then we could force the FindMap to iterate in a defined order.

2023-02-22 21:01 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/ColumnLogging.java
> +//                uniqueColumnKey, _columnScopeKey,
Thanks, that is now drek.  I tried to imitate the old behavior of identifying two columns as  being the "same" by comparing ColumnLogging objects, until I decided it was hopeless.  I'll track these down.

2023-02-22 21:02 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/ColumnLogging.java
> +        throw new UnsupportedOperationException();
I wanted to make sure that no one is using .equals() or .compareTo() since the old usage of these methods were all cases of bad logic.

2023-02-22 21:04 UTC, labkey-matthewb commented on query/src/org/labkey/query/sql/QuerySelectView.java
> +                    // Use UnexpectedException to be consistent I guess??
We need  a separate design/PR to figure out the right error to throw.  I'm being consistent with the existing code in that problems with being able to do required audit logging throws Unauthorized.  I don't particularly like that choice.

2023-02-22 21:05 UTC, labkey-matthewb commented on query/src/org/labkey/query/sql/QueryUnion.java
> +        QueryTableInfo fakeTableInfo = new QueryTableInfo(this, "UNION")
I thought about it.  Then I thought, it might be even better to get rid of the need for the fake table.  But this train ran out of track.

2023-02-24 19:37 UTC, labkey-adam requested changes

2023-02-24 19:37 UTC, labkey-adam commented on api/src/org/labkey/api/data/ColumnLogging.java
> +    public ColumnLogging addScope(String scope)
Rename since `scope` is unused?

2023-02-24 19:37 UTC, labkey-adam commented on api/src/org/labkey/api/data/ColumnLogging.java
> +     * time if column logging is enabled.  I don't particularly like this pattern.  I would be better to maybe
```suggestion
     * time if column logging is enabled.  I don't particularly like this pattern.  It would be better to maybe
```

2023-02-24 19:37 UTC, labkey-adam commented on api/src/org/labkey/api/data/ColumnLogging.java
> +     * psas in a QueryLogging objet into query compile?
```suggestion
     * pass in a QueryLogging object into query compile?
```

2023-02-27 17:27 UTC, labkey-matthewb commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                return _i < _row.size();
On next() and construct we skip ahead.

2023-02-27 17:28 UTC, labkey-matthewb commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                    entryList.add(null);
added a comment to consider using LinkedHashMap

2023-02-27 17:29 UTC, labkey-jeckels commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                return _i < _row.size();
Yes, I see that next() will skip blank entries. But what if only blank entries remain? hasNext() will return true even though it shouldn't, won't it?

2023-02-27 18:17 UTC, labkey-matthewb commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                return _i < _row.size();
I'm not seeing it.  In this case next() will iterate to the end of the list and we'll be sitting at _i==_row.size() and return false.
When next() returns it has to be true that either a) we are on an entry or b) off the end.

2023-02-27 18:40 UTC, labkey-matthewb commented on query/src/org/labkey/query/sql/QueryUnion.java
> +                col._columnLogging = new ColumnLogging(this.getSchema().getSchemaName(), "UNION", col.getFieldKey(), shouldLog, dataLoggingColumns, "TODO", sqap);
Thanks.  Also see 47399

2023-02-27 18:45 UTC, labkey-matthewb commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                return _i < _row.size();
Added assert

2023-02-27 18:48 UTC, labkey-jeckels commented on api/src/org/labkey/api/collections/ArrayListMap.java
> +                return _i < _row.size();
Ah, my mistake. I wasn't catching that next() was advancing *after* it had pulled the element it will return. You're right, this should be fine.

2023-02-27 19:56 UTC, labkey-jeckels approved these changes
@labkey-matthewb there are a couple of comments that you didn't respond to related to comments, etc. If you saw them and don't think it's worth adjusting, that's fine, but wanted to check they weren't missed.

2023-02-27 19:56 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/ColumnLogging.java
> +        throw new UnsupportedOperationException();
Makes sense for `equals()` Seems like the best way to make sure code doesn't try to compare us is to not implement Comparable and in the first place.

2023-02-27 19:56 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QAggregate.java
> +        REGR_INTERCEPT(false, false)            // TODO: Should this be true?
```suggestion
        REGR_INTERCEPT(false, false)

```

2023-02-27 19:56 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QueryLookupWrapper.java
> +    class PassThroughColumn extends QLWColumn
This a comment on the difference would still be nice

2023-02-27 20:04 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/ColumnLogging.java
> +        throw new UnsupportedOperationException();
I see, missed that.

2023-02-27 20:55 UTC, labkey-matthewb commented on query/src/org/labkey/query/sql/QAggregate.java
> +        REGR_INTERCEPT(false, false)            // TODO: Should this be true?
I think these should probably be (true, true), using the same logic as for SUM/MIN/MAX?

2023-02-27 21:33 UTC, labkey-adam commented on query/src/org/labkey/query/sql/QAggregate.java
> +        REGR_INTERCEPT(false, false)            // TODO: Should this be true?
Or (true, false). I guess you're arguing that the intercept could be an actual value in the single row case? I have a hard time seeing how a single floating point number, unconnected to any PTID, could ever be interpreted as PHI. This is very different to me than MIN/MAX which can operate on strings. But I don't think it matters much either way, so you could go with (true, true) to be conservative.

2023-02-27 21:36 UTC, labkey-matthewb commented on query/src/org/labkey/query/sql/QAggregate.java
> +        REGR_INTERCEPT(false, false)            // TODO: Should this be true?
I just did a test, and it requires two rows to return non-null value.  So I’m good leaving it as well.

2023-02-27 21:42 UTC, labkey-jeckels commented on query/src/org/labkey/query/sql/QAggregate.java
> +        REGR_INTERCEPT(false, false)            // TODO: Should this be true?
I don't log a comment, but I also thought about this and decided it was safe. Sure, it's possible that the calculated intercept happens to be exactly the same as `y` value where `x==0` but that seems like having a values that happens to be equal to the standard deviation - the same number, but not PHI

2023-02-28 01:10 UTC, labkey-adam approved these changes

2023-02-28 01:12 UTC, merged