Move stored amount fields from inventory.item table to exp.materials table
LabKey/platform pull request #4130
Opened 2023-02-20 03:28 UTC by labkey-susanh

#### Rationale
We want to make it easier for users to track the amounts of samples, whether they are in storage or not. Currently, users define their own domain fields for tracking amounts, which doesn't allow us to use the application functionality for editing these amounts or compute aliquot amounts. When we begin supporting inventory item, it will also be more common that the samples would not be tracked in storage, but we still want to allow users to provide amounts and units in a way the application can easily interact with them. By moving the amount and units fields from the inventory.item table into the exp.materials table, these values can be tracked before, during and after the samples are in storage.

Not all the work is done here, but I want to get some feedback.

TODO items:
- Handle permissions for StorageEditor
- Handle populating amounts and units when using SampleID QuerySelect when adding samples to storage
- Probably updating SamplesEditableGrid to remove Storage tab, but at least showing the Samples tab so Storage Editors can update amounts and units
- Moving metric and amount-related methods, etc. into ui-components

#### Related Pull Requests
- https://github.com/LabKey/inventory/pull/743

#### Changes
- Move data for inventory.items.volume and inventory.items.volumeUnits columns to exp.materials table
- Remove initialVolume, volume, and volumeUnits columns from inventory.items table
- Rename "Volume" and "VolumeUnits" to "StoredAmount" and "Units"
- Move classes and methods associated with measurements and amounts into api module in a new measurement package
- Move aliquot rollup methods into sample data iterators

2023-02-20 20:48 UTC, XingY requested changes

2023-02-20 20:48 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                if (!aliquotParentLsids.isEmpty() && (!Objects.equals(existingAmount, newAmount) || !Objects.equals(existingUnits, newUnits)))
This logic seems problematic. 

Existing record map might not always be present, for example, when import with merge from LKS, without detailed audit log.

For merge/update, if existing record is present, compare volume/unit. If existing record is not present (either merge a new record, or detailed audit is not on), then recalc needs to be set as long as the record is aliquot. This would include parents that are false positive for recalc, but better than missing recalc.

2023-02-20 20:48 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    aliquotParentLsids.add((String) get(_aliquotedFromCol));
For insert/merge, `get(_aliquotedFromCol))` returns parent name, not parent lsid.

2023-02-20 20:48 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            if (_context.getErrors().hasErrors() || !hasAmountData())
aliquot count change also triggers recalc, but I believe that's already handled in ExperimentSerivceImpl.saveExpMaterialAliquotOutputs so checking amount here is sufficient.

2023-02-20 20:48 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    aliquotParentLsids.add((String) get(_aliquotedFromCol));
For update, get(aliquotedfromlsidcol) should return parent lsid.

2023-02-20 20:48 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            if (isSample)
I believe this step can be skipped for INSERT. Whenever an new aliquot is created, it always triggers recal (handled by ExperimentServiceImpl.saveExpMaterialAliquotOutputs)

2023-02-20 20:48 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            if (!_sampleType.isMedia() && rows != null && (rows.get(0).containsKey("StoredAmount") || rows.get(0).containsKey("Amount") || rows.get(0).containsKey("Units")))
The row by row updateRows might have different set of fields in each row. The recal logic should be checked in each _update, where we have accurate new vs old information for each row.

2023-02-21 00:06 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                if (!aliquotParentLsids.isEmpty() && (!Objects.equals(existingAmount, newAmount) || !Objects.equals(existingUnits, newUnits)))
Logic updated to account for missing existing record.

2023-02-21 00:07 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    aliquotParentLsids.add((String) get(_aliquotedFromCol));
Capturing either name or lsid values for aliquot parents now.

2023-02-21 00:08 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            if (isSample)
Thanks. Added condition on import type.

2023-02-21 00:08 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            if (!_sampleType.isMedia() && rows != null && (rows.get(0).containsKey("StoredAmount") || rows.get(0).containsKey("Amount") || rows.get(0).containsKey("Units")))
Ugh. Well, I guess this is already slow. Moved this check into `_update`.

2023-02-23 18:51 UTC, XingY requested changes
Can we not use display column? Also, media sample type needs to recalc for aliquot created count.

2023-02-23 18:51 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                if (_aliquotedFromCol != null && get(_aliquotedFromCol) != null)
aliquotedFromLsid should be preferred if updateOnly. The AliquotedFrom provided for updateOnly is ignored.

2023-02-23 18:51 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            if (hasNext)
Should this be handled in a smaller batch size? Is there any danger with a too large set of updatedSampleLsids in memory?

2023-02-23 18:51 UTC, XingY commented on api/src/org/labkey/api/data/measurement/AmountDataColumn.java
> +    public Object getDisplayValue(RenderContext ctx)
When using display column, sort and filter wouldn't work correctly. Is there a plan to handle that?

2023-02-23 18:51 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            if (!_sampleType.isMedia())
The only case that can bypass recalc for media sample type is updateRows. For insert/delete, the addition or removal of aliquots triggers aliquot created count recalc.

2023-02-23 18:51 UTC, XingY commented on experiment/resources/schemas/exp.xml
> +              <className>org.labkey.api.data.measurement.AmountDataColumn$Factory</className>
Do we have to use a display column? This would make sort/filtering not reliable. Since we are already doing so much manipulation of data during insert/update, can we just convert the amount and unit during insert/update, so the stored db value would match the expected display value?

2023-02-23 18:56 UTC, XingY commented on experiment/resources/schemas/exp.xml
> +              <className>org.labkey.api.data.measurement.AmountDataColumn$Factory</className>
I guess the scenario that's messy is when sample type's unit gets changed. But then we can just update all amounts and units then?

2023-02-23 20:30 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    existingAmount = (Double) existingMap.get("StoredAmount");
It's likely that my story to support disabling system fields will get merged first. When you merge in those changes, you might need to mark storedamount and units as not disableble for now, and then have a follow up story to support allow disabling them.

2023-02-23 21:26 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            if (!_sampleType.isMedia())
Ah, shoot. Yes. Gotta do this for media since we support aliquots for media now.

2023-02-23 23:51 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            if (!_sampleType.isMedia())
Ok, deferring this until we do the follow-on story for media where the amount fields are properly supported.

2023-02-24 00:02 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +            if (hasNext)
I don't know that memory would be an issue, but the giant IN clause might be. I'll see about batching this up, but might defer it to a separate branch, depending on what else I need to fix.

2023-02-24 00:40 UTC, labkey-susanh commented on api/src/org/labkey/api/data/measurement/AmountDataColumn.java
> +    public Object getDisplayValue(RenderContext ctx)
We have this problem already (a value of 100 uL will sort larger than 2 mL), so we aren't addressing it immediately.

2023-02-24 00:44 UTC, labkey-susanh commented on experiment/resources/schemas/exp.xml
> +              <className>org.labkey.api.data.measurement.AmountDataColumn$Factory</className>
We chose to store the data as entered because of better data integrity, so I'll leave this as is for now. We can discuss further with @labkey-hannah when she's back.

2023-02-24 00:45 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    existingAmount = (Double) existingMap.get("StoredAmount");
Thanks for the reminder.

2023-02-25 23:29 UTC, XingY approved these changes

2023-02-25 23:29 UTC, XingY commented on api/src/org/labkey/api/data/measurement/UnitsDataColumn.java
> +                Measurement.Unit storedUnit = Measurement.Unit.valueOf(units.toString());
units.toString().trim()?

2023-02-25 23:29 UTC, XingY commented on experiment/resources/schemas/exp.xml
> +              <className>org.labkey.api.data.measurement.AmountDataColumn$Factory</className>
Is there any way for users to see the data as stored? When the fields were with inventory.items, users can go to items table to see the actual value, even though on samples grids they uses display column. How would users get this information with the changes to override display column at this level?

2023-02-25 23:29 UTC, XingY commented on experiment/resources/schemas/exp.xml
> +              <className>org.labkey.api.data.measurement.AmountDataColumn$Factory</className>
Also, not all sample types have type level units. LKS doesn't. Would the indiscriminate use of display column complicate certain scenarios unnecessarily?

2023-02-26 00:08 UTC, labkey-susanh commented on api/src/org/labkey/api/data/measurement/UnitsDataColumn.java
> +                Measurement.Unit storedUnit = Measurement.Unit.valueOf(units.toString());
Done. Thanks.

2023-02-26 00:12 UTC, labkey-susanh commented on experiment/resources/schemas/exp.xml
> +              <className>org.labkey.api.data.measurement.AmountDataColumn$Factory</className>
I hope the display columns account for the absence of the display units well, but it is difficult (at least when testing) to not have the raw values available.  Perhaps it's worth adding separate columns (e.g., "RawAmount" and "RawUnits") that wrap the amount and units columns, respectively, and don't have a display column factory.  Brings in more columns that might conflict with existing domain columns, of course.

2023-03-01 19:30 UTC, merged