Issue 47440: LKSM: withCounter jumping
LabKey/platform pull request #4175
Opened 2023-03-04 05:31 UTC by XingY

#### Rationale
WithCounter name expression uses DBSequence to generate a next sequence number for a particular prefix string in a specific container. It's reported that users are seeing generated count using withCounter name expression would jump. This is mostly due to DBSequence CUD intentionally uses its own transaction to simulate database sequence behavior, and partly due to the cached preallocates remembering the last used count.

#### Related Pull Requests
* 

#### Changes
* Introduce ReclaimablePreallocate and related util to allow rolling back of DB sequence updates
* Switch WithCounter syntax to use ReclaimablePreallocate
* Explicitly sync ReclaimablePreallocate at the end of name generation task and remove them from cache
* Note that Create/Read of ReclaimablePreallocate continues to use its own transaction because those are mostly harmless

2023-03-04 15:10 UTC, labkey-matthewb commented
There are a lot of issues to consider with this which makes me hesitant to consider this for 23.3 without some testing under load/contention.

- This will effectively serialize insert into tables that use these counters
- That may be OK, but we would probably want to grab locks on involved counters at the beginning of the main transaction to reduce deadlocks
-  We locate sequences with one filter/index (container, name, id) and update using another (container, rowid).  I wonder if that increases the chance of deadlock scenarios, potentially with unrelated sequences?
- Deadlocks on unrelated sequences might be more of a problem on SQL Server (just guessing).  We might want to consider aiming to load the DbSequence objects using the name index outside the transaction, and only using the rowid index in the transaction.
-  Unrelated, why do we use container in the update statement?

2023-03-06 20:50 UTC, labkey-jeckels commented
I also worry about deadlocks, especially on SQLServer. Do we have a stress test that covers this scenario? Or could be adapted to cover it? @labkey-martyp @labkey-danield https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=46808

2023-03-06 23:01 UTC, XingY commented
> There are a lot of issues to consider with this which makes me hesitant to consider this for 23.3 without some testing under load/contention.
> 
> * This will effectively serialize insert into tables that use these counters
> * That may be OK, but we would probably want to grab locks on involved counters at the beginning of the main transaction to reduce deadlocks
> * We locate sequences with one filter/index (container, name, id) and update using another (container, rowid).  I wonder if that increases the chance of deadlock scenarios, potentially with unrelated sequences?
> * Deadlocks on unrelated sequences might be more of a problem on SQL Server (just guessing).  We might want to consider aiming to load the DbSequence objects using the name index outside the transaction, and only using the rowid index in the transaction.
> * Unrelated, why do we use container in the update statement?

Thanks Matt. 

I agree this is too much for 23.3. The other option is to have this change go in 23.3 under an experimental flag, which would be used by a few hosted postgres users only. We can then test and evaluate this change in develop. 

- Not sure what it would take to grab lock at the beginning of the main transaction... The update/insert sqls has XLOCK and ROWLOCK applied to them. Also, all mutating actions are synchronized. 
- Do you mean to use (container, name, id) for UPDATE when useCurrentTransaction == true?  
- I agree container seems not needed in Update since PK is rowId

2023-03-06 23:03 UTC, XingY commented
> I also worry about deadlocks, especially on SQLServer. Do we have a stress test that covers this scenario? Or could be adapted to cover it? @labkey-martyp @labkey-danield https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=46808

Good pointer. We plan to make available of this feature in 23.3 under an experimental flag only. We should definitely add scenarios in stress test in develop.

2023-03-06 23:33 UTC, labkey-martyp commented
> I also worry about deadlocks, especially on SQLServer. Do we have a stress test that covers this scenario? Or could be adapted to cover it? @labkey-martyp @labkey-danield https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=46808

ExperimentStressTest would be a good one to use. Right now it's failing due to a different sql server deadlock issue. I should be able to get back to that this week.

2023-03-06 23:37 UTC, XingY commented
> > I also worry about deadlocks, especially on SQLServer. Do we have a stress test that covers this scenario? Or could be adapted to cover it? @labkey-martyp @labkey-danield https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=46808
> 
> ExperimentStressTest would be a good one to use. Right now it's failing due to a different sql server deadlock issue. I should be able to get back to that this week.

Thanks Marty. FYI, I'm separately working on deferring aliquot rollup compute. Now that inventory tables no longer triggers recompute, I might as well reenable this test in my other branch. https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=47246

2023-03-06 23:51 UTC, labkey-martyp commented
> > > I also worry about deadlocks, especially on SQLServer. Do we have a stress test that covers this scenario? Or could be adapted to cover it? @labkey-martyp @labkey-danield https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=46808
> > 
> > 
> > ExperimentStressTest would be a good one to use. Right now it's failing due to a different sql server deadlock issue. I should be able to get back to that this week.
> 
> Thanks Marty. FYI, I'm separately working on deferring aliquot rollup compute. Now that inventory tables no longer triggers recompute, I might as well reenable this test in my other branch. https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=47246

Oh great, I didn't realize that work was being done. Yeah that RecomputeRollup column is a pretty hot column during import, glad to hear you're deferring the rollup.

2023-03-08 21:35 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/DbSequenceManager.java
> +
check null==rowId

2023-03-08 21:46 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +        if (seq instanceof DbSequence.ReclaimablePreallocate)
Instance of should be pushed into the method on the individual classes or to DbSequenceManager.  The user of DbSequencerManager shouldn't be need to help with the implementation differences.

2023-03-08 21:55 UTC, labkey-matthewb commented
I'm having a hard time convincing myself this is correct.  I believe that in order to be correct, the code depends on only one transaction can be using a particular reclaimable db sequence at a time.  This _might_ be true on postgres due to the lock collected in getRowId(withUpdateLock=true).  However, the use of a map by getReclaimablePreallocateSequence() makes it possible (certainly with sqlserver), that the same object may be returned to two callers.  When the sequence is removed from the map by invalidateReclaimablePreallocateSequence(), this does not do anything about instances of this object that may still be held by other threads.  

The very simplest change I can think of to make this work would be to use a regular DbSequence (w/o preallocation) with the useCurrentTransaction() idea.  To do both transaction and preallocation and useCurrentTransaction() might be possible, but will require some tricky synchronization between the in-memory sequence objects and the sql transactions.

2023-03-08 22:05 UTC, XingY commented
> I'm having a hard time convincing myself this is correct. I believe that in order to be correct, the code depends on only one transaction can be using a particular reclaimable db sequence at a time. This _might_ be true on postgres due to the lock collected in getRowId(withUpdateLock=true). However, the use of a map by getReclaimablePreallocateSequence() makes it possible (certainly with sqlserver), that the same object may be returned to two callers. When the sequence is removed from the map by invalidateReclaimablePreallocateSequence(), this does not do anything about instances of this object that may still be held by other threads.
> 
> The very simplest change I can think of to make this work would be to use a regular DbSequence (w/o preallocation) with the useCurrentTransaction() idea. To do both transaction and preallocation and useCurrentTransaction() might be possible, but will require some tricky synchronization between the in-memory sequence objects and the sql transactions.

The ReclaimablePreallocateSequence is a half way solution that allows rollback of sequences without race condition. The newly introduced 3rd param to withCounter force ReclaimablePreallocateSequence to only reserve 1 sequence, effectively turning it into a non preallocate. For some clients / scenarios, the continuity are more important than performance, so the 3rd param to the name expression will allow them to opt in for correctness over performance. But the default syntax would allow better performance and correctness in a non race condition scenario: if a single tread has to rollback, but no competing thread is using the same sequence, then no gap will be produced. 

I worry the use of DBSeq without preallocate would be too slow. It's used by aliquot generation which is known to be produced at large quantities. So I feel a compromised solution might be better.

2023-03-09 19:00 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/NameGenerator.java
> +                if (!("true".equals(noGapBool) || "'true'".equals(noGapBool) || "false".equals(noGapBool) || "'false'".equals(noGapBool)))
I don't like the pattern of using "bare" boolean values because it makes future changes or generalization of the syntax difficult.  Maybe the use of named options would be better.

2023-03-10 19:13 UTC, labkey-matthewb requested changes
I think this all looks good except I would not use getReclaimablePreallocateSequence() in NameGenerator for 23.3.   I don't think the in-memory object will stay synced with the database in all scenarios.

2023-03-10 19:48 UTC, XingY commented
> I think this all looks good except I would not use getReclaimablePreallocateSequence() in NameGenerator for 23.3. I don't think the in-memory object will stay synced with the database in all scenarios.

Do you think that we might be able to get ReclaimablePreallocateSequence 100% correct in develop? If so, then sure we can use the non preallocates in 23.3 and safely switch later. But if not, I worry if we make DBSequence without preallocate the default in 23.3, then we won't able to default to the faster ReclaimablePreallocate later, because we don't want clients to see behavior regression.

2023-03-10 20:41 UTC, labkey-matthewb commented
> > I think this all looks good except I would not use getReclaimablePreallocateSequence() in NameGenerator for 23.3. I don't think the in-memory object will stay synced with the database in all scenarios.
> 
> Do you think that we might be able to get ReclaimablePreallocateSequence 100% correct in develop? If so, then sure we can use the non preallocates in 23.3 and safely switch later. But if not, I worry if we make DBSequence without preallocate the default in 23.3, then we won't able to default to the faster ReclaimablePreallocate later, because we don't want clients to see behavior regression.

That is a really good question…. I _think_ we can.  DbSequence works because the database is “in charge” and it always asks the database what the next value is.  Preallocate is a bit of a hybrid, but you can think of it as being “in charge”, because sync() is telling the database what the next value is.  Transacted Preallocate is tricky because we want to be able to sync() (tell the database) and also handle rollback (probably ask the database).  I think we can make this work by using DbScope.addCommitTask().

2023-03-10 20:58 UTC, XingY commented
> > > I think this all looks good except I would not use getReclaimablePreallocateSequence() in NameGenerator for 23.3. I don't think the in-memory object will stay synced with the database in all scenarios.
> > 
> > 
> > Do you think that we might be able to get ReclaimablePreallocateSequence 100% correct in develop? If so, then sure we can use the non preallocates in 23.3 and safely switch later. But if not, I worry if we make DBSequence without preallocate the default in 23.3, then we won't able to default to the faster ReclaimablePreallocate later, because we don't want clients to see behavior regression.
> 
> That is a really good question…. I _think_ we can. DbSequence works because the database is “in charge” and it always asks the database what the next value is. Preallocate is a bit of a hybrid, but you can think of it as being “in charge”, because sync() is telling the database what the next value is. Transacted Preallocate is tricky because we want to be able to sync() (tell the database) and also handle rollback (probably ask the database). I think we can make this work by using DbScope.addCommitTask().

Sounds good. changes made to not use preallocates in 23.3

2023-03-10 21:11 UTC, labkey-matthewb approved these changes

2023-03-14 17:06 UTC, merged