TableSelector getAggregates optimization to only use PK columns when requesting COUNT(*) aggregate
LabKey/platform pull request #4185
Opened 2023-03-08 20:57 UTC by cnathe

#### Rationale
In the related PR, we made an optimization so that when generating the select SQL for a sample type, we skip the INNER JOIN to the materialized table when no columns from that table were being selected. This PR make the same type of change for Data Class tables. 

In addition, it makes a change to the TableSelector getAggregates() method so that if just the COUNT(*) aggregate is being requested, which happens for every DataRegion in LKS, we only use the PK columns for the given table. This allows for that aggregate query to make use of the optimizations made for the sample type and data class tables as mentioned above.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/4183

#### Changes
* Apply the checkSelectedColumnsFromRootOnly() check to Data Classes as well as Sample Types
* TableSelector getAggregates() method update to only use PK columns when getting just the COUNT(*) aggregate

2023-03-08 21:14 UTC, labkey-matthewb requested changes

2023-03-08 21:14 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/TableSelector.java
> +        Collection<ColumnInfo> aggColumns = aggregates.size() == 1 && aggregates.get(0).isCountStar() ? _table.getPkColumns() : _columns;
Need to check that getPkColumns is non-empty().

2023-03-08 21:17 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/TableSelector.java
> +        Collection<ColumnInfo> aggColumns = aggregates.size() == 1 && aggregates.get(0).isCountStar() ? _table.getPkColumns() : _columns;
It's also possible to do add an expr column like "new ExprColumn(table, "~one~", new SqlFragment("1"))

2023-03-09 00:45 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpRunItemTableImpl.java
> +    protected boolean checkSelectedColumnsFromRootOnly(Set<FieldKey> selectedColumns, Set<String> rootColNames)
I might change the name of this method to more clearly indicate what the true or false value it returns indicates. Something like `containsOnlyRootColumns`.

2023-03-09 00:45 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
> +        sql.append(") ").append(subAlias);
Was this closing paren always missing? I'm not seeing where the open paren got added.

2023-03-14 20:51 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExpRunItemTableImpl.java
> +    protected boolean checkSelectedColumnsFromRootOnly(Set<FieldKey> selectedColumns, Set<String> rootColNames)
Good call. Changed.

2023-03-14 20:53 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
> +        sql.append(") ").append(subAlias);
Nope, the closing paren was always there. It was split out from end of the previous line 693.

2023-03-15 16:31 UTC, cnathe commented on api/src/org/labkey/api/data/TableSelector.java
> +        Collection<ColumnInfo> aggColumns = aggregates.size() == 1 && aggregates.get(0).isCountStar() ? _table.getPkColumns() : _columns;
Done. Thanks for the suggestion!

2023-03-15 18:27 UTC, labkey-susanh approved these changes

2023-03-20 17:41 UTC, labkey-matthewb commented
Note for future possible changes:  We might also want to detect case when only provisioned columns are present.  It would be great to make the common lookup to sample type usages also avoid this join.

2023-03-20 17:41 UTC, labkey-matthewb approved these changes

2023-03-20 18:49 UTC, merged