QueryService.getSelectBuilder()
LabKey/platform pull request #4186
Opened 2023-03-08 22:22 UTC by labkey-matthewb

#### Rationale
There are a lot of getSelectSql() overloads in QueryService.  The SelectBuilder allows us to make a more sane API, but maybe a bit more verbose.  We can also roll up some of the selector() and select() methods.  Lastly, this builder will propagate QueryLogging between getSelectSql() and the Selector for execution helping with the usage pattern there.

#### Related Pull Requests
* 

#### Changes
*

2023-03-10 23:41 UTC, labkey-nicka reviewed
I like it!

2023-03-10 23:41 UTC, labkey-nicka commented on api/src/org/labkey/api/dataiterator/QueryDataIteratorBuilder.java
> +import static org.labkey.api.data.DataRegion.MessagePart.filter;
Unnecessary import.

2023-03-10 23:41 UTC, labkey-nicka commented on api/src/org/labkey/api/data/NameGenerator.java
> +                            var select = QueryService.get().getSelectBuilder(lookupTable)
I'm definitely in favor of dropping the need to pass in `null` for sort almost everywhere.

2023-03-10 23:41 UTC, labkey-nicka commented on api/src/org/labkey/api/query/QueryService.java
> +     * superseded by getSelectBuilder()
nit: Consider `superseded by {@link QueryService#getSelectBuilder}` here an in similar comments.

2023-03-17 22:09 UTC, labkey-adam requested changes
Is there a compelling reason to hang `getSelectBuilder()` off QueryService? Wouldn't it be more convenient to allow creating a new `SelectBuilder` via `SelectBuilder.get(TableInfo)`?

2023-03-20 20:14 UTC, labkey-matthewb commented on api/src/org/labkey/api/query/QueryService.java
> +     * superseded by getSelectBuilder()
Done

2023-03-20 20:18 UTC, labkey-matthewb commented
> Is there a compelling reason to hang `getSelectBuilder()` off QueryService? Wouldn't it be more convenient to allow creating a new `SelectBuilder` via `SelectBuilder.get(TableInfo)`?

That pattern would be nice.  However, getSelectBuilder(schema,sql) makes use of internal query.main classes.  So, adding these to a service interface makes sense, in that case at least.

2023-03-20 21:16 UTC, labkey-adam approved these changes

2023-03-20 22:52 UTC, merged