Issue 43559: Domain designer error on invalid lookup
LabKey/platform pull request #4198
Opened 2023-03-14 21:53 UTC by labkey-martyp

#### Rationale
This throws an error and doesn't allow a domain design to be saved if it has an invalid lookup. The use case would be when a lookup target table is altered after a domain is created. Next time the domain design is opened the field and form give an error and won't allow the domain to be saved until corrected.

https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=43559&_docid=issue%3A43559

#### Related Pull Requests
- https://github.com/LabKey/labkey-ui-components/pull/1141

#### Changes
- Add lookupIsValid flag to property descriptor calculated for API query
- Calculate valid lookup based on container and table name within schema
- Update @labkey/components package with UI handling of lookupIsValid

2023-03-15 00:20 UTC, labkey-jeckels requested changes
This is causing BVT failures.

```
java.lang.NullPointerException: Cannot invoke "org.labkey.api.query.UserSchema.getTableNames()" because the return value of "org.labkey.api.query.QueryService.getUserSchema(org.labkey.api.security.User, org.labkey.api.data.Container, String)" is null
  at org.labkey.api.exp.property.DomainUtil.isValidPdLookup(DomainUtil.java:184)
  at org.labkey.api.exp.property.DomainUtil.getDomainDescriptor(DomainUtil.java:264)
  at org.labkey.api.exp.property.DomainUtil.getDomainDescriptor(DomainUtil.java:199)
  at org.labkey.api.exp.property.AbstractDomainKind.getDomainNamePreviews(AbstractDomainKind.java:321)
```

2023-03-15 00:26 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        Set<String> tableNames = QueryService.get().getUserSchema(user, lookupContainer, p.getLookupSchema()).getTableNames();
Can we use a `DefaultSchema` to help cache schemas in case multiple lookups for the same domain reference the same schemas? @labkey-matthewb

2023-03-15 00:26 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        if (tableNames.stream().anyMatch(p.getLookupQuery()::equalsIgnoreCase))
Could also use a `CaseInsensitiveHashSet`

2023-03-15 13:48 UTC, labkey-martyp commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        Set<String> tableNames = QueryService.get().getUserSchema(user, lookupContainer, p.getLookupSchema()).getTableNames();
> This is causing BVT failures.
> 
> ```
> java.lang.NullPointerException: Cannot invoke "org.labkey.api.query.UserSchema.getTableNames()" because the return value of "org.labkey.api.query.QueryService.getUserSchema(org.labkey.api.security.User, org.labkey.api.data.Container, String)" is null
>   at org.labkey.api.exp.property.DomainUtil.isValidPdLookup(DomainUtil.java:184)
>   at org.labkey.api.exp.property.DomainUtil.getDomainDescriptor(DomainUtil.java:264)
>   at org.labkey.api.exp.property.DomainUtil.getDomainDescriptor(DomainUtil.java:199)
>   at org.labkey.api.exp.property.AbstractDomainKind.getDomainNamePreviews(AbstractDomainKind.java:321)
> ```

This is fixed. Templates sneaking in invalid schemas.

2023-03-15 13:49 UTC, labkey-martyp commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        Set<String> tableNames = QueryService.get().getUserSchema(user, lookupContainer, p.getLookupSchema()).getTableNames();
@josheckels QueryService.getUserSchema does use a DefaultSchema. Is that what you're referring to?

2023-03-15 15:42 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        Set<String> tableNames = QueryService.get().getUserSchema(user, lookupContainer, p.getLookupSchema()).getTableNames();
Right - it creates a DefaultSchema behind the scenes, but it uses a new one for each time that you call `QueryService.get().getUserSchema()`. That means that it can't reuse a `UserSchema`. However, if you create and reuse your own `DefaultSchema` (one per container), it would be able to cache and reuse the schemas, which can sometimes be expensive to construct. It might be easier to talk if I'm not yet making sense.

2023-03-15 16:51 UTC, cnathe commented on core/package.json
> +    "@labkey/components": "2.308.0-fb-domain-invalid-lookup.0",
since the field editor component is used in both LKB and LKSM apps, I'd suggest also opening an fb for those modules and bumping this package version there as well.

2023-03-15 22:07 UTC, labkey-matthewb commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        Set<String> tableNames = QueryService.get().getUserSchema(user, lookupContainer, p.getLookupSchema()).getTableNames();
Yes, reusing DefaultSchema is a good idea in general.  In this case, it's not immediately obvious who would be hanging on to the DefaultSchema.  Would the caller of getDomainDescriptor() pass it in?

2023-03-15 23:57 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        Set<String> tableNames = QueryService.get().getUserSchema(user, lookupContainer, p.getLookupSchema()).getTableNames();
I suggested to Marty that he make `getDomainDescriptor()` manage it. That would at least reuse the `DefaultSchema` for all of the properties in a single domain.

2023-03-16 16:23 UTC, labkey-jeckels approved these changes
Thanks for the DefaultSchema changes. They look good so I'm approving, though the TeamCity build is failing for unrelated reasons.

2023-03-21 15:43 UTC, merged