Add Rename Container API Action
LabKey/platform pull request #4335
Opened 2023-04-20 23:52 UTC by RosalineP

#### Rationale
We are seeking to add the ability to rename a container to our APIs, the first step of which is the addition of some server-side changes.

#### Related Pull Requests
* 

#### Changes
* Rename error check that is already being handled in `ContainerManager.rename`
* Add new action

2023-04-24 13:59 UTC, cnathe requested changes

2023-04-24 13:59 UTC, cnathe commented on core/src/org/labkey/core/admin/AdminController.java
> -            }
curious why this validation check is being removed here? is it because it is already checked in the UI / JSP or something along those lines? It seems like it is still a valid check.

2023-04-24 13:59 UTC, cnathe commented on core/src/org/labkey/core/admin/AdminController.java
> -            }
ah, I think I see now. Looks like this validation check and others are already being done within `ContainerManager.rename()`

2023-04-24 13:59 UTC, cnathe commented on core/src/org/labkey/core/CoreController.java
> +    public class RenameContainerAction extends MutatingApiAction<SimpleApiJsonForm>
I was expecting to see some validation checks here, but then (as per the other comments in this PR) I noticed that they are happening within the `ContainerManager.rename()` method. Maybe worth a comment here saying where the validation is happening.

2023-04-24 13:59 UTC, cnathe commented on core/src/org/labkey/core/CoreController.java
> +            boolean addAlias = json.optBoolean("addAlias");
Is there a specific reason for using this form of JSON binding and the `SimpleApiJsonForm`? I was expecting something more like the SampleManagerController.RenameProjectAction which uses `ProjectSettingsForm` or the AdminController.RenameFolderAction which uses `ManageFoldersForm`. Any reason for not creating an explicity java class in this case?

2023-04-24 13:59 UTC, cnathe commented on core/src/org/labkey/core/CoreController.java
> +    public class RenameContainerAction extends MutatingApiAction<SimpleApiJsonForm>
Also, is there a reason why this new action was added to the CoreController? I guess I would have expected it to live right next to the UI version in AdminController.

2023-04-25 00:02 UTC, RosalineP commented on core/src/org/labkey/core/CoreController.java
> +    public class RenameContainerAction extends MutatingApiAction<SimpleApiJsonForm>
Added the comment! I think the original thought was that the action could be (in alphabetical order, as the file goes) in the same file as the CreateContainerAction, DeleteContainerAction, MoveContainerAction in CoreController but I think having it next to the UI action in AdminController makes more sense

2023-04-25 00:03 UTC, RosalineP commented on core/src/org/labkey/core/CoreController.java
> +            boolean addAlias = json.optBoolean("addAlias");
I meant for this to be reviewed after getting pulled to real PR (which was unclear, my bad there) so there were some artifacts of me looking at adjacent actions and following their patterns—but I've updated this to use the more normal java class pattern!

2023-04-25 13:10 UTC, cnathe approved these changes

2023-04-25 13:10 UTC, cnathe commented on core/src/org/labkey/core/admin/AdminController.java
> +        private boolean addAlias = true;
does the UI action also default this to `true`?

2023-04-25 15:48 UTC, RosalineP commented on core/src/org/labkey/core/admin/AdminController.java
> +        private boolean addAlias = true;
So, the UI default checks it to true but the `ManageFoldersForm` defaults it to false. Maybe because the UI is default toggled to true. So I opted for true here

2023-04-25 21:45 UTC, merged