Project level data type configuration schema and UI
LabKey/platform pull request #4417
Opened 2023-05-12 13:43 UTC by XingY

#### Rationale

#### Related Pull Requests
* 

#### Changes
*

2023-05-15 22:27 UTC, labkey-susanh requested changes

2023-05-15 22:27 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/api/ExperimentService.java
> +        storagelocation
Can we capitalize to better align with Java naming conventions (or the naming convention in this file, at least)?

2023-05-15 22:27 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +    public Map<String, Object>[] getContainerDataTypeExclusions(DataTypeForExclusion dataType, String excludedContainerId, Integer dataTypeRowId)
```suggestion
    public Map<String, Object>[] getContainerDataTypeExclusions(@Nullable DataTypeForExclusion dataType, @Nullable String excludedContainerId, @Nullable Integer dataTypeRowId)
```

2023-05-15 22:27 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +    public void ensureContainerDataTypeExclusions(DataTypeForExclusion dataType, @Nullable Collection<Integer> excludedDataTypeRowIds, String excludedContainerId, User user)
```suggestion
    public void ensureContainerDataTypeExclusions(DataTypeForExclusion dataType, @Nullable Collection<Integer> excludedDataTypeRowIds, @Nullable String excludedContainerId, User user)
```

Perhaps this would be better called `updateContainerDataTypeExclusions`?

2023-05-17 20:08 UTC, XingY commented on api/src/org/labkey/api/exp/api/ExperimentService.java
> +        storagelocation
done

2023-05-18 00:11 UTC, labkey-susanh approved these changes

2023-05-18 05:09 UTC, merged