Update db consistency check for missing storage column
LabKey/platform pull request #4423
Opened 2023-05-15 03:33 UTC by labkey-martyp

#### Rationale
Update the db consistency check to handle the case a property descriptor does not have a storage column name. Throw an error explaining the issue and fix the issue by copying the PD name to the storage column name (instead of deleting and re-adding the field).

Related Reports:
http://localhost:8080/labkey/admin-doCheck.view
http://localhost:8080/labkey/<Container>/experiment-types-repair.view?domainUri=<param>

#### Changes
* Report that the PD is missing storage column name (instead of PD missing column and column missing a PD)
* On fix, add the PD name as the storage column name

2023-05-15 15:10 UTC, labkey-jeckels requested changes

2023-05-15 15:10 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/property/StorageProvisionerImpl.java
> +                if (null == propDescriptor.getStorageColumnName())
I think this should also check to see if `hardColumnNames` has the storage column. Otherwise, it could end up pointing to a column that doesn't actually exist in the table

2023-05-15 15:10 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/property/StorageProvisionerImpl.java
> +                        pd.setStorageColumnName(pd.getName());
As commented below, we should only do this when the column is really in the table. Or am I missing a check elsewhere here that will catch it?

2023-05-16 17:13 UTC, labkey-martyp commented on experiment/src/org/labkey/experiment/api/property/StorageProvisionerImpl.java
> +                if (null == propDescriptor.getStorageColumnName())
Ok I added that check. I was going for best effort fix here before just removing and adding the PD.

2023-05-16 17:13 UTC, labkey-martyp commented on experiment/src/org/labkey/experiment/api/property/StorageProvisionerImpl.java
> +                        pd.setStorageColumnName(pd.getName());
I added that. Fixing the domain refreshes and re-runs the report which would throw a subsequent error in the case you're mentioning here, but we can save that additional step and just check initially if the column exists.

2023-05-17 16:32 UTC, labkey-jeckels approved these changes

2023-05-17 16:32 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/property/StorageProvisionerImpl.java
> +                        pd.setStorageColumnName(pd.getName());
Oh, I hadn't considered a multi-step process to get the domain back to healthy.

2023-05-17 16:53 UTC, merged