Issue 47268: Export Does Not Include Failed Lookup Values
LabKey/platform pull request #4465
Opened 2023-05-28 18:55 UTC by labkey-bpatel

#### Rationale
Issue [47268](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=47268): Export Does Not Include Failed Lookup Values

#### Changes
* Export broken lookup values just like it is displayed in the UI

2023-05-29 00:32 UTC, labkey-jeckels approved these changes

2023-05-29 00:32 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/DisplayColumn.java
> +                    return "<" + ctx.get(this.getColumnInfo().getName()) + ">";
```suggestion
                    return "<" +value + ">";
```

2023-06-02 22:05 UTC, labkey-jeckels requested changes
This approach means that integer lookup values that do resolve are treated as strings. That means they get left-aligned, don't sort/filter as desired, in Excel, etc.

Can we be more targeted and only flip to string cells for broken lookups?

2023-06-03 18:36 UTC, labkey-bpatel commented
> This approach means that integer lookup values that do resolve are treated as strings. That means they get left-aligned, don't sort/filter as desired, in Excel, etc.
> 
> Can we be more targeted and only flip to string cells for broken lookups?

Excellent point! Now updated

2023-06-03 21:21 UTC, labkey-jeckels approved these changes

2023-06-08 19:56 UTC, merged