Project level data type - remove experimental flag
LabKey/platform pull request #4467
Opened 2023-05-29 22:31 UTC by XingY

#### Rationale

#### Related Pull Requests
* 

#### Changes
* remove isProductProjectDataTypeSelectionEnabled experimental flag
* allow querying for container data type exclusions by container path

2023-05-30 22:13 UTC, labkey-susanh requested changes

2023-05-30 22:13 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        sql.append(" AND DataType = ?");
Should this be `sql.append(" AND DataType = ").appendValue(dataType.name())` (and similar below)?

2023-05-30 22:13 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                Container container = ContainerManager.ensureContainer(excludedContainerIdOrPath);
`ensureContainer` is going to create the container if it doesn't exist. Is that what we want?

2023-05-30 22:13 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +    public void _removeDataTypeExclusion(Collection<Integer> rowIds, DataTypeForExclusion dataType, @Nullable String excludedContainerId)
Obviously not a functional problem, but the use of `_` as a prefix to a public method name seems not quite right stylistically.  This name doesn't seem like it will conflict with other names, so the `_` doesn't seem necessary.  (Maybe naming conventions have changed for Java, but I don't think `_` is usually used as a prefix for private function names either.)

2023-05-31 03:24 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                Container container = ContainerManager.ensureContainer(excludedContainerIdOrPath);
good catch. fixed

2023-05-31 03:25 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        sql.append(" AND DataType = ?");
Hmm... Is one preferred over the other?

2023-05-31 14:02 UTC, labkey-susanh approved these changes

2023-05-31 14:02 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        sql.append(" AND DataType = ?");
I had thought the `appendValue` was becoming the new preferred syntax, but the use of `add` obviously still works.

2023-05-31 18:20 UTC, merged