Issue 48056: More list indexing fixes
LabKey/platform pull request #4535
Opened 2023-06-25 04:48 UTC by labkey-bpatel

#### Rationale
Issue [48056](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=48056): More list indexing fixes

#### Changes
*

2023-06-26 20:04 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListManager.java
> +        TableInfo listTable = list.getTable(User.getSearchUser());
I've seen User.getSearchUser() used elsewhere so using it here - unless I am missing something, it does not seem right since the search user might just not have the write permission.

2023-06-27 22:49 UTC, labkey-adam requested changes
See comments

2023-06-27 22:49 UTC, labkey-adam commented on list/src/org/labkey/list/model/ListManager.java
>          deleteIndexedAttachments(list);
Shouldn't this call be conditional on `list.getFileAttachmentIndex()`, similar to the others?

2023-06-27 22:49 UTC, labkey-adam commented on list/src/org/labkey/list/model/ListManager.java
>      }
FYI: I'm planning to push a change that significantly simplifies this batch handling. It's old code, but worth fixing.

2023-06-27 22:49 UTC, labkey-adam commented on list/src/org/labkey/list/model/ListManager.java
> +                }, DbScope.CommitTaskOption.POSTCOMMIT);
This isn't needed or useful. `setLastIndexed()` is called by the indexer thread, so this will never be in a transaction.

2023-06-27 22:49 UTC, labkey-adam commented on list/src/org/labkey/list/model/ListManager.java
> +        TableInfo listTable = list.getTable(User.getSearchUser());
We just need the scope, and we know it's the LabKey scope. Could just call `DbScope.getLabKeyScope()` and call it good.

2023-06-27 22:49 UTC, labkey-adam commented
See BVT failures as well

2023-06-28 04:37 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListManager.java
> +        TableInfo listTable = list.getTable(User.getSearchUser());
Sounds good, thanks!

2023-06-28 04:37 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListManager.java
>          deleteIndexedAttachments(list);
Yup, i missed that! Thank you!

2023-06-28 04:39 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListManager.java
> +                }, DbScope.CommitTaskOption.POSTCOMMIT);
This was one of my initial additions, I had meant to remove it, thanks for catching it

2023-06-28 12:44 UTC, labkey-adam requested changes

2023-06-28 12:44 UTC, labkey-adam commented on list/src/org/labkey/list/model/ListManager.java
> +                    (newEachItemBodyTemplate != null && !newEachItemBodyTemplate.equals(oldEachItemBodyTemplate)) ||
I don't think these checks are correct... switching from custom template to standard template will not trigger a clear, because new template is null. I think you want `Objects.equals()` in both cases.

2023-06-28 12:44 UTC, labkey-adam commented on list/src/org/labkey/list/model/ListManager.java
> +                    (newEntireListBodyTemplate != null && !newEntireListBodyTemplate.equals(oldEntireListBodyTemplate)) ||
Same here: use `Objects.equals()`

2023-06-28 12:48 UTC, labkey-adam commented
@labkey-bpatel This PR is close. One more requested change (use `Objects.equals()`). Please also review my recent commit for sanity. I'm out for a while today, but will be able to review again this afternoon.

2023-06-28 17:47 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListManager.java
> +                    (newEachItemBodyTemplate != null && !newEachItemBodyTemplate.equals(oldEachItemBodyTemplate)) ||
good point! done!

2023-06-28 17:53 UTC, labkey-bpatel commented
> @labkey-bpatel This PR is close. One more requested change (use `Objects.equals()`). Please also review my recent commit for sanity. I'm out for a while today, but will be able to review again this afternoon.

Requested change is in. Thanks for those updates, much cleaner.

2023-06-29 14:28 UTC, labkey-adam approved these changes
I think this PR is ready to go, but please review my attachment indexing changes and the test results before merging.

2023-06-30 04:40 UTC, merged