Add support for ancestor lookups for data classes
LabKey/platform pull request #4597
Opened 2023-07-18 16:25 UTC by labkey-susanh

#### Rationale
We are finding there is a demand for supporting source lineage in order to model real-world data. This PR adds support for using Ancestor lookups in query grids in the same way we support it for samples. 

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/1236
* https://github.com/LabKey/labkey-ui-premium/pull/138
* https://github.com/LabKey/sampleManagement/pull/1970
* https://github.com/LabKey/biologics/pull/2240

#### Changes
* Add metric to count the number of data class objects that have data class parents
* Add Ancestor lookup column to DataClass tables and update `ClosureQueryHelper` to also compute closure for data class objects.

2023-07-18 18:26 UTC, labkey-matthewb requested changes

2023-07-18 18:26 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ClosureQueryHelper.java
> +            return getValueSql(userSchema, type, sourceLSID, objectId, "m" + st.getRowId(), true);
Doesn't the last boolean parameter here depend on sourceType (TableType type) rather than targetType?

If so, maybe just pass sourceType all the way through instead of converting to a boolean?

2023-07-18 22:07 UTC, XingY commented on experiment/src/org/labkey/experiment/ExperimentModule.java
> +                results.put("dataWithDataParentsCount", new SqlSelector(ExperimentService.get().getSchema(), "SELECT COUNT(DISTINCT d.sourceApplicationId) FROM exp.data d\n" +
Would this include Biologics registry related entities? Is this what we want?

2023-07-19 14:15 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExperimentModule.java
> +                results.put("dataWithDataParentsCount", new SqlSelector(ExperimentService.get().getSchema(), "SELECT COUNT(DISTINCT d.sourceApplicationId) FROM exp.data d\n" +
The related entities are generally not represented by experiment runs, so I think this will be fine. Question out to @labkey-hannah about the particulars here, though.

2023-07-19 15:29 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExperimentModule.java
> +                results.put("dataWithDataParentsCount", new SqlSelector(ExperimentService.get().getSchema(), "SELECT COUNT(DISTINCT d.sourceApplicationId) FROM exp.data d\n" +
Hannah indicated that this count should be fine for our usage evaluation purposes.

2023-07-19 15:30 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ClosureQueryHelper.java
> +            return getValueSql(userSchema, type, sourceLSID, objectId, "m" + st.getRowId(), true);
I've made this change, though I'm still a bit baffled why I've seen no difference in behavior when using one or the other implementation. I must not be looking at the right combination of source and target tables...

2023-07-20 15:50 UTC, labkey-matthewb approved these changes

2023-07-27 14:10 UTC, merged