New Line Support for Multi Value Filters
LabKey/platform pull request #4608
Opened 2023-07-19 23:28 UTC by RosalineP

#### Rationale
Whereas previously it was necessary to use a semicolon delimited list of values with multi-value filters such as 'Contains One Of', with these changes it is possible to use a newline as a delimiter. As such, filter value inputs for relevant multi-value filters have been changed from field inputs to textarea inputs. See [spec](https://docs.google.com/document/d/1148zLiMiyYkYbZd2mODGhH2kQK7XIdZGsK3lktnpWh0/edit?usp=sharing) for more details.

#### Related Pull Requests
* 

#### Changes
* Where relevant, use secondary value seperator while parsing values
* Ext updates to support frontend textarea filter-value input (thanks Xing!)
* Update packages

2023-07-19 23:34 UTC, RosalineP commented on api/webapp/clientapi/ext3/FilterDialog.js
> +                emptyText: xType === 'textarea' ? 'Use semicolon or new line to separate entries' : null,
ToDo: Update as Adam suggested to 'Use new line or semicolon to separate entries'

2023-07-25 18:01 UTC, XingY requested changes

2023-07-25 18:01 UTC, XingY commented on query/src/org/labkey/query/reports/getdata/FilterClauseBuilder.java
> +            assertEquals("(((\"Field1\" IN ('value2', 'value1'))))", toLabKeySQL(CompareType.IN, "value1;value2", JdbcType.VARCHAR));
Why did the ordering change?

2023-07-25 18:01 UTC, XingY commented on api/webapp/clientapi/ext3/FilterDialog.js
> +                emptyText: xType === 'textarea' ? 'Use semicolon or new line to separate entries' : null,
still todo?

2023-07-25 18:01 UTC, XingY commented on api/src/org/labkey/api/data/CompareType.java
> +        return _secondaryValueSeparator;
_secondaryValueSeparator is never set and always null. Can getSecondaryValueSeparator() just return null and skipping adding _secondaryValueSeparator?

2023-07-25 18:01 UTC, XingY commented on api/src/org/labkey/api/data/CompareType.java
> +        return (secondarySeparator != null)
Seems random to me that trimming is only done when there is a secondarySeparator. What about instead of using String secondarySeparator,  use boolean allowNewlineSep?

2023-07-25 18:01 UTC, XingY commented on api/src/org/labkey/api/data/CompareType.java
> +        return _secondaryValueSeparator;
public boolean isNewLineSeparatorAllowed()
    {
        return false;
    }

2023-07-25 18:01 UTC, XingY commented on api/src/org/labkey/api/data/CompareType.java
> +            value = value.replace(secondarySeparator, separator);
This should check !value.startsWith(JSON_MARKER_START)

2023-07-25 18:32 UTC, RosalineP commented on api/webapp/clientapi/ext3/FilterDialog.js
> +                emptyText: xType === 'textarea' ? 'Use semicolon or new line to separate entries' : null,
Done!

2023-07-25 18:41 UTC, RosalineP commented on api/src/org/labkey/api/data/CompareType.java
> +            value = value.replace(secondarySeparator, separator);
Good catch, thanks!

2023-07-25 19:03 UTC, RosalineP commented on query/src/org/labkey/query/reports/getdata/FilterClauseBuilder.java
> +            assertEquals("(((\"Field1\" IN ('value2', 'value1'))))", toLabKeySQL(CompareType.IN, "value1;value2", JdbcType.VARCHAR));
At first I thought this was specific to the helper functions and unimportant, but it turns out that despite parseParams() returning a set, here we do rely on the ordering. I've updated the code to preserve order

2023-07-25 19:59 UTC, RosalineP commented on api/src/org/labkey/api/data/CompareType.java
> +    protected static Set<String> parseParams(Object value_, String separator, boolean isNewLineSeparatorAllowed)
I ended up getting rid of the other signature so that other usages would actually pass in their isNewLineSeparatorAllowed() fn, but let me know if that wasn't what you were picturing!

2023-07-25 20:01 UTC, RosalineP commented on api/src/org/labkey/api/data/CompareType.java
> +        return _secondaryValueSeparator;
Like so?

2023-07-25 20:57 UTC, XingY approved these changes

2023-07-27 21:14 UTC, merged