Issue 46427: Slow queries for runs related to datas and materials
LabKey/platform pull request #4625
Opened 2023-07-26 00:58 UTC by labkey-jeckels

#### Rationale
We can avoid joining to the `exp.data` and `exp.material` tables for these queries because they're only invoked for single rows at a time, and we already have the data object so we know if it has a `sourceApplicationId`

#### Changes
* Drop the extra join and don't do an `OR` unless we need to

2023-07-26 13:38 UTC, labkey-susanh approved these changes

2023-07-26 13:44 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                        WHERE di.dataId = ?""");
```suggestion
                        WHERE di.dataId = ? """);
```

2023-07-26 13:44 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        sql.add(data.getRowId());
Should this use `sql.appendValue` instead?

2023-07-26 13:44 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        sql.add(material.getRowId());
Same comments here.

2023-07-26 22:27 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                        WHERE di.dataId = ?""");
I fixed the whitespace problem with a different commit.

2023-07-26 22:29 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        sql.add(data.getRowId());
`appendValue()` inlines the value into the SQL itself. `add()` supplies a value for the `?` parameter. The latter means that the DB can reuse the same query plan over multiple executions, and that we don't end up with a bunch of variations with different rowId values in the query profiler.

2023-07-26 22:32 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        sql.add(data.getRowId());
Ah right.

2023-07-26 22:45 UTC, labkey-matthewb requested changes

2023-07-26 22:45 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            sql.append(" OR pa.RowId = ?");
OR where the two sides reference different tables are _terrible_
Better to just UNION the two cases

2023-07-27 01:07 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            sql.append(" OR pa.RowId = ?");
OK. New version pushed.

2023-07-28 17:40 UTC, labkey-matthewb approved these changes

2023-07-28 21:17 UTC, merged