Fb sampletype refactor
LabKey/platform pull request #4745
Opened 2023-09-15 16:27 UTC by labkey-matthewb

#### Rationale
Optimize the schema used to implement ExpMaterialTableImpl (SampleType tables) to improve performance.

#### Related Pull Requests
* 

#### Changes
*

2023-09-15 18:40 UTC, XingY reviewed
Here are some additional missed checks:

SampleTypeUpdateServiceDI
`boolean isAliquot = !StringUtils.isEmpty(oldAliquotedFromLSID);`
`String aliquotRoot = (String) oldRow.get(RootMaterialLSID.name());` 

SampleManagerWorkflowSampleCompareType
`if ("aliquots".equalsIgnoreCase(aliquotType))
                    sql.append(" AND M.rootmateriallsid = ?").add(lsid);`

2023-09-15 18:40 UTC, XingY commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    if (map.containsKey(RootMaterialLSID.toString()) || !map.containsKey(LSID.toString()))
Should RootMaterialLsid be added to NOT_FOR_UPDATE? Also, what if user provide an bad rootmateriallsid for creating a non-aliquot sample, will it get checked?

2023-09-15 18:40 UTC, XingY commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.009-23.010.sql
> +UPDATE exp.material
Will importing an old exported folder archive with samples be problematic after this?

2023-09-15 19:49 UTC, cnathe commented
As mentioned in the chat thread, this doesn't look to be working quite as expected. After switching to the fb and starting up my server with a sample type that has ~2 million rows, I was not able to get the data grid to load at all within the app (I waited approx 10 min):
<img width="1871" alt="Screenshot 2023-09-15 at 2 44 40 PM" src="https://github.com/LabKey/platform/assets/6411206/04886da6-7bb4-4af1-860f-56b229697c79">

2023-09-15 20:05 UTC, labkey-susanh commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.009-23.010.sql
> +UPDATE exp.material
The folder export for samples doesn't explicitly include the rootmateriallsid, so I think it should be OK as long as we do the right thing when we create the new derivation runs that come from the export.

2023-09-15 20:05 UTC, labkey-susanh commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +        if (isCalculated() || !isUserEditable() || isAutoIncrement() || isVersionColumn() || null != getJdbcDefaultValue())
The `isUserEditable` check always worries me after I discovered that is is what is used to determine which fields are shown in a details view (see [Issue 43760](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=43760)) and thus may not actually correspond to a normal interpretation of "user-editable".  I'm sure you know better than I about such things, but is a check for `isReadOnly` in addition or instead warranted here?

2023-09-15 20:07 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    if (map.containsKey(RootMaterialLSID.toString()) || !map.containsKey(LSID.toString()))
It is/was already added.  See just above before the displayed diff at line 2242.

2023-09-15 20:09 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +        if (isCalculated() || !isUserEditable() || isAutoIncrement() || isVersionColumn() || null != getJdbcDefaultValue())
I also find the overlapping properties options confusing.  I was surprised to not find one of isUserEditable or isReadOnly here.  Thanks for the issue pointer.

2023-09-15 20:09 UTC, labkey-matthewb commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.009-23.010.sql
> +UPDATE exp.material
I just made a fix in this code XarReader.updateSourceInfo()

2023-09-15 20:19 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/BaseColumnInfo.java
> +        if (isCalculated() || !isUserEditable() || isAutoIncrement() || isVersionColumn() || null != getJdbcDefaultValue())
I agree that getFieldKeysToShow() seems wrong.  However, it also seems right that a field that can't be user-edited can't be required for insert.

2023-09-18 19:01 UTC, cnathe commented
> As mentioned in the chat thread, this doesn't look to be working quite as expected. After switching to the fb and starting up my server with a sample type that has ~2 million rows, I was not able to get the data grid to load at all within the app (I waited approx 10 min): <img alt="Screenshot 2023-09-15 at 2 44 40 PM" width="1871" src="https://user-images.githubusercontent.com/6411206/268380564-04886da6-7bb4-4af1-860f-56b229697c79.png">

To close the loop. I went back to my large DB with the fb and this time things performed much better. Maybe my DB was performing some other actions or the stats weren't updated yet. After the upgrade, which took 50 minutes, the sample type with 2 million rows loaded within a few seconds (which was the case before the upgrade as well) but now when I applied a "contains filter" to one of the provisioned columns for the sample type the grid loaded in < 10 seconds (note the same action without this change took > 2 minutes).

2023-09-18 19:40 UTC, labkey-matthewb commented
> As mentioned in the chat thread, this doesn't look to be working quite as expected. After switching to the fb and starting up my server with a sample type that has ~2 million rows, I was not able to get the data grid to load at all within the app (I waited approx 10 min): <img alt="Screenshot 2023-09-15 at 2 44 40 PM" width="1871" src="https://user-images.githubusercontent.com/6411206/268380564-04886da6-7bb4-4af1-860f-56b229697c79.png">

The obvious alternative strategy is to try a SELECT INTO/RENAME instead of UPDATE in place.  A quick search of the code shows about a half-dozen FOREIGN KEYS outside the exp module that point to exp.material.  That makes the SELECT INTO strategy much more challenging.

2023-09-21 16:29 UTC, XingY requested changes

2023-09-21 16:29 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                        sql.append(propertyColumn.getValueSql("m_aliquot")).append(" AS ").append(propertyColumn.getSelectName());
Shouldn't it be `.appendIdentifier(propertyColumn.getSelectName())` instead

2023-09-21 17:29 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                        sql.append(propertyColumn.getValueSql("m_aliquot")).append(" AS ").append(propertyColumn.getSelectName());
Nice catch.  We should probably switch getSelectName() to return a SQLFragment or have another method.

2023-09-21 22:11 UTC, XingY approved these changes

2023-09-21 22:43 UTC, merged