Automation test for TOTP 2FA integration with LabKey Server
LabKey/platform pull request #4761
Opened 2023-09-20 17:04 UTC by labkey-sweta

#### Rationale
Automation test for TOTP 2FA integration with LabKey Server

https://docs.google.com/document/d/1HvnsKeXBNhX1D5Tq7DkEnlN9m09GoJtkCj56oxhwQIA/edit

#### Related Pull Requests
https://github.com/LabKey/mfa/pull/4

#### Changes
*

2023-09-20 23:04 UTC, labkey-tchad requested changes

2023-09-20 23:04 UTC, labkey-tchad commented on devtools/test/src/org/labkey/test/params/devtools/SecondaryAuthenticationTOTPProvider.java
> +package org.labkey.test.params.devtools;
You should be able to put this class in the `mfa` repository.
```suggestion
package org.labkey.test.params.mfa;
```

2023-09-22 14:33 UTC, labkey-sweta commented on devtools/test/src/org/labkey/test/params/devtools/SecondaryAuthenticationTOTPProvider.java
> +package org.labkey.test.params.devtools;
I added this class here, because everything was part of devtools

Still makes sense to move?

2023-09-22 18:46 UTC, labkey-tchad requested changes

2023-09-22 18:46 UTC, labkey-tchad commented on devtools/test/src/org/labkey/test/params/devtools/SecondaryAuthenticationTOTPProvider.java
> +package org.labkey.test.params.devtools;
Yes, it should move. `SecondaryAuthenticationProvider` is in here because the only secondary auth test we had previously was for the trivial one defined in the `devtools` module

2023-09-25 20:23 UTC, labkey-tchad requested changes
I don't think any of these changes are needed.

2023-09-26 08:28 UTC, closed without merging