User count metrics for site roles and special groups
LabKey/platform pull request #4776
Opened 2023-09-25 18:54 UTC by labkey-jeckels

#### Rationale
Knowing the numbers of users assigned to these site-wide roles and groups will help understand how they are used, and monitor for unusual assignments.

#### Changes
* New UsageMetricsProvider to capture user counts in site-wide roles and the special site admin and developer groups
* Minor code cleanup

2023-09-25 23:35 UTC, labkey-adam requested changes
Unless I'm misreading, the metrics provider group handling needs to be adjusted

2023-09-25 23:35 UTC, labkey-adam commented on api/src/org/labkey/api/security/SecurityManager.java
> +                            case GROUP -> getAllGroupMembers((Group)principal, MemberType.ACTIVE_USERS);
Seems like a no-op. Don't you want to do something like `count += getAllGroupMembers().size()` here?

2023-09-25 23:35 UTC, labkey-adam commented on api/src/org/labkey/api/security/SecurityManager.java
> +            Map<String, Integer> roleCounts = new HashMap<>();
Optional: using a `HashBag` might be cleaner. It handles the initialization and accumulation, and provides `add(value, count)`.

2023-09-25 23:55 UTC, labkey-jeckels commented on api/src/org/labkey/api/security/SecurityManager.java
> +                            case GROUP -> getAllGroupMembers((Group)principal, MemberType.ACTIVE_USERS);
Indeed

2023-09-25 23:56 UTC, labkey-jeckels commented on api/src/org/labkey/api/security/SecurityManager.java
> +            Map<String, Integer> roleCounts = new HashMap<>();
I didn't see an easy way to get the role name -> count map from it so I left as-is

2023-09-26 00:06 UTC, labkey-adam approved these changes

2023-09-26 15:17 UTC, merged