Update list search timestamp to only update if resource not deleted
LabKey/platform pull request #4839
Opened 2023-10-19 01:20 UTC by labkey-ians

#### Rationale
[Issue #48878](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=48878) Search indexer has race condition

#### Changes
* Update list indexer to only update if item resource is present

2023-10-19 20:54 UTC, labkey-matthewb requested changes

2023-10-19 20:54 UTC, labkey-matthewb commented on list/src/org/labkey/list/model/ListManager.java
> +
I think this additional condition in the WHERE clause is redundant.  The original already checks that the row exists.  Wasn't the bug that the actual list got deleted?

2023-10-19 22:35 UTC, labkey-adam commented on list/src/org/labkey/list/model/ListManager.java
> +
Correct... I discussed this with Ian. My suggestion is to catch, swallow constraint violations, and re-throw anything else.

2023-10-23 18:28 UTC, labkey-adam approved these changes

2023-10-23 18:36 UTC, labkey-matthewb commented on list/src/org/labkey/list/model/ListManager.java
> +                            if (e.isConstraintException())
Has anyone tested that table not found throws an exception that is flagged as a constraint exception???  I might be, but I wouldn't expect that.

2023-10-23 21:44 UTC, labkey-ians commented on list/src/org/labkey/list/model/ListManager.java
> +                            if (e.isConstraintException())
tested this against both MS-SQL and psql.

2023-10-23 21:44 UTC, labkey-matthewb approved these changes

2023-10-24 18:19 UTC, merged