use document-uri instead of source-file
LabKey/platform pull request #4841
Opened 2023-10-19 22:34 UTC by labkey-matthewb

#### Rationale
document-uri is better for avoiding duplicates

#### Related Pull Requests
* 

#### Changes
*

2023-10-19 23:20 UTC, labkey-tchad requested changes
I thought of another way to 'disable' this endpoint. It could no-op if the logger is turned off. Like:
```
if (!_log.isWarnEnabled())
{
    return new JSONObject().put("success", false);
}
``` 

Also, we should update `server/webapps/log4j2.xml` to put these warning into a separate file. That would make it possible for tests to check for new warnings (and fail if we want).

2023-10-19 23:20 UTC, labkey-tchad commented on core/src/org/labkey/core/admin/AdminController.java
> +                }
Should use `JSONObject.opt*` for items that might not be there; `get*` will just throw an exception if they don't find anything. Also, `JSONObject.toString` can take an indent factor to make it look pretty.
```suggestion
                JSONObject cspReport = jsonObj.optJSONObject("csp-report");
                if (cspReport != null)
                {
                    String urlString = cspReport.optString("document-uri", null);
                    if (urlString != null)
                    {
                        String path = new URLHelper(urlString).deleteParameters().getPath();
                        if (null == reports.put(path, Boolean.TRUE))
                        {
                            var jsonStr = jsonObj.toString(2);
                            _log.warn("ContentSecurityPolicy warning on page: " + urlString + "\n" + jsonStr);
                        }
                    }
                }
```

2023-10-20 17:24 UTC, labkey-tchad approved these changes
One small fix

2023-10-20 17:24 UTC, labkey-tchad commented on core/src/org/labkey/core/admin/AdminController.java
> +                    String urlString = cspReport.optString("document-uri");
Unless specified, `optString(key)`'s default value is `""`, not `null`.
```suggestion
                    String urlString = cspReport.optString("document-uri", null);
```

`org.json` has numerous questionable design decisions with regard to `null` values.

2023-10-20 17:56 UTC, labkey-matthewb commented on core/src/org/labkey/core/admin/AdminController.java
> +                    String urlString = cspReport.optString("document-uri");
Thanks, now I know.

2023-10-20 19:39 UTC, merged