Sample Types: Add RootMaterialRowId
LabKey/platform pull request #4844
Opened 2023-10-20 20:29 UTC by labkey-nicka

#### Rationale
This introduces a new `RootMaterialRowId` column into the `exp.material` table which emulates the `RootMaterialLSID` column. This column identifies the root material for a sample which is useful for derivates and aliquots. Additionally, in materialized Sample Type tables the `RowId` for the sample is now replicated into the materialized table. When joining to materialized Sample Type tables `RootMaterialRowId` is now used instead of `RootMaterialLSID` which has been shown to result in moderate to significant gain in query execution times for Sample Types with a large number of samples.

This is the first part of a few:

1. Add `RootMaterialRowId` and replace most logic (this part)
2. Update Aliquot Recalculation to use RootMaterialRowId
3. Remove `RootMaterialLSID`

#### Related Pull Requests
* 

#### Changes
- Upgrade SQL scripts to add `RootMaterialRowId` column to `exp.material` table.
- Upgrade code to add `RowId` to materialized Sample Type tables.
- Refactor `SampleTypeService.recomputeSampleTypeAvailableAliquotRollup` into `ExperimentUpgradeCode` as it is only utilized during upgrade. Remove from service interface.
- Update XAR export/import to translate rowId to LSID and back again for `RootMaterialRowId`.

**Note to reviewers**: You will see some replicated logic between `RootMaterialLSID` and `RootMaterialRowId`. The intention is for this to be removed when `RootMaterialLSID` is removed.

2023-10-20 20:44 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +        return SampleTypeServiceImpl.get().recomputeSamplesRollup(
@labkey-matthewb It didn't seem necessary to call `refreshSampleTypeMaterializedView()` during the upgrade here. Should I be? Note, that this is an older upgrade script invoking this (specifically `exp-23.007-23.008.sql`).

2023-10-20 21:09 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +                selectAll(CaseInsensitiveHashSet.of("name", "rootmateriallsid")); // TODO: Investigate this
Oops. Looks like I failed to go back and look at this one. I'll get this updated.

2023-10-23 19:02 UTC, labkey-matthewb requested changes

2023-10-23 19:02 UTC, labkey-matthewb commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            SQLFragment nonAliquotRowsSQL = new SQLFragment("SELECT * FROM exp.material WHERE RowId IN (")
Does this method now need to consider propertyColumn.getDerivationDataScope()?

2023-10-23 19:02 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +        SQLFragment createIndex = new SQLFragment("CREATE INDEX IF NOT EXISTS ").append(tableName).append("_rowid ")
This is failing on SQL Server

2023-10-23 19:29 UTC, XingY commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.010-23.011.sql
> +UPDATE exp.material AS mat SET RootMaterialRowId = (
On a DB with 3M samples, this line took 21 minutes to run. The entire script took 30 minutes to run. For clients who are upgrading from <23.9, they would be running 23.009-23.001, which also took a long time to run. The combined run time could be frustrating. Worse still, 23.009-23.001 is basically stale with 23.010-23.011. I wonder if we can be smarter on script rollup.

2023-10-23 19:29 UTC, XingY commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec("lsid", JdbcType.VARCHAR, 300).setNullable(false),
Is there a plan to remove lsid from provisioned?

2023-10-23 19:29 UTC, XingY commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec.ForeignKey("lsid", "exp", "Material", "LSID", null, false),
Same question as to why lsid is still needed as key?

2023-10-23 19:47 UTC, labkey-matthewb commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.010-23.011.sql
> +UPDATE exp.material AS mat SET RootMaterialRowId = (
Interesting idea!

2023-10-23 19:48 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +        return SampleTypeServiceImpl.get().recomputeSamplesRollup(
I think this is fine.

2023-10-23 20:08 UTC, labkey-nicka commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.010-23.011.sql
> +UPDATE exp.material AS mat SET RootMaterialRowId = (
I mocked this out last week and could move forward with an upgrade similar to this.

2023-10-23 20:14 UTC, labkey-nicka commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec("lsid", JdbcType.VARCHAR, 300).setNullable(false),
Considered it scope creep.

2023-10-23 20:15 UTC, labkey-nicka commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec.ForeignKey("lsid", "exp", "Material", "LSID", null, false),
Considered it scope creep.

2023-10-23 20:15 UTC, labkey-nicka commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            SQLFragment nonAliquotRowsSQL = new SQLFragment("SELECT * FROM exp.material WHERE RowId IN (")
Why would this change when shifting from `RootMaterialLSID` to `RootMaterialRowId`? Or as you asking in general?

2023-10-23 20:19 UTC, labkey-matthewb commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            SQLFragment nonAliquotRowsSQL = new SQLFragment("SELECT * FROM exp.material WHERE RowId IN (")
In general, this looks like a code path that might have been overlooked previously?

2023-10-23 20:26 UTC, XingY commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec("lsid", JdbcType.VARCHAR, 300).setNullable(false),
But not even in a future story?

2023-10-23 20:28 UTC, labkey-nicka commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec("lsid", JdbcType.VARCHAR, 300).setNullable(false),
A more verbose answer. There are several follow-up changes that have been suggested but not necessarily investigated:

1. Remove `lsid` from the materialized sample type tables as it exists on `exp.material`.
1. Remove `name` from the materialized sample type tables as it exists on `exp.material`.
1. Remove/replace `rowId` from `exp.material` and utilize `exp.object.objectid`. The idea here is to reduce the number of tables/joins that have to be involved in the minimal query. I'm still unclear on this one exactly.

2023-10-23 20:39 UTC, XingY commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec("lsid", JdbcType.VARCHAR, 300).setNullable(false),
Name is used for merge/update case. The statement utils uses name as part of key for the WHERE clause. I don't think name can be removed..

2023-10-23 21:00 UTC, labkey-nicka commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.010-23.011.sql
> +UPDATE exp.material AS mat SET RootMaterialRowId = (
So I dropped this idea when we established that we're keeping `RootMaterialLSID` around past this PR. It will need to be populated so skipping the logic is something we could do BUT we'll want to roll in the other parts of this story to do all this together (which would be fine with me).

2023-10-23 21:02 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +        SQLFragment createIndex = new SQLFragment("CREATE INDEX IF NOT EXISTS ").append(tableName).append("_rowid ")
Fixed.

2023-10-23 21:13 UTC, labkey-nicka commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            new PropertyStorageSpec("lsid", JdbcType.VARCHAR, 300).setNullable(false),
Cool, sounds good. Hadn't investigated any of these yet.

2023-10-23 21:42 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
>              }
IsAliquot should update to check rowId instead of LSID.

2023-10-23 21:48 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
>              }
Same with computeInnerSelectedColumns

2023-10-23 22:54 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
>              }
I intentionally left this intact for after the changes to account for recalculate in case that had any impact. I have the patch locally to convert this. I'll commit this portion now.

2023-10-24 17:24 UTC, labkey-matthewb approved these changes
I would like to see Xing's approval also before merging.

2023-10-24 17:40 UTC, labkey-matthewb requested changes

2023-10-24 17:40 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                columnInfo.setFk(getExpSchema().getMaterialForeignKey(getLookupContainerFilter(), Column.RowId.name()));
set IsUserEditable(false) to avoid this being considered a required column (as the underlying column is NOT NULL)

2023-10-24 19:50 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
>              }
Done. See c7ae1d02.

2023-10-24 19:56 UTC, labkey-nicka commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.010-23.011.sql
> +UPDATE exp.material AS mat SET RootMaterialRowId = (
So I haven't taken it as far as optimizing for pre-23.9 upgrades but I did attempt to shore up the upgrade time it takes. With ae7c2f9 it will do the following on Postgres:

1. Drop all known indices/constraints on `exp.material`
2. Create and populate a temporary table with the `RowId` to `RootMaterialRowId` relationships.
3. Update all rows in the `exp.material` table.
4. Recreate all known indices/constraints on `exp.material`.

This is taking ~10 minutes for 3.2m rows on Postgres 13 on my development machine.

I will do the same for SQL Server if we agree this strategy is the one we want to take. That said, I haven't really performance tested SQL Server with a large database.

2023-10-24 19:57 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
> +                columnInfo.setFk(getExpSchema().getMaterialForeignKey(getLookupContainerFilter(), Column.RowId.name()));
Done. See e56141b.

2023-10-24 21:03 UTC, labkey-matthewb approved these changes

2023-10-24 21:17 UTC, XingY reviewed
Are you working on removing rootmateriallsid from XarReader / XarExporter? Not sure what the status of manual testing is at, but should cover folder import that contains aliquots and subaliquots.

2023-10-24 21:28 UTC, labkey-nicka commented
> Are you working on removing rootmateriallsid from XarReader / XarExporter? Not sure what the status of manual testing is at, but should cover folder import that contains aliquots and subaliquots, including from older and new folder archives

Yes, I'm addressing that TODO. It will not be fully removed because we need to maintain the rootMaterialLSID in the XAR and translate from rowId and back.

2023-10-25 21:06 UTC, labkey-nicka commented
> > Are you working on removing rootmateriallsid from XarReader / XarExporter? Not sure what the status of manual testing is at, but should cover folder import that contains aliquots and subaliquots, including from older and new folder archives
> 
> Yes, I'm addressing that TODO. It will not be fully removed because we need to maintain the rootMaterialLSID in the XAR and translate from rowId and back.

@XingY Alright, I've taken a look at the XAR export/import and it appears to be doing the round-trip successfully.

2023-10-26 16:23 UTC, labkey-nicka commented on experiment/resources/schemas/dbscripts/postgresql/exp-23.010-23.011.sql
> +UPDATE exp.material AS mat SET RootMaterialRowId = (
I've revised the Postgres update to not drop/add constraints -- only indices. The drop/add of constraints wasn't providing a clear performance gain so I opted for simplicity.

As for SQL Server the approach I've stuck with the `UPDATE Material SET RootMaterialRowID FROM ... INNER JOIN ...` approach. I trialed using a `MERGE` statement but wasn't seeing a clear performance gain (although I didn't test this with millions of samples):

```sql
MERGE exp.material AS Target
USING exp.material AS Source
ON Target.rootmateriallsid = Source.lsid
WHEN MATCHED THEN UPDATE SET
Target.rootmaterialrowid = Source.rowid
```

SQL Server appears to be much better about not needing to update indices when fields in the index are not changed (we're only changing the newly introduced `RootMaterialRowId` column here) so I've elected to not drop/add indices on SQL Server.

2023-11-07 00:53 UTC, XingY approved these changes

2023-11-07 00:53 UTC, XingY commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            SQLFragment nonAliquotRowsSQL = new SQLFragment("SELECT * FROM exp.material WHERE RowId IN (")
Agree this seems like an existing flaw unrelated to work in this PR. This is coded for ParentOnly fields.

2023-11-07 00:53 UTC, XingY commented on experiment/src/org/labkey/experiment/XarExporter.java
> +            ExpMaterial rootMaterial = ExperimentService.get().getExpMaterial(material.getRootMaterialRowId());
Typically many aliquots will share the same parent/root. During folder export, I'd expect this to get called many times for the same rootMaterialRowId, is it worth putting rootLsid in a cache? rootLsid can even be a map of <rowId, relativizedLsid>

2023-11-07 00:53 UTC, XingY commented on experiment/src/org/labkey/experiment/XarReader.java
> +            if (StringUtils.isEmpty(rootMaterialLSID))
again, can we put lsid/rowid in a local cache?

2023-11-08 19:38 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/XarExporter.java
> +            ExpMaterial rootMaterial = ExperimentService.get().getExpMaterial(material.getRootMaterialRowId());
Good idea. Added with 6b297a3.

2023-11-08 19:38 UTC, labkey-nicka commented on experiment/src/org/labkey/experiment/XarReader.java
> +            if (StringUtils.isEmpty(rootMaterialLSID))
See 6b297a3.

2023-11-10 18:37 UTC, merged