Import Excel datetimes with seconds
LabKey/platform pull request #4873
Opened 2023-10-25 22:40 UTC by labkey-adam

#### Rationale
We're failing to parse seconds from Excel datetime cells. https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=48930

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/2942

2023-10-25 23:09 UTC, labkey-matthewb requested changes

2023-10-25 23:09 UTC, labkey-matthewb commented on api/src/org/labkey/api/reader/ExcelLoader.java
> +            return DateUtil.formatDateTimeISO8601WithSeconds(getDateFromExcelDouble(value));
This is an odd function name.  ISO8601 includes seconds.  The version without seconds is just derived from LabKey's old default display format.

2023-10-25 23:09 UTC, labkey-matthewb commented on api/src/org/labkey/api/util/DateUtil.java
> +        return formatDateTime(date, ISO_DATE_FORMAT_STRING + " " + LONG_TIME_FORMAT_STRING);
As per note above LONG_TIME_FORMAT_STRING really should be called ISO_TIME_FORMAT_STRING.  What we call ISO_TIME_FORMAT_STRING isn't.

2023-10-25 23:09 UTC, labkey-matthewb commented on api/src/org/labkey/api/reader/ExcelLoader.java
> +        @Test
Nice

2023-10-26 00:25 UTC, labkey-susanh commented on api/src/org/labkey/api/reader/ExcelLoader.java
> +            return DateUtil.formatDateTimeISO8601WithSeconds(getDateFromExcelDouble(value));
ISO8601 also apparently includes milliseconds. Do we abandon this name or actually want to use IS08601?

2023-10-26 14:59 UTC, labkey-matthewb commented on api/src/org/labkey/api/reader/ExcelLoader.java
> +            return DateUtil.formatDateTimeISO8601WithSeconds(getDateFromExcelDouble(value));
Yes, thanks for the correction.

2023-10-26 18:26 UTC, labkey-adam commented on api/src/org/labkey/api/reader/ExcelLoader.java
> +            return DateUtil.formatDateTimeISO8601WithSeconds(getDateFromExcelDouble(value));
My understanding is ISO 8601 is not a single format; the standard defines many, many date, time, and date+time formats. Formats can include space, T, Z, colons, etc. or not. Times are **not** required to have seconds, milliseconds, or even minutes. I believe all of the ISO constants are valid ISO formats and the ISO methods format using ISO formats.

2023-10-26 18:28 UTC, labkey-adam commented on api/src/org/labkey/api/reader/ExcelLoader.java
> +            return DateUtil.formatDateTimeISO8601WithSeconds(getDateFromExcelDouble(value));
I'm fine if we don't want to reference ISO 8601 and agree we should come up with a better naming system so we're clear which format is which being used. But let's not pretend there's only one true ISO format and the others are not ISO.

2023-10-26 18:29 UTC, labkey-adam commented on api/src/org/labkey/api/util/DateUtil.java
> +        return formatDateTime(date, ISO_DATE_FORMAT_STRING + " " + LONG_TIME_FORMAT_STRING);
They're both ISO

2023-10-26 19:48 UTC, labkey-matthewb approved these changes

2023-10-26 21:52 UTC, labkey-susanh approved these changes

2023-10-27 18:04 UTC, merged