coverage for in-product upsell messaging
LabKey/platform pull request #4934
Opened 2023-11-07 22:54 UTC by labkey-chrisj

#### Rationale
This adds regression coverage for our local-configuration of in-product upsell messaging

#### Related Pull Requests
n/a

#### Changes

- [x] add support for marketingMessage to `EditUpgradeMessagePage`
- [x] new test class

2023-11-09 19:32 UTC, labkey-tchad requested changes
One missing scenario: logging out then back in should cause the banner to reappear after you've dismissed it.

2023-11-09 19:32 UTC, labkey-tchad commented on mothership/test/src/org/labkey/test/pages/mothership/EditUpgradeMessagePage.java
>      public Input createIssueURL()
If you're going to switch to a getter/setter pattern, please refactor all of the `Input` methods to match.

2023-11-09 19:32 UTC, labkey-tchad commented on mothership/test/src/org/labkey/test/tests/mothership/InProductMessagingTest.java
> +@Category({})
Add to `Daily` suite
```suggestion
@Category({Daily.class})
```

2023-11-09 19:32 UTC, labkey-tchad commented on mothership/test/src/org/labkey/test/tests/mothership/InProductMessagingTest.java
> +        ExperimentalFeaturesHelper.enableExperimentalFeature(createDefaultConnection(), "localMarketingUpdates");
Enable/disable the experimental feature in `@BeforeClass`/`@AfterClass`. This is an API operation so it's safe to clean up like that.
Also, you might want to use `WebTestHelper.getRemoteApiConnection(false)` instead of `createDefaultConnection()` since there's so much impersonating in these tests.

2023-11-09 19:32 UTC, labkey-tchad commented on mothership/test/src/org/labkey/test/tests/mothership/InProductMessagingTest.java
> +     */
I think this is a different kind of banner than those covered by the `BannerHelper`
```suggestion
```

2023-11-09 19:32 UTC, labkey-tchad commented on mothership/test/src/org/labkey/test/tests/mothership/InProductMessagingTest.java
> +                .addPermission("Author", "home");
This is misleading. Having an account means you are explicitly **not** a guest. You just need to sign out to check what a guest would see, though I don't think that guests can see this banner.

2023-11-09 21:27 UTC, labkey-chrisj commented on mothership/test/src/org/labkey/test/tests/mothership/InProductMessagingTest.java
> +     */
We may want to talk with the devs (possibly with the UX folks as well) about standardizing those things.
Smells like technical debt all around

2023-11-09 22:26 UTC, labkey-chrisj commented on mothership/test/src/org/labkey/test/pages/mothership/EditUpgradeMessagePage.java
>      public Input createIssueURL()
Happy to.

2023-11-09 22:43 UTC, labkey-chrisj commented
I added in the logout/login to confirm re-showing dismissed message, also updated to correctly verify guest scenario

2023-11-10 00:23 UTC, labkey-tchad approved these changes
`doCleanup` doesn't get run when tests fail. The experimental feature should be disabled in an `@AfterClass` method to make sure it doesn't get left on.

2023-11-10 00:26 UTC, labkey-tchad commented
FYI, the mothership tests are failing.

2023-11-14 23:33 UTC, merged