Requestability rules grid is now Ext4
LabKey/platform pull request #4968
Opened 2023-11-17 20:54 UTC by labkey-adam

#### Rationale
Component was converted from Ext3 to Ext4, but this test didn't get the memo

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/4959

2023-11-17 21:53 UTC, labkey-tchad requested changes
Removing the synchronizing waits is likely to cause trouble on TeamCity

2023-11-17 21:53 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudySimpleExportTest.java
>          clickButton("Submit", 0);
Use helpers for menu and window to properly wait for page to change.
```suggestion
        _ext4Helper.clickExt4MenuButton(false, Ext4Helper.Locators.ext4Button("Add Rule"), false, "Custom Query");
        Window window = new Window("Add Custom Query Rule", getDriver()); // org.labkey.test.components.ext4.Window
        _ext4Helper.selectComboBoxItem("Schema:", "auditLog");
        _ext4Helper.selectComboBoxItem("Query:", "FileSystem");
        _ext4Helper.selectComboBoxItem("Mark vials:", "Unavailable");
        window.clickButton("Submit", true);
```

2023-11-17 22:15 UTC, labkey-adam commented
> Removing the synchronizing waits is likely to cause trouble on TeamCity

Thanks for the updates. I was trying to follow the pattern in `SpecimenBaseTest.setupRequestabilityRules()`, which I don't think had these waits.

2023-11-17 23:53 UTC, labkey-adam commented
Test is passing on this FB: https://teamcity.labkey.org/buildConfiguration/bt20/2753474?buildTab=tests

2023-11-18 00:20 UTC, labkey-tchad approved these changes

2023-11-18 00:20 UTC, labkey-tchad commented on study/test/src/org/labkey/test/tests/study/StudySimpleExportTest.java
> +        Window window = new Window("Add Custom Query Rule", getDriver()); // org.labkey.test.components.ext4.Window
Sorry, this comment wasn't intended to be committed. I was just pointing to the component.

2023-11-18 02:24 UTC, merged