Upgrade TinyMCE and Wiki
LabKey/platform pull request #4969
Opened 2023-11-17 23:14 UTC by labkey-ians

#### Rationale
Clean up a lot of CSP errors, and upgrade the TinyMCE editor that we've been using forever

#### Related Pull Requests
* TBD

#### Changes
* Swap Tiny_Mce (v3) for TinyMce (v6)
* Update `Wiki` module to use new version

2023-11-28 19:20 UTC, labkey-adam requested changes
Need to update platform/scripts.txt

2023-11-30 00:56 UTC, RosalineP approved these changes
This is looking good! I did a light amout of manual testing with old wiki issues I remembered and the new editor handled it all nicely. The functionality parity (like not having a fullscreen mode anymore) makes sense. I had a few questions but nothing blocking.

2023-11-30 00:56 UTC, RosalineP commented on wiki/resources/web/wiki/internal/wikiEdit.js
> +// TODO can these be removed?
Are this and the one on 718 todos for this PR or for the future?

2023-11-30 00:56 UTC, RosalineP commented on wiki/resources/web/wiki/internal/wikiEdit.js
> +        // }
Is this an intentionally left-in comment?

2023-11-30 00:56 UTC, RosalineP commented on wiki/resources/web/wiki/internal/Wiki.js
> +
Are this and the other style comment in WikiEdit.js todos for future work?

2023-11-30 00:56 UTC, RosalineP commented on wiki/resources/web/wiki/internal/wikiEdit.js
> +        if (!confirmOverride) {
Just curious, why is it that we are wanting to consistently show this when the user switches to Visual rather than checking for elements?

2023-11-30 00:56 UTC, RosalineP commented on wiki/resources/web/wiki/internal/wikiEdit.js
> +                    "Your page contains elements that" :
Nit: I feel like in general "Your page contains elements that" is better than "Some non-visual elements", in that it gets the same idea across without having to check textContainsNonVisualElements() and avoiding the repitition in "Some non-visual elements are not supported by the visual editor and may be removed."

2023-11-30 23:12 UTC, labkey-adam approved these changes

2023-11-30 23:12 UTC, labkey-ians commented on wiki/resources/web/wiki/internal/wikiEdit.js
> +        if (!confirmOverride) {
Per Molly's feedback the concern is Users losing elements particularly formatting when flipping, since we aren't checking all possible elements that can be 'cleaned,' it felt like a broader warning was warranted.

2023-11-30 23:12 UTC, labkey-ians commented on wiki/resources/web/wiki/internal/Wiki.js
> +
yes, w/ reminder of where to look in Tiny's docs

2023-11-30 23:12 UTC, labkey-ians commented on wiki/resources/web/wiki/internal/wikiEdit.js
> +        // }
removed

2023-11-30 23:12 UTC, labkey-ians commented on wiki/resources/web/wiki/internal/wikiEdit.js
> +// TODO can these be removed?
removed, tabs never got added

2023-12-01 00:51 UTC, merged