Issue 49216: Set JDBC preparedThreshold=0 for PostgreSQL
LabKey/platform pull request #5017
Opened 2023-12-05 18:24 UTC by labkey-nicka

#### Rationale
This seeks to address [Issue 49216](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49216) by setting JDBC parameter `preparedThreshold=0` for all PostgreSQL primary database connections. Setting the parameter in this way [disables prepared statement caching](https://jdbc.postgresql.org/documentation/server-prepare/#deactivation) which is known to cause problems when schema changes occur.

**Note:** I'm certainly not hard set on this solution -- more of a first-pass at the moment.

#### Changes
- Attempt to consolidate handling of setting connection properties for `DbScope`.
- Update PostgreSQL dialect to use `DbScope` to set connection property.
- Mimic pattern of retrieving "application name" parameter from a generic dialect for new `dialect.getDisablePreparedStatementCachingEntry()`

2023-12-06 17:01 UTC, labkey-adam requested changes
I have some local changes. Will commit some time today and add my approval.

2023-12-06 23:51 UTC, labkey-adam approved these changes

2023-12-06 23:59 UTC, labkey-adam commented
@labkey-nicka I've approved, but you should review my changes. I hope they (along with my comment in the issue) are self-explanatory. Note that since `disablePreparedStatementCaching()` was super specific to PostgreSQL, I opted to remove the SqlDialect method, loosen some visibility on LabKeyDataSource, and let PG prepare() set the property directly. I also got rid of a sneaky, but unnecessary, connection getting made before the no-other-connections check; not sure why this wasn't causing problems with the check, but it's gone now so I'm not going to worry about it.

If you and TeamCity are satisfied, feel free to merge. Thanks for your help!

2023-12-07 17:18 UTC, labkey-nicka reviewed
Looks good. This is much cleaner.

2023-12-07 17:26 UTC, merged