Convert move entities between projects APIs to use new query-moveRows.api
LabKey/platform pull request #5049
Opened 2023-12-14 16:45 UTC by cnathe

#### Rationale
After we enabled moving of entities between projects, we knew that moving via the API would eventually be helpful. This is particularly useful since we’ve limited the number of entities that can be moved via the UI for performance purposes. We also realized after the implementation that instead of having individual controller actions for each entity type, we could consolidate them into a single MoveRowsAction in the QueryController and have the implementations for each handled within the specific QueryUpdateService for the entities table.

#### Related Pull Requests
- https://github.com/LabKey/platform/pull/5049
- https://github.com/LabKey/labkey-ui-components/pull/1369
- https://github.com/LabKey/labkey-ui-premium/pull/279
- https://github.com/LabKey/biologics/pull/2582
- https://github.com/LabKey/labbook/pull/584
- https://github.com/LabKey/inventory/pull/1129
- https://github.com/LabKey/sampleManagement/pull/2302

#### Changes
- Initial QueryController.MoveRowsAction and QueryUpdateService moveRows() 
  - require targetContainerPath param in addition to standard save rows action params
  - extend ApiSaveRowsForm to support getting rowIds from the selectionKey
  - allow for target container param as targetContainer or targetContainerPath and allow for auditUserComment or userComment
  - add new MoveEntitiesPermission to be used for permission checks in table QueryUpdateServices that implement moveRows()
- Remove MoveSamplesAction and move implementation to SampleTypeUpdateServiceDI moveRows()
- Remove MoveDataClassObjectsAction and move implementation to ExpDataClassDataTableImpl.DataClassDataUpdateService moveRows()
- Remove MoveAssayRunsAction and move implementation to ExpRunTableImpl.RunTableUpdateService moveRows()
- Remove AbstractMoveEntitiesAction and related form class

2023-12-14 21:58 UTC, labkey-susanh requested changes

2023-12-14 21:58 UTC, labkey-susanh commented on api/src/org/labkey/api/data/ContainerManager.java
> +            errors.reject(ERROR_GENERIC, "You do not have permission to move rows to this target container: " + targetIdOrPath + ".");
```suggestion
            errors.reject(ERROR_GENERIC, "You do not have permission to move rows to the target container: " + targetIdOrPath + ".");

```
Do we have the query name that we could pass in here for better user feedback ("permission to move rows from 'My Sample Type' to the target container: X")?

2023-12-14 21:58 UTC, labkey-susanh commented on experiment/src/client/test/integration/MoveAssayRunsAction.ispec.ts
> +            expect(exception).toEqual('No \'rows\' array supplied!');
Does this message really need the `!`? It's consistent, I'm sure, but not all that astonishing (to me).

2023-12-14 21:58 UTC, labkey-susanh commented on experiment/src/client/test/integration/MoveAssayRunsAction.ispec.ts
> +            }, {...topFolderOptions, ...editorUserOptions}).expect(500);
I wouldn't expect a 500 error here. That says something went wrong on the server, not that the request was bad.

2023-12-14 21:58 UTC, labkey-susanh commented on experiment/src/client/test/integration/MoveSamplesAction.ispec.ts
> +            }, {...topFolderOptions, ...editorUserOptions}).expect(500);
Also won't expect a 500 response here. This isn't a server error.

2023-12-14 21:58 UTC, labkey-susanh commented on experiment/src/client/test/integration/MoveSourcesAction.ispec.ts
> +            expect(exception).toEqual('No \'rows\' array supplied!');
Using double quotes here would be more readable than escaping the single quotes.

2023-12-14 21:58 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                        moveFile(renameData);
If the move fails we'll still be counting that as a moved file. Not a big deal since we don't rely on these counts too much, but not entirely accurate.

2023-12-14 21:58 UTC, labkey-susanh commented on query/src/org/labkey/query/controllers/QueryController.java
> +        moveRows(MoveEntitiesPermission.class, QueryService.AuditAction.UPDATE)
Is this separate permissions class needed? Do we need to distinguish it from `UpdatePermission`?

2023-12-14 21:58 UTC, labkey-susanh commented on query/src/org/labkey/query/controllers/QueryController.java
> +            if (json.has(PROP_TARGET_CONTAINER) && !json.has(PROP_TARGET_CONTAINER_PATH))
Do we need to support both of these?

2023-12-14 21:58 UTC, labkey-susanh commented on query/src/org/labkey/query/controllers/QueryController.java
> +                // if moving run items from a type, the selections from other selectionKeys in that container will
```suggestion
                // if moving entities from a type, the selections from other selectionKeys in that container will

```

2023-12-15 14:13 UTC, cnathe commented on experiment/src/client/test/integration/MoveAssayRunsAction.ispec.ts
> +            expect(exception).toEqual('No \'rows\' array supplied!');
done

2023-12-15 14:14 UTC, cnathe commented on api/src/org/labkey/api/data/ContainerManager.java
> +            errors.reject(ERROR_GENERIC, "You do not have permission to move rows to this target container: " + targetIdOrPath + ".");
Yes, added queryName to error message

2023-12-15 14:14 UTC, cnathe commented on experiment/src/client/test/integration/MoveAssayRunsAction.ispec.ts
> +            }, {...topFolderOptions, ...editorUserOptions}).expect(500);
catch IllegalArgumentException and rethrow as ValidationException

2023-12-15 14:14 UTC, cnathe commented on experiment/src/client/test/integration/MoveSamplesAction.ispec.ts
> +            }, {...topFolderOptions, ...editorUserOptions}).expect(500);
catch IllegalArgumentException and rethrow as ValidationException

2023-12-15 14:14 UTC, cnathe commented on experiment/src/client/test/integration/MoveSourcesAction.ispec.ts
> +            expect(exception).toEqual('No \'rows\' array supplied!');
done

2023-12-15 14:33 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +            if (json.has(PROP_TARGET_CONTAINER) && !json.has(PROP_TARGET_CONTAINER_PATH))
no, changed to only support "targetContainerPath" and "auditUserComment"

2023-12-15 14:34 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                        moveFile(renameData);
Yeah, agreed. Since the file moves happen in an post commit task, this count wasn't getting included in the response object. I couldn't come up with a better way to make this work but open to suggestions.

2023-12-15 14:43 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +        moveRows(MoveEntitiesPermission.class, QueryService.AuditAction.UPDATE)
I didn't think it was going to be...the move samples, sources, and assay runs all worked fine using UpdatePermission as the moveRows action check. However, when I got to the move notebooks case, I couldn't find another way to get past the NotebookTable NotebookUpdateService.hasPermission check. I couldn't find a way to get the TableInfo QUS for this NotebookTable in the general moveRows case in a way that would `_allowInsertUpdate`. @labkey-nicka @labkey-susanh if either of you have a suggestion about how to do with without adding a new permission class, that would be awesome.

2023-12-15 16:27 UTC, labkey-susanh commented on query/src/org/labkey/query/controllers/QueryController.java
> +        moveRows(MoveEntitiesPermission.class, QueryService.AuditAction.UPDATE)
I see how that's a problem now, yes and am also not seeing a better way out of this.

2023-12-15 16:28 UTC, labkey-susanh approved these changes

2023-12-15 16:28 UTC, labkey-susanh commented on query/src/org/labkey/query/controllers/QueryController.java
> +                    throw new ValidationException("No '" + PROP_ROWS + "' array supplied.");
Thank you for this!

2023-12-15 16:37 UTC, labkey-nicka commented on query/src/org/labkey/query/controllers/QueryController.java
> +        moveRows(MoveEntitiesPermission.class, QueryService.AuditAction.UPDATE)
Indeed this is intentional. We don't want API users to be able to insert/update against the notebook table even if they have insert/update permissions. Adding a new class seems like a reasonable approach to me but I'd also be curious what @labkey-klum thinks.

2023-12-15 16:52 UTC, labkey-klum commented on query/src/org/labkey/query/controllers/QueryController.java
> +        moveRows(MoveEntitiesPermission.class, QueryService.AuditAction.UPDATE)
Agreed, introducing a new permission class is the cleanest way to deal with the notebook table permissions.

2023-12-15 19:26 UTC, merged