ObjectMapper consistency
LabKey/platform pull request #5103
Opened 2024-01-06 01:37 UTC by labkey-matthewb

#### Rationale
use JsonUtil.DEFAULT_MAPPER for consistency across the code base.

#### Related Pull Requests
* 

#### Changes
*

2024-01-06 18:15 UTC, labkey-adam requested changes
Adjust MultiValueTest.jsp?

2024-01-06 18:15 UTC, labkey-adam commented on query/src/org/labkey/query/MultiValueTest.jsp
> +        ObjectMapper om = JsonUtil.DEFAULT_MAPPER.copy();
Is `copy()` necessary?

2024-01-06 18:15 UTC, labkey-adam commented on query/src/org/labkey/query/MultiValueTest.jsp
> +        ObjectMapper om = JsonUtil.DEFAULT_MAPPER.copy();
Is `copy()` necessary?

2024-01-06 18:15 UTC, labkey-adam commented on query/src/org/labkey/query/MultiValueTest.jsp
> +        ObjectMapper om = new ObjectMapper().copy();
`JsonUtil.DEFAULT_MAPPER`? Why `copy()`?

2024-01-06 23:37 UTC, labkey-matthewb commented on query/src/org/labkey/query/MultiValueTest.jsp
> +        ObjectMapper om = JsonUtil.DEFAULT_MAPPER.copy();
Coz that way I don't have to read the test to see if it mutates the ObjectMapper.

2024-01-06 23:37 UTC, labkey-matthewb commented on query/src/org/labkey/query/MultiValueTest.jsp
> +        ObjectMapper om = new ObjectMapper().copy();
oops

2024-01-07 00:18 UTC, labkey-adam approved these changes

2024-01-08 01:54 UTC, merged