JavaScriptFragment.asJson()
LabKey/platform pull request #5108
Opened 2024-01-09 20:12 UTC by labkey-matthewb

replace Jsp.unsafe() with JavaScriptFragment.unsafe() in <script> blocks replace new ObjectMapper() with JsonUtil.DEFAULT_MAPPER or JsonUtil.createDefaultMapper()

#### Rationale

#### Related Pull Requests
* 

#### Changes
*

2024-01-23 05:03 UTC, labkey-adam commented on mothership/src/org/labkey/mothership/MothershipManager.java
> +        ObjectMapper mapper = JsonUtil.createDefaultMapper();
Could be `JsonUtil.DEFAULT_MAPPER`

2024-01-23 05:37 UTC, labkey-adam requested changes
There's an h() to q() conversion in there somewhere

2024-01-23 05:37 UTC, labkey-adam commented on study/src/org/labkey/study/view/datasetVisibility.jsp
>              storeId : '<%=h(storeId)%>',
That looks wrong

2024-01-23 05:37 UTC, labkey-adam commented on study/src/org/labkey/study/view/datasetVisibility.jsp
>              storeId : '<%=h(storeId)%>',
Meaning line 250

2024-01-26 14:25 UTC, labkey-matthewb commented on mothership/src/org/labkey/mothership/MothershipManager.java
> +        ObjectMapper mapper = JsonUtil.createDefaultMapper();
I've taken to using DEFAULT_MAPPER when I can inline the whole usage.  Just a style choice and speeds up converting code (what does readerForUpdating() do?  beats me.).

2024-01-26 14:31 UTC, labkey-matthewb commented on study/src/org/labkey/study/view/datasetVisibility.jsp
>              storeId : '<%=h(storeId)%>',
I assume this is some Ext weirdness where you have to htmlEncode() id's so they don't get injected into the html?  I don't think I changed this.

2024-01-26 14:41 UTC, labkey-matthewb commented on study/src/org/labkey/study/view/datasetVisibility.jsp
>              storeId : '<%=h(storeId)%>',
configRequestabilityRules.jsp has a strange use of h() which I changed to qh(), not sure if it's wrong.

2024-01-26 18:37 UTC, labkey-adam approved these changes

2024-01-27 01:02 UTC, merged