Automatically add Google Analytics URLs to CSP when enabled
LabKey/platform pull request #5200
Opened 2024-02-06 19:02 UTC by labkey-jeckels

#### Rationale
We know the external URLs that will be used for Google Analytics tracking, so they're safe and easy to register automatically with the content security policy.

#### Changes
* Inject Google URLs into CSP when GA tracking is enabled

2024-02-06 21:50 UTC, labkey-matthewb commented on core/src/org/labkey/core/analytics/AnalyticsServiceImpl.java
> +            ContentSecurityPolicyFilter.registerAllowedConnectionSource(ANALYTICS_CSP_KEY_1, GOOGLE_TAG_MANAGER_URL);
Too bad this method isn't multi-valued

2024-02-06 21:52 UTC, labkey-matthewb requested changes
I don't think this is solving any problem.  a) AllowedConnectionSource is for connect-src not script-src b) script-src uses strict dynamic so the problem is with including the nonce, not the presense/absence of the host.

2024-02-06 22:31 UTC, labkey-jeckels commented
> I don't think this is solving any problem. a) AllowedConnectionSource is for connect-src not script-src b) script-src uses strict dynamic so the problem is with including the nonce, not the presense/absence of the host.

Without these changes, on my dev machine where I have GA enabled (the built-in option, not the custom analytics script option), I get CSP violations reported. They go away when I run with this code. We have these two URLs in the `connect-src` for the CSPs we're deploying on our container instances today. Is that a wrong example to model this on?

2024-02-06 22:37 UTC, labkey-matthewb commented
> > I don't think this is solving any problem. a) AllowedConnectionSource is for connect-src not script-src b) script-src uses strict dynamic so the problem is with including the nonce, not the presense/absence of the host.
> 
> Without these changes, on my dev machine where I have GA enabled (the built-in option, not the custom analytics script option), I get CSP violations reported. They go away when I run with this code. We have these two URLs in the `connect-src` for the CSPs we're deploying on our container instances today. Is that a wrong example to model this on?

Sorry, I'm still thinking about the problem with today's deployments caused by not having the the script-nonce set.  Once we get pass that, we still have to make the API calls to do the actually analytics tracking... Those do need the connect-src.

So yes this would be useful.  mea culpa

2024-02-06 22:41 UTC, labkey-matthewb approved these changes

2024-02-07 16:21 UTC, labkey-adam approved these changes

2024-02-07 17:18 UTC, labkey-jeckels commented on core/src/org/labkey/core/analytics/AnalyticsServiceImpl.java
> +            ContentSecurityPolicyFilter.registerAllowedConnectionSource(ANALYTICS_CSP_KEY_1, GOOGLE_TAG_MANAGER_URL);
I thought the same thing. Your comment inspired me to make it var-arg, now pushed into this FB.

2024-02-07 17:19 UTC, labkey-jeckels commented
> > > I don't think this is solving any problem. a) AllowedConnectionSource is for connect-src not script-src b) script-src uses strict dynamic so the problem is with including the nonce, not the presense/absence of the host.
> > 
> > 
> > Without these changes, on my dev machine where I have GA enabled (the built-in option, not the custom analytics script option), I get CSP violations reported. They go away when I run with this code. We have these two URLs in the `connect-src` for the CSPs we're deploying on our container instances today. Is that a wrong example to model this on?
> 
> Sorry, I'm still thinking about the problem with today's deployments caused by not having the the script-nonce set. Once we get pass that, we still have to make the API calls to do the actually analytics tracking... Those do need the connect-src.
> 
> So yes this would be useful. mea culpa

OK, great. Yes, this doesn't do anything for the custom `<script>` scenario

2024-02-07 18:22 UTC, merged