class change due to commons-compress upgrade (#5247)
LabKey/platform pull request #5258
Opened 2024-02-21 21:29 UTC by labkey-ians

* Upgrade version of commons-compress

#### Rationale
Backporting commons-compress upgrade

#### Related Pull Requests
https://github.com/LabKey/server/pull/736
https://github.com/LabKey/server/pull/726

#### Changes
* Version bump to commons-compress

2024-02-21 21:30 UTC, labkey-adam approved these changes

2024-02-21 22:09 UTC, labkey-tchad requested changes
Looks like `commons-io` also needs an update. Lots of server errors with `java.lang.NoClassDefFoundError: org/apache/commons/io/build/AbstractStreamBuilder`

2024-02-22 01:02 UTC, labkey-ians commented
Looks like the remaining test is failing on the base branch also.

2024-02-22 01:03 UTC, labkey-tchad approved these changes

2024-02-22 01:13 UTC, merged