Miscellaneous issues
LabKey/platform pull request #5337
Opened 2024-03-18 18:29 UTC by labkey-klum

#### Related issues
- https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49335
- https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=49371

#### Rationale
- Return `HTMLString` objects for the QC state UI interfaces
- Do a better job of reporting errors when using a visit map to translate strings to visits.

2024-03-19 17:11 UTC, labkey-matthewb requested changes

2024-03-19 17:11 UTC, labkey-matthewb commented on study/src/org/labkey/study/controllers/StudyController.java
> -            return panelHtml.toString();
really need to convert getQcStateHtml() as well.  It seems to append string without using filter().  HtmlStringBuilder makes it harder to miss filtering strings

2024-03-19 21:32 UTC, labkey-klum commented on study/src/org/labkey/study/controllers/StudyController.java
> -            return panelHtml.toString();
done

2024-03-20 18:16 UTC, labkey-matthewb approved these changes

2024-03-20 22:11 UTC, merged