Use simpler check for authenticated user
LabKey/platform pull request #5360
Opened 2024-03-22 23:56 UTC by labkey-matthewb

#### Rationale
AuthenticatedRequest.isGuestSession() returns false for robots causing us to track sessions that won't ever fire SessionListener.sessionDestroyed()

#### Related Pull Requests
- 

#### Changes
-

2024-03-23 00:01 UTC, labkey-matthewb commented
Not right yet.  It seems we do want to track "real" guests?

2024-03-23 00:32 UTC, labkey-matthewb commented
I think AuthenticatedRequest.isGuestSession() isn't very meaningful here.  I think these changes are correct if the intention is that getActiveUserSessionCount() returns the count authenticated users sessions.  If that's not the case, then I'm confused about what the previous code was trying to do.

2024-03-23 23:35 UTC, labkey-jeckels approved these changes

2024-03-23 23:37 UTC, labkey-jeckels requested changes
The new assert on line 509 is failing.

2024-03-25 05:14 UTC, labkey-jeckels approved these changes

2024-03-25 05:14 UTC, labkey-jeckels commented on api/src/org/labkey/api/security/UserManager.java
> +            if (null != userId && 0 != userId)
```suggestion
            if (null != userId && getGuestUser().getUserId() != userId)
```

2024-03-25 20:58 UTC, merged