AbDisc: Plate Set Worklist & Instrument Instructions
LabKey/platform pull request #5459
Opened 2024-04-24 22:07 UTC by RosalineP

#### Rationale
See spec [here](https://docs.google.com/document/d/1TpINpd9UlIJCPYzrAbWxNzvTIqJUw1ZbNN_lvzW8MrQ/edit#heading=h.6oglt1vd831o).
#### Related Pull Requests
- 

#### Changes
- Create ArrayExcelWriter
- Modify ExcelWriter to support setting full file name
- Create WorklistAction and InstrumentInstructionAction, alongside related supporting fns

2024-04-24 22:09 UTC, RosalineP commented
Pending manual testing, as well as server-side and client-side unit tests

2024-04-24 22:16 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +    public ColumnDescriptor[] getColumnDescriptors(String prefix, Set<FieldKey> includedMetadataCols)
Considered doing an enum or such for the prefix, but was waffling on it

2024-04-24 22:18 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +    private final Map<String, FieldKey> FKMap = Map.of(
So this thing I've done is kind of weird. Hopefully by looking at the usages it's intelligible why I thought defining this constant might be useful—open to alternate structures, though!

2024-04-24 22:20 UTC, RosalineP commented on assay/src/org/labkey/assay/PlateController.java
> +    public static class WorkListAction extends ReadOnlyApiAction<WorklistForm>
(For both of these actions) I just saw that ExportAction exists—if that's the right class to use here I can update

2024-04-24 22:23 UTC, RosalineP commented on assay/src/org/labkey/assay/PlateController.java
> +                Set<FieldKey> sourceIncludedMetadataCols = PlateManager.get().getMetadataColumns(form.getSourcePlateSetId(), getContainer(), getUser());
Could possibly use some comments? Not totally sure how well this parses to the outside eye now

2024-04-25 18:03 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +    private final Map<String, FieldKey> FKMap = Map.of(
Consider making the map case insensitive

2024-04-25 18:03 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +        try (Results rs = QueryService.get().select(wellTable, getWellColumns(wellTable, destinationIncludedMetadataCols), new SimpleFilter(FKMap.get("plateSetId"), destinationPlateSetId), new Sort("
Are we relying on this sort?

2024-04-25 18:04 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +                if (sampleIdToDestinationRow.containsKey(sampleId))
would `computeIfAbsent` be more concise?

2024-04-25 18:06 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +        try (Results rs = QueryService.get().select(wellTable, getWellColumns(wellTable, sourceIncludedMetadataCols), new SimpleFilter(FKMap.get("plateSetId"), sourcePlateSetId), new Sort("rowid")))
Keep in mind that sorting this way may not always guarantee row/column ordering. Consider either adding a sorter or add test coverage that will fail if this were ever to change.

2024-04-25 18:12 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +                includedMetadataCols.add(FieldKey.fromParts("properties", name));
The `well` table is responsible for how metadata is joined into the schema. To make this more maintainable, consider moving this to a static method on `WellTable`.

2024-04-25 18:18 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +        if (!prefix.equals("Destination "))
The prefix should probably be converted to a string constant.

2024-04-25 18:24 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +    public Set<FieldKey> getMetadataColumns(int plateSetId, Container c, User u) throws ValidationException
These new methods that were added to `PlateManager` seem very tailored to be useful to only worklist and instrument instruction generation and might be confusing to other users. Recommendation is to move these to another class and expose the methods needed from `PlateManager`, it doesn't look there is much needed additionally, maybe just `getWellTable`. Consider adding some comments to the code as well.

2024-04-25 18:27 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +            throw new RuntimeException(e);
In these cases you are almost always better off using : `UnexpectedException.wrap(e)` to improve the generated stack trace.

2024-04-25 18:34 UTC, labkey-klum commented on assay/src/org/labkey/assay/PlateController.java
> +                if (plateSetSource == null || plateSetDestination == null)
Consider moving this check up (or in validateForm) before we do all the work to generate the data. Similar feedback for the `InstrumentInstructionAction`.

2024-04-25 18:58 UTC, labkey-klum commented on api/src/org/labkey/api/data/ArrayExcelWriter.java
> +public class ArrayExcelWriter extends ExcelWriter
Maybe some javadoc to describe what this class is and does. Is this really an array writer? It seems to accept a list of lists so just curious what prompted the name.

2024-04-25 19:00 UTC, labkey-klum commented on api/src/org/labkey/api/data/ArrayExcelWriter.java
> +    private final List<List<Object>> data;
If you don't care whether the thing inside of each list entry is another list you could also use a data structure like : `List<Object[]>`.

2024-04-25 19:02 UTC, labkey-klum commented on api/src/org/labkey/api/data/ArrayExcelWriter.java
> +    public class MapArrayDisplayColumn extends DisplayColumn
Doesn't seem related to a map array, perhaps copied from `MapArrayExcelWriter`. Consider renaming to something more accurate.

2024-04-25 19:20 UTC, labkey-klum requested changes
please consider some of the suggested changes.

2024-04-25 19:52 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +            "position", FieldKey.fromParts("position"),
define and use constants where possible on the table classes

2024-04-25 19:54 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +        try (Results rs = QueryService.get().select(wellTable, getWellColumns(wellTable, destinationIncludedMetadataCols), new SimpleFilter(FKMap.get("plateSetId"), destinationPlateSetId), new Sort("
Yes—see other comment thread around line 2719!

2024-04-25 19:57 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +        try (Results rs = QueryService.get().select(wellTable, getWellColumns(wellTable, sourceIncludedMetadataCols), new SimpleFilter(FKMap.get("plateSetId"), sourcePlateSetId), new Sort("rowid")))
Yes, I remember you bringing this up earlier, and I chatted with Nick about it—we thought that in the eventuality we change row insertion into a plate to be sparse (such that we cannot rely on rowid for order anymore) this will be another spot where we have to update the code. I'll be sure to add some test coverage if it shakes out for the server-side unit tests, if not I'll pop this into the selenium test recommendations

2024-04-25 20:19 UTC, RosalineP commented on api/src/org/labkey/api/data/ArrayExcelWriter.java
> +public class ArrayExcelWriter extends ExcelWriter
Added some documentation! I think I used arrays in an initial implementation and then switched to more lists. Now that I've updated so that `data` is `List<Object[]>` the name seems a little more reasonable

2024-04-25 20:55 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +    public Set<FieldKey> getMetadataColumns(int plateSetId, Container c, User u) throws ValidationException
Like so? (Also added some comments!)

2024-04-25 21:21 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +    private final Map<String, FieldKey> FKMap = Map.of(
Elided this since I started using constants in the FKMap, good to know this exists though!

2024-04-25 21:24 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +            "position", FieldKey.fromParts("position"),
@labkey-klum Take a look at my idea here for making this a bit nicer, let me know what you think... got tripped up on the lookup cols that didn't seem appropriate to put as constants on WellTable. The FieldKey parts are untouched because it felt like there would have to be a lot of making-into-undercase and bits where things don't quite align, like 'Row' being the const on WellTable but in FKMap within the lookup I need 'rows'

2024-04-25 23:04 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/PlateSetExport.java
> +    ) throws RuntimeSQLException, ValidationException
minor: RuntimeSQLException is not a checked exception so you don't need to declare it here.

2024-04-25 23:04 UTC, labkey-klum approved these changes

2024-04-26 22:49 UTC, labkey-nicka commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +            sample2.setCpasType(sampleType.getLSID());
nit: There is a comment in the `LineageTest` about not using `generateNextDbSeqLSID` in tests.

<img width="1008" alt="image" src="https://github.com/LabKey/platform/assets/3926239/3439242f-704b-442c-bd9b-9e9145326a4c">

That said, it is used in tests all over:

<img width="918" alt="image" src="https://github.com/LabKey/platform/assets/3926239/1693990a-7881-4ffe-b726-6db304b6636a">

Seems like either that comment needs to go away or there is actually a reason to not use it and use `generateSampleLSID().setObject(sampleName).toString()` instead.

2024-04-26 22:49 UTC, labkey-nicka commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +            SampleTypeService.get().deleteSampleType(sampleType.getRowId(), container, user, null);
nit: Seems odd that the `PlateManager.TestCase` is individually cleaning up these structures. Other tests normally just call `JunitUtil.deleteTestContainer()` and then dereference `container` and `user`. Something like:

```java
@AfterClass
public static void cleanup()
{
    deleteTestContainer();
    _container = null;
    _user = null;
}
```

2024-04-26 23:51 UTC, RosalineP commented on assay/src/org/labkey/assay/plate/PlateManager.java
> +            sample2.setCpasType(sampleType.getLSID());
Huh, interesting, good catch—not using generateNextDbSeqLSID works fine so I've updated to the generateSampleLSID() method

2024-04-30 19:44 UTC, merged