include the sample ID for the well in the transform script result data.
LabKey/platform pull request #5466
Opened 2024-04-30 19:58 UTC by labkey-klum

#### Rationale
[related issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=50276)

Make the sample ID from the well table available in the results file that is handed to the transform script. This is only available when the LKB plate experimental feature is enabled since it is the only way that samples can be plated into plates/plate sets.

2024-04-30 21:59 UTC, cnathe requested changes

2024-04-30 21:59 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                        row.put("SampleID", wellBean.getSampleId());
I tested this locally, and this does give me the sample RowId in the runDataFile.tsv for the transform script. But just as we include the Plate ID instead of the plate RowId, I was expecting the Sample ID (name). Would that be possible to include instead of the rowId?

2024-05-02 16:03 UTC, cnathe approved these changes

2024-05-02 16:03 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                        // include the sample information from the well (Issue 50276)
@labkey-klum in my local testing, I have the first set of wells in my plate empty (i.e. blanks). This means that the mergedRows for those didn't have sampleId and sampleName values. This resulted in the runDataFile not having those columns (likely because it was using the first row to get the column headers. 

I made a slight change with this commit: https://github.com/LabKey/platform/pull/5466/commits/3b778ee812f01ba505512ab30322f41969e5648e
Can you take a look?

2024-05-02 18:16 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                        // include the sample information from the well (Issue 50276)
Yes, looks great, thanks for making that change.

2024-05-02 19:32 UTC, merged