Issue 50354: LKSM: Include indicator of unavailable file in apps
LabKey/platform pull request #5526
Opened 2024-05-22 22:43 UTC by XingY

#### Rationale

#### Related Pull Requests
- 

#### Changes
-

2024-05-23 18:58 UTC, cnathe requested changes

2024-05-23 18:58 UTC, cnathe commented on api/src/org/labkey/api/data/AbstractFileDisplayColumn.java
> +            String url = null == s ? null : s.eval(ctx);
I was confused by this change at first. However, looking at IntelliJ, it looks like you are effectively skipping over the renderURL override in DataColumn.java and reverting back to the one in DisplayColumn.java. Is that correct? If so, might be worth a comment here.

2024-05-23 18:58 UTC, cnathe commented on api/src/org/labkey/api/study/assay/FileLinkDisplayColumn.java
> +                result += " (unavailable)";
it looks like I am getting double "(unavailable)" messages in the LKS side now with this change. This class already adds the suffix at line 328. is that not enough to detect on the client side for the app?
<img width="815" alt="Screenshot 2024-05-23 at 1 58 16 PM" src="https://github.com/LabKey/platform/assets/6411206/757c67ac-e80c-4750-ae06-5facf98c056a">

2024-05-24 16:31 UTC, cnathe approved these changes

2024-05-24 18:54 UTC, XingY commented on api/src/org/labkey/api/data/AbstractFileDisplayColumn.java
> +            String url = null == s ? null : s.eval(ctx);
Yep, comment added

2024-05-24 18:56 UTC, XingY commented on api/src/org/labkey/api/study/assay/FileLinkDisplayColumn.java
> +                result += " (unavailable)";
good catch. should be fixed now. The LKS side uses a different code path for display column to add the suffix.The client side needs getQuery api displayValues changed.

2024-05-28 21:41 UTC, merged