Issue 50380: LKSM: Explore adding a metric to provide number of unavailable files on a server
LabKey/platform pull request #5531
Opened 2024-05-24 03:43 UTC by XingY

#### Rationale
Issue [50380](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=50380)
A new system maintenance task is added to query for missing files from file domain fields, which is then added to the metrics report. The metrics gives a summary stats of missing files per container per datatype. A new api action is also added to allow detailed query of which files are missing for a specific container. 

#### Related Pull Requests
- 

#### Changes
-

2024-05-24 03:44 UTC, XingY commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +public class FileLinkMetricsMaintenanceTask implements SystemMaintenance.MaintenanceTask
Should this system task be disabled by default?

2024-05-24 04:59 UTC, labkey-jeckels requested changes

2024-05-24 04:59 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +                            containerMetrics.put(source, missingFiles.get(source).size());
Per our current policy, we shouldn't collect container-level metrics:

https://www.labkey.org/Documentation/Archive/24.3/wiki-page.view?name=reportUsageStatistics#exception

I suggest collapsing this to site-wide counts for metric reporting, but retaining the ability to report at a per-container level for admins who have access to the server itself, as it will be extremely helpful to track down the problematic records.

2024-05-24 18:33 UTC, XingY commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +                            containerMetrics.put(source, missingFiles.get(source).size());
Good reminder. Updated to show a summary count instead.

2024-05-29 00:14 UTC, labkey-jeckels requested changes

2024-05-29 00:14 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/api/ExperimentService.java
> +    Map<String, Map<String, Set<String>>> doMissingFilesCheck(User user, Container container) throws SQLException;
Do we need to expose this to other modules? It looks like all callers are within the experiment module so it probably isn't needed here.

2024-05-29 00:14 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                String filePath = rs.getString("FilePath");
Can we push this into a WHERE clause instead?

2024-05-29 00:14 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                if (filePath.startsWith("file:"))
We may have S3 URLs in `exp.data`, which will start with `s3://`

Perhaps check if it's a URI (construct a `URI` and catch the exception falling back on the `File` constructor if not). If so, use `Files.exists(Path.of(uri))` instead.

2024-05-29 00:14 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        try (ResultSet rs = new SqlSelector(CoreSchema.getInstance().getSchema(), selectSql).getResultSet(false))
This has the potential to return a massive list. Maybe we should bail out if we hit 1,000 or 10,000 missing files for both perf and memory use?

2024-05-29 00:14 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +public class FileLinkMetricsMaintenanceTask implements SystemMaintenance.MaintenanceTask
That seems like a good idea for starters, but it might be a pain to enable where we want it. We could add a startup property to enable but should check with SysEng on preferences. Our initial focus is for LKSM customers.

@labkey-adam @labkey-stuartm @labkey-jony @labkey-willm

2024-05-29 00:14 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +                svc.registerUsageMetrics(ExperimentServiceImpl.MODULE_NAME, () -> metrics);
Won't this keep adding a usage metrics implementation every time it runs? Can we register it once and serve up the most recent data?

2024-05-30 16:26 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                if (filePath.startsWith("file:"))
This task checks for files for File_Link field type only, so they would be from either exp.object or provisioned table, but not exp.data. But turns out we currently don't support File_Link fields with S3 storage (Issue 50538 , not sure if it ever worked). We should probably address 50538 and punt this to 24.7.

2024-05-30 16:41 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                String filePath = rs.getString("FilePath");
The WHERE already checks for FilePath not null, I added the check here to be extra cautious, but can remove it.

2024-05-30 19:56 UTC, XingY commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +public class FileLinkMetricsMaintenanceTask implements SystemMaintenance.MaintenanceTask
OK, I made this turned off by default and added a new startup prop to turn this on:
FileLinkMetrics.EnableFileLinkMetricsTask;startup = true

2024-05-30 19:56 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        try (ResultSet rs = new SqlSelector(CoreSchema.getInstance().getSchema(), selectSql).getResultSet(false))
Changes made to cap at 1000 missing files

2024-05-30 23:17 UTC, XingY commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +                svc.registerUsageMetrics(ExperimentServiceImpl.MODULE_NAME, () -> metrics);
updated to register only once

2024-05-30 23:18 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                if (filePath.startsWith("file:"))
We might be able to punt the S3 part to 24.7. Since users aren't able to upload S3 files for FILE_LINK fields in the 1st place, the metrics is irrelevant at the moment.

2024-05-31 00:45 UTC, labkey-jeckels approved these changes

2024-05-31 00:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +            log.error("Unable to run missing files check task. {}", e.getMessage());
It's usually helpful to have the full stack trace logged.

```suggestion
            log.error("Unable to run missing files check task.", e);
```

2024-05-31 00:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                if (filePath.startsWith("file:"))
Deferring any S3 handling sounds fine. Can you add a comment in the code and/or issue to make sure we remember to make this metric compatible when we start supporting it?

2024-05-31 00:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +                    String disabled = writableProps.get(SystemMaintenance.DISABLED_TASKS_PROPERTY_NAME);
Can we consolidate any of this with the code in `SystemMaintenance.setProperties()`? It's unfortunate to have more places that know the details of how these values are parsed and persisted.

2024-05-31 17:11 UTC, XingY commented on experiment/src/org/labkey/experiment/FileLinkMetricsMaintenanceTask.java
> +                    String disabled = writableProps.get(SystemMaintenance.DISABLED_TASKS_PROPERTY_NAME);
yep, done

2024-05-31 18:54 UTC, merged