Sample Type & Source Type Designer Roles
LabKey/platform pull request #5546
Opened 2024-05-29 19:28 UTC by XingY

#### Rationale

#### Related Pull Requests
- https://github.com/LabKey/labkey-ui-components/pull/1505
- https://github.com/LabKey/labkey-ui-premium/pull/424
- https://github.com/LabKey/platform/pull/5546
- https://github.com/LabKey/limsModules/pull/319

#### Changes
- new designer roles for samples and dataclasses
- Change DeleteProtocolByRowIdsAPI to require DesignAssayPermission instead of delete perm
- check for existing data in datatype before deleting a datatype for non-admins
- jest integration test for designer roles

2024-06-04 19:58 UTC, cnathe requested changes

2024-06-04 19:58 UTC, cnathe commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        }
was this change for a different issue? if so, can you add the issue number? seems unrelated to this story

2024-06-04 19:58 UTC, cnathe commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            return !st.hasData();
this returns before checking DesignSampleTypePermission. so would this be true for an empty sample type if the user was and editor or reader?

2024-06-04 19:58 UTC, cnathe commented on core/src/org/labkey/core/CoreModule.java
> +            roleAssignments.put("sampleTypeDesignerCount", new SqlSelector(CoreSchema.getInstance().getSchema(), "SELECT COUNT(*) FROM core.RoleAssignments WHERE userid > 0 AND role = ?", "org.labkey
the SQL here is the same for all so could be factored out to a variable

2024-06-04 19:58 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
> +                return !dataClass.hasData();
similar comment here, this could return true without checking for `DesignDataClassPermission`, right?

2024-06-04 19:58 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                            throw new UnauthorizedException("You do not have sufficient permissions to delete '" + protocol.getName() + "'.");
this is all transacted, so should work fine but should this check be moved to the top of this method so that we don't have to go through the work of deleting the datasets and runs just to find out that we are throwing here?

2024-06-04 19:58 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            if (sampleType == null || nameGen.getExpressionSummary() == null)
this also seems unrelated to this story? issue number to add here maybe?

2024-06-04 19:58 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                        throw new UnauthorizedException("You do not have sufficient permissions to delete this assay design.");
this check was added for DeleteProtocolByRowIdsAction but not for DeleteProtocolByRowIdsAPIAction above. Was that intentional?

2024-06-05 19:48 UTC, XingY commented on api/src/org/labkey/api/data/NameGenerator.java
> +                        }
Yep, this is from exception report, no issue number

2024-06-05 19:48 UTC, XingY commented on experiment/src/org/labkey/experiment/api/SampleTypeUpdateServiceDI.java
> +            if (sampleType == null || nameGen.getExpressionSummary() == null)
same, this is from exception report, no issue number

2024-06-05 20:16 UTC, XingY commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +            return !st.hasData();
good catch, fixed

2024-06-05 20:16 UTC, XingY commented on core/src/org/labkey/core/CoreModule.java
> +            roleAssignments.put("sampleTypeDesignerCount", new SqlSelector(CoreSchema.getInstance().getSchema(), "SELECT COUNT(*) FROM core.RoleAssignments WHERE userid > 0 AND role = ?", "org.labkey
done

2024-06-05 20:17 UTC, XingY commented on experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
> +                return !dataClass.hasData();
fixed

2024-06-05 20:17 UTC, XingY commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +                            throw new UnauthorizedException("You do not have sufficient permissions to delete '" + protocol.getName() + "'.");
updated

2024-06-05 20:17 UTC, XingY commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                        throw new UnauthorizedException("You do not have sufficient permissions to delete this assay design.");
change made so it's checked for both actions

2024-06-05 21:35 UTC, cnathe approved these changes

2024-06-11 00:07 UTC, merged