select query logging
LabKey/platform pull request #5643
Opened 2024-07-01 20:25 UTC by labkey-matthewb

#### Rationale
Fixes for log all queries

#### Related Pull Requests
- 

#### Changes
-

2024-07-03 19:13 UTC, labkey-adam requested changes
Seems good and not too invasive. Need to fix test failures in compliance, et al. Please finish comment in SampleDatasetTable:137.

2024-07-03 19:13 UTC, labkey-adam commented on study/src/org/labkey/study/query/SampleDatasetTable.java
> +    // NOTE we are going to wrap a
???

2024-07-08 21:58 UTC, labkey-adam commented on api/src/org/labkey/api/query/FilteredTable.java
> +            _rules = canApplyTableRules() ? findTableRules() : TableRules.NOOP_TABLE_RULES;
Any risk of race conditions here? Should we assign to `_rules` in the constructor instead of lazily?

2024-07-08 22:00 UTC, labkey-adam approved these changes

2024-07-08 23:18 UTC, labkey-matthewb commented on api/src/org/labkey/api/query/FilteredTable.java
> +            _rules = canApplyTableRules() ? findTableRules() : TableRules.NOOP_TABLE_RULES;
Explicitly in the constructor might be better.   However, there's no race condition.  getTableRules() will get called before/by applyTableRules() which happens during construction anyway.

2024-07-10 00:04 UTC, merged