Switch assay import to use DataIterator
LabKey/platform pull request #5703
Opened 2024-07-22 22:57 UTC by labkey-jeckels

#### Rationale
Building on earlier work to make assay import stream data to handle large files, using `DataIterator` for the streaming aligns this code with other streaming approaches.

#### Changes
- New helpers for Map-oriented DataIterating
- Switch from the temporary `ValidatingDataRowIterator` to `DataIterator`
- Stronger enforcement of `DataIterator` assumptions

2024-07-23 18:11 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/AbstractMapDataIterator.java
> +                    return copyRows(rows);
nice

2024-07-23 18:21 UTC, labkey-matthewb commented on api/src/org/labkey/api/exp/OntologyManager.java
> +                                          DataIterator rawRows,
This is great.  We should leave a TODO (and backlog task) that there really shouldn't be usages of insertTabDelimited() for the tuple-store where we have a Domain and a wrapping TableInfo.  StandardDataIteratorBuilder and TableInsertDataIteratorBuilder should understand most of this insertTabDelimited() stuff.  There's still all the inputs etc and other higher level data-handling, such as inputs, to contend with (see ExpDataIterators).

2024-07-23 18:25 UTC, labkey-matthewb commented on api/src/org/labkey/api/qc/TsvDataSerializer.java
> +                    columns = new ArrayList<>(row.keySet());
It should be the same, but it is slightly odd to not ask the ColumnInfo's for the column names.

2024-07-23 23:20 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/MapDataIterator.java
> +                if (name != null && skip.contains(name))
should this be || instead of && (or just and assert != null)?

2024-07-23 23:33 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/AbstractMapDataIterator.java
> +    public static DataIteratorBuilder builderOf(List<Map<String, Object>> maps)
Why not the static methods on class MapDataIterator?

2024-07-23 23:39 UTC, labkey-matthewb requested changes
Some small comments to consider.  It would be good to consolidate the MapDataIterator.of() methods and AbstractMapDataIterator.builderOf() methods.

2024-07-24 01:09 UTC, labkey-jeckels commented on api/src/org/labkey/api/dataiterator/MapDataIterator.java
> +                if (name != null && skip.contains(name))
Yes

2024-07-24 18:43 UTC, labkey-jeckels commented on api/src/org/labkey/api/dataiterator/AbstractMapDataIterator.java
> +    public static DataIteratorBuilder builderOf(List<Map<String, Object>> maps)
No good reason. I consolidated to the `MapDataIterator` version.

2024-07-24 18:44 UTC, labkey-jeckels commented on api/src/org/labkey/api/qc/TsvDataSerializer.java
> +                    columns = new ArrayList<>(row.keySet());
Switched to use ColumnInfos

2024-07-24 18:45 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/OntologyManager.java
> +                                          DataIterator rawRows,
Comment added and I consolidated some of the overrides. Take a look and please update the comment if I didn't capture what you wanted.

2024-07-24 21:01 UTC, labkey-matthewb approved these changes

2024-07-25 23:10 UTC, labkey-jeckels commented on api/src/org/labkey/api/qc/TsvDataSerializer.java
> +                    columns = new ArrayList<>(row.keySet());
Had to push a follow-up fix so that it noticed when a map transformer added new fields to the map. Feel free to review the latest

2024-07-26 19:10 UTC, labkey-matthewb requested changes

2024-07-26 19:10 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/DataIteratorUtil.java
> +
This does not seem like the right fix to me.  Users of the DataIterator expect to be able to inspect the column list immediately after construction.  The constructor of the _MapTransformer class should know the columns it might add to the output map.

2024-07-26 19:10 UTC, labkey-matthewb commented on api/src/org/labkey/api/dataiterator/DataIteratorUtil.java
> +
For instance we will construct a INSERT/UPDATE statements based on the metadata of the dataiterator.  It won't work to add columns later.

2024-07-29 20:37 UTC, labkey-matthewb approved these changes

2024-07-29 21:07 UTC, labkey-jeckels commented on api/src/org/labkey/api/dataiterator/DataIteratorUtil.java
> +
Switched to having the map transforming step declare the possible fields up front.

2024-07-29 21:38 UTC, merged