Respect distribution-provided properties
LabKey/platform pull request #5890
Opened 2024-09-26 21:35 UTC by labkey-adam

#### Rationale
As of the newest gradle plugins version, distributions now include a properties file with distribution name, archive filename, and (optionally) supported databases. This PR reads and uses those properties.

Related: https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=51326

#### Related Pull Requests
- https://github.com/LabKey/gradlePlugin/pull/219

#### Changes
- Read `distribution.properties` file, if present. Read it once & stash the results and optimize `shouldReceiveMarketingUpdates()` to address [Issue 51326](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=51326).
- Stop reading standalone `distribution` file
- Show distribution name and filename on server information page and export diagnostics
- In production mode, throw if the primary database is not supported by the distribution
- Stop allowing `cpasDataSource`
- Deprecate support for PostgreSQL 12 and start claiming that PostgreSQL 17 (just released) is tested

2024-09-27 15:05 UTC, labkey-jeckels approved these changes

2024-09-27 15:05 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/SupportedDatabase.java
> +        throw new IllegalStateException("Dialect not supported");
Unlikely to ever hit this, but always nice to include the dialect that was supplied in the error message

2024-09-27 15:05 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/MothershipReport.java
> +        addParam("distributionFilename", AppProps.getInstance().getDistributionFilename());
These values are stored in real columns in `mothership.serversession`. Better to add this to the JSON metrics, likely in `CoreModule`. As-is, the `distributionFilename` value will be ignored.

2024-10-01 18:50 UTC, labkey-tchad requested changes
`EmbeddedExtractor` needs to be updated to handle the new `distribution.properties` file. `shouldExtract`, `getDistributionInfo`, and `LabKeyDistributionInfo` need to know the name of the new file and how to handle the new structure

2024-10-01 18:55 UTC, labkey-adam commented
> `EmbeddedExtractor` needs to be updated to handle the new `distribution.properties` file. `shouldExtract`, `getDistributionInfo`, and `LabKeyDistributionInfo` need to know the name of the new file and how to handle the new structure

Yep, I have those changes locally

2024-10-01 19:03 UTC, labkey-adam commented
> > `EmbeddedExtractor` needs to be updated to handle the new `distribution.properties` file. `shouldExtract`, `getDistributionInfo`, and `LabKeyDistributionInfo` need to know the name of the new file and how to handle the new structure
> 
> Yep, I have those changes locally

@labkey-tchad those changes need to go into a separate PR since they're in the `server` repo. Can you approve this PR to unblock it?

2024-10-01 19:05 UTC, labkey-tchad approved these changes

2024-10-01 19:14 UTC, merged