Plate replicate rollups and AbDisc assay re-import
LabKey/platform pull request #5906
Opened 2024-10-02 18:26 UTC by labkey-klum

#### Rationale
Introduces support for the calculation of standard deviation and mean values for replicate well groups for protocols that support plate metadata in LKB folders. Replicate aggregates are computed for numerical measures in the results domain and are automatically joined to the results views.

In support of LKB AB discovery scenarios (and potentially others), this also introduces the notion of the addition of assay run data over time through the existing assay run re-import feature. Plate set plate data can be added to a run over multiple imports. The server will attempt to combine / merge prior data with new data on a plate boundary within a single plate set during each subsequent import / re-import.

#### Changes

#### Related Pull Requests

2024-10-09 18:50 UTC, cnathe requested changes

2024-10-09 18:50 UTC, cnathe commented on api/src/org/labkey/api/assay/AssayRunUploadContext.java
> +        MERGE_DATA
do we have a comment in the code somewhere as to what "merge" means in this context (i.e. regarding the "replace existing plates but append new plates" behavior)? just thinking it might be good to put some comment / description here in the enum otherwise.

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +        if (getProvider().isPlateMetadataEnabled(getProtocol()))
should this also have the `isExperimentalAppPlateEnabled` or is that not needed here?

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +            if (replicateTable != null)
if replicateTable is null here, it looks like the call to `super.createProviderTable(name, cf)` will also end up returning null, so probably can just drop this if statement and always return replicateTable here.

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +                            if (col != null && col.isMeasure() && col.getJdbcType().isNumeric())
this check for "isMeasure and isNumeric" happens in a couple of places (maybe only 2 that I see?). I was thinking it would be good to share in a helper method, but I don't think that will work since this one is ColumnInfo objects and the other is DomainProperty.

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +            return new DefaultQueryUpdateService(this, getRealTable());
Do we really want this PlateReplicateStats table to be editable? I was thinking it would be read only. We don't want users to be able to insert/update/delete rows into this table directly, do we?

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                        for (Map<String, Object> row : _parsePlateData(container, user, prevData, provider, protocol, plateSet, plates, prevFile, settings))
I wasn't expecting that we'd reparse the previous file here. For example, if I imported plate1 data for a plate set with plate1 and plate2 and then came back to re-import and attach plate2. Then this works. But if I had edited results in the plate1 data prior to re-import, those edits would be lost as we'd be going back to the original file here. Thoughts?

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                            replicateRow.put(measure.getKey() + PlateReplicateStatsDomainKind.REPLICATE_STD_DEV_SUFFIX, stat.getStdDev());
there is a case on update where we would need to remove a mean / sd value instead of just updating it. For example, if you had a replicate well group with values for measures1 which resulted in a mean / sd value and then edit the assay results rows to blank out those values for measure1, we'd want the mean / sd to also be removed.

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +            return tableInfo.getUpdateService();
see previous comment. should this just return the default QUS here instead of having it on the table itself?

2024-10-09 18:50 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateTriggerFactory.java
> +                    try (DbScope.Transaction tx = ExperimentService.get().ensureTransaction())
I'm surprised we'd have a new transaction here. isn't this trigger already happening in a transaction? or do we need a new transaction here because this is on complete?

2024-10-09 19:55 UTC, labkey-chrisj commented
One thing we may want to do is apply a standard format for decimal/float-based columns; with the default format we end up not rounding numbers we probably ought to round in our mean/stddev calculation column: 
<img width="450" alt="image" src="https://github.com/user-attachments/assets/29964c5b-fbb3-4932-b03e-74216130d3f3">

2024-10-10 19:16 UTC, labkey-klum commented on api/src/org/labkey/api/assay/AssayRunUploadContext.java
> +        MERGE_DATA
I added some comments to this enum, the various options were meant to be interpreted by the data handlers but I described the plate based behavior.

2024-10-10 19:17 UTC, labkey-klum commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +        if (getProvider().isPlateMetadataEnabled(getProtocol()))
no longer needed, this was leftover from when there were two variants of plate metadata

2024-10-10 19:18 UTC, labkey-klum commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +            if (replicateTable != null)
done

2024-10-10 19:18 UTC, labkey-klum commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +                            if (col != null && col.isMeasure() && col.getJdbcType().isNumeric())
exactly 😢

2024-10-10 19:24 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/AssayPlateTriggerFactory.java
> +                    try (DbScope.Transaction tx = ExperimentService.get().ensureTransaction())
that's true, removed.

2024-10-10 19:59 UTC, labkey-klum commented on assay/src/org/labkey/assay/TSVProtocolSchema.java
> +            return new DefaultQueryUpdateService(this, getRealTable());
The table is provisioned, so we want to use the update service to interact with the generated stats. I've removed the table from the visible names in the schema and added some code to prevent users from getting an updatable version of the table.

2024-10-10 19:59 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                            replicateRow.put(measure.getKey() + PlateReplicateStatsDomainKind.REPLICATE_STD_DEV_SUFFIX, stat.getStdDev());
agreed, fixed.

2024-10-11 03:57 UTC, labkey-klum commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                        for (Map<String, Object> row : _parsePlateData(container, user, prevData, provider, protocol, plateSet, plates, prevFile, settings))
After discussing with Cory and Nick, the plan is to not reparse the previous file, but to rely on the run results in the database for this re-import

2024-10-11 15:01 UTC, cnathe approved these changes

2024-10-11 15:01 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                Object plateObj = rows.get(0).get(AssayResultDomainKind.PLATE_COLUMN_NAME);
it doesn't look like `plateObj` is used, I believe it can be removed.

2024-10-11 15:01 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                //    plateFieldKey = FieldKey.fromParts(AssayResultDomainKind.PLATE_COLUMN_NAME);
remove commented lines?

2024-10-11 15:01 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                            replicateRow.put(measure.getKey() + PlateReplicateStatsDomainKind.REPLICATE_MEAN_SUFFIX, null);
minor: could collapse to a single line:
`replicateRow.put(measure.getKey() + PlateReplicateStatsDomainKind.REPLICATE_MEAN_SUFFIX, !Double.isNaN(stat.getMean()) ? stat.getMean() : null);`

2024-10-11 15:01 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                            replicateRow.put(measure.getKey() + PlateReplicateStatsDomainKind.REPLICATE_STD_DEV_SUFFIX, null);
minor: could collapse to a single line:
`replicateRow.put(measure.getKey() + PlateReplicateStatsDomainKind.REPLICATE_STD_DEV_SUFFIX, !Double.isNaN(stat.getStdDev()) ? stat.getStdDev() : null);`

2024-10-11 20:57 UTC, merged