Add support for users updating the CSP's sources
LabKey/platform pull request #5965
Opened 2024-10-21 21:26 UTC by labkey-ians

#### Rationale
[Secure Issue 50544: UI-based support for customizing CSP-allowed servers](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=50544)
I added a new link in the Admin Console > Settings > Configuration column and reused the External Redirect UI, forms, and controller. 

#### Changes
- Generalized the ExternalRedirectAdminAction's JSPs, form, and methods
- Added a method to register the new source hosts with the CSP at startup and save

2024-10-22 00:40 UTC, labkey-adam requested changes

2024-10-22 00:40 UTC, labkey-adam commented on api/src/org/labkey/api/settings/AppPropsImpl.java
>      }
Could factor out a common method that takes the enum constant to eliminate duplicate code

2024-10-22 00:40 UTC, labkey-adam commented on api/src/org/labkey/api/settings/WriteableAppProps.java
>  }
Factor out a common method here as well?

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/CoreModule.java
> +        LOG.debug("Registered [{}] as an allowed connection source", String.join(", ", AppProps.getInstance().getExternalSourceHosts()));
```suggestion
        LOG.debug("Registered [{}] as an allowed connection source", () -> String.join(", ", AppProps.getInstance().getExternalSourceHosts()));

```

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/CoreModule.java
> +        LOG.debug("Registered [{}] as an allowed connection source", String.join(", ", AppProps.getInstance().getExternalSourceHosts()));
Totally optional, but this avoids doing the join work unless the level is `DEBUG`.

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +            form.setExistingHostsList(form.getTypeEnum() == ExternalServerType.Source ? AppProps.getInstance().getExternalSourceHosts() : AppProps.getInstance().getExternalRedirectHosts());
Cleaner (and more future expandable) would be to push the enum-specific details into each constant. So caller would be something like:
```
form.setExistingHostsList(form.getTypeEnum().getHostsList());
```

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                update = handleHostPost(form, appProps::getExternalRedirectHosts, appProps::setExternalRedirectHosts,  errors);
Ideally, this code wouldn't know anything about the specific behaviors of the enum constants... just pass the enum constant into `handleHostPost()` and implement `getHosts()` and `setHosts()` on the enum.

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                }
Similarly, implement `afterSave()` on the enum and call it unconditionally. Empty method in the case of Redirect.

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
>                  for (String externalRedirectHost : redirectHosts)
```suggestion
                for (String externalHost : externalHosts)

```

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                List<String> redirectHosts = getHosts.get();
```suggestion
                List<String> externalHosts = getHosts.get();

```

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                        setHosts.accept(redirectHosts);
```suggestion
                        setHosts.accept(externalHosts);

```

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                List<String> redirectHosts = form.getExistingHostList(); //get hosts from the form, this includes updated hosts
Rename... `externalHosts`?

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                    List<String> existingRedirectHosts = getHosts.get();
Rename?

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                String newExternalRedirectHost = StringUtils.trimToEmpty(form.getNewExternalHost());
Rename

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +            JspView<ExternalHostsForm> newView = new JspView<>("/org/labkey/core/admin/addNewExternalRedirectHost.jsp", form, errors);
Should probably change the JSP names

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +            JspView<ExternalHostsForm> existingView = new JspView<>("/org/labkey/core/admin/existingExternalRedirectHosts.jsp", form, errors);
Should probably change the JSP names

2024-10-22 00:40 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
>          @Override
Need to update `addNavTrail()` as well. A help topic needs to be defined on the enum and used here. And the title needs to change based on the enum.

2024-10-23 02:54 UTC, labkey-adam approved these changes
One question about trimming hosts before storing

2024-10-23 02:54 UTC, labkey-adam commented on api/src/org/labkey/api/settings/WriteableAppProps.java
> +        storeStringValue(propName, String.join(EXTERNAL_HOST_DELIMITER, externalSourceHosts));
Previous code did a `trim()` on each url... no longer needed?

2024-10-23 17:47 UTC, labkey-ians commented on api/src/org/labkey/api/settings/WriteableAppProps.java
> +        storeStringValue(propName, String.join(EXTERNAL_HOST_DELIMITER, externalSourceHosts));
I don't believe so. I moved the trim to the validation & set-addition step. I guess that opens a potential hole if we add new callers, but I think "trimming" fits better as part of the validation/sanitation process.

2024-10-23 18:25 UTC, labkey-adam commented on api/src/org/labkey/api/settings/WriteableAppProps.java
> +        storeStringValue(propName, String.join(EXTERNAL_HOST_DELIMITER, externalSourceHosts));
Cool, I missed that

2024-10-24 17:00 UTC, merged