Junit test for timestamps on French SQL Server
LabKey/platform pull request #5997
Opened 2024-10-28 17:27 UTC by labkey-adam

#### Rationale
Related PR fixes issues with timestamps used in compare clauses on SQL Server. This adds a junit test for the fix.

#### Related Pull Requests
- https://github.com/LabKey/platform/pull/5987

#### Changes
- Optional ability to pass a `Connection` to a `TableSelector`
- Exercise timestamps with various compare clause scenarios. On SQL Server, exercise the test steps with connection set to English and then French.

2024-10-28 17:37 UTC, labkey-jeckels approved these changes

2024-10-28 17:37 UTC, labkey-jeckels commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServer2016Dialect.java
> +            throw new RuntimeException(e);
RuntimeSQLException?

2024-10-28 19:14 UTC, labkey-tchad commented
Verifying on [`Old Dependencies`](https://teamcity.labkey.org/buildConfiguration/LabKey_247Release_Internal_InternalSuites_OldDependenciesSqlserver/3245095?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true) suite. If there were to be surprise failures, that seems like a likely place.

2024-10-28 23:49 UTC, labkey-tchad requested changes
This seems to be causing a connection leak.

2024-10-29 00:34 UTC, labkey-tchad commented
Yup, got a run with mem tracker stacktraces enabled:
```
org.labkey.api.util.MemTracker.put(MemTracker.java:371)
org.labkey.api.data.ConnectionWrapper.<init>(ConnectionWrapper.java:119)
org.labkey.bigiron.mssql.MicrosoftSqlServer2016Dialect$TestCase$1.getWrapped(MicrosoftSqlServer2016Dialect.java:365)
org.labkey.bigiron.mssql.MicrosoftSqlServer2016Dialect$TestCase$1.<init>(MicrosoftSqlServer2016Dialect.java:354)
org.labkey.bigiron.mssql.MicrosoftSqlServer2016Dialect$TestCase.testCompareClauses(MicrosoftSqlServer2016Dialect.java:352)
```

2024-10-29 12:48 UTC, labkey-adam commented
> Yup, got a run with mem tracker stacktraces enabled:
> 
> ```
> org.labkey.api.util.MemTracker.put(MemTracker.java:371)
> org.labkey.api.data.ConnectionWrapper.<init>(ConnectionWrapper.java:119)
> org.labkey.bigiron.mssql.MicrosoftSqlServer2016Dialect$TestCase$1.getWrapped(MicrosoftSqlServer2016Dialect.java:365)
> org.labkey.bigiron.mssql.MicrosoftSqlServer2016Dialect$TestCase$1.<init>(MicrosoftSqlServer2016Dialect.java:354)
> org.labkey.bigiron.mssql.MicrosoftSqlServer2016Dialect$TestCase.testCompareClauses(MicrosoftSqlServer2016Dialect.java:352)
> ```

Yep, I see that. Will track it down...

2024-10-30 14:49 UTC, labkey-adam commented
Note that the one BVT test run in red above passed in a subsequent run: https://teamcity.labkey.org/buildConfiguration/LabKey_247Release_Community_BvtBSqlserver/3251902?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false

2024-10-30 15:49 UTC, labkey-tchad approved these changes

2024-10-30 16:11 UTC, merged

2024-10-30 16:25 UTC, labkey-tchad approved these changes
This is making me very paranoid about anonymous classes.

2024-10-30 16:25 UTC, labkey-tchad commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServer2016Dialect.java
> +            scope.clearConnection();
Maybe put this in a `try/finally` to make sure it gets cleared if the test fails.

2024-10-30 18:01 UTC, labkey-adam commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServer2016Dialect.java
> +            scope.clearConnection();
@labkey-tchad The most recent version (what I merged earlier today) replaced the anonymous `DbScope` and `ConnectionWrapper` overrides with concrete subclasses. `TestScope` implements `AutoCloseable`, so the connection does get closed in a `try/finally`. Look it over and let me know if you have further feedback...

2024-10-30 19:25 UTC, labkey-tchad commented on bigiron/src/org/labkey/bigiron/mssql/MicrosoftSqlServer2016Dialect.java
> +            scope.clearConnection();
Oops. I was just looking at one commit instead of the entire PR.