Add the Ability to filter file uploads based on file extensions
LabKey/platform pull request #6043
Opened 2024-11-11 21:30 UTC by labkey-ians

#### Rationale
[Secure Issue 51524: Allowlist for acceptable types of file upload](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=51524)

#### Changes
- updated shared jsps
- Add allow list
- and extension checker to file uploads

2024-11-12 00:01 UTC, labkey-jeckels requested changes

2024-11-12 00:01 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/FileUtil.java
> +        String allowedExtensions = String.join("|", AppProps.getInstance().getAllowedExtensions()).replace(".", "\\.");
What about other special regex characters, like `-` or `(`?

This seems like a good candidate for a small unit test.

2024-11-12 00:01 UTC, labkey-jeckels commented on core/src/org/labkey/core/admin/ExternalServerType.java
> +                        This list is the set of file extensions that LabKey will allow through. Any extension that is not in this list will be rejected, this includes mulitple extensions. If the list
```suggestion
                        This list is the set of file extensions that LabKey will accept for uploads. Any extension that is not in this list will be rejected, this includes multiple extensions. For example, .gz is not sufficient to allow .tar.gz; you must specify .tar.gz. If the list is blank, then this check is ignored.
```

2024-11-12 00:01 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/FileUtil.java
> +        String badExtension = checkExtension(s);
This method is only invoked if the server has been configured to block these patterns, via a separate property. It's also only consulted for WebDav uploads.

The customer who raised this concern would want it to apply to all uploads, including attachments to issues, wikis, etc.

2024-11-12 00:01 UTC, labkey-jeckels commented on core/src/org/labkey/core/admin/AdminController.java
> +        if (ModuleLoader.getInstance().hasModule("Premium"))
The combo of checking for the premium module and the class/enum names on the next line is too much for me.

We could clean it up by making this a non-premium feature. I'm fine with that given the implementation approach.

2024-11-12 00:01 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/FileUtil.java
> +        String badExtension = checkExtension(s);
I think that means also checking in AntiVirusMultipartResolver.

2024-11-12 22:26 UTC, labkey-ians commented on core/src/org/labkey/core/admin/ExternalServerType.java
> +                        This list is the set of file extensions that LabKey will allow through. Any extension that is not in this list will be rejected, this includes mulitple extensions. If the list
updated

2024-11-12 22:27 UTC, labkey-ians commented on api/src/org/labkey/api/util/FileUtil.java
> +        String allowedExtensions = String.join("|", AppProps.getInstance().getAllowedExtensions()).replace(".", "\\.");
test added, using Pattern.quote()

2024-11-12 22:29 UTC, labkey-ians commented on api/src/org/labkey/api/util/FileUtil.java
> +        String badExtension = checkExtension(s);
Added it to the AntiVirusMultipartResolver. Its unclear to me how to best add this call to the Spring `StandardServletMultipartResolver`

2024-11-13 00:28 UTC, labkey-jeckels requested changes

2024-11-13 00:28 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/FileUtil.java
> +            assertNotNull("No extension matched unexpectedly", checkExtension("No extension", mockProps));
I hadn't considered files with no extension. I guess it's OK to reject them all at this point.

2024-11-13 00:28 UTC, labkey-jeckels commented on core/src/org/labkey/core/admin/ExternalServerType.java
> +                        This list is the set of file extensions that LabKey will accept for uploads. Any extension that is not in this list will be rejected, this includes multiple extensions. For ex
Typo in my suggestion: "is not sufficient to all" should be "is not sufficient to allow"

2024-11-13 00:28 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/FileUtil.java
>              return "Filename may not begin with any of these characters: -$";
We should pull the check of `AppProps.getInstance().isInvalidFilenameUploadBlocked()` out of `DavController.checkAllowedFileName()` and put it here around the prexisting set of checks. Otherwise, we're ignoring that setting.

2024-11-13 00:28 UTC, labkey-jeckels commented on core/src/org/labkey/core/webdav/DavController.java
> +                throw new IOException("The file extension is not allowed.");
This may reject the name unrelated to the exception. Let's use the message this call returns instead of hard-coding the error message

2024-11-13 00:28 UTC, labkey-jeckels commented on api/src/org/labkey/api/util/FileUtil.java
> +        String badExtension = checkExtension(s);
Looks like we'll need another subclass of `StandardServletMultipartResolver` that lives in the API module. The default implementation in AntiVirusProviderRegistry should return that new subclass, which looks at the file name. We can refactor `AntiVirusMultipartResolver` to inherit from the new subclass and reduce duplicated code.

2024-11-14 17:59 UTC, labkey-jeckels approved these changes

2024-11-14 21:29 UTC, labkey-matthewb commented on api/src/org/labkey/api/util/FileUtil.java
> +        if (extensionChecker == null)
When does this get cleared?  It seems very sticky.

2024-11-14 21:37 UTC, labkey-matthewb commented
Do we want to allow folder names to have "." in them?  Disallowing doesn't seem to be related to the original goal of the feature.

2024-11-14 23:23 UTC, labkey-matthewb requested changes

2024-11-14 23:23 UTC, labkey-matthewb commented on core/src/org/labkey/core/webdav/DavController.java
> +                throw new IOException(notAllowedMsg);
throw DavException in  the dav controller to get the file browser to display an expected UI.  Maybe use 409 SC_CONFLICT?  or 406 (SC_NOT_ACCEPTABLE)

2024-11-19 19:05 UTC, labkey-ians commented on api/src/org/labkey/api/util/FileUtil.java
> +        if (extensionChecker == null)
It only gets changed in setExtensionChecker which is called when the WritableAppProps.setAllowedFileExtensions is called when the new Allow List prop is saved or when the server is starting up

2024-11-19 19:17 UTC, labkey-matthewb commented on api/src/org/labkey/api/util/FileUtil.java
> +        if (extensionChecker == null)
I see.  The pattern confused me.  I would have expected a getExtensionCheck() that wrapped the null check.

2024-11-19 19:17 UTC, labkey-matthewb approved these changes

2024-11-20 00:07 UTC, merged