24.12 fb delete participant
LabKey/platform pull request #6054
Opened 2024-11-14 05:13 UTC by labkey-bpatel

#### Rationale

#### Related Pull Requests
- 

#### Changes
-

2024-11-16 00:07 UTC, labkey-jeckels requested changes

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +    <p>Select <%= h(subjectNounSingular.toLowerCase())%> you want to delete from this study.
```suggestion
    <p>Select <%= h(subjectNounSingular.toLowerCase())%> you want to delete from this study?
```

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                queryParam: 'query.ParticipantId~contains',
Should this use `subjectNounColName`?

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                       html: "Are you sure you want to delete " + <%=q(subjectNounSingular.toLowerCase())%> + " '" + participantIdToDelete + "'?"
Need to HTML encode.

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/controllers/StudyController.java
> +                    if (pgm.length == 1) //a participant is associated with only one group, so there should be only one row
The DB lets a participant belong to multiple groups. Why not delete them all?

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/controllers/StudyController.java
> +                return new ApiSimpleResponse("success", false);
I don't think the client will get the errors. Probably they should.

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/controllers/StudyController.java
> +            String participantIdColumnName = deleteParticipantForm.getParticipantIdColumnName();
There's no need to rely on the client to pass `participantIdColumnName` and `participantTableNamePrefix`. You're getting the `Study` in a few lines - you can just ask it.

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/controllers/StudyController.java
> +            List<String> lsids = Arrays.asList(ts.getArray(String.class));
I think you can simplify a bit by getting maps from the `TableSelector`. Then you don't need to translate the Strings into maps yourself.

2024-11-16 00:07 UTC, labkey-jeckels commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                        viewParticipantDataLink.update('<a class="labkey-text-link" href="' + LABKEY.ActionURL.buildURL('study', 'participant.view', null, { 'participantId': combo.getValue() }) + '"
In some places you hardcode `Participant` in the UI, and other places you use the study's subject noun. Seems like we should be consistent.

2024-11-18 23:50 UTC, labkey-klum commented on study/src/org/labkey/study/controllers/StudyController.java
> +            List<Map<String, Object>> keys = new ArrayList<>();
You probably don't need to declare this `Collection` since there will only be a single value

2024-11-18 23:52 UTC, labkey-klum commented on study/src/org/labkey/study/controllers/StudyController.java
> +            TableSelector ts = new TableSelector(ti, Collections.singleton("lsid"), new SimpleFilter(FieldKey.fromString(participantIdColumnName), participantId), null);
Consider swapping out the hard-coded string for `DatasetDomainKind.LSID`

2024-11-19 00:54 UTC, labkey-klum commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +            var viewParticipantDataLink = Ext4.create('Ext.Component', {
Perhaps a nicer pattern is to delegate the link rendering to a template instead of rewriting the entire anchor tag. We can also enable / disable the button and link if there is a selected participantID, currently you get a useless link until something is selected (same with the delete button).

```
            var viewParticipantDataLink = Ext4.create('Ext.Component', {
                tpl: new Ext4.XTemplate(
                        '<a class="labkey-text-link" href="{[this.getURL(values)]}" target="_blank">View Participant Data</a>',
                        {
                            getURL : function(values){
                                return LABKEY.ActionURL.buildURL('study', 'participant.view', null, { 'participantId': values.participantId })
                            }
                        }
                ),
                padding: '3 0 0 20',
                data: {partipantId : null},
                disabled: true
            });

            var participantCombo = Ext4.create('Ext.form.field.ComboBox',{
                name : 'participantCombo',
                store: this.participantStore,
                valueField : <%=q(subjectNounColName)%>,
                displayField : <%=q(subjectNounColName)%>,
                labelWidth : 120,
                labelSeparator: '',
                fieldLabel : (<%=q(subjectNounSingular)%> + " ID"),
                editable: true,
                queryMode: 'remote',
                minChars: 2,
                typeAhead: true,
                queryParam: 'query.ParticipantId~contains',
                listeners: {
                    change: function(combo, value) {
                        // Update link when a selection is made
                        viewParticipantDataLink.update({participantId : value});
                        viewParticipantDataLink.setDisabled(value === null);
                        deleteButton.setDisabled(value === null);
                    }
                }
            });
```

2024-11-19 00:55 UTC, labkey-klum commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                console.log("Deleting " + participantIdToDelete);
Left over from debugging?

2024-11-19 00:58 UTC, labkey-klum commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                var dialog = Ext4.create('Ext.window.Window', {
You should be able to simplify this interaction, I don't think you need to create a window and can just use a message box. I don't know if there is a lot to gain to not dismiss the window until after the Ajax request has completed since we show a success / error message anyway.
```
              Ext4.Msg.show({
                    title   : 'Confirmation',
                    msg     : "Are you sure you want to delete " + <%=q(subjectNounSingular.toLowerCase())%> + " '" + participantIdToDelete + "'?",
                    buttons : Ext4.MessageBox.YESNO,
                    icon    : Ext4.MessageBox.QUESTION,
                    fn      : function(id){
                        if (id === 'yes'){
                            Ext4.getBody().mask("Deleting...");
                            Ext4.Ajax.request({
                                url : LABKEY.ActionURL.buildURL("study", "deleteParticipant"),
                                method : 'POST',
                                jsonData : { participantIdColumnName : <%=q(subjectNounColName)%>, participantId : participantIdToDelete, tableNamePrefix: <%=q(subjectNounSingular)%> },
                                headers : {'Content-Type' : 'application/json'},
                                scope: this,
                                success: function() {
                                    Ext4.getBody().unmask();
                                    displayDoneChangingMessage("Success", "Successfully deleted " +  <%=q(subjectNounSingular)%> + " " + participantIdToDelete + '.');
                                    // Refresh the ComboBox store after deletion
                                    participantCombo.setValue(null);
                                    participantCombo.getStore().load();
                                },
                                failure: function(response, options){
                                    Ext4.getBody().unmask();
                                    LABKEY.Utils.displayAjaxErrorResponse(response, options, false, 'An error occurred:' + response.responseText);
                                },
                            });
                        }
                    }
                });
```

2024-11-21 01:14 UTC, labkey-bpatel commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +    <p>Select <%= h(subjectNounSingular.toLowerCase())%> you want to delete from this study.
Do we want this to be "Select Participant you want to delete from this study?" ?

2024-11-21 01:18 UTC, labkey-bpatel commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                queryParam: 'query.ParticipantId~contains',
I initially tested it with a non-EHR study, and appears to work for both EHR and non-EHR cases; so, it didn't occur to me to update it earlier. Now updated. Thanks!

2024-11-21 01:19 UTC, labkey-bpatel commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                       html: "Are you sure you want to delete " + <%=q(subjectNounSingular.toLowerCase())%> + " '" + participantIdToDelete + "'?"
ah my good friend HTML encode! done!

2024-11-21 01:24 UTC, labkey-bpatel commented on study/src/org/labkey/study/controllers/StudyController.java
> +                    if (pgm.length == 1) //a participant is associated with only one group, so there should be only one row
You are correct! Looks like I was mistaken about the participant group association, didn't realize it can be many to many.

2024-11-21 01:24 UTC, labkey-bpatel commented on study/src/org/labkey/study/controllers/StudyController.java
> +                return new ApiSimpleResponse("success", false);
Good point, now updated.

2024-11-21 01:25 UTC, labkey-bpatel commented on study/src/org/labkey/study/controllers/StudyController.java
> +            String participantIdColumnName = deleteParticipantForm.getParticipantIdColumnName();
Ah i see, now updated.

2024-11-21 01:27 UTC, labkey-bpatel commented on study/src/org/labkey/study/controllers/StudyController.java
> +            List<String> lsids = Arrays.asList(ts.getArray(String.class));
I wrote it how the steps worked in my head, but yup, can be simplified, now done

2024-11-21 01:30 UTC, labkey-bpatel commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                        viewParticipantDataLink.update('<a class="labkey-text-link" href="' + LABKEY.ActionURL.buildURL('study', 'participant.view', null, { 'participantId': combo.getValue() }) + '"
Agreed, fixed

2024-11-21 01:30 UTC, labkey-bpatel commented on study/src/org/labkey/study/controllers/StudyController.java
> +            List<Map<String, Object>> keys = new ArrayList<>();
True, now removed and adjusted accordingly

2024-11-21 01:30 UTC, labkey-bpatel commented on study/src/org/labkey/study/controllers/StudyController.java
> +            TableSelector ts = new TableSelector(ti, Collections.singleton("lsid"), new SimpleFilter(FieldKey.fromString(participantIdColumnName), participantId), null);
Ah, that's good to know! Updated, thanks!

2024-11-21 01:31 UTC, labkey-bpatel commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                console.log("Deleting " + participantIdToDelete);
removed

2024-11-21 17:15 UTC, labkey-jeckels commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +    <p>Select <%= h(subjectNounSingular.toLowerCase())%> you want to delete from this study.
Nevermind. I misread the sentence and was thinking this was a confirmation question.

2024-11-22 16:54 UTC, labkey-klum approved these changes
You probably know this but the 24.12 prefix on the FB name isn't necessary if you are targeting develop.

2024-11-22 17:04 UTC, labkey-jeckels approved these changes
One more encoding request but no need for additional review.

2024-11-22 17:04 UTC, labkey-jeckels commented on study/src/org/labkey/study/view/manageAlternateIds.jsp
> +                        '<a class="labkey-text-link" href="{[this.getURL(values)]}" target="_blank">View ' + <%=q(subjectNounSingular)%> + ' Data</a>',
`subjectNounSingular` should be HTML-encoded before being passed to `q()`

2024-11-22 17:34 UTC, labkey-bpatel commented
> You probably know this but the 24.12 prefix on the FB name isn't necessary if you are targeting develop.

Yup, I wasn't sure how long this story would take since I was not prioritizing it over other requests, so had it prefixed 24.12 just in case.

2024-11-22 22:04 UTC, merged