Result level exclusions for plate based assays
LabKey/platform pull request #6060
Opened 2024-11-16 00:06 UTC by labkey-klum

#### Rationale
Adds initial support to exclude wells from certain operations for plate enabled assays. Assay results will include a `state` field which can be set to a value in the `core.DataState` table. The data state will determine what operations are allowed for values in that row. Initially only a single `excluded` data state will be supported but others can be added later. Also, currently the excluded state will prevent the well from participating in any replicate statistical calculations.

Data states will be scoped to the project level. An upgrade script was added to update the result domain for any plate enabled assays in a LKB folder.

#### Related Pull Requests
https://github.com/LabKey/limsModules/pull/925

2024-11-19 21:06 UTC, cnathe approved these changes

2024-11-19 21:06 UTC, cnathe commented on api/src/org/labkey/api/assay/plate/PlateDataStateManager.java
> +        analysis("included for any data or statistical analysis, curve fitting etc");
nice, I like that this is a more general DataOperation that can be checked rather than just having the AssayPlateMetadataServiceImpl check for the "Excluded" state directly.

2024-11-19 21:06 UTC, cnathe commented on api/src/org/labkey/api/assay/plate/PlateDataStateManager.java
> +        return true;
this works to prevent delete of this state. the error message is a little odd in that I didn't actually have any usages of the state yet, but I think that is fine.

2024-11-19 21:06 UTC, cnathe commented on api/src/org/labkey/api/assay/plate/PlateDataStateManager.java
> +        return stateType != null && stateType.getPermittedOps().contains(operation);
as mentioned in the manual testing "issues found", this looks to be excluding rows from replicate calculations if they have a non-Excluded state (i.e. Available, Locked). Is that expected / wanted behavior?

2024-11-20 15:07 UTC, cnathe requested changes

2024-11-20 15:07 UTC, cnathe commented on api/src/org/labkey/api/assay/plate/PlateDataStateManager.java
> +        return true;
see manual test plan. looks like this is preventing any core.DataState from being deleted (even those from sample statuses for example).

2024-11-20 18:24 UTC, labkey-klum commented on api/src/org/labkey/api/assay/plate/PlateDataStateManager.java
> +        return stateType != null && stateType.getPermittedOps().contains(operation);
I think for now since we will be limiting what data state can be added to the assay row for the near term. This maybe speaks to adding some validation on insert / update regarding what is a valid state?

2024-11-20 18:25 UTC, labkey-klum commented on api/src/org/labkey/api/assay/plate/PlateDataStateManager.java
> +        return true;
I'll update, it probably just needs to be conditionalized to be one of the states we care about.

2024-11-21 22:37 UTC, cnathe approved these changes
A couple of minor comments, but otherwise the fixes for the issues mentioned in the test plan check out. Looks good.

2024-11-21 22:37 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                    throw new ValidationException(String.format("The data state : %s is not valid for this assay", state.getStateType()));
I think we want to use `state.getLabel()` in the error message instead of `state.getStateType()`.

Also, the format of the error message seems odd to me with the colon in it. I'd suggest: 
```suggestion
                    throw new ValidationException(String.format("The data state '%s' is not valid for this assay.", state.getLabel()));
```

2024-11-21 22:37 UTC, cnathe commented on assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
> +                            throw new ExperimentException(String.format("No data states for the rowID : %d was found", stateRowId));
as mentioned in the other comment, I'd suggest removing the colon from the error message and adding a period.
```suggestion
                            throw new ExperimentException(String.format("No data states for the rowID %d was found.", stateRowId));
```

2024-11-22 16:52 UTC, merged