Chart builder support for Trendline option in line chart
LabKey/platform pull request #6100
Opened 2024-11-25 19:00 UTC by cnathe

#### Rationale
Adding a chart builder feature to allow selection of a line chart Trendline option: Linear Regression, 3PL, 4PL, etc. This will be in addition to the default line chart trendline option of "Point-to-Point". Note that this new option will only show in the UI for LIMS products. Also note that the nonlinear curve fit options are only available for assay data. Other data types will see the Linear Regression and Polynomial types.

#### Related Pull Requests
- https://github.com/LabKey/labkey-ui-components/pull/1650

#### Changes
- GenericChartHelper support for querying and rendering line chart config layers based on trendline config
- query for per-series trendline data using new premium-calculateCurveFit API
- render new Path layer for each trendline series data
- queryTrendlineData() to be called during queryChartData()
- Add trendline hover text to show curve fit params and stats
- Add Trendline Option to Line Charts for LKS Chart Wizard
- Filter trendline options based on schema prefix (i.e. linear vs non-linear options)
- LKS chart wizard trendline option to be LIMS only (check feature flag in moduleContext)
- null checks for vis sort fn string checks

2024-11-25 19:36 UTC, cnathe commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +    }
@labkey-klum can you verify these equations against the server side ParameterCurveFit (and related classes) fitCurve() method?

2024-11-25 20:36 UTC, labkey-klum commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +    }
Yup, those match the server side code.

2024-11-25 23:45 UTC, labkey-alan requested changes
Overall this looks good, but I do think there are some changes we should make

2024-11-25 23:45 UTC, labkey-alan commented on core/webapp/vis/src/utils.js
> +    var aIsEmptyCategory = a && a.indexOf !== undefined && (a.indexOf("Not in ") == 0 || a == '[Blank]'),
would it maybe be more correct to do something like:

```suggestion
    var aIsEmptyCategory = a && typeof a === 'string' && (a.indexOf("Not in ") == 0 || a == '[Blank]'),
```

2024-11-25 23:45 UTC, labkey-alan commented on core/webapp/vis/src/utils.js
> +    if (aso.toLowerCase === undefined || bso.toLowerCase === undefined) return 0;
```suggestion
    if (typeof aso !== 'string' || typeof bso !== 'string') return 0;
```

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/chartWizard/chartTypeDialog/trendlineField.js
> +            }
```suggestion
            const data = this.options.map((key) => {
                const option = LABKEY.vis.GenericChartHelper.TRENDLINE_OPTIONS[key];
                return [option.value, option.label, option.showMin, option.showMax, option.schemaPrefix];
            });
```

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/chartWizard/chartTypeDialog/trendlineField.js
> +            }
I'm fairly certain we can use let/const in our normal JS files now. All browsers support these keywords and IIRC we updated our minifier to support the newer syntax.

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/chartWizard/chartTypeDialog/trendlineField.js
> +        return values;
```suggestion
        return {
            trendlineType: this.getTrendlineTypeCombo().getValue()
        };
```

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/chartWizard/chartTypeDialog/trendlineField.js
> +    {
1. I'm assuming it's just our Ext "standard" to use `initComponent : function ()` instead of `initComponent: function()`, is that correct?
2. Nit: The opening paren is on a new line here, but elsewhere below it's on the same line as `function()`, so we should probably put it on the same line as function. However, it looks like in other files we have it on the next line. I'm not sure it matters too much, as long as we're consistent within the same file.

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/chartWizard/chartTypePanel.js
> +            }
```suggestion
            let hidden = false;
            if (field.name === 'trendline') {
                const hasChartBuilding = LABKEY.getModuleContext('core').productFeatures?.indexOf('ChartBuilding') !== -1;
                const hasPremium = LABKEY.getModuleContext('api').moduleNames.indexOf('premium') !== -1;
                hidden = !hasPremium || !hasChartBuilding;
            }
```

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +                    $.each(trendlineData, async function (idx, trendline) {
Two things:

1. This doesn't need to be async, since we're not awaiting anything
2. We should be able to just do `trendlineData.forEach((trendline, idx) => {});`, I know we use jQuery elsewhere in this file for historical reasons, but it's not really needed anymore, so I am not sure we should add more jQuery code.

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +        $.each(trendline.data.curveFit, function (key, value) {
Same as my previous comment, and for all below, I don't think we should use `$.each()`, as it's no longer necessary, and it's more verbose. I don't think we need to be going out of our way to remove existing usages, but we shouldn't add new ones.

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +    var hasPremiumModule = function() {
For this definition, and all other new ones in this PR I think we should use `let` and `const` where appropriate, and avoid `var`, as `var` has several downsides, and we're no longer limited by our minifier.

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +            _queryTrendlineData(trendlineConfig, xName, yMeasures[0].name).then(function() {
It's a little odd that `_queryTrendLineData` is `async`, but this method isn't, and is using promises.

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +    var _querySeriesTrendlineData = async function(trendlineConfig, seriesData, xName, yName) {
This doesn't need to be `async function`, because it's using Promise to wrap `Ajax.request`

2024-11-25 23:45 UTC, labkey-alan commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +            queryTrendlineData(chartConfig, measureStore.records(), function(trendlineData) {
I think we should make `queryTrendlineData` an async function that returns the data, and make this success callback an async function. Then we can skip having to pass a callback to `queryTrendlineData`

2024-11-26 14:55 UTC, cnathe commented on core/webapp/vis/src/utils.js
> +    var aIsEmptyCategory = a && a.indexOf !== undefined && (a.indexOf("Not in ") == 0 || a == '[Blank]'),
yup, done

2024-11-26 14:57 UTC, cnathe commented on core/webapp/vis/src/utils.js
> +    if (aso.toLowerCase === undefined || bso.toLowerCase === undefined) return 0;
done

2024-11-26 15:09 UTC, cnathe commented on visualization/resources/web/vis/chartWizard/chartTypeDialog/trendlineField.js
> +            }
yes, I verified by running `./gradlew compressClientLibs` locally

2024-11-26 15:09 UTC, cnathe commented on visualization/resources/web/vis/chartWizard/chartTypeDialog/trendlineField.js
> +        return values;
done

2024-11-26 15:11 UTC, cnathe commented on visualization/resources/web/vis/chartWizard/chartTypeDialog/trendlineField.js
> +    {
I don't now that we were ever very good about using "standards" or linting back in the Ext4 days. I've updated this file to remove the space before the colon and to move the opening paren to the same line.

2024-11-26 15:18 UTC, cnathe commented on visualization/resources/web/vis/chartWizard/chartTypePanel.js
> +            }
done

2024-11-26 15:20 UTC, cnathe commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +                    $.each(trendlineData, async function (idx, trendline) {
done and done

2024-11-26 15:28 UTC, cnathe commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +        $.each(trendline.data.curveFit, function (key, value) {
done

2024-11-26 15:29 UTC, cnathe commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +    var hasPremiumModule = function() {
done

2024-11-26 15:31 UTC, cnathe commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +    var _querySeriesTrendlineData = async function(trendlineConfig, seriesData, xName, yName) {
done

2024-11-26 15:35 UTC, cnathe commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +            _queryTrendlineData(trendlineConfig, xName, yMeasures[0].name).then(function() {
I switched this to async / await to match

2024-11-26 15:47 UTC, cnathe commented on visualization/resources/web/vis/genericChart/genericChartHelper.js
> +            queryTrendlineData(chartConfig, measureStore.records(), function(trendlineData) {
done

2024-11-26 16:24 UTC, labkey-alan approved these changes
Looks good

2024-12-04 14:50 UTC, merged