Avoid returning FK metadata for a malformed TableInfo
LabKey/platform pull request #6128
Opened 2024-12-05 01:28 UTC by labkey-jeckels

#### Rationale
https://www.labkey.org/_mothership/mothership-showStackTraceDetail.view?exceptionStackTraceId=39156

```
Stack Trace	
org.json.JSONException: JSONObject["queryName"] not found.
	at org.json.JSONObject.get(JSONObject.java:596)
	at org.json.JSONObject.getString(JSONObject.java:883)
	at org.labkey.query.persist.QueryManager.validateFk(QueryManager.java:826)
	at org.labkey.query.persist.QueryManager.validateColumn(QueryManager.java:768)
	at org.labkey.query.persist.QueryManager.validateQueryMetadata(QueryManager.java:749)
	at org.labkey.query.controllers.QueryController$ValidateQueryMetadataAction.execute(QueryController.java:7338)
	at org.labkey.query.controllers.QueryController$ValidateQueryMetadataAction.execute(QueryController.java:7299)
	at org.labkey.api.action.BaseApiAction.handlePost(BaseApiAction.java:239)
	at org.labkey.api.action.ReadOnlyApiAction.handleGet(ReadOnlyApiAction.java:34)
```

#### Changes
- Bail out if we have a null query or schema name

2024-12-05 01:28 UTC, labkey-jeckels commented
@labkey-matthewb do you think we should handle this differently?

2024-12-05 20:33 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/JsonWriter.java
> +            if (queryName == null || schemaName == null)
This isn't an error.  There are many foreign keys that don't point at tables in the visible user schemas.  The FK is only required to support getLookupTableInfo().  These two properties are meant to help the UI recognize that it might already have the meta-data of the lookup table cached.

2024-12-05 20:35 UTC, labkey-matthewb requested changes
There are many cases where we want to show that FKs exist that don't point to public tables (e.g. lineage lookups)

2024-12-06 00:00 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/JsonWriter.java
> +            if (queryName == null || schemaName == null)
OK. What do you suggest in we do with a null `queryName` in `QueryManager.validateFk()`? Show a warning? Treat it as healthy and skip trying to resolve the `TableInfo` around line 855 in `QueryManager`?

We've been getting this exception for a while now. https://www.labkey.org/_mothership/project-begin.view?ExceptionSummary.StackTrace~contains=org.json.JSONException%3A%20JSONObject%5B%22queryName%22%5D%20not%20found.

2024-12-06 20:25 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/JsonWriter.java
> +            if (queryName == null || schemaName == null)
I'm pretty sure the schema browser/customize view use this information.  The fix might be for the validateQuery to not try to validate queries that are not marked "public".  And maybe use JSONObject.optString() to avoid throwing an unhandled exception.

2024-12-06 21:02 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/JsonWriter.java
> +            if (queryName == null || schemaName == null)
It's already warning about non-public lookup targets. I made it not do any validation if there's no `queryName`

2024-12-09 19:44 UTC, labkey-jeckels commented on api/src/org/labkey/api/data/JsonWriter.java
> +            if (queryName == null || schemaName == null)
@labkey-matthewb can you take a look at the latest?

2024-12-09 20:03 UTC, labkey-matthewb approved these changes

2024-12-09 20:40 UTC, merged