Add restrictions on names of domains
LabKey/platform pull request #6140
Opened 2024-12-10 02:47 UTC by XingY

#### Rationale

#### Related Pull Requests
- 

#### Changes
-

2024-12-11 22:31 UTC, labkey-susanh requested changes

2024-12-11 22:31 UTC, labkey-susanh commented on api/src/org/labkey/api/data/NameGenerator.java
> +                    // TODO, parents broken
Still TODO?

2024-12-11 22:31 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
> +    public boolean supportNamingPattern()
```suggestion
    public boolean supportsNamingPattern()
```

2024-12-11 22:31 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +            return "Domain name must not be blank";
```suggestion
            return "Domain name must not be blank.";
```

2024-12-11 22:31 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +            return prefix + "Domain name must start with a letter or a number character.";
```suggestion
            return prefix + "Domain name must start with a letter or a number.";
```
(or it could be "must not start with a letter or a digit")

2024-12-11 22:31 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        //final String legalChars = " -_()&/.:";
Remove?

2024-12-11 22:31 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +    public static @Nullable String validateDomainName(@NotNull String domainName, String kindName, boolean supportNamingPattern)
```suggestion
    public static @Nullable String validateDomainName(@NotNull String domainName, String kindName, boolean supportsNamingPattern)
```

2024-12-11 22:31 UTC, labkey-susanh commented on api/src/org/labkey/api/exp/property/DomainUtil.java
> +        String prefix = "Invalid " + kindName + " name. ";
```suggestion
        String prefix = "Invalid " + kindName + " name '" + domainName + "'.";
```

2024-12-11 22:31 UTC, labkey-susanh commented on study/test/src/org/labkey/test/tests/study/StudyDatasetsTest.java
> +    protected void renameDataset(String error, String orgName, String newName, String orgLabel, String newLabel, String... fieldNames)
```suggestion
    protected void renameDataset(@Nullable String error, String orgName, String newName, String orgLabel, String newLabel, String... fieldNames)
```

2024-12-13 00:46 UTC, XingY commented on api/src/org/labkey/api/data/NameGenerator.java
> +                    // TODO, parents broken
fixed

2024-12-13 14:32 UTC, labkey-susanh approved these changes

2024-12-16 15:05 UTC, merged