Customizable File Templates for Sources, Sample Types & Assay Designs
LabKey/platform pull request #6167
Opened 2024-12-20 20:30 UTC by XingY

#### Rationale

#### Related Pull Requests
- 

#### Changes
-

2024-12-26 23:04 UTC, cnathe requested changes

2024-12-26 23:04 UTC, cnathe commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +        return getKindName();
do we want toLowerCase() for these? maybe it doesn't matter but the other dir names seem to all be lowercase.

2024-12-26 23:04 UTC, cnathe commented on api/src/org/labkey/api/util/FileUtil.java
> +    private static final String[] DECODED = {"%", "%#", "&", "@", "~", "{", "}", "[", "]", "+", " "};
can the if/elseif block in the `encodeForURL` for loop above be refactored to use these String[] objects? basically to a single if statement like "if character exists in DECODED, replace with the same index in ENCODED".

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +        {
there is a lot of validation that is happening in the `getUploadedTemplates()` method and the 'execute()` method. Can / should any of that be moved to here?

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +                throw new IllegalStateException("Unable to load file service");
```suggestion
                throw new IllegalStateException("Unable to load file service.");

```

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +            List<Pair<String, String>> updatedTemplates = getUploadedTemplates(form, kind);
we call `getUploadedTemplates` here, which will end up saving the files to the filesystem. And then we do a few more validation checks that aren't related to the files. If one of those throws, the files will stay on the filesystem right? Should we move this call after the validation checks (down towards line 703 where it is used)?

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +                throw new IllegalArgumentException("Domain '" + domainURI + "' not found");
```suggestion
                throw new IllegalArgumentException("Domain '" + domainURI + "' not found.");

```

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +                throw new NotFoundException("Could not find the specified schema in the folder '" + container.getPath() + "'");
```suggestion
                throw new NotFoundException("Could not find the specified schema in the folder '" + container.getPath() + "'.");

```

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +                throw new NotFoundException("Could not find the specified query in the schema '" + form.getSchemaName() + "'");
```suggestion
                throw new NotFoundException("Could not find the specified query in the schema '" + form.getSchemaName() + "'.");

```

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +                throw new NotFoundException("Could not find the specified query in the schema '" + form.getSchemaName() + "'");
```suggestion
                throw new NotFoundException("Could not find the specified query in the schema '" + form.getSchemaName() + "'.");

```

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +            if (!updatedTemplates.equals(existingCustomTemplates))
since these vars are both ArrayLists, will they ever be considered equal? From the UI, I opened the manage templates modal for a sample type that already had 2 custom tempaltes > edited the label for one and then put the label back to what it was > clicked Save. The code still went into this if statement.

2024-12-26 23:04 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +                }
I don't love this string replacement in the XML. Does it not work to do something like what MetadataTableJSON.java does where it uses `parseDocument(queryDef.getMetaData())` to get the current document > call something like `xmlTable.setImportTemplates(...)` to set the new values > then do the `queryDef.setMetadataXml(metadata)` and save below?

2024-12-27 00:52 UTC, XingY commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +                }
Good point. moved this action to query controller and updated to use xml parser/setting instead.

2024-12-27 00:53 UTC, XingY commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +            if (!updatedTemplates.equals(existingCustomTemplates))
Hmm.. for this scenario described, it doesn't go inside the if block for me.

2024-12-27 00:53 UTC, XingY commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +            List<Pair<String, String>> updatedTemplates = getUploadedTemplates(form, kind);
updated

2024-12-27 00:53 UTC, XingY commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +        {
moved to validate

2024-12-27 00:53 UTC, XingY commented on api/src/org/labkey/api/util/FileUtil.java
> +    private static final String[] DECODED = {"%", "%#", "&", "@", "~", "{", "}", "[", "]", "+", " "};
good point. updated

2024-12-30 15:00 UTC, cnathe approved these changes

2024-12-30 15:00 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +                    queryDef = QueryManager.get().getQueryDef(container, schemaName, queryName, false);
queryDef is always null here so not sure that if statement is needed. 
```suggestion
                QueryDef queryDef = QueryManager.get().getQueryDef(container, schemaName, queryName, false);

```

2024-12-30 20:37 UTC, merged