[CODE REVIEW] 6498: MultiAuthentication UI Work
LabKey/platform pull request #670
Opened 2019-12-12 01:14 UTC by RosalineP

(For comments and info, see email)

2019-12-14 00:20 UTC, labkey-alan requested changes
I've added a lot of requested changes, nothing major, mostly small details that I think overall will make a big difference. In general we shouldn't be using `<br />`, `<hr />`, or `style={}`, and should instead use CSS. We should also add .DS_Store to the .gitignore file, and also remove the ones currently checked in.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        this.savePls = this.savePls.bind(this);
You can get rid of the need to bind functions in the constructor if you use the "fat arrow" function syntax when defining a function. So instead of something like:

```
function savePls() {
    // stuff goes here
}
```

You can do:

```
savePls = () => {
    // stuff goes here
}
```

The biggest convenience provided by "fat arrow" functions is automatic binding to `this`, which 99% of the time is what you want.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +    savePls() {
What does savePls mean? This method name is confusing to me. Is there a more appropriate name we could use?

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        Ajax.request({
I would recommend making a separate method that is named that implements this Ajax request, and then make the body of componentDidMount call that method. I know it seems like an arbitrary thing to do, but offhand I have no clue what this Ajax request is for, so by putting it in a named function it will be more clear as to what we're doing here.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            ...prevState,
If you're only touching dirty you don't need `...prevState`, and you don't need to do `dirty: dirty`. Instead all you need to do is `this.setState(() => ({ dirty }));`

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        let aProps = Object.getOwnPropertyNames(a);
Use const for variables you don't re-assign, and use `Object.keys` instead.

```
const aProps = Object.keys(a);
```

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        for (var i = 0; i < aProps.length; i++) {
Don't use a for loop here. Instead, use `Array.some()`. 

```
return aProps.some((key) => {
    return a[key] !== b[key];
});
```

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        console.log(this.state);
Don't console.log, though I'm assuming we just need to actually implement this?

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            ...prevState,
You don't need `...prevState`.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        {
Curly braces should be on the same line as the if statement.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        {
Also this if statement could be the first thing done in the function.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +    reorder = (list, startIndex, endIndex) => {
This method should be implemented differently. I think we might have some helpers around for this, if not something like lodash probably does as well. At a minimum, if we decide to implement this ourselves it should not be using splice. Never use splice, only use slice.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +    handleChangeToPrimary(event) {
I'm trying to figure out what this method does, it looks like we want to change the attribute of an object that is in a list. Immutable is not the answer here unless the object is already an immutable object, and we're going to return a modified immutable object. But we're not doing that here, we're just using immutable as a convenience to manipulate the object, then converting it back to a regular JS object. We should pick one. Here is what I would do, in pseudo code:

```
const items = this.state.singSignOnAuth;
const item = { ...items[id], [name]: value };
const head = items.slice(0, id);
const tail = items.slice(id);
this.setState({ primary: [...head, item, ...tail] });
```

I think that is correct, but I'm not entirely sure what the purpose of this method is. It feels weird to be manipulating `this.state.singleSignOnAuth` but stashing the changes as `primary` on `this.state` via `this.setState`.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        const l = List(this.state[stateSection]);
See my comment above about `handleChangToPrimary`

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        this.setState(prevState => ({
I would flip this: first call Ajax.request, then when it returns, confirming the item is deleted, then remove it from state.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                {this.state.dirty && <Alert>You have unsaved changes to your authentication configurations. Hit "Save and Finish" to apply these changes.</Alert>}
This line is much too long.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            <div style={{minWidth:"1100px"}}>
Unless absolutely necessary, do not use `style`. Always use CSS class names to style your components.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/authenticationConfiguration.scss
> +  user-select: none;
Is there a reason we want a `.noHighlight` class? This disables a user from selecting text, which in my experience there is no need for. If anything it makes it more difficult for users to open issue requests because if they have a problem with a component that is rendering text they cannot highlight they'll be required to manually type in the text they're seeing.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +
Way too much whitespace after the imports. Also, is the todo below still relevant?

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +        let primary = this.props.primary;
Unless you are re-assigning the values of these variables you should not be using `let`. Use `const`.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                    <a style={{float: "right"}} href={"https://www.labkey.org/Documentation/wiki-page.view?name=authenticationModule&_docid=wiki%3A32d70b80-ed56-1034-b734-fe851e088836"} > Get help wi
This line is much too long. We should factor out the URL to be a constant defined near the top of this file, or if we have a useful constants file put it in there.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                    <br/><br/>
We shouldn't need to use `<br />`. Instead, use CSS.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                    <strong> Labkey Login Form Authentications </strong>
We probably don't need to use `<strong>`, and instead should use some CSS.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                    <a style={{float: "right"}} href={"https://www.labkey.org/Documentation/wiki-page.view?name=authenticationModule&_docid=wiki%3A32d70b80-ed56-1034-b734-fe851e088836"} > Get help wi
Also, do not use style attributes. Please use CSS.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        {this.props.canEdit &&
This is much too complex to be inside of a block of JSX. This whole block of code is hard to read. We should factor this stuff out into a variable called `dropDownBody` or something similar, so the body of this component can just be `{dropDownBody}`. Switching between JS and JSX multiple times in a block is confusing, not very readable, and should be avoided.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                                {(loginFormAuth && this.props.canEdit)
This block should be converted to a variable called `primaryAuthTab` and the body of this div should just be `{primaryAuthTab}`

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                            <div className={"auth-tab"}>
`<div className={"auth-tab"}>` and be `<div className="auth-tab">`

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                                return (<div> Single Sign On Authentications (SSOs) allow the use of one set of login credentials that are authenticated by the third party service provider (e.g. Goog
This line is much too long.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                    <hr/>
We probably shouldn't be using `<hr/>`, and instead should be using a CSS class that defines `border`, `border-bottom`, or something similar.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                                {(secondary && this.props.canEdit)
This block should be converted to a variable called `secondaryAuthTab` and the body of this div should just be `{secondaryAuthTab}`.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        enabled={item.enabled ? "Enabled" : "Disabled"}
To me a variable called `enabled` implies it is a boolean. This looks to be taking text. Maybe it should be a boolean, and the `SimpleAuthRow` component should be in charge of rendering "Enabled" or "Disabled" based on the value.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        edit={moreInfoIcon}
`edit` should probably be called `editIcon`.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +
unnecessary whitespace

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +
unnecessary whitespace

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +}
Files should end in a blank line.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/ConfigurationModal.tsx
> +export default class ConfigurationModal extends React.PureComponent<any, ConfigurationModalProps> {
There should be a line of white space between the interface and class definitions.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/ConfigurationModal.tsx
> +
too much whitespace between imports and body of file

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/ConfigurationModal.tsx
> +                            onClick={() => this.props.closeModal()}
You can probably just make this:

`onClick={this.props.closeModal}`

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +        return(
This render function is much too complex. It swaps between JSX/JS 9 times.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                        key={index.toString()}
You probably don't need to call index.toString() here. Could just pass `key={index}`

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            switch (field.type) {
The indentation for the code in this switch statement is not quite right. What I typically do in these cases, and what a lot of the community seems to do is something like this:

```
return (
    <TextInput
        key={index}
        className="bottom-margin"
        // etc.
    />
);
```

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/EditableAuthRow.tsx
> +// figure out TS typing for a function
There are several ways:

```
interface Example {
    foo: Function // basically says this can be any function at all.
    bar: (arg1: number, arg2: string) => string  // This is the syntax for defining a function with typed args and a return type.
}
```

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/EditableAuthRow.tsx
> +                onClick={() => this.props.handlePrimaryToggle(this.props.enabled, this.props.id, this.props.stateSection)}
Line much too long.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/EditableAuthRow.tsx
> +class LightupHandle extends React.Component<HandleProps, HandleState>{
If your component is stateless you don't have to define a state type at all. This can be:

`React.Component<HandleProps>`

Also, this should be a PureComponent.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/FACheckBox.tsx
> +import * as React from 'react'
Please use:

`import React from 'react';` 

1. This is the syntax recommended by the React team.
2. Semicolons are not optional.
3. The react team also recommends importing individual items from React as well, so I would do `import React, { PureComponent } from 'react';`, then change `React.PureComponent` to `PureComponent`

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/GlobalAuthConfigs.tsx
> +            {id: "AutoCreateAccounts", text: "Auto-create authenticated users"}];
The trailing `];` should be on its own line, and all items including the last item should end with `,`.

2019-12-14 00:20 UTC, labkey-alan commented on core/src/client/components/GlobalAuthConfigs.tsx
> +                {rowTexts.map((text) => (
Instead of hard coding the `RowTexts` variable at the top of render, and mapping over them inside of JSX you should define `rowTexts` as a constant near the top of the file, then define `const rowTexts = ROW_TEXTS.map()` at the top of render, and put it in the JSX as `{rowTexts}`. It will be much more readable this way.

2019-12-14 00:28 UTC, labkey-alan commented
@cnathe I'm assuming now that @labkey/dependencies is gone just having a dependency on ui-components is good enough correct?

2019-12-16 19:43 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        this.savePls = this.savePls.bind(this);
Oh, awesome -- updated!

2019-12-16 19:43 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +    savePls() {
Oh, this was easy to miss, but I had a '// Testing functions' note in the constructor's function bindings -- savePls is just being used for testing and will definitely not make it to the final functions

2019-12-16 19:43 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        Ajax.request({
Good point, done

2019-12-16 19:43 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            ...prevState,
Oh, right! Done

2019-12-16 19:43 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        let aProps = Object.getOwnPropertyNames(a);
Done

2019-12-16 19:44 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        console.log(this.state);
Yup, correct! This is intended to be the save for the enabled/disabled toggles on the individual rows right now, and that form doesn't currently exist

2019-12-16 19:44 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        {
Done

2019-12-16 19:44 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            <div style={{minWidth:"1100px"}}>
Noted, in my email!

2019-12-16 19:44 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/authenticationConfiguration.scss
> +  user-select: none;
This style is used specifically for the FACheckBox component, which highlights weirdly if a user clicks a checkbox moderately quickly. Users will still be able to highlight and copy+paste surrounding text 👍

2019-12-16 19:44 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +
Fixed -- some of them, yup, but pruned out the done todos

2019-12-16 19:44 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +        let primary = this.props.primary;
Done

2019-12-16 19:53 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                {this.state.dirty && <Alert>You have unsaved changes to your authentication configurations. Hit "Save and Finish" to apply these changes.</Alert>}
Fixed

2019-12-16 20:04 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        {this.props.canEdit &&
Ah, good points -- fixed!

2019-12-16 20:08 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                                {(loginFormAuth && this.props.canEdit)
Done

2019-12-16 20:10 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                            <div className={"auth-tab"}>
Oops, yup. Fixed

2019-12-16 20:10 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                                return (<div> Single Sign On Authentications (SSOs) allow the use of one set of login credentials that are authenticated by the third party service provider (e.g. Goog
Fixed

2019-12-16 20:13 UTC, RosalineP commented on core/src/client/components/EditableAuthRow.tsx
> +class LightupHandle extends React.Component<HandleProps, HandleState>{
Gotcha, done!

2019-12-16 20:16 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +}
Done

2019-12-16 20:16 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +
Fixed

2019-12-16 20:16 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +
Fixed

2019-12-16 20:38 UTC, RosalineP commented on core/src/client/components/FACheckBox.tsx
> +import * as React from 'react'
Gotcha -- fixed

2019-12-16 20:38 UTC, RosalineP commented on core/src/client/components/GlobalAuthConfigs.tsx
> +            {id: "AutoCreateAccounts", text: "Auto-create authenticated users"}];
Right -- fixed

2019-12-16 20:39 UTC, RosalineP commented on core/src/client/components/ConfigurationModal.tsx
> +
Fixed

2019-12-16 20:47 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        edit={moreInfoIcon}
Done

2019-12-16 20:47 UTC, RosalineP commented on core/src/client/components/ConfigurationModal.tsx
> +export default class ConfigurationModal extends React.PureComponent<any, ConfigurationModalProps> {
Fixed

2019-12-16 21:06 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        enabled={item.enabled ? "Enabled" : "Disabled"}
Thoughts on this?: 
The enabled prop sometimes takes a jsx (an enabled toggle) to display, and sometimes only needs to display text ('enabled' or 'disabled'). Is that structure acceptable style? 
Would changing the variable name to enabledDisplay or such help clear up the confusing seems-like-boolean implication?

2019-12-16 21:11 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                                {(secondary && this.props.canEdit)
Done

2019-12-16 21:14 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            ...prevState,
Q: Dynamic key names without the ...prevState brings up TS errors for me. Proper way to resolve?

2019-12-16 21:17 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                    <a style={{float: "right"}} href={"https://www.labkey.org/Documentation/wiki-page.view?name=authenticationModule&_docid=wiki%3A32d70b80-ed56-1034-b734-fe851e088836"} > Get help wi
Fixed! (Inline style issue noted in prev comment)

2019-12-16 21:19 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            switch (field.type) {
Gotcha! Fixed

2019-12-16 21:20 UTC, RosalineP commented on core/src/client/components/EditableAuthRow.tsx
> +                onClick={() => this.props.handlePrimaryToggle(this.props.enabled, this.props.id, this.props.stateSection)}
Q: (Check if new indenting is good)

2019-12-16 21:24 UTC, RosalineP commented on core/src/client/components/DragAndDropPane.tsx
> +        return(
Q: Yeah, pretty gross. Some of it can be taken apart, and some of it is due to the way Beautiful Drag n Drop is structured. Good candidate to talk about ways to make this bit cleaner + more intelligible.

2019-12-16 21:28 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                        key={index.toString()}
Fixed!

2019-12-16 21:31 UTC, RosalineP commented on core/src/client/components/EditableAuthRow.tsx
> +                onClick={() => this.props.handlePrimaryToggle(this.props.enabled, this.props.id, this.props.stateSection)}
Q: (Recommended linter?)

2019-12-16 21:36 UTC, RosalineP commented on core/src/client/components/GlobalAuthConfigs.tsx
> +                {rowTexts.map((text) => (
Ah, that is nicer! Fixed

2019-12-16 21:44 UTC, RosalineP commented on core/src/client/components/ConfigurationModal.tsx
> +                            onClick={() => this.props.closeModal()}
Ah true, fixed

2019-12-16 22:05 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            ...prevState,
A: Mark all as optional in interface -- set defaults

2019-12-16 22:10 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/authenticationConfiguration.scss
> +  user-select: none;
(Is fine!)

2019-12-16 22:13 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        enabled={item.enabled ? "Enabled" : "Disabled"}
Suggestion, two props:
enabled - bool
canEdit
Consider defaults

2019-12-17 00:19 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +    handleChangeToPrimary(event) {
Resolved

2019-12-17 00:27 UTC, RosalineP commented on core/src/client/components/EditableAuthRow.tsx
> +                onClick={() => this.props.handlePrimaryToggle(this.props.enabled, this.props.id, this.props.stateSection)}
Resolved

2019-12-17 00:28 UTC, RosalineP commented on core/src/client/components/EditableAuthRow.tsx
> +// figure out TS typing for a function
Oh awesome :)

2019-12-17 01:10 UTC, RosalineP commented on core/src/client/components/DragAndDropPane.tsx
> +        return(
Improved

2019-12-17 01:22 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                    <strong> Labkey Login Form Authentications </strong>
Done

2020-01-29 22:50 UTC, labkey-alan requested changes
There are several `.DS_Store` files checked into this branch. We should remove them and add them to the .gitignore.

2020-01-29 22:50 UTC, labkey-alan commented on core/package.json
> +    "@labkey/components": "0.13.1-fb-compactFileAttachmentForm.0",
We'll want to make sure we bump ui-components to a prod version, then merge the ui-components branch before we merge this branch.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.spec.tsx
> +    // test('Save button triggers', () => {
Let's remove this commented out code unless there is a good reason to keep it around. I have a feeling we have test coverage for this via selenium though. If we don't have test coverage I can work with you to get this test working.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        // const configObj = JSON.parse(config);
There is a lot of commented out code in this function, and it looks like what is in the utils file. We should remove it.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            toggleSomeModalOpen: this.toggleSomeModalOpen,
Can we rename this to `toggleModalOpen`?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                <Button className="labkey-button primary parent-panel__save-button" onClick={() => this.saveChanges}>
onClick can just be `onClick={this.saveChanges}`. No need to create a wrapper function on every render.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                        window.location.assign(ActionURL.buildURL('admin', 'showAdmin'));
I would make this click handler a method on the class called `onCancel`.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/authenticationConfiguration.css
> +  -ms-transform: translateY(-50%);
@cnathe @labkey-susanh do we know if our CSS loader(s) automatically inject the vendor prefixes for us?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/utils.ts
> +    console.log("configObj", configObj);
Should remove these console.log statements.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/utils.ts
> +
Unnecessary blank line.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/utils.ts
> +    let newState = prevState.slice(0); // To reviewer: This avoids mutation of prevState, but is it overzealous?
No, this is not overzealous, this is the correct solution. The only way this would be overzealous is if there is a case where state is *not* modified, but that does not seem to be the case. If state is not modified it is preferable to return the same object so the shallow equality checks work.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    primaryProviders?: Record<string, any>;
Why are we using the TypeScript Record type here? I don't think we should be using it here if we're defining it as <string, any>, at least not from my understanding of the TS docs: https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkt

Is there a better type we could be using? Something more prescriptive? Or is this really an object that could be anything? If so, could we just use any? If we want to be strict about strings for keys we could say `{ [key: string]: any }`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    primaryProviders?: Record<string, any>;
This is also true for AuthenticationConfiguration component. It looks like this component takes a subset of the state of AuthenticationConfiguration, it may be worth your time to export the props interface here and have the AuthenticationConfiguration State interface it, this way there aren't duplicate definitions, and if one changes it will be compile time checked by the other, and only need to be changed in one place.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +        const primaryTab_SSO =
This naming convention is weird. We shouldn't need the underscore at all, same with the other tab variables.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +interface ViewOnlyAuthConfigRows_Props {
Remove the underscore. Also move this component above where it is used. Yes JavaScript has hoisting, but we really shouldn't rely on it as a feature if we don't have to.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        <Tab eventKey={1} title="Primary">
Overall this entire render function is very complex, I think this is a good target to split into several sub components. We should have a `<PrimaryLoginFormTab>`, `<PrimarySSOTab>`, `<SecondaryTab>`, then the `<Tabs>` body could look like:
```
<Tabs>
    <PrimaryLoginFormTab />
    <PrimarySSOTab />
    <SecondaryTab />
</Tabs>
```

with props passed to each tab of course.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        <Tab eventKey={1} title="Primary">
The benefits here being that it is more readable, but also you can more easily craft test cases for each tab.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +            modalOpen: false,
You should be setting default state for highlight here as well.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +    onToggleModal = (toggled: string): void => {
This method is weird. Why is toggled a string? We only have one attribute that can ever be toggled, `modalOpen`, so we shouldn't need to pass the attribute name as a string. This handler can take no arguments.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +            [toggled]: !this.state[toggled],
In this context `this.state` is *_not_* guaranteed to be the most up to date state. Instead you must toggle state this way:

```
this.setState((state) => ({
    modalOpen: !state.modalOpen,
    highlight: false,
}));
```

The only way to properly compute state based on the current state value is to look at the state value passed into the setState handler function.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +            <>
No need to wrap this in `<>`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +            <>
No need to wrap this in `<>`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +                        this.setHighlight(true);
Is there a reason we can't use CSS to handle highlights?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +        const modal = this.state.modalOpen && isDatabaseAuth ? databaseModal : dynamicModal;
Instead of instantiating the database and dynamic modals every time, then assigning to a const before returning you could have modal be `let modal;` then have an if block to set to the appropriate modal.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +    passwordRules: Record<string, string>;
We should define an interface for passwordRules and currentSettings, the interface looks pretty obvious from the default values set in state.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +            currentSettings: {strength: "", expiration: ""}
We should be consistent about double or single quotes, above we have single, here we have double. We should probably use single as that seems to be what most other frontend folks use around LabKey.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +        const form = {
No need to construct a form object here, could just pass this.state.currentSettings to `jsonData` below.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +        const optionsMap = {
Since this never changes, this should be a constant defined at the top of the file.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                        <div dangerouslySetInnerHTML={{ __html: this.state.passwordRules.Weak }} />
Why are we dangerously setting inner HTML here?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                                    value={expiration}>
Please put the closing `>` on the same indent level as the opening `<`. In this particular case it really makes the options below look like props.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                                    <option value="Never">Never</option>
These options are all duplicates of `optionsMap` above, we should just iterate over that map and generate the options from it, this way if the `optionsMap` changes we don't need to update these options.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                                {'More about authentication'}
`{'More about authentication'}` can just be `More about authentication`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                            onClick={() => this.props.closeModal()}
onClick can just be `onClick={this.props.closeModal}`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +    primaryProviders?: Record<string, any>;
Can we define a more descriptive type here?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +    actionFunctions?: { [key: string]: Function };
I think we should name this `actions`, and we should define a proper interface so the component can explicitly define what actions it is expecting.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +    constructor(props) {
This constructor is not needed as it doesn't do anything (yay!).

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +    deleteAction?: Function;
This should be called `onDelete`.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +        const response = confirm(
Is there a reason we aren't using a `<Modal>` here? The built-in dialogs generated by `confirm` do not look good.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +    actionFunctions?: { [key: string]: Function };
This true anywhere else we're following this pattern as well.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +                            modalType={providers && { ...providers[item.provider] }}
Do we need to be copying the provider object here? Couldn't we just do `modalType={providers ? providers[item.provider] : null }`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +                            {...item} // contains data of an individual auth config
If `item` is the data for an auth config, should we name this variable `authConfig`? Should we also rename `this.props.rowInfo` to something more descriptive like `authConfigs`?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +                            stateSection={stateSection}
The variable name `stateSection` is confusing to me, is there a more descriptive name we can use?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    changedFiles?: any; // Note to reviewer: should be string[], but am receiving 'includes does not exist on type string[]' TS error
It looks like includes is and ES7 feature: https://github.com/Microsoft/TypeScript/issues/2340

We should probably not use it unless we can verify that WebPack/Babel are properly including a polyfill. Otherwise we should use array.find, array.indexOf, or something similar.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    modalType?: AuthConfigProvider;
All of the attributes on the props interface are labeled as optional, but it appears many are expected to have a value other than undefined. We should make sure the interface properly indicates which ones are optional so we have better compile time safety and less runtime errors.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    modalType?: AuthConfigProvider;
If they are all truly optional then we should be doing a lot more undefined checks on the props we're using. For example we do string concatenation with an optional property, that would end up with the string being postfixed with `undefined`, which is probably not what we want. We also have a case where we call `toString` on a prop, if undefined that will cause a runtime exception.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            emptyRequiredFields: null,
We really should be initializing all potential state fields here instead of a subset.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        Object.keys(this.state).map(item => {
add an empty line above this.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        const emptyRequiredFields = requiredFields.filter(name => this.state[name] == '');
This filter, and the above reduce, could be combined into a single reduce function that reduces into an array of blank required fields.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        this.setState({ enabled: !this.state.enabled });
This is an incorrect usage of this.setState. If you are computing any state based on current state you must use the callback form of setState and reference the state object passed into the callback function.

`this.seState(state => ({enabled: !state.enabled}));`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        this.setState(() => ({ deletedLogos: arr }));
This is an incorrect usage of setState, you do not have the most current state object unless you are using the state object passed into the setState handler, and you are directly mutating the state object, instead of making an immutable transformation, do this instead:
`this.setState(state => ({ deletedLogos: [ ...state.deletedLogos, value] }));`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            [name]: !oldState,
This is an incorrect usage of setState, you do not have the most current state object unless you are using the state object passed into the setState handler.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        this.setState(() => ({ [name]: '', changedFiles }));
This is an incorrect usage of setState, you do not have the most current state object unless you are using the state object passed into the setState handler, and you are directly mutating the state object. See my previous comment about immutable transformation on an array.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        for (let i = 0; i < fields.length; i++) {
This can be simplified to use Array.findIndex: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                        return;
We pass `canEdit` below, which seems redundant if we're only ever rendering the text input below if we can edit it. Is there reason we have this extra guard here? Does the TextInput not properly handle `canEdit`?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                            index={index + 2}
Why are we always incrementing index by 2 here? We should probably add a comment explaining.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                            canEdit={this.props.canEdit}
There are a ton of references to `this.props.canEdit` in this method, we should probably just pull it out as a variable at the top of the method `const { canEdit, /* other props needed like title, description etc. */ } = this.props`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                            emptyRequiredFields={this.state.emptyRequiredFields}
We shouldn't be passing the entire emptyRequiredFields object here, instead we should just be passing the individual value needed by the component, unless the consuming component is using multiple values from this object, but I don't think it is.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                    {modalType && this.dynamicallyCreateFields(modalType.settingsFields, this.state.search)}
It is confusing to me that we pass a variable called search to `dynamicallyCreateFields`, which references it as `expandableOpen`. Is there a reason we rename the variable? It looks to only be used by `dynamicallyCreateFields`. The `search` variable is also stored on state, but I am not seeing anywhere in this file where we are ever changing the value of `search`, is this variable needed?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        this.setState(() => ({
Why is this setState done in componentDidMount? It seems to me that this could be done in the constructor when we set `this.state = {...}`.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    dynamicallyCreateFields = (fields: AuthConfigField[], expandableOpen) => {
In general we should only be generating JSX inside of a render function. If your render function is so complex that you need to split it into smaller functions, it is typically a good idea to create a new component instead. This makes it easier to test. I would convert `dynamicallyCreateFields` to `<DynamicFields />`, just like what you did with `<SSOFields />`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                        {modalType.testLink && (
This block of code is similar to the above SSOFields block, but in this case we'll always be rendering a wrapper div for the modal test button, sometimes it will be empty. Do we always want to be rendering this div?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                                }>
Please put the `>` on the same level of indent as the opening `<`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                                {'More about ' + this.props.provider + ' authentication'}
This is a good case for JavaScript template strings:

``{`More about ${this.props.provider} authentication`}``

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +// I tried adding 'es7' and then 'es2017' to my 'lib' in tsconfig.json, as stackoverflow suggested, to no avail
As state above we probably shouldn't be using this feature unless we know for sure that babel is transpiling this to something compatible in all browsers. I would otherwise use indexOf or something similar.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +class TextInput extends PureComponent<any> {
Props type should not be any here, instead it should be `TextInputProps`.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            this.props.emptyRequiredFields && this.props.emptyRequiredFields.includes(this.props.name);
As stated above we should just pass a `requiredAndEmpty` prop to this component, OR have this component compute it by passing `required` to it, and having it check `this.props.value === '' && required`, but that will make it always render the error even on initial render which we may not want.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +class CheckBoxInput extends PureComponent<any> {
Props type should not be `any`, should be CheckBoxInputProps

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                    {this.props.caption} {this.props.required ? '*' : null}
Instead of constantly referencing `this.props.PropName` I would grab the variables needed out of `this.props` at the top `{ description, caption, required } = this.props`;

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            this.props.emptyRequiredFields && this.props.emptyRequiredFields.includes(this.props.name);
You could track a simple dirty state on this component as well that only renders the error if the field has been touched and is not valid.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                        onChange={e => this.props.handleChange(e)}
I think this can just be `onChange={handleChange}` assuming you've pulled `handleChange` out of the props at the top of render.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                        onChange={e => this.props.handleChange(e)}
I would also consider renaming `handleChange` to `onChange` as it's a bit more confusing when we arbitrarily rename props as we pass them around.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        return (
Use destructuring here to pull out the props you use.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                    {this.props.canEdit ? (
Instead of rendering two different checkboxes based on canEdit, why don't we just pass canEdit directly to the checkbox? Why is the non-editable case expecting the prop value to be a string? That seems odd to me.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +        const { options } = this.props;
Desctructure the other props used here as well.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    options?: Record<string, string>;
I think we need to better define the type passed into this component. Also, why is options optional? Are we expecting to run into a case where there are no options to select for an input?

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                                        {options[item]}{' '}
The body of the option here seems rather odd. Why do we have `{' '}` before and after the option? That seems unnecessary. Browsers will trim white space when rendering unless you use non-breaking spaces (`&nbsp;`), which should not be necessary here.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                    <div dangerouslySetInnerHTML={{ __html: this.props.html }} />
Does this HTML come from the server or something? Are we sure this is safe? If so, we should document that via a comment. If not, we should not be using `dangerouslySetInnerHTML`.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +class SmallFileUpload extends PureComponent<any> {
Props type should be `SmallFileInputProps` instead of `any`.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                            initialFileNames={this.props.value && ['']}
If `value` is not set we pass `initialFileNames` as `false`. The type signature for `FileAttachmentForm` says it should be an array of strings only, it does not indicate that boolean values are acceptable, so we should probably do something like this: `value ? [''] : undefined`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                            key={this.props.text}
This component isn't rendering a list, so key is not needed here. If this is being rendered inside of a list, then the consumer passes `key` to it as a prop, but you should never list `key` as a prop on a component yourself.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/FACheckBox.tsx
> +    key?: string;
`key` is never used. You should also never have a prop called `key`, that is for React only.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/FACheckBox.tsx
> +interface Props {
All of the props are listed as optional, but nowhere do we do a check for undefined, so we should fix that, or make them all required.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/FACheckBox.tsx
> +            <>
No need to wrap this in `<>`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/GlobalSettings.tsx
> +interface State {
Props and state look to be identical, so we shouldn't need duplicate definitions. I would probably just call this interface `Props`.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/GlobalSettings.tsx
> +                            ? () => {
This isn't particularly readable. One solution would be to make the FACheckbox not call the click handler if canEdit is false. Then you can always pass the same click handler to FACheckbox with no worry of it being incorrectly called.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/GlobalSettings.tsx
> +        const { canEdit } = this.props;
Destructure all of the other props you're using here.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/SSOFields.tsx
> +    headerLogoUrl?: string;
All of the props here are listed as optional, but in multiple cases we assume they are present. We should either check for undefined when using them, or change the props to be required. They should probably all be required.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/SSOFields.tsx
> +            <>
I think we should probably be wrapping this in a real DOM element and appending a className to it. This would help us when we write selenium tests.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/SSOFields.tsx
> +interface ImgFileAttachForm_Props {
I would define all interfaces and components used by the SSOFields component before it. Most people read a file from top to bottom, as I am doing now, and we really shouldn't rely on hoisting as a feature of JS.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/SSOFields.tsx
> +    handleDeleteLogo?: Function;
onFileChange and handleDeleteLogo are optional, but we do no checks if they are undefined which can lead to runtime errors, but also, in all of their usages it looks like we pass a value in, so we really should make these required instead of optional.

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/SSOFields.tsx
> +        const noImageSelectedDisplay = (
This should be converted to its own Component, similar to how we have `<LoadingSpinner />`

2020-01-29 22:50 UTC, labkey-alan commented on core/src/client/components/SSOFields.tsx
> +                                key={this.props.text}
Key should not be required here.

2020-01-30 00:35 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/utils.ts
> +    let newState = prevState.slice(0); // To reviewer: This avoids mutation of prevState, but is it overzealous?
Gotcha!
(Comment removed)

2020-01-30 01:26 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
> +            <>
Unfortunately, the "&nbsp; Enabled" text after the icon will bring up an error if not the the empty tags

2020-01-30 01:26 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
> +            <>
(Same as above comment)

2020-01-30 01:38 UTC, RosalineP commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                        <div dangerouslySetInnerHTML={{ __html: this.state.passwordRules.Weak }} />
The div contents are only rendered text—the 'Weak' and 'Strong' descriptions.
It was decided that the text should live server-side. The bullet lists (as preserved from older code) get sent in raw html string form

2020-01-30 01:39 UTC, RosalineP commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                        <div dangerouslySetInnerHTML={{ __html: this.state.passwordRules.Weak }} />
We could decide the text should live client-side, or I can add a comment explaining why dangerouslySetInnerHTML is used

2020-01-30 01:40 UTC, RosalineP commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                                    value={expiration}>
Resolved, but maybe we should change this rule in the linter? I recall having the indenting as you suggest previously, and the linter adjusting it.

2020-01-30 01:43 UTC, RosalineP commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                            onClick={() => this.props.closeModal()}
This raises the error 

> TS2322: Type 'Function' is not assignable to type '(event: MouseEvent<SVGSVGElement, MouseEvent>) => void'.
  Type 'Function' provides no match for the signature '(event: MouseEvent<SVGSVGElement, MouseEvent>): void'.

The suggested solution from a search was the wrap it with a fat arrow. Perhaps there is a better way?

2020-01-30 01:50 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +            toggleSomeModalOpen: this.toggleSomeModalOpen,
👍

2020-01-30 02:00 UTC, RosalineP commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +        const optionsMap = {
Moved up, changed variable name to snake case with allcaps

2020-01-30 02:05 UTC, RosalineP commented on core/src/client/components/SSOFields.tsx
> +            <>
Currently Chris is grabbing the classNames on the ImageAndFileAttachmentForm, which seems to be working well

2020-01-30 02:11 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                            index={index + 2}
Since there are two other FileAttachmentForms on the modal. Comment added!

2020-01-30 02:37 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +class TextInput extends PureComponent<any> {
Was mentioned above in reviewer comment! Resolved

2020-01-30 02:51 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                                        {options[item]}{' '}
Ah, the linter does that. I thought I'd stripped all of them out. Thanks for the catch!

2020-01-30 02:59 UTC, RosalineP commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                        <div dangerouslySetInnerHTML={{ __html: this.state.passwordRules.Weak }} />
(Comment added anyway)

2020-01-30 03:01 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                    <div dangerouslySetInnerHTML={{ __html: this.props.html }} />
Comment added. Since only text is rendered, this should be safe to display. (Same lives-on-server matter as the dangerouslySetInnerHTML on DatabaseConfigurationModal)

2020-01-30 03:05 UTC, RosalineP commented on core/src/client/components/GlobalSettings.tsx
> +        const { canEdit } = this.props;
Everything except for `this.props[text.id]` destructured

2020-01-30 17:28 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    primaryProviders?: Record<string, any>;
Realized this should be AuthConfigProvider[]

2020-01-30 17:53 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        <Tab eventKey={1} title="Primary">
Factored out the two tabs. Also placed the database DynamicConfigurationModal into its own const for clarity

2020-01-30 18:02 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
> +    onToggleModal = (toggled: string): void => {
Yeah, that is absolutely weird... my only guess is that it's like that because that function used to be handling more stuff before we changed the functionality, and I clearly forgot to update the fn.

2020-01-30 19:14 UTC, RosalineP commented on core/src/client/components/DragAndDropPane.tsx
> +                            stateSection={stateSection}
Changed to configType

2020-01-30 19:35 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
> +                        this.setHighlight(true);
Oh, my god, that's a real facepalm. Fixed

2020-01-30 21:08 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                    {modalType && this.dynamicallyCreateFields(modalType.settingsFields, this.state.search)}
Hm, right. So 'search' is the name of a field that is passed to us and generated, and must be referred to as 'search.' This is a special field because it determines whether or not any following fields get created (See LDAP config, 'ldap search' checkbox in the modal) and this implementation is what ultimately Adam and I decided on. 

I've made the naming consistent, sticking to 'search'. Search will be toggled by my generic `checkCheckBox` fn, so it is needed

2020-01-30 21:59 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                            emptyRequiredFields={this.state.emptyRequiredFields}
Correct... I now differentiate between the DynamicConfigurationModal string[] 'emptyRequiredFields', and only pass into input-components the boolean 'requiredFieldEmpty'.

2020-01-30 22:21 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                        {modalType.testLink && (
Nope we do not!

2020-01-30 23:09 UTC, labkey-tchad requested changes
The move put the test classes in some weird directories. e.g. `devtools/test/src/org.labkey.test/test.devtools`

2020-01-30 23:09 UTC, labkey-tchad commented on devtools/test/src/org.labkey.test/components.devtools/SecondaryAuthConfigureDialog.java
> +package org.labkey.test.components.devtools;
The location for these is messed up (check the file path)

2020-01-30 23:09 UTC, labkey-tchad commented on devtools/test/src/org.labkey.test/params.devtools/SecondaryAuthenticationProvider.java
> +package org.labkey.test.params.devtools;
Fix file location

2020-01-30 23:09 UTC, labkey-tchad commented on devtools/test/src/org.labkey.test/test.devtools/SecondaryAuthenticationTest.java
> +/*
Fix file location

2020-01-30 23:09 UTC, labkey-tchad commented on devtools/test/src/org.labkey.test/test.devtools/SecondaryAuthenticationTest.java
> +@Category({Git.class})
Does enabling secondary auth require the premium module or something? Why is this in the `Git` suite? That's usually for stuff that can't run in Community suites.

2020-01-30 23:46 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
> +        const response = confirm(
Updated to modal

2020-01-31 00:04 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    options?: Record<string, string>;
Made un-optional.

The type itself applies to the options
```
{
          "emailAddress" : "Email Address",
          "transient" : "Transient",
          "unspecified" : "Unspecified"
}
```

and

```
{
          "UserID" : "User ID",
          "UserName" : "User Name",
          "FullEmailAddress" : "Full Email Address"
}
```

for which I thought <string, string> would be valid?

2020-01-31 02:36 UTC, labkey-adam commented on devtools/test/src/org.labkey.test/test.devtools/SecondaryAuthenticationTest.java
> +@Category({Git.class})
It does not require premium. Just requires the devtools module.

2020-01-31 17:55 UTC, labkey-klum commented on api/src/org/labkey/api/security/AuthenticationManager.java
delete this code?

2020-01-31 20:52 UTC, labkey-klum approved these changes
reviewed java code, looks like frontend and test code have previously been reviewed

2020-02-04 22:11 UTC, labkey-tchad approved these changes
Only needed to fix the directory names for the moved test classes so I just did it.

2020-02-04 22:13 UTC, labkey-tchad commented
@labkey-alan I removed the `.DS_Store`. Could you re-review to make sure your other review feedback has been adressed.

2020-02-05 01:47 UTC, labkey-alan requested changes
There are some issues with setState in AuthenticationConfiguration.tsx that need to be addressed (directly manipulating state). The interface stuff we can address in the later story and I can help you come up with a plan to get the optional/required props all squared a way once and for all.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                this.checkIfDirty(this.state.globalSettings, this.state.dirtinessData.globalSettings);
This could be done at the same time we compute the new state, we could drop checkIfDirty below and just call isEquivalent on `newState.globalSettings` and `newState.dirtinessData.globalSettings`. If we do it as a callback like this by the time you call this.checkIfDirty the state may have changed.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                this.setState(() => ({ dirty }));
this.draggableIsDirty access the current state, by the time the setState callback here toggles the dirty bit the state could have changed. All of the getting/checking of state to check if it's dirty should be done at the same time you're setting new state. The general process should look like this:

```
this.setState((state) => {
    // 1. compute new state that you want
    const newState = { ...state } // do stuff here
    // 2. Compute dirty state based on new and old state
    const dirty = checkDirty(oldState, newState);
    return {...newState, dirty};
});
```

Though, looking at this function, doesn't it only ever get called if we for sure re-ordered something? If so, then wouldn't it be safe to assume that draggable is dirty and we don't need to even bother with a deep check? Or is it possible this is called and nothing is re-ordered?

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        dirtinessData[configType] = newState;
Shouldn't this be: `cons dirtinessData = { ...this.state.dirtinessData, [configType]: newState }`? Otherwise you're directly manipulating a state object, a deeply nested one at that.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +        const {addNewPrimaryDropdown, loginFormTipText, primaryTabLoginForm, SSOTipText, primaryTabSSO, canEdit} = this.props;
Line is too long.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    secondaryProviders?: AuthConfigProvider[];
Looking at the usages of ViewOnlyAuthConfigRows you only ever pass in primaryProviders OR secondaryProviders, but never both. You could collapse these to props into `providers`. They'd still need to be optional, as would data, because we might still be loading, but you could avoid that ternary on line 20 and drop a prop.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +class SecondaryTab extends PureComponent<SecondaryTabProps> {
This is unused and can be removed, props interface too.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        canEdit={this.props.canEdit}
You destructured this.props.canEdit above as `canEdit` so you can just use that here and elsewhere below.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +interface Props extends AuthConfig {
`canEdit` and `draggable`, can be required, they're always passed. It's possible description, provider, enabled, and toggleModalOpen may also be converted to required but I can't immediately tell because we spread objects as props (`{...authConfig}`) in places AuthRow is consumed.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +    closeModal?: Function;
closeModal is always used and can be made required.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                                    data-key="1"
We don't appear to be using this `data-key` attribute anywhere. Is it for tests or something else?

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/DragAndDropPane.tsx
> +    actions?: Actions;
All of the props here are always passed except for primary/secondary providers, but those are the same type and we even merge them into a single variable (providers). I would make it one arg called `providers`, and make all props required.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    loginLogoUrl?: string;
It's very hard for me to determine what props here are actually required or optional because where we pass them in we do a lot of `{...this.props}`, and we inherit from other interfaces that have optional props, but I think all of these might actually be able to be made required.

AuthConfig in particular is something we inherit from a lot, and everything in that interface is listed as optional, but I don't think anything on it actually is. If we made them optional so we can use it as a state interface you could define your state interface as `Partial<AuthConfig>`. The `Partial` type in TypeScript will make any required attributes optional.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            ...fieldValues,
In your follow up work I would make fieldValues be it's own object on state, instead of copying them inline. For example, if we ever introduce a field value called `enabled` it will overwrite your enabled flag here. In general it's a good idea to put all form state in one object separate from other pieces of state.

2020-02-05 01:47 UTC, labkey-alan commented on core/src/client/components/GlobalSettings.tsx
> +        this.state = {
I don't think we need this constructor, or state, we don't seem to reference state at all.

2020-02-05 02:08 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +class SecondaryTab extends PureComponent<SecondaryTabProps> {
SecondaryTab used

2020-02-05 02:12 UTC, RosalineP commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +                                    data-key="1"
Looks like a lingering prop from a prior iteration. Removed

2020-02-05 02:16 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            ...fieldValues,
Noted this down, and will keep this comment open

2020-02-05 02:22 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
> +interface Props extends AuthConfig {
Made a note of description, provider, enabled, and toggleModalOpen for followup work

2020-02-05 02:23 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
> +interface Props extends AuthConfig {
(Edits to canEdit and draggable made. Keeping this comment open because it mentions followup work.)

2020-02-05 02:57 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    loginLogoUrl?: string;
The functions and canEdit were require-able.

Went a little bit through the AuthConfig interface. It's used in a number of props as well so I'm going to bunt that that to followup work.

2020-02-05 03:22 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                this.checkIfDirty(this.state.globalSettings, this.state.dirtinessData.globalSettings);
Changed. Also changed handling as per your comment on this file around line 221. Not totally sure if my changes are what you were thinking, so keeping this comment open for you to verify

2020-02-05 03:52 UTC, RosalineP commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                this.setState(() => ({ dirty }));
The deep check is to ensure dirtiness is correctly calculated if someone drags something out of order (dirtiness set), and then drags it back into the original order (dirtiness unset).

This one was a bit tricky to make work given the way draggableIsDirty was working—keeping this comment open for you to verify the changes are correct

2020-02-05 18:30 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                this.checkIfDirty(this.state.globalSettings, this.state.dirtinessData.globalSettings);
This one looks good, the one below is still referencing stale state, I'll add a comment with a proposed fix that should work. There is also some commented out code below this that I think can be removed.

2020-02-05 18:30 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                this.setState(() => ({ dirty }));
Got it 👍

2020-02-05 18:48 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +    loginLogoUrl?: string;
Yeah, makes sense. I have a plan on how to fix these interfaces up, we can talk about it later today.

2020-02-05 19:07 UTC, labkey-alan requested changes

2020-02-05 19:07 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +    updateAuthRowsAfterSave = (config: string, configType: string): void => {
This method should use the state variable passed into setState like this:

```
updateAuthRowsAfterSave = (config: string, configType: string): void => {
    this.setState((state) => {
        const prevState = state[configType];
        const newState = addOrUpdateAnAuthConfig(config, prevState, configType);

        // Update our dirtiness information with added modal, since dirtiness should only track reordering
        const dirtinessData = { ...state.dirtinessData, [configType]: newState };
        return { [configType]: newState, dirtinessData };
    });
};
```

2020-02-05 20:19 UTC, labkey-alan approved these changes

2020-02-05 20:26 UTC, merged