Item 6654 : Specimen Designer Migration
LabKey/platform pull request #715
Opened 2019-12-31 17:45 UTC by labkey-ankurj

2019-12-31 18:24 UTC, labkey-jeckels requested changes

2019-12-31 18:24 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/SpecimenDomainKind.java
> +            List<List<String>> results = checkRollups(null, null, optionalSpecimenProps, container, user);
Do warnings ever get propagated? Seems like they just get dropped.

I'd prefer a simple Java class to capture the errors and warnings instead of a un-documented convention that errors are the first thing in the list and warnings are the second, but I'd be OK with adding JavaDoc describing this.

2019-12-31 18:24 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/AbstractSpecimenDomainKind.java
> +    protected ValidationException getValidationException(List<String> errors)
Could we build up a ValidationException directly instead of first accumulating as a list and then converting?

2020-01-01 01:39 UTC, labkey-ankurj commented on study/src/org/labkey/study/model/SpecimenDomainKind.java
> +            List<List<String>> results = checkRollups(null, null, optionalSpecimenProps, container, user);
Warnings were added to Window.confirm before this migration work. Need guidance on how to go about them now.

2020-01-01 01:39 UTC, labkey-ankurj commented on study/src/org/labkey/study/model/AbstractSpecimenDomainKind.java
> +    protected ValidationException getValidationException(List<String> errors)
Yes, changed locally.

2020-01-02 14:30 UTC, cnathe commented on study/src/org/labkey/study/view/manageStudy.jsp
> +                        <td><%=link("Edit SpecimenEvent fields", specimenEventUrl)%></td>
Even though the table name doesn't have a space, should we add one here for the link label (i.e. "Specimen Event")?

2020-01-02 16:56 UTC, labkey-ankurj commented on study/src/org/labkey/study/view/manageStudy.jsp
> +                        <td><%=link("Edit SpecimenEvent fields", specimenEventUrl)%></td>
changed.

2020-01-03 23:47 UTC, labkey-jeckels requested changes

2020-01-03 23:47 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/SpecimenDomainKind.java
> +        if (!results.getWarnings().isEmpty())
Can we consolidate these in the base class so we don't need three very similar implementations?

2020-01-03 23:47 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/SimpleValidationWarning.java
> +    private String _severity;
I think we can fold this into SimpleValidationError, instead of having the warning subclass that can have a variety of severities (including error)

2020-01-03 23:47 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/SimpleValidationWarning.java
> +        ObjectError error = new ObjectError(objectName, codes, null, getMessage());
We talked about doing this via a subclass of ObjectError instead of as a code. I think the approach here could confuse the code in ApiResponseWriter.convertToJSON() because it wouldn't know if the value of the code is the severity or the propertyId

2020-01-17 20:48 UTC, labkey-jeckels requested changes

2020-01-17 20:48 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/SimpleValidationError.java
> +    public static class Warning extends FieldError
Let's remove this subclass and just use the SimpleValidationError directly, with a constructor argument that specifies the Severity.

2020-01-17 20:48 UTC, labkey-jeckels commented on api/src/org/labkey/api/action/ApiResponseWriter.java
> +            if (error instanceof SimpleValidationError.Warning)
If we remove the Warning subclass, we just check if it's an instanceof SimpleValidationError and it's severity != error

2020-01-17 20:48 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/SimpleValidationError.java
> +        return Objects.equals(_message, that._message);
Let's include the severity in this check as well

2020-01-17 20:48 UTC, labkey-jeckels commented on api/src/org/labkey/api/action/ApiResponseWriter.java
> +            String severity = "Error";
Please use a value based on the Severity enum instead of a separate hard-coded string.

2020-01-17 20:48 UTC, labkey-jeckels commented on api/webapp/clientapi/core/Domain.js
> +         * @param {boolean} config.includeWarnings set this to true, if server side warnings are desired along with the errors
Add a note that if this is set to true and there are warnings detected, they will prevent the save from completing successfully

2020-01-17 20:48 UTC, labkey-jeckels commented on experiment/package.json
> +    "@labkey/components": "0.13.0-fb-specimenDesigner.0"
Presumably this will be different in the final commit?

2020-01-17 20:48 UTC, labkey-jeckels commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        console.log("domain, ", domain);
Remove?

2020-01-17 20:48 UTC, labkey-jeckels commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        console.log("saving despite warnings");
Same here - delete the log()?

2020-01-17 20:48 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/AbstractSpecimenDomainKind.java
> +    private String getMessageString(List<String> messages)
I think StringUtils.join() is equivalent.

2020-01-17 20:48 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/AbstractSpecimenDomainKind.java
> +                if(!prop.isRequired())
Is this right? Should it be using mandatory instead of required?

2020-01-17 20:48 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/SpecimenDomainKind.java
> +                if (!prop.isRequired() && vialFields.contains(prop.getName().toLowerCase()))
Same thing - I think this is the same incorrect use of isRequired() and should be checking if it's a mandatory field instead

2020-01-17 21:30 UTC, cnathe commented on experiment/package.json
> +    "@labkey/components": "0.13.0-fb-specimenDesigner.0"
Yes, the final step before merging the labkey-ui-components PR (which will get merged before this one) is the update this to the next @labkey/components release version.

2020-01-17 21:43 UTC, cnathe requested changes

2020-01-17 21:43 UTC, cnathe commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +                        badDomain: badDomain
I assume it will still work if we don't add the "badDomain" state value here and just set badDomain as the "domain" state value.

2020-01-17 21:43 UTC, cnathe commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +            submitting : false
You can probably leave this value for "submitting" as is (which should be true at this point) since we are going to call submitHandler and set it back to try anyway.

2020-01-17 21:43 UTC, cnathe commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +    setShowWarnings = () => {
This should be renamed. This is the callback for the cancel right? Maybe call it "onSubmitWarningsCancel".

2020-01-17 21:47 UTC, labkey-ankurj commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +                        badDomain: badDomain
It didn't work as in this catch badDomain is a different object (DomainException) not the domain design. This is the point where I discussed of detaching domain exception from domain. I can think about working with that if it is expensive to store one more object in the state here.

2020-01-17 21:49 UTC, labkey-ankurj commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +            submitting : false
if submitting is left true here, then the callback to submitHandler does not finish because of check at line 101 in submitHandler and it finishes without saving the domain.

2020-01-17 21:51 UTC, labkey-ankurj commented on study/src/org/labkey/study/model/AbstractSpecimenDomainKind.java
> +    private String getMessageString(List<String> messages)
This method is not being used, will remove it.

2020-01-17 21:59 UTC, cnathe commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +                        badDomain: badDomain
No, it isn't too expensive to store the additional object. I remember our discussion now, thanks.

2020-01-17 22:21 UTC, labkey-jeckels requested changes

2020-01-17 22:21 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/SimpleValidationError.java
> +    public static class Warning extends FieldError
Scratch that. Now that I understand this better, I just propose renaming Warning to FieldWarning

2020-01-17 22:28 UTC, labkey-ankurj commented on api/webapp/clientapi/core/Domain.js
> +         * @param {boolean} config.includeWarnings set this to true, if server side warnings are desired along with the errors
done

2020-01-17 22:28 UTC, labkey-ankurj commented on api/src/org/labkey/api/action/ApiResponseWriter.java
> +            String severity = "Error";
done

2020-01-17 22:28 UTC, labkey-ankurj commented on api/src/org/labkey/api/query/SimpleValidationError.java
> +    public static class Warning extends FieldError
done

2020-01-17 22:29 UTC, labkey-ankurj commented on api/src/org/labkey/api/query/SimpleValidationError.java
> +        return Objects.equals(_message, that._message);
done

2020-01-17 22:33 UTC, labkey-ankurj commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        console.log("domain, ", domain);
done

2020-01-17 22:33 UTC, labkey-ankurj commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        console.log("saving despite warnings");
done

2020-01-17 22:34 UTC, labkey-ankurj commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +    setShowWarnings = () => {
changed.

2020-01-17 23:33 UTC, labkey-jeckels approved these changes
Looks good for the things I requested. Will let @cnathe re-review for the things he commented on.

2020-01-20 14:03 UTC, cnathe approved these changes

2020-01-20 21:02 UTC, cnathe commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        const rollupURI = "https://www.labkey.org/Documentation/wiki-page.view?name=specimenCustomProperties";
@labkey-ankurj You can make use of the `LABKEY.helpLinkPrefix` helper variable here. I think you'd want
`const rollupURI = LABKEY.helpLinkPrefix + 'specimenCustomProperties';`

2020-01-23 01:34 UTC, labkey-ankurj commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        const rollupURI = "https://www.labkey.org/Documentation/wiki-page.view?name=specimenCustomProperties";
@cnathe this is giving me compile error locally : TS2339: Property 'helpLinkPrefix' does not exist on type 'LabKey'.

2020-01-23 14:00 UTC, cnathe commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        const rollupURI = "https://www.labkey.org/Documentation/wiki-page.view?name=specimenCustomProperties";
@labkey-ankurj I thought we already had a usage of that in the experiment module, but if not you just need to add it to the experiment/src/client/types/main.d.ts file to fix that compile error.

`
type LabKey = {
    defaultHeaders: any
    devMode: boolean
    container: any
    contextPath: string
    helpLinkPrefix: string
    moduleContext: any
    user: any
    vis: any
};
`

2020-01-23 23:57 UTC, labkey-ankurj commented on experiment/src/client/DomainDesigner/DomainDesigner.tsx
> +        const rollupURI = "https://www.labkey.org/Documentation/wiki-page.view?name=specimenCustomProperties";
added, thanks.

2020-01-24 01:13 UTC, labkey-jeckels approved these changes
Two small suggestions. No need for additional review unless you have questions about them.

2020-01-24 01:13 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/SpecimenDomainKind.java
> +        try (var transaction = DbSchema.get("Study", DbSchemaType.Module).getScope().ensureTransaction())
Can replace the call to DbSchema.get() with StudySchema.getInstance().getSchema(), here and in the other files.

2020-01-24 01:13 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/VialDomainKind.java
> +            Set<String> specimenFields = new HashSet<>();
Seems easier and safer to use a CaseInsensitiveHashSet instead

2020-01-24 23:14 UTC, merged