Item 6583: Run builder - allow relative file path for exp datas
LabKey/platform pull request #778
Opened 2020-01-28 03:49 UTC by labkey-martyp

- Incoming file paths when converting from file to exp.data can be relative to the file root.  Don't need full path including file root.

2020-01-30 21:01 UTC, labkey-kevink requested changes

2020-01-30 21:01 UTC, labkey-kevink commented on api/src/org/labkey/api/data/ExpDataFileConverter.java
> +                    String root = FileContentService.get().getFileRootPath(container, FileContentService.ContentType.files).toString();
It looks like the `ExperimentJSONConverter.PIPELINE_PATH` will resolve the relative path against the pipeline root already.  Can you see if that will work in this scenario?

2020-02-06 00:23 UTC, labkey-martyp commented on api/src/org/labkey/api/data/ExpDataFileConverter.java
> +                    String root = FileContentService.get().getFileRootPath(container, FileContentService.ContentType.files).toString();
@labkey-kevink So the reason I went this route is because the WebDav controller always saves to the file root (@files).  If we use PIPELINE_PATH and they have a pipeline override set, then when trying to assign that data file to a run it will check if it exists in the pipeline root and it won't be there.

The only reason we're doing relative URL at all is because the WebDav controller doesn't send back any useful information on save, so the UI really has no idea where it actually saved to.

2020-02-06 00:45 UTC, labkey-kevink commented on api/src/org/labkey/api/data/ExpDataFileConverter.java
> +                    String root = FileContentService.get().getFileRootPath(container, FileContentService.ContentType.files).toString();
Ah, I see.

2020-02-06 00:45 UTC, labkey-kevink approved these changes

2020-02-21 16:46 UTC, merged