Issue 39413: ETL with different container in source query
LabKey/platform pull request #807
Opened 2020-02-05 17:52 UTC by labkey-martyp

ETL with a different container in the source query was trying to check for target table in the source query.  Update to just ignore source query container if container is not a workbook or source query container is not a child of current container.

2020-02-05 19:03 UTC, labkey-jeckels requested changes

2020-02-05 19:03 UTC, labkey-jeckels commented on api/src/org/labkey/api/query/UserSchema.java
> +        if (ret != null && (!ret.isWorkbook() || !ret.hasAncestor(c)))
Please add a comment as to why this is here, with a pointer to the issue.

2020-02-25 16:45 UTC, labkey-martyp commented on api/src/org/labkey/api/query/UserSchema.java
> +        if (ret != null && (!ret.isWorkbook() || !ret.hasAncestor(c)))
Comment added.  Had to do a small update to not do this check if incoming container value is same as current container.

2020-02-25 16:58 UTC, labkey-jeckels approved these changes

2020-02-25 17:03 UTC, merged