Update Module
LabKey/platform pull request #825
Opened 2020-02-10 20:28 UTC by labkey-ivyc

(Created for Matt because he is OOO)

2020-02-10 21:30 UTC, labkey-jeckels requested changes

2020-02-10 21:30 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/DefaultModule.java
> +    private boolean _useSourcePath = false;
Looks like this was added but never used.

2020-02-10 21:30 UTC, labkey-jeckels commented on api/src/org/labkey/api/premium/PremiumService.java
> +    default ActionURL getUpdateModuleURL(String module)
Mark this as @Nullable?

2020-02-10 21:30 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/ModuleLoader.java
> +                        if (null != moduleFile && moduleFile.getName().endsWith(".module") && moduleFile.isFile())
Make this case-insensitive?

2020-02-10 21:30 UTC, labkey-jeckels commented on query/src/org/labkey/query/olap/ServerManager.java
> +            assertEquals("OLAP descriptors from the query module", 4, MODULE_DESCRIPTOR_CACHE.getResourceMap(module).size());
Does this belong here? I don't see any changes to the descriptors

2020-02-10 21:30 UTC, labkey-jeckels commented on core/src/org/labkey/core/admin/AdminController.java
> +                                        TD(String.valueOf(moduleContext.getInstalledVersion())),
@labkey-adam Do we want to show the schema version here too? I think you were planning to do this, but if it's in a separate FB it won't be easy to merge.

2020-02-10 21:42 UTC, labkey-jeckels requested changes

2020-02-10 21:42 UTC, labkey-jeckels commented on api/src/org/labkey/api/module/ModuleLoader.java
> +                return null;
Should this error out and/log log?

2020-02-10 22:26 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                                        TD(String.valueOf(moduleContext.getInstalledVersion())),
Yes, this was already changed to display Release Version and Schema Version on develop. Those changes will need to be merged from develop.

2020-02-10 22:26 UTC, labkey-adam commented on core/src/org/labkey/core/admin/AdminController.java
> +                                        TD(String.valueOf(moduleContext.getInstalledVersion())),
GitHub is showing that conflict below

2020-02-11 17:50 UTC, labkey-matthewb commented on query/src/org/labkey/query/olap/ServerManager.java
> +            assertEquals("OLAP descriptors from the query module", 4, MODULE_DESCRIPTOR_CACHE.getResourceMap(module).size());
That change snuck in.  Should take care of itself after next merge from develop.

2020-02-11 17:52 UTC, labkey-matthewb commented on api/src/org/labkey/api/module/ModuleLoader.java
> +                return null;
When built as a webapp we can run w/o using LabKeyBootstrap classloader.

2020-02-11 17:53 UTC, labkey-matthewb commented on api/src/org/labkey/api/module/ModuleLoader.java
> +                        if (null != moduleFile && moduleFile.getName().endsWith(".module") && moduleFile.isFile())
I thought about that, but decided to start strict.  Let me know if you think there's a real usage that is not lowercase.

2020-02-11 17:55 UTC, labkey-matthewb commented on api/src/org/labkey/api/module/DefaultModule.java
> +    private boolean _useSourcePath = false;
fixed

2020-02-11 17:55 UTC, labkey-matthewb commented on api/src/org/labkey/api/premium/PremiumService.java
> +    default ActionURL getUpdateModuleURL(String module)
fixed

2020-02-12 03:06 UTC, labkey-jeckels approved these changes

2020-03-02 14:52 UTC, labkey-adam approved these changes

2020-03-07 00:27 UTC, merged