Enable SimpleRedirectAction to redirect to whitelisted external hosts
LabKey/platform pull request #830
Opened 2020-02-13 01:51 UTC by labkey-ians

Not sure if this should go in as hotfix?

2020-02-13 05:10 UTC, labkey-jeckels requested changes

2020-02-13 05:10 UTC, labkey-jeckels commented on api/src/org/labkey/api/action/SimpleRedirectAction.java
> +        return HttpView.redirect(url, url.isAllowableHost());
I'm worried that this will start always including a host name in the redirect (unless it doesn't match our whitelist), and that this might inject the baseServerURL into redirects that didn't use it before. Ideally, this shouldn't matter, but I've seen plenty of servers where the baseServerURL wasn't set correctly, and this could make them harder to use (perhaps even impacting the ability to update them).

Let me know if I'm misreading the code!

2020-02-13 05:11 UTC, labkey-jeckels commented
This behavior hasn't changed recently, correct? If not, I'd say the fix can probably wait for 20.3 unless we've received strong feedback that it's a high priority.

2020-02-13 18:58 UTC, labkey-ians commented on api/src/org/labkey/api/action/SimpleRedirectAction.java
> +        return HttpView.redirect(url, url.isAllowableHost());
So the concern is that "|| url.isLocalUri(getRootContext())" wont match because the baseServerURL is misconfigured? Leading to a full url, and because the baseServerUrl is misconfigured any local redirects will point to an invalid (non-labkey) uri?

Then it seems like you would need a different action class to perform external redirects. As i'm not sure how you could reconcile all the misconfiguration permutations to detect a misconfigured local URI.

2020-02-14 01:09 UTC, labkey-jeckels commented on api/src/org/labkey/api/action/SimpleRedirectAction.java
> +        return HttpView.redirect(url, url.isAllowableHost());
The concern is that isAllowableHost() will return true for all URLs except ones that are pointed at a server that doesn't match our whitelist. Thus, we'll effectively always include a full URL including server hostname with this patch.

Most returnURL GET parameters don't include a server name, so they've been treated as relative URLs for redirect purposes. I think this change will append in the baseServerURL as the hostname for them.

Maybe I'm wrong about the behavior (I haven't tested it myself), but I was hoping that returnURLs that arrived without a hostname would continue to be treated as relative URLs, and those with a server name (that's on the whitelist, of course) would include them. Perhaps it's not practical to distinguish them though?

2020-02-14 18:05 UTC, labkey-ians commented on api/src/org/labkey/api/action/SimpleRedirectAction.java
> +        return HttpView.redirect(url, url.isAllowableHost());
The HttpView.redirect method call should localize it:

    public static HttpView redirect(URLHelper url, boolean allowAbsoluteUrl)
    {
        return new HttpRedirectView((!allowAbsoluteUrl || url.isLocalUri(getRootContext())) ? url.getLocalURIString() : url.getURIString());
    }

2020-02-15 23:44 UTC, labkey-jeckels commented on api/src/org/labkey/api/action/SimpleRedirectAction.java
> +        return HttpView.redirect(url, url.isAllowableHost());
Cool!

2020-02-15 23:44 UTC, labkey-jeckels approved these changes
Sorry for the bad assumption on when we'll do a full URL including hostname. Thanks for the explanation.

2020-02-17 18:04 UTC, merged