Issue 39640: Error rendering
LabKey/platform pull request #844
Opened 2020-02-19 01:37 UTC by labkey-adam

2020-02-20 18:54 UTC, labkey-matthewb requested changes

2020-02-20 18:54 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/DataColumn.java
> +        HtmlString errors = getErrors(ctx);
mark getErrors() with @NotNull (or check null != errors)

2020-02-20 18:54 UTC, labkey-matthewb commented on api/src/org/labkey/api/data/RenderContext.java
> +                errStr = HtmlString.unsafe(PageFlowUtil.filter(getViewContext().getMessage((MessageSourceResolvable) m), true));
This is fine.  In the interest of self-documenting code, might be nice to have something like HtmlString.preserveLineBreaks(message)

2020-02-21 17:10 UTC, labkey-matthewb approved these changes

2020-02-21 18:23 UTC, labkey-adam commented on api/src/org/labkey/api/data/DataColumn.java
> +        HtmlString errors = getErrors(ctx);
Done

2020-02-21 18:26 UTC, labkey-adam commented on api/src/org/labkey/api/data/RenderContext.java
> +                errStr = HtmlString.unsafe(PageFlowUtil.filter(getViewContext().getMessage((MessageSourceResolvable) m), true));
Added an HtmlString.of() variant that takes a translateWhiteSpaceflag, and migrated a few usages like this. Using a flag matches our approach in PageFlowUtil.filter() and JspBase.h().

2020-02-21 19:05 UTC, merged