Epic 6798 : List Domain Designer Conversion
LabKey/platform pull request #855
Opened 2020-02-21 00:36 UTC by labkey-bpatel

- Configure list module for React page.
- Addition of an Experimental feature to toggle on/off the new React page.
- Addition of GetDomainDetailsAction (variant of existing GetDomainAction) to return domain kind specific properties; and related refactoring.
- Deprecate GetDomainAction & update to client api docs.
- Bind of DomainKind specific options/properties to a bean for CreateDomain & SaveDomainAction (generifying of DomainKind and related refactoring).
- Notable List specific changes:  Add/override updateDomain(), modify createDomain(), create non-gwt bean, and other minor changes necessary for the new List Designer.

2020-02-21 20:06 UTC, labkey-jeckels requested changes
I didn't review the .ts or .tsx files, but here are the suggestions for the Java changes

2020-02-21 20:06 UTC, labkey-jeckels commented on assay/package.json
> +    "@labkey/components": "0.25.0-fb-list-designer-6798.2"
Don't forget to update before merging

2020-02-21 20:06 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainKind.java
>       * Create a Domain appropriate for this DomainKind.
This isn't the right JavaDoc for this method, looks like a copy/paste

2020-02-21 20:06 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +    abstract public DomainKindProperties getDomainKindProperties(GWTDomain domain, Container container, User user);
Should this return DomainKindProperties or T? Do we need the DomainKindProperties interface at all now?

2020-02-21 20:06 UTC, labkey-jeckels commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +    abstract public DomainKindProperties getDomainKindProperties(GWTDomain domain, Container container, User user);
and should this method be @Nullable?

2020-02-21 20:06 UTC, labkey-jeckels commented on api/webapp/clientapi/core/Domain.js
> +         * @param {boolean} config.options Domain Kind specific properties.
This should be {Object}, not {boolean}

2020-02-21 20:06 UTC, labkey-jeckels commented on api/webapp/clientapi/core/Domain.js
> +    *          <li><b>defaultDisplayValue:</b> Default value to display. (string)</li>
Let's put these newly doc'd properties at the bottom of the list - they're less likely to be relevant to the developer than the others.

2020-02-21 20:06 UTC, labkey-jeckels commented on internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
> +public abstract class AbstractIssuesListDefDomainKind<T> extends AbstractDomainKind<JSONObject>
This doesn't need its own <T> - all subclasses use JSONObject. This should clean up some of the casting in other spots in the code.

2020-02-21 20:06 UTC, labkey-jeckels commented on list/src/org/labkey/list/controllers/ListController.java
> +    public class GetListPropertiesAction extends ReadOnlyApiAction<ListDefinitionForm>
Do we still need this or can we just use the new general-purpose domain API?

2020-02-21 20:06 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +            if (null == domain || null == table)
If domain is null, I assume the call to ListService.getList() will blow up

2020-02-21 20:06 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                if (null != newKey && !key.getName().equalsIgnoreCase(newKey.getName()))
If newKey == null, shouldn't that be a problem too?

2020-02-21 20:06 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                    if (changedName && e.isConstraintException())
Better to check for this up front instead of catching an exception

2020-02-21 20:06 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +        ValidationException errors = new ValidationException();
Do we need this here. Shouldn't the centralized Domain saving code handle this?

2020-02-21 20:06 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +        if (null != newListProps.getName() && !newListProps.getName().equals(updatedListProps.getName()))
Why bother checking if it's equal? It's just as easy to stomp over the old value with an identical one.

2020-02-21 20:06 UTC, labkey-jeckels commented on study/src/org/labkey/study/model/AbstractSpecimenDomainKind.java
> +public abstract class AbstractSpecimenDomainKind<T> extends AbstractDomainKind<JSONObject>
Same as the issue domain kind - no need for this class to take a T

2020-02-21 20:06 UTC, labkey-jeckels commented on study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
> +public abstract class AbstractStudyDesignDomainKind extends AbstractDomainKind<JSONObject>
What do you think about introducing a convenience subclass of AbstractDomainKind that is tied to JSONObject, so that and using that here and other places so we don't need to implement getTypeClass() in so many places? Not sure it's worth it, but could be more convenient.

2020-02-24 15:01 UTC, cnathe commented on api/webapp/clientapi/core/Domain.js
> +    LABKEY.Domain.get(successHandler, errorHandler, 'study', 'StudyProperties');
Looks like there as still a few places in this doc info that reference "get" instead of "getDomainDetails", here and up above for the success and failure callback info.

2020-02-24 23:51 UTC, labkey-bpatel commented on api/src/org/labkey/api/exp/property/DomainKind.java
>       * Create a Domain appropriate for this DomainKind.
Now updated

2020-02-24 23:52 UTC, labkey-bpatel commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +    abstract public DomainKindProperties getDomainKindProperties(GWTDomain domain, Container container, User user);
It was my initial implementation, but after adding generics, <DomainKindProperties> is now removed.

2020-02-24 23:52 UTC, labkey-bpatel commented on api/webapp/clientapi/core/Domain.js
> +         * @param {boolean} config.options Domain Kind specific properties.
Good eye, now updated.

2020-02-24 23:53 UTC, labkey-bpatel commented on api/webapp/clientapi/core/Domain.js
> +    *          <li><b>defaultDisplayValue:</b> Default value to display. (string)</li>
Makes sense, now updated

2020-02-24 23:54 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                    if (changedName && e.isConstraintException())
its now updated by Cory as part of a bug fix.

2020-02-24 23:57 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +        if (null != newListProps.getName() && !newListProps.getName().equals(updatedListProps.getName()))
True, good point, now updated.

2020-02-24 23:59 UTC, labkey-bpatel commented on study/src/org/labkey/study/model/AbstractSpecimenDomainKind.java
> +public abstract class AbstractSpecimenDomainKind<T> extends AbstractDomainKind<JSONObject>
I think it was giving me a compile time error given my changes, hence I had included it. But now removed after adding a convenience subclass 'BaseAbstractDomainKind' of AbstractDomainKind.

2020-02-25 00:00 UTC, labkey-bpatel commented on study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
> +public abstract class AbstractStudyDesignDomainKind extends AbstractDomainKind<JSONObject>
Good idea, thanks for suggesting. Meet 'BaseAbstractDomainKind', subclass of AbstractDomainKind. And it was worth it.

2020-02-25 00:00 UTC, labkey-bpatel commented on api/webapp/clientapi/core/Domain.js
> +    LABKEY.Domain.get(successHandler, errorHandler, 'study', 'StudyProperties');
Good catch, now updated!

2020-02-25 00:01 UTC, labkey-bpatel commented on internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
> +public abstract class AbstractIssuesListDefDomainKind<T> extends AbstractDomainKind<JSONObject>
Yup, now removed.

2020-02-25 00:51 UTC, labkey-bpatel commented on list/src/org/labkey/list/controllers/ListController.java
> +    public class GetListPropertiesAction extends ReadOnlyApiAction<ListDefinitionForm>
I think this was added for the new list designer to get list properties from a listId, it is currently being used in react code.

2020-02-25 00:51 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +            if (null == domain || null == table)
Good point, now updated

2020-02-25 18:18 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                if (null != newKey && !key.getName().equalsIgnoreCase(newKey.getName()))
Perhaps I am missing something here -- this code is in updateDomain(), a null newKey is what's expected since we don't want key field name to be changed during update (and its a problem only if newKey is not null and not same as existing key).

2020-02-25 18:23 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +        ValidationException errors = new ValidationException();
Now removed, since duplicate name check is already happening in DomainUtil.validateProperties().

2020-02-25 20:02 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                if (null != newKey && !key.getName().equalsIgnoreCase(newKey.getName()))
As per our discussion, this is check is now in place. Thanks for clarifying!

2020-02-25 20:03 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +        if (null != newListProps.getName() && !newListProps.getName().equals(updatedListProps.getName()))
Additionally, have removed read-only properties such as keyName, keyType, and lastIndexed.

2020-02-25 20:13 UTC, labkey-bpatel commented on api/webapp/clientapi/core/Domain.js
> +         * @param {boolean} config.options Domain Kind specific properties.
Also, have added an additional Note and have listed read-only properties for IntList and VarList. 
Let me know what you think! Thanks!

2020-02-26 00:29 UTC, labkey-jeckels commented on internal/src/org/labkey/api/exp/property/BaseAbstractDomainKind.java
> +public abstract class BaseAbstractDomainKind<T> extends AbstractDomainKind<JSONObject>
This shouldn't take a <T> - T is never used

2020-02-26 00:29 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                    throw new IllegalArgumentException("Key field not provided, expecting key field '" + key.getName() + "'");
Why are these IllegalArgumentExceptions instead of adding to the errors object? And if it makes sense to not use errors, please use ApiUsageException instead to avoid mothership logging.

2020-02-26 00:29 UTC, labkey-jeckels commented on api/webapp/clientapi/core/Domain.js
> +         * @param {boolean} config.options Domain Kind specific properties.
Works for me.

2020-02-26 00:38 UTC, labkey-jeckels requested changes
Close, but a few more suggestions

2020-02-26 00:38 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +            updatedListProps.setDescription(newListProps.getDescription());
Does this mean that you can't completely clear out a description once it's been set?

2020-02-26 00:38 UTC, labkey-jeckels commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                    throw new IllegalArgumentException("Key field not provided, expecting key field '" + key.getName() + "'");
Why are these IllegalArgumentExceptions instead of adding to the errors object? And if it makes sense to not use errors, please use ApiUsageException instead to avoid mothership logging.

2020-02-26 03:23 UTC, labkey-bpatel commented on internal/src/org/labkey/api/exp/property/BaseAbstractDomainKind.java
> +public abstract class BaseAbstractDomainKind<T> extends AbstractDomainKind<JSONObject>
Now updated!
(Actually that's what I had initially, but I was getting some error around that, I must not have updated something correctly since it builds fine now)

2020-02-26 03:25 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                    throw new IllegalArgumentException("Key field not provided, expecting key field '" + key.getName() + "'");
Now added to the error obj for updateDomain().
CreateDomain() was using IllegalArugmentException as well, but now those are changed to use ApiUsageException.

2020-02-26 03:27 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +            updatedListProps.setDescription(newListProps.getDescription());
AH! Excellent point! (You alluded to this earlier as well, but didn't quiet take that further).
Null checks are now removed for all props except name.

2020-02-26 03:28 UTC, labkey-bpatel commented on list/src/org/labkey/list/model/ListDomainKind.java
> +                    throw new IllegalArgumentException("Key field not provided, expecting key field '" + key.getName() + "'");
Done!

2020-02-26 05:01 UTC, labkey-jeckels approved these changes

2020-02-26 18:34 UTC, cnathe approved these changes

2020-02-27 21:55 UTC, merged