Item 6834: Display Source Types: Add category field to exp.dataclasses
LabKey/platform pull request #861
Opened 2020-02-21 23:50 UTC by XingY

2020-02-24 17:15 UTC, labkey-susanh requested changes

2020-02-24 17:15 UTC, labkey-susanh commented on experiment/resources/schemas/dbscripts/postgresql/exp-20.000-20.001.sql
> +ALTER TABLE exp.DataClass ADD COLUMN Category VARCHAR(500) NULL;
500 seems quite large for the category.  I expect the strings to be no more than 20 characters in general.

2020-02-24 17:15 UTC, labkey-susanh commented on experiment/resources/schemas/dbscripts/postgresql/exp-20.000-20.001.sql
> +ALTER TABLE exp.DataClass ADD COLUMN Category VARCHAR(500) NULL;
I also wonder if we don't want Category to be an EnumTableType.

2020-02-24 17:15 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/insertDataClass.jsp
> +    <%-- TODO: dataclass.category field not yet supported for LKS insert --%>
@cnathe For your current story on creating source types, you are also making changes to the LKS view of this, right?  It seems like we should add a dropdown for specifying a category, in which case using an Enum is even more appropriate.

2020-02-24 17:15 UTC, labkey-susanh commented on query/src/org/labkey/query/QueryServiceImpl.java
> +    @NotNull public List<QueryIconURLProvider> getQueryIconURLProvider()
```suggestion
    @NotNull public List<QueryIconURLProvider> getQueryIconURLProviders()
```
Returning a list, so plural seems appropriate

2020-02-24 17:39 UTC, cnathe commented on experiment/src/org/labkey/experiment/insertDataClass.jsp
> +    <%-- TODO: dataclass.category field not yet supported for LKS insert --%>
Yes, we can add this part as a task to the Data Class Designer story that I am working on. I will do that now so I don't forget.

2020-02-25 00:16 UTC, labkey-susanh approved these changes

2020-02-25 19:38 UTC, merged