Issue 39807: Can't delete external schemas
LabKey/platform pull request #879
Opened 2020-02-26 19:21 UTC by labkey-bpatel

2020-02-26 21:07 UTC, labkey-adam requested changes
As written, the null case would be a strange confirmation message. I would do something like:

```
String schemaName = isBlank(form.getBean().getUserSchemaName()) ? "this schema" : "the schema '" + form.getBean().getUserSchemaName() + "'";
return new HtmlView("Are you sure you want to delete " + schemaName + "? The tables and queries defined in this schema will no longer be accessible.");
```

2020-02-26 21:45 UTC, labkey-bpatel commented
Good point! I've included your suggestion. Thanks!

2020-02-26 23:55 UTC, labkey-adam approved these changes

2020-02-28 18:31 UTC, labkey-bpatel commented
Unrelated test failure in BVT postgres. Newly added tests to delete Linked and External Schema pass (ran as personal build on Daily A). Merging.

2020-02-28 18:33 UTC, merged