Fb query metadata editor
LabKey/platform pull request #885
Opened 2020-02-27 00:35 UTC by labkey-ankurj

2020-02-27 15:20 UTC, cnathe commented
@labkey-ankurj I saw this PR open up so took a quick look. Overall looks good. There is a README doc page with the steps for "Setting up a LabKey module" here: https://github.com/LabKey/platform/tree/develop/webpack

Looks like you just need to update query/build.gradle and platform/.gitignore.

2020-03-11 16:01 UTC, cnathe approved these changes

2020-03-11 16:01 UTC, cnathe commented on api/src/org/labkey/api/query/QueryView.java
> -    public static final String EXPERIMENTAL_EXPORT_COLUMN_HEADER_TYPE = "export-column-header-type";
I assume this is unrelated to this story but just removed because it isn't used anymore?

2020-03-11 16:01 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +import org.labkey.experiment.api.GWTDomainMixin;
Was this additional import intentional? is it needed/used?

2020-03-11 16:01 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
> +import org.labkey.experiment.api.GWTDomainMixin;
Oh, nevermind. I see in the next file changed that the class moved packages. Got it.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/queryMetadataEditor.scss
> +  margin: 1px 5px;
I believe you only wanted the margin on the right side of the buttons, correct? If so, you could likely use `margin-right: 5px;` here.

2020-03-11 16:01 UTC, cnathe commented on .gitignore
> +query/node_modules
See my previous comment on this PR about adding a README file to the query module similar to the list module and experiment module.

2020-03-11 16:01 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +        om.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
This code is an exact copy from PropertyController.java right? Any chance we can find a shared location to put this static method so that they can both use it?

2020-03-11 16:01 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +    private GWTTableInfo saveMetadata(GWTTableInfo gwtTableInfo, String schemaName) throws MetadataUnavailableException
The saveMetdata, getMetadata, and resetToDefault all look to be copies of the MetadataServiceImpl.java class, is that right? If so, would it be possible to instead just make use of that MetadataService and keep the code in that file/class?

2020-03-11 16:01 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +            resp.put("success", true);
should we return the newly saved object here along with the success: true? likely doesn't matter too much since I assume the UI is just going to navigate after the response from this call.

2020-03-11 16:01 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +            resp.put("success", true);
Looks like the saveMetadata() call already returns the getMetadata() response at the end, so probably a quick think to add into the api response.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/entryPoints.js
> +        permission: 'admin', // this is admin so that direct access to this view has highest level perm, see PropertyController.EditDomainAction for main usage
will want to make sure to update the comment here once we put this in use in the QueryController as we won't want to reference PropertyController.EditDomainAction here. It will end up being QueryController.MetadataQueryAction right?

2020-03-11 16:01 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +    @RequiresPermission(EditQueriesPermission.class)
The MetadataQueryAction has `@RequiresAllOf({EditQueriesPermission.class, UpdatePermission.class})`, do we want the same here?

2020-03-11 16:01 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +    public class ResetQueryMetadataAction extends MutatingApiAction<QueryForm>
The MetadataQueryAction has `@RequiresAllOf({EditQueriesPermission.class, UpdatePermission.class})`, do we want the same here?

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +            //TODO: remove domainId from this call
Yes, updating the fetchQueryMetadata to remove that unneeded param would be good. Also, see my comment in the PR for labkey-api-js. I'm wondering if we should just have this fetchQueryMetadata action and Ajax.request here in the query module and not in labkey-api-js or labkey-ui-components as I assume this is the only component that will ever need it.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        console.log("called");
remove console.log()

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +    showSave: boolean,
For the other designers we have been leaving the save button always enabled. Was there a specific reason to disable it here? If not, I'd recommend matching the other designers behavior.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        Ajax.request({
minor: could move this to an actions.ts file as a sibling to this components. I think that would especially make sense if we do move the getQueryMetadata function to this module so that the actions.ts has both of those as functions this component can call.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        this.setState(() => ({dirty: false}), () => {
For both this Edit Source button and the View Data button, do we want to add in a "you have unsaved changes would you like to save before navigating" confirmation modal? It looks like that is what the current GWT query metadata editor does when these buttons are clicked in the dirty state? I believe the DomainDesigner.tsx file has an example of this confirm/save when the cancel button is clicked.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        this.setState(() => ({dirty: false}), () => {
same comment as above

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        Ajax.request({
See comment above. Could also move this Ajax.request into the actions.ts file so that they are all together in one place and not in this component directly.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +    onResetBtnHandler = () => {
It looks like the current GWT edit medata UI has a confirm "are you sure you want to reset / lose changes" modal. Do we want to replicate that for this new UI component?

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +export class AliasField extends PureComponent<AliasFieldProps, AliasFieldState> {
I would probably rename this file/component to AliasFieldModal to indicate that it is a modal. When I first saw it, I thought the name meant it was just the input field part.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +            selectedFieldName: domainFields.get(0).name
If we have the domainFields as a prop, do we need to hold onto all of these things directly in state? Could we just have a `selectedIndex` state set to 0 and then fetch the field or name when needed using the props and state?

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +        if (onAdd && selectedDomainFieldIndex) {
if `selectedDomainFieldIndex` is zero I believe this if statement will be false. I think you want `selectedDomainFieldIndex !== undefined` or something along those lines.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +            const domainFieldChange = domainFields.get(selectedDomainFieldIndex)
If you make the change I suggested related to the state object, this is likely where I'd suspect you get the selected field object and then use the name from it instead of having the selectedFieldName in state.

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +                    lockType: undefined,
any other things in the DomainField properties that needs to be cleared out, like propertyId?

2020-03-11 16:01 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +                <FormControl
I think you could use the shared `<SelectInput>` component here instead. It would handle the label for you and can take in the options and onChange, etc. as props. See example in ListPropertiesAdvancedSettings.tsx for the DisplayTitle component.

2020-03-11 16:21 UTC, cnathe requested changes
Oops, I meant to mark this as request changes per my review notes. Let me know if you have any questions.

2020-03-12 21:23 UTC, labkey-ankurj commented on api/src/org/labkey/api/query/QueryView.java
> -    public static final String EXPERIMENTAL_EXPORT_COLUMN_HEADER_TYPE = "export-column-header-type";
Correct.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +    showSave: boolean,
When there is no change initially, do we want to have the save button enabled, I matched the gwt query metadata save functionality.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/entryPoints.js
> +        permission: 'admin', // this is admin so that direct access to this view has highest level perm, see PropertyController.EditDomainAction for main usage
yes

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/queryMetadataEditor.scss
> +  margin: 1px 5px;
done

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +export class AliasField extends PureComponent<AliasFieldProps, AliasFieldState> {
Renamed

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +export class AliasField extends PureComponent<AliasFieldProps, AliasFieldState> {
Does modal means a dialog?

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +            //TODO: remove domainId from this call
Updated, I removed the fetchQueryMetadata from shared components and moved here in actions.ts

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        console.log("called");
done

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        Ajax.request({
Yes.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        this.setState(() => ({dirty: false}), () => {
Added the confirmModal.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        this.setState(() => ({dirty: false}), () => {
Added

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +    onResetBtnHandler = () => {
Added

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        Ajax.request({
Done.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +    private GWTTableInfo saveMetadata(GWTTableInfo gwtTableInfo, String schemaName) throws MetadataUnavailableException
The implementation plan specifies to delete the service and impl and that is getting deleted in the next part of the story. I can put it back if that seems more relevant.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +    public class ResetQueryMetadataAction extends MutatingApiAction<QueryForm>
Replaced.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +    @RequiresPermission(EditQueriesPermission.class)
Replaced.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +                <FormControl
Using it now.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +                    lockType: undefined,
I don't think so, but now also clearing out propertyId

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +            selectedFieldName: domainFields.get(0).name
With the new SelectInput, I realized I am not able to get index instead I am getting the DomainField object, so only keeping the domainField object. question on the similar note - is it expensive to keep more things in state?

2020-03-12 21:23 UTC, labkey-ankurj commented on .gitignore
> +query/node_modules
added

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +        if (onAdd && selectedDomainFieldIndex) {
yes, removed this from if.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +            const domainFieldChange = domainFields.get(selectedDomainFieldIndex)
changed the state object.

2020-03-12 21:23 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +        om.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
Moving this to PropertyService.

2020-03-12 21:29 UTC, labkey-ankurj commented on query/build.gradle
> +//project.tasks.npmInstall.dependsOn(project.project(BuildUtils.getPlatformProjectPath(project.gradle)).tasks.npmInstall)
I am not able to build locally with having this line.

2020-03-12 21:56 UTC, labkey-susanh commented on query/build.gradle
> +//project.tasks.npmInstall.dependsOn(project.project(BuildUtils.getPlatformProjectPath(project.gradle)).tasks.npmInstall)
You will also need to add:
```
project.evaluationDependsOn(BuildUtils.getPlatformProjectPath(project.gradle))
```
(See, for example the `experiment/build.gradle` file)

2020-03-12 22:34 UTC, labkey-ankurj commented on query/build.gradle
> +//project.tasks.npmInstall.dependsOn(project.project(BuildUtils.getPlatformProjectPath(project.gradle)).tasks.npmInstall)
Thanks Susan, added.

2020-03-13 14:39 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +    showSave: boolean,
I think that is the route we've been going for the other designers, so I would match what they are doing so that we can be consistent with the new designers.

2020-03-13 14:39 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        this.navigateToEditSource();
Since the this.onSaveBtnHandler() involves an Ajax call, won't this line execute too early (i.e. before the save has happened)? Probably should pass through the callback function to the onSaveBtnHandler. Something like this maybe:
```suggestion
        if (dirty) {
            this.onSaveBtnHandler(this.navigateToEditSource);
        }
        else {
             this.navigateToEditSource();
        }
```

2020-03-13 14:39 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        this.navigateToViewData();
same comment as above for the `onConfirmEditSource` function.

2020-03-13 14:39 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +            })
If you did the callback suggestion from above, I think this function would look something like this.

```suggestion
    onSaveBtnHandler = (onSaveNavigation) => {
        const { domain, schemaName, messages } = this.state;

        saveQueryMetadata(domain, schemaName)
            .then(() => {
                this.showMessage("Save Successful", 'success', 0);
                this.setState(() => ({
                    showSave: false,
                    dirty: false
                }), () => {
                    onSaveNavigation();
                });
            })
```

2020-03-13 14:39 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +export class AliasField extends PureComponent<AliasFieldProps, AliasFieldState> {
Yes

2020-03-13 14:43 UTC, cnathe commented on query/src/client/QueryMetadataEditor/components/AliaseField.tsx
> +            selectedFieldName: domainFields.get(0).name
Nope, it isn't very expensive to keep those other things in state. The reason to keep state as minimal as possible is so that the related properties don't get out of sync. If there is a selectedIndex and a selectedName in state, it is much more likely to forget to update one and not the other over just updating the selectedObject type of variable.

2020-03-13 14:45 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +    private GWTTableInfo saveMetadata(GWTTableInfo gwtTableInfo, String schemaName) throws MetadataUnavailableException
I see. Since this QueryController.java class is already huge, I was thinking it might be nice to keep those things in the MetadataService instead so that the controller is just handling the action/view parts and the backend updates would happen in the service. We use this split in a lot of other places.

2020-03-13 14:48 UTC, cnathe approved these changes
A few more minor comments but I'll go ahead and approve now.

2020-03-13 17:19 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +    private GWTTableInfo saveMetadata(GWTTableInfo gwtTableInfo, String schemaName) throws MetadataUnavailableException
@labkey-jeckels please consider and suggest in the code review of the next part of this story.

2020-03-14 16:22 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +    private GWTTableInfo saveMetadata(GWTTableInfo gwtTableInfo, String schemaName) throws MetadataUnavailableException
Added a suggestion along these lines to https://github.com/LabKey/platform/pull/949

2020-03-16 13:26 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +        }
To ensure that these happen after the state change is complete, you probably want to put them into the callback for the setState function. So it would look something like this:

```suggestion
        this.setState(() => ({
            showResetConfirmationModal: false,
            showViewDataConfirmationModal: false,
            showEditSourceConfirmationModal: false,
            dirty: false
        }), () => {
                if (showViewDataConfirmationModal) {
                   this.navigateToViewData();
               }

               if (showEditSourceConfirmationModal) {
                   this.navigateToEditSource();
               }
        });
```

2020-03-16 13:26 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +            this.onSaveBtnHandler(this.navigateToEditSource());
With the () at the end of the function parameter won't it call the function before calling this.onSaveBtnHandler (i.e. call this.navigateToEditSource() and use its return param, if any, as the parameter. I think you want the following:

```suggestion
            this.onSaveBtnHandler(this.navigateToEditSource);
```

2020-03-16 13:26 UTC, cnathe commented on query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
> +            this.onSaveBtnHandler(this.navigateToViewData());
Same as above, do you want?
```suggestion
            this.onSaveBtnHandler(this.navigateToViewData);
```

2020-03-16 22:53 UTC, merged