Merge Sample Type UI creation and editing into one page
LabKey/platform pull request #894
Opened 2020-02-29 00:16 UTC by labkey-ians

2020-03-03 20:50 UTC, cnathe requested changes

2020-03-03 20:50 UTC, cnathe commented on api/src/org/labkey/api/exp/api/DomainKindProperties.java
> +public interface DomainKindProperties
Have you done a recent merge from develop? Binal ended up removing this class at the end of her PR changes for the list designer platform changes. I assume this file will go away once that merge happens.

2020-03-03 20:50 UTC, cnathe commented on api/src/org/labkey/api/exp/api/ExpSampleSet.java
> +public interface ExpSampleSet extends ExpObject, DomainKindProperties
see comment from last file about this DomainKindProperties class being remove

2020-03-03 20:50 UTC, cnathe commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKindProperties.java
> +//TODO rename? SampleTypeDomainDetails?
do you plan to leave this TODO or make the change?

2020-03-03 20:50 UTC, cnathe commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKindProperties.java
> +            ss.getIdCols().forEach(col -> this.idCols.add(col.getPropertyId()));  //TODO verify this...
leave TODO or ...?

2020-03-03 20:50 UTC, cnathe commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKindProperties.java
> +        //TODO probably need to do more here... see MassSpecFractionsDomainKind.createDomain
leaving TODO or ...?

2020-03-03 20:50 UTC, cnathe commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +            throw new UnauthorizedException("You don't have permission to create a new domain");
I like this base validateOptions helper. This check does the create case, you could likely also add the update case as something like: 
`if (isUpdate && this.canEditDefinition(...)`
but looks like you might have to pass in the Domain object in that case so I can see leaving it out.

2020-03-03 20:50 UTC, cnathe commented on assay/src/org/labkey/assay/PlateBasedAssaySampleSetDomainKind.java
> +        //TODO this is probably broken too. Maybe we should throw a not supported exception here?
Same question from the commonAssay PR related to this. I included Josh to get his review of that PR so we can see what he says.

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/entryPoints.js
> +        title: 'Field Editor',
I would change this title to be 'Sample Type Designer'

2020-03-03 20:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/XarExporter.java
> +//        }
leaving TODO or ...?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
> +    //TODO remove
leaving TODO or ...?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                else
Just curious when we would ever end up in this else block? If we get to this code wouldn't the domainKind always have to be a SampleSetDomainKind?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                        editTypeButton.setDisplayPermission(UpdatePermission.class);
UpdatePermission doesn't seem like it would be a high enough permissions here, but as per the other comment, I'm not sure what type of domain kinds would end up here anyway.

2020-03-03 20:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +    @Deprecated //Use PropertyController.SaveDomainAction
I would not have expected that this action would be deprecated. I see that you removed the UpdateMaterialSourceApiAction, I could see that one being deprecated (but I think removing it is better/correct). Isn't this UpdateMaterialSourceAction still going to be the action in the LKS UI for updating a sample type design?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +    @Deprecated //Use PropertyController.CreateDomainAction
Same comment as above. Won't this CreateSampleSetAction still be where the LKS UI goes for creating a new sample type design?

2020-03-03 20:50 UTC, cnathe commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +//public class SampleSetDomainKind extends AbstractDomainKind<SampleTypeDomainKindProperties>
remove comment?

2020-03-03 20:50 UTC, cnathe commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +            return;  //TODO verify this is correct...
wouldn't you still want to call the super.validateOptions in this case? It has a permissions check in it which still would seem valid.

2020-03-03 20:50 UTC, cnathe commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +    //TODO Remove or use?
I'm guessing the answer is that you are using this and can remove this comment.

2020-03-03 20:50 UTC, cnathe commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +//        }
These seem like valid test cases for a new sample set create case. Are they commented out because they are called elsewhere and these lines can be removed? Or should they be uncommented?

2020-03-03 20:50 UTC, cnathe commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +//            throw new IllegalArgumentException("Value for Name field may not exceed " + nameMax + " characters.");
same as comment about, this seems like a valid check that we either know is happening elsewhere and this can be deleted or that it should be uncommented.

2020-03-03 20:50 UTC, cnathe commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +        ExpSampleSet sampleSet = options.getRowId() != -1 ? ss.getSampleSet(options.getRowId()) : null;
I don't think that zero is a valid RowId either. Should this check be `options.getRowId() > 0`?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/entryPoints.js
> +        permission: 'admin', // this is admin so that direct access to this view has highest level perm, see PropertyController.EditDomainAction for main usage
This permissions of 'admin' is correct, but the comment refers to PropertyController. EditDomainAction, I think that should actually be ExperimentController.BaseSampleSetAction right?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +export const NAME_EXPRESSION_TOPIC = 'sampleIDs#expression';
This const exists on the shared component side and I was not expecting that it would be needed here. I would have thought that it could be set in the SampleTypeDesigner shared component and not have to be used / passed as a prop here.

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +} as Partial<IDomainField>;
I haven't looked at the PR on the labkey-ui-components side yet, but how is this field config getting used? Do we end up adding a default first field in the SampleTypeDesigner component or something like that? I would have expected the SampleTypeDesigner fields domain to start out empty in this case.

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        initQueryGridState();
For my implementation of the DataClassDesigner shared component, I put this `initQueryGridState()` call inside of the DataClassPropertiesPanel constructor and it looks to be working as expected and I didn't have to do the same call here in the LK usage side.

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        if ((!schemaName || !queryName) && !RowId) {
Since the LK button that generates the URL for the Sample Type designer edit case only uses RowId as a param, I don't think we need to also support the schemaName/queryName params. I would drop that. Also, since this component is used in both the create and update case. I wasn't expecting a check here in the constructor. Instead I thought we'd skip the check here and then conditionally, in the componentDidMount either load the existing one if there is a rowId and assume it is the create case if not.

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +            this.fetchSampleTypeDomain(domainId, schemaName, queryName);
Is this case needed? won't the only way to get to this component be either for the create case (which doesn't have a rowId param) or for the update case (with a rowId param)?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +            getSampleSet({rowId})
Would it make sense to put this as an action/helper on the shared component side? I haven't looked at the PR for sapmleManagement yet, but assume it might have to do something similar to this?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +    private fetchSampleTypeDomain = (domainId, schemaName?, queryName?): void => {
Would it make sense to put this as an action/helper on the shared component side? I haven't looked at the PR for sapmleManagement yet, but assume it might have to do something similar to this?

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        //TODO check permissions
I don't think we need this permissions check on the LKS side. The two ways to view this component would be: 1) through the ExperimentController actions which already have the correct permissions check 2) via the experiment-sampleTypeDesigner.view resource/view, which via the entryPoint.js file is set as admin perm required.

2020-03-03 20:50 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        if (menuLoading) {
I don't see menuLoading in the props type definition. Also, I don't think we would be waiting for any menu to load here in the LKS side (I assume that part came from the SM app code?). Maybe calling this isLoading, but I assume it is a state variable not prop?

2020-03-06 23:52 UTC, labkey-ians commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKindProperties.java
> +//TODO rename? SampleTypeDomainDetails?
removed TODO, kept name same to match with ListDomainKindProperties

2020-03-07 00:10 UTC, labkey-ians commented on api/src/org/labkey/api/exp/api/SampleTypeDomainKindProperties.java
> +        //TODO probably need to do more here... see MassSpecFractionsDomainKind.createDomain
removed TODO

2020-03-07 00:43 UTC, labkey-ians commented on assay/src/org/labkey/assay/PlateBasedAssaySampleSetDomainKind.java
> +        //TODO this is probably broken too. Maybe we should throw a not supported exception here?
This method isn't called as far as I can tell. This overrides the underlying SampleSetDomainKind, but the implemented Assay gets updated through the AssayService. The better option here I think is throwing a NotImplementedException or similar.

2020-03-07 00:54 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/XarExporter.java
> +//        }
Uncommented for now. I don't feel confident in removing block for now.

2020-03-07 00:54 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
> +    //TODO remove
Removed TODO for now. I don't feel confident in removing method atm.

2020-03-07 00:58 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                else
@labkey-tchad I also think we can remove this block, did you run into a scenario where that wasn't the case?

2020-03-07 01:02 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +                        editTypeButton.setDisplayPermission(UpdatePermission.class);
Update permission is what was used previously. But I think you're correct and we can probably just delete this block.

2020-03-07 01:14 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +    @Deprecated //Use PropertyController.SaveDomainAction
nope, both SampleTypeDesigner implementations (LKS and SM) should go through Domain.SaveDomain. I only deprecated since I thought it might be exposed through the client apis; otherwise I think it could be removed.

2020-03-07 01:14 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
> +    @Deprecated //Use PropertyController.CreateDomainAction
nope, both SampleTypeDesigner implementations (LKS and SM) should go through Domain.SaveDomain. I only deprecated since I thought it might be exposed through the client apis; otherwise I think it could be removed.

2020-03-07 01:23 UTC, labkey-ians commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +            return;  //TODO verify this is correct...
fixed. Moved to after super call

2020-03-07 01:24 UTC, labkey-ians commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +//public class SampleSetDomainKind extends AbstractDomainKind<SampleTypeDomainKindProperties>
removed. (I feel like I've removed some of these TODOs previously)

2020-03-07 01:25 UTC, labkey-ians commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +    //TODO Remove or use?
TODO removed.

2020-03-07 02:12 UTC, labkey-ians commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +//            throw new IllegalArgumentException("Value for Name field may not exceed " + nameMax + " characters.");
Name is coming through the GwtDesign. Passed in as a parameter and uncommented

2020-03-07 02:13 UTC, labkey-ians commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +//        }
Name is coming through the GwtDesign. Passed in as a parameter and uncommented

2020-03-07 02:14 UTC, labkey-ians commented on api/src/org/labkey/api/exp/property/DomainKind.java
> +            throw new UnauthorizedException("You don't have permission to create a new domain");
passed down Domain and added Update check

2020-03-07 02:18 UTC, labkey-ians commented on internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
> +        ExpSampleSet sampleSet = options.getRowId() != -1 ? ss.getSampleSet(options.getRowId()) : null;
I thought 0 was valid, but not positive (no pun intended), but it should be > rather than !=

2020-03-07 02:25 UTC, labkey-ians commented on experiment/src/client/entryPoints.js
> +        permission: 'admin', // this is admin so that direct access to this view has highest level perm, see PropertyController.EditDomainAction for main usage
corrected.

2020-03-07 02:25 UTC, labkey-ians commented on experiment/src/client/entryPoints.js
> +        title: 'Field Editor',
Changed.

2020-03-07 02:36 UTC, labkey-ians commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +export const NAME_EXPRESSION_TOPIC = 'sampleIDs#expression';
removed.

2020-03-07 02:40 UTC, labkey-ians commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +} as Partial<IDomainField>;
This is used to match previous behavior which adds a (hidden from designer) SampleId field. I think it should probably be visible and readOnly but was trying to match original behavior first.

2020-03-07 02:40 UTC, labkey-ians commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        initQueryGridState();
Moved to SampleTypeDesigner

2020-03-07 02:47 UTC, labkey-ians commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        if ((!schemaName || !queryName) && !RowId) {
Added check for action, and banner message if update case and no rowId parameter.

2020-03-07 02:50 UTC, labkey-ians commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +            this.fetchSampleTypeDomain(domainId, schemaName, queryName);
I think the edit fields button was supplying schema and query, but since we removed that I think it is safe to just target the rowId.

2020-03-09 17:09 UTC, labkey-ians commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        if (menuLoading) {
removed. Never set or tracked.

2020-03-09 17:09 UTC, labkey-ians commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +        //TODO check permissions
removed.

2020-03-10 14:40 UTC, cnathe approved these changes

2020-03-10 14:40 UTC, cnathe commented on experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
> +            queryName,
It doesn't look like schemaName or queryName are expected anymore or used in this component, so I believe they can be removed from the state interface. Looks like fetchSampleTypeDomain is only using the domainId now.

2020-03-16 23:47 UTC, labkey-tchad commented
I opened an [issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39987) to track problems arising from this refactor.

2020-03-19 19:44 UTC, merged