Item 6835: Data Class designer updates for use in Sample Manager
LabKey/platform pull request #918
Opened 2020-03-06 17:09 UTC by cnathe

2020-03-14 00:51 UTC, Sigmonia requested changes

2020-03-14 00:51 UTC, Sigmonia commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +public class DataClassDomainKindProperties
Better name for these: DataClassPropertiesModel ?

2020-03-14 00:51 UTC, Sigmonia commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +        return name;
Should these String getters be StringUtils.trimToNull(name)?

2020-03-14 00:51 UTC, Sigmonia commented on experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
> +        window.addEventListener("beforeunload", this.handleWindowBeforeUnload);
Would be nice to pull this, the remove, and the supporting methods into a HOC

2020-03-14 00:51 UTC, Sigmonia commented on experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
> +    public DataClassDomainKindProperties getDomainKindProperties(GWTDomain domain, Container container, User user)
```suggestion
    public DataClassDomainKindProperties getDomainKindProperties(@NotNull GWTDomain domain, Container container, User user)
```

2020-03-14 00:51 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        options.setDescription(description);
We should be consistent with this. For ST I used the description field that is part of the GWTDomain.

2020-03-14 00:51 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
> -        String description = domain.getDescription();
We should be consistent with this. For ST I used the description field that is part of the GWTDomain. Primarily because this was already in place.

2020-03-14 00:51 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            //TODO do DataClasses actually support default values? The DataClassDomainKind does not override showDefaultValueSettings to return true so it isn't shown in the UI.
Still relevant?

2020-03-14 00:51 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            dataClass.setDescription(options.getDescription());
Again should make this consistent across our various domain types

2020-03-14 00:51 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        if (options.getNameExpression() != null && options.getNameExpression().length() > nameExpMax)
Do these string values need to be cleaned up? StringUtils.trimToNull?

2020-03-14 00:51 UTC, labkey-ians commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        if (options.getCategory() != null && options.getCategory().length() > categoryMax)
same trimToNull?

2020-03-16 22:00 UTC, cnathe commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +public class DataClassDomainKindProperties
@labkey-ians  Yes that is probably better. I was just following the name from ListDomainKindProperties. Did you use a different name for your sample type conversion work?

2020-03-16 22:10 UTC, labkey-ians commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +public class DataClassDomainKindProperties
Nope did the same as you, followed List. But i'm game to make the change in my branch too.

2020-03-19 17:48 UTC, cnathe commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +public class DataClassDomainKindProperties
We can refactor them together after both these branches are merged.

2020-03-19 17:52 UTC, cnathe commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +        return name;
I don't think this would be the right place for that, these are just the bean getters/settings. I'd prefer if the trimToNull is done when pulling the values out of the options object before save. Thoughts?

2020-03-19 18:13 UTC, cnathe commented on experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
> +        window.addEventListener("beforeunload", this.handleWindowBeforeUnload);
Good idea. Done.

2020-03-19 18:16 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
> +    public DataClassDomainKindProperties getDomainKindProperties(GWTDomain domain, Container container, User user)
Done.

2020-03-19 18:17 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            //TODO do DataClasses actually support default values? The DataClassDomainKind does not override showDefaultValueSettings to return true so it isn't shown in the UI.
Yes. I don't know the answer and need to follow-up with Kevin (will likely do that during the LKS side of this designer work).

2020-03-19 19:16 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        options.setDescription(description);
But the top level DataClass object is the one that has the description field. I saw that domain description field usage in your ST branch. For data classes, the description for a create and for update go into the top level DataClass object (from what I can tell). As your next comment mentions, I saw the usage of domain.getDescription in the previous DataClassDomainKind.createDomain code, but I can't figure out how that would have ever been populated on that domain object in the first place.

2020-03-19 19:17 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
> -        String description = domain.getDescription();
See comment above.

2020-03-19 19:17 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +            dataClass.setDescription(options.getDescription());
See comments above.

2020-03-19 19:33 UTC, labkey-ians commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +        return name;
I tend to agree, my only concern is not calling it when necessary. This gives a chokepoint to reduce the chance that trim wouldn't be applied.

2020-03-19 19:38 UTC, cnathe commented on api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
> +        return name;
Good point. I'll give it a go.

2020-03-19 19:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        if (options.getNameExpression() != null && options.getNameExpression().length() > nameExpMax)
Done. From the comment above, adding the trimToNull inside of the getters for DataClassDomainKindProperties did the trick.

2020-03-19 19:50 UTC, cnathe commented on experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
> +        if (options.getCategory() != null && options.getCategory().length() > categoryMax)
Done. From the comment above, adding the trimToNull inside of the getters for DataClassDomainKindProperties did the trick.

2020-03-20 05:04 UTC, Sigmonia approved these changes

2020-03-20 14:19 UTC, merged