Item 6993: delete old querymetadata editor gwt code
LabKey/platform pull request #949
Opened 2020-03-14 01:52 UTC by labkey-ankurj

2020-03-14 16:21 UTC, labkey-jeckels requested changes
Please completely remove the platform/query/gwtsrc directory. If the three remaining classes are still being used, fold them into the ./src directory, and rename them them from GWTColumnInfo to JSONColumnInfo or something like that.

2020-03-14 16:21 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +            return ModuleHtmlView.get(ModuleLoader.getInstance().getModule("query"), "queryMetadataEditor");
Not sure where to put this comment, but I agree with @cnathe's suggestion to not fold all of the old MetadataServiceImpl code directly into the already huge QueryController.

You don't need a full Service and ServiceImpl interface though, since you wouldn't be exposing it to other modules. You might be able to just move code into a renamed JSONTableInfo.save() method or something like that.

2020-03-17 00:02 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +            return ModuleHtmlView.get(ModuleLoader.getInstance().getModule("query"), "queryMetadataEditor");
@labkey-jeckels 
does rename of GWTTableInfo --> MetadataDomainJSON and GWTColumnInfo --> MetadataDomainFieldJSON make sense?

2020-03-17 00:04 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +            return ModuleHtmlView.get(ModuleLoader.getInstance().getModule("query"), "queryMetadataEditor");
The metadata use case isn't really Domain-based, so maybe MetadataTableJSON and MetadataColumnJSON instead?

2020-03-17 00:05 UTC, labkey-ankurj commented on query/src/org/labkey/query/controllers/QueryController.java
> +            return ModuleHtmlView.get(ModuleLoader.getInstance().getModule("query"), "queryMetadataEditor");
makes sense, thanks.

2020-03-17 13:21 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +            return ModuleHtmlView.get(ModuleLoader.getInstance().getModule("query"), "queryMetadataEditor");
Instead of a full service and service impl implementation, which I agree isn't needed since this isn't going to be used outside of this module, we've use the "manager" name for several usages like this. So maybe putting that code that was previously in the MetadataServiceImpl.java class into a new class names QueryMetadataManager.java?

2020-03-17 15:03 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +            return ModuleHtmlView.get(ModuleLoader.getInstance().getModule("query"), "queryMetadataEditor");
That would be a fine approach too, but yesterday Ankur showed me code that had a static getter on the MetadataTableJSON class, and a non-static save() method. Either seems OK to me.

2020-03-17 15:08 UTC, cnathe commented on query/src/org/labkey/query/controllers/QueryController.java
> +            return ModuleHtmlView.get(ModuleLoader.getInstance().getModule("query"), "queryMetadataEditor");
Sounds good. Sorry I misread some of the responses above regarding the usages of the MetadataTableJSON and MetadataColumnJSON classes. Makes sense now. Thanks.

2020-03-17 23:17 UTC, labkey-jeckels requested changes

2020-03-17 23:17 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +            _form = queryForm;
Can we avoid having both the form and the URL parameter code? Does the form by itself not work?

2020-03-17 23:17 UTC, labkey-jeckels commented on query/src/org/labkey/query/controllers/QueryController.java
> +                return new SimpleErrorView(errors);
I'd throw a NotFoundException instead

2020-03-18 00:26 UTC, labkey-jeckels approved these changes

2020-03-26 17:41 UTC, merged