Issue 40012: Query webpart saved charts not rendering in custom view
LabKey/platform pull request #970
Opened 2020-03-19 17:56 UTC by labkey-nicka

#### Rationale
[Issue 40012](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=40012) identified a scenario where our async rendering of webparts would intermittently fail to render properly resulting in a broken user experience.

![image](https://user-images.githubusercontent.com/3926239/77098087-0a4a2700-69cf-11ea-9f1a-cf6fab623aee.png)

I've added a new taglib `<labkey:loadClientDepdencies>` that is intended to supplant usages of `<labkey:scriptDependency>` which was deprecated in 18.1. With this change we'll no longer have to worry about dependencies loading out of order.

#### Changes
* Introduce new `<labkey:loadClientDepdencies>` tag to our tag library. See classes documentation for intended use.
* Remove `<labkey:scriptDependency/>` tag as this leads to erroneous behavior when global callbacks are not supplied. Additionally, the global callback pattern made it difficult to work with in situations where multiple of the same webpart are rendered to a single page.

#### TODO
* I still need to validate the handling of .css dependencies to ensure they load correctly.
* Confirm with @labkey-adam non-usage of `HtmlString`.

2020-03-19 18:02 UTC, labkey-nicka commented
There appears to be a superfluous  usage of `<labkey:scriptDependency/>` in one of our client modules. Triaging.

2020-03-19 19:51 UTC, labkey-adam commented
Thank you for getting rid of ScriptDependenciesTag (and for correcting spelling on loadClientDependencies in the Rationale :)). As for the HtmlString todo, I'm not sure what the question is, but here's a stab at an answer or two. We assume that our tags receive unencoded parameters and the underlying code knows how to encode everything properly; this is the opposite of JSP expressions. I suspect your print(String) is giving you red squiggles. You could use HtmlString internally, but that's not really correct since you're generating JavaScript. (Ideally, we'd have JavaScriptString or something that knows that encoding.) I'll make the code with some other comments. Let me know if you had a different question in mind...

2020-03-19 20:05 UTC, labkey-adam requested changes

2020-03-19 20:05 UTC, labkey-adam commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +                    files.append(delim).append("'").append(dependency.getScriptString()).append("'");
```suggestion
                    files.append(delim).append("'").append(script).append("'");
```

2020-03-19 20:05 UTC, labkey-adam commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +                String script = dependency.getScriptString();
Shouldn't this be JavaScript quoted? Might be unlikely to have funny characters in these paths, but still good form.

2020-03-19 20:05 UTC, labkey-adam commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +    private void print(StringBuilder sb) throws JspException
Pass in CharSequence instead? Would allow the doEndTag() simplification.

2020-03-19 20:05 UTC, labkey-adam commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +        print(sb);
Replace bulk of this with ```print("}, true);\n");```? Assuming CharSequence change below.

2020-03-19 20:33 UTC, labkey-adam commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> + * contained in a JSP. This ensures the JSPs dependencies are loaded in both sync and async
```suggestion
 * contained in a JSP. This ensures the JSP's dependencies are loaded in both sync and async
```

2020-03-19 22:03 UTC, labkey-nicka commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +                    files.append(delim).append("'").append(dependency.getScriptString()).append("'");
Good catch. Didn't catch this in my slight refactor. 8544e6a.

2020-03-19 22:03 UTC, labkey-nicka commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +                String script = dependency.getScriptString();
Good form +1. 8544e6a.

2020-03-19 22:04 UTC, labkey-nicka commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +    private void print(StringBuilder sb) throws JspException
8544e6a

2020-03-19 22:04 UTC, labkey-nicka commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> + * contained in a JSP. This ensures the JSPs dependencies are loaded in both sync and async
8544e6a

2020-03-19 22:06 UTC, labkey-nicka commented on api/src/org/labkey/api/jsp/taglib/LoadClientDependenciesTag.java
> +        print(sb);
8544e6a

2020-03-19 22:09 UTC, labkey-nicka commented
> Thank you for getting rid of ScriptDependenciesTag (and for correcting spelling on loadClientDependencies in the Rationale :)). As for the HtmlString todo, I'm not sure what the question is, but here's a stab at an answer or two. We assume that our tags receive unencoded parameters and the underlying code knows how to encode everything properly; this is the opposite of JSP expressions. I suspect your print(String) is giving you red squiggles. You could use HtmlString internally, but that's not really correct since you're generating JavaScript. (Ideally, we'd have JavaScriptString or something that knows that encoding.) I'll make the code with some other comments. Let me know if you had a different question in mind...

Yes, I wasn't sure on our handling of today's unsafe indicators so I appreciate you taking a look. The passing in of a `CharSequence` resolved that (by obfuscation?). Using `PageFlowUtil.jsString()` on user input is good for now in lieu of having a `JavaScriptString`.

2020-03-26 16:09 UTC, labkey-klum approved these changes

2020-03-27 16:48 UTC, labkey-adam approved these changes

2020-03-27 16:50 UTC, merged