6883: MultiAuth Followup Work
LabKey/platform pull request #988
Opened 2020-03-24 17:00 UTC by RosalineP

2020-04-01 23:05 UTC, labkey-alan requested changes

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +                this.setState({ [configType]: newState });
Any new state that is calculated on existing state should be calculated inside the setState callback. So you should be computing newState like so:
```
this.setState((state) => ({
    [configType]: state[configType].filter(auth => auth.configuration !== configuration),
}));
```

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
> +        if (!formConfigurations &&
You could simplify this check by storing a loading state variable in your state object. Then follow a pattern like this:

1. Initialize the loading variable to true in the constructor when you define this.state = { ... };
2. When the config is done loading set the variable to false.
3. In render just pull loading from state and render the loading spinner if it's true.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    determineConfigType = (addModalType: string): string => {
This is a bit of a nit, but this method could be simplified a bit:
```
determineConfigType = (addModalType: string): string => {
    const { primaryProviders } = this.props;
    const authInfo = primaryProviders[addModalType];

    if (authInfo) {
        return authInfo.sso ? 'ssoConfigurations' : 'formConfigurations';
    }

    return 'secondaryConfigurations';
};
```

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +        const authenticationDocsLink = helpLink;
We don't do anything additional to the helpLink variable except rename it here, which is not necessary. We could just use it inline below as `helpLink`.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        authConfig={{description: dbAuth.description, provider: dbAuth.provider, enabled: dbAuth.enabled}}
I'm a bit confused by this. Is there a reason you can't just pass dbAuth as the authConfig? Why construct a new object?

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    modalOpen: boolean;
I'm a bit confused as to why we need a third variable for tracking whether a modal is open. Could we not know this based purely on the state of `primaryModalOpen` and `secondaryModalOpen`? Or maybe `modalOpen` should be a string type where the string value is the modal that is open `secondary` or `primary`, and null/undefined is not open?

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +        const isDatabaseAuth = (authConfig.provider == 'Database');
Don't need parens here.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
>                          canEdit && toggleModalOpen(false);
This line is JavaScript and not JSX, this line should be converted to a normal if statement.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/AuthRow.tsx
> +                        onClick={() => onDelete(authConfig.configuration, configType)}
Since this click handler is computed entirely with props it seems more appropriate to have the parent pass in a click handler that already knows which configuration and configType to deal with, then just pass onDelete like so:

```
onClick={onDelete}
```

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +import {AuthConfig, DatabasePasswordRules, DatabasePasswordSettings} from "../AuthenticationConfiguration/models";
AuthConfig is an unused import.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +        const expiration = currentSettings.expiration;
```suggestion
        const { strength, expiration } = currentSettings;
```

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DatabaseConfigurationModal.tsx
> +        const expiration = currentSettings.expiration;
Would need to change references below to use `strength` instead of `passwordStrength`, or you could rename the state variable.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            } as AuthConfigFields,
The introduction of AuthConfigFields has required us to add in a bunch of compiler workarounds like the string accessors above, and the `as AuthConfigFields` here. It's also not possible that fieldValues will have all of the fields defined in AuthConfigFields because no one object exists that has them. This is one of those rare cases where a more loose type definition is appropriate due to the dynamic nature of this component. I would type fieldValues as `any`, or maybe `{ [key: string]: any}` if the field keys are definitely strings.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +                                headerLogoUrl={authConfig.headerLogoUrl}
extra indentation not needed.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +                />
```suggestion
               <LabelHelpTip title="Tip" body={() => <div>{description}</div>} />
```

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +                />
This same suggestion can be repeated a few times below.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +                <LabelHelpTip
I can't attach a comment further above due to how GitHub renders these diffs, but the CheckBox input has props set to `any`, and `CheckboxInputProps` is unused. We should properly define the props interface for CheckBox.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +    fieldValues: any;
This further reinforces what I was saying about `fieldValues` in DynamicConfigurationModal. I think `any` is the most appropriate type.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
>          }
```suggestion
        let stopPoint = fields.findIndex((field) => 'dictateFieldVisibility' in field) + 1;
        
        if (stopPoint === 0) {
            stopPoint = fields.length;
        }
```

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
>          }
That should work, but I did not test it.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +
Unnecessary empty line

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +
Unnecessary empty line

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +
Unnecessary empty line

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +
Unnecessary empty line

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +                            value={fieldValues[field.name]}
Instead of repeatedly referencing `fiedlValues[field.name]` here and below I would just extract it to a variable called `fieldValue` above.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +
Unnecessary empty line.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +                    );
```suggestion
                    return <FixedHtml key={index} caption={field.caption} html={field.html}/>;
```

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/DynamicFields.tsx
> +                    );
I think `{..field}` here is a mistake. You'll also want to remove `key` from the `FixedHtml` component props, key is build into React Components and should not be defined by your own components. Key should also be removed from `InputFieldProps`.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/components/GlobalSettings.tsx
> +    globalSettings: GlobalSettingsOptions;
This entire state interface can be removed. `GlobalSettings` makes no references to `this.state` or `this.setState`.

2020-04-01 23:05 UTC, labkey-alan commented on core/src/client/AuthenticationConfiguration/models.ts
> +    key?: number;
`key` should be removed, that is a prop provided and handled by React.

2020-04-01 23:46 UTC, RosalineP commented on core/src/client/components/AuthRow.tsx
>                          canEdit && toggleModalOpen(false);
Altered so that the prop is 

`                    closeModal={() => {
                        this.onToggleModal("editModalOpen", this.state.editModalOpen);
                        if (canEdit) {
                            toggleModalOpen(false);
                        } 
                    }}
`

2020-04-02 00:29 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +                        authConfig={{description: dbAuth.description, provider: dbAuth.provider, enabled: dbAuth.enabled}}
Oop. No good reason. Was following the pattern of the other authConfigs and got some code blindness. Fixed!

2020-04-02 00:36 UTC, RosalineP commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    modalOpen: boolean;
So the naming for this might be a little unclear—the primaryModalOpen tracks whether an 'add new' modal of primary auth is open, the secondaryModalOpen tracks whether an 'add new' modal of secondary auth is open, and modalOpen is whether an existing auth config's 'edit' modal is open. 
It's necessary to track whether it's a primary or secondary modal open (I checked if I could use a single 'addModalOpen') because that determines what server-supplied Provider data the code sends to the modal. 
'modalOpen' is only really useful in preventing a bug where an edit modal would be open, and you could click + drag rows _through_ the modal, which is why 'modalOpen' gets rebranded as 'isDragDisabled'.
I could rename 'modalOpen' to 'editModalOpen'?

2020-04-02 00:59 UTC, RosalineP commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            } as AuthConfigFields,
Oh gotcha. Makes sense, I thought my intersection type was a little hacky because it did cover all of the existing AuthProvider field types, but its existence kind of defeated the purpose of making those fields dynamic in the first place.
Since some of the values are strings and some are bools, I've left it as an `any`.

2020-04-02 01:15 UTC, RosalineP commented on core/src/client/components/DynamicFields.tsx
> +                <LabelHelpTip
Fixed!

2020-04-02 01:19 UTC, RosalineP commented on core/src/client/components/DynamicFields.tsx
>          }
Works, and is neater!

2020-04-02 01:29 UTC, RosalineP commented on core/src/client/components/DynamicFields.tsx
> +                    );
Oh man can't believe that got left in there. Done and done, fixed

2020-04-02 21:54 UTC, labkey-alan commented on core/src/client/components/AuthConfigMasterPanel.tsx
> +    modalOpen: boolean;
Yeah it would be much more clear if it was renamed to editModalOpen, let's do that.

2020-04-02 21:56 UTC, labkey-alan commented on core/src/client/components/DynamicConfigurationModal.tsx
> +            } as AuthConfigFields,
👍 Plus if you have it as `any` if/when we add a new type it'll render automatically with no extra effort.

2020-04-06 18:54 UTC, labkey-alan approved these changes

2020-04-07 02:14 UTC, merged