Issue 38148: Allow sample parents to be completely removed
LabKey/platform pull request #993
Opened 2020-03-25 15:20 UTC by labkey-susanh

In the case of importing or updated data through the API, an empty string value provided for a parent field (DataInputs/* or MaterialInputs/*) indicates that the parents from that class or set should be completely removed.  (Use of the empty string is consistent with behavior for other fields as well.)  When importing from a file, the value will come through as a null value instead of the empty string.

Removal of parents of data class objects is not modified here.

2020-03-25 16:45 UTC, labkey-jeckels requested changes
A few suggestions, but open to push back if you don't agree

2020-03-25 16:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                    else // we have parent columns but the parent value is empty, indciating that the parents should be cleared
```suggestion
                    else // we have parent columns but the parent value is empty, indicating that the parents should be cleared
```

2020-03-25 16:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentMaterialMap.put(sample, "Sample");
Can we introduce a constant here? ExpMaterialRunInput.DEFAULT_ROLE is used in other places, but it looks like we're using "Sample" here instead of "Material".

2020-03-25 16:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentDataMap = Collections.singletonMap(data, "Data");
I think this could use the existing ExpDataRunInput.DEFAULT_ROLE constant

2020-03-25 16:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                        allParts.add(new Pair<String, String>(_parentCols.get(parentCol), ""));
I don't like using the empty string (even if it's existing behavior), especially given your comment that other pathways come in with null values. I recommend that we try to transform empty strings to nulls as early in the process as we can.

2020-03-25 17:25 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentMaterialMap.put(sample, "Sample");
Constants are great, and I'm happy to add one, but is this actually supposed to be one of these mysterious "roles"?   Still unclear what those are used for and if changing this will have some nasty consequences in some respect or another.

2020-03-25 17:34 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentMaterialMap.put(sample, "Sample");
Yes, those are used as the role.

Roles aren't very interesting when there's a single input, but help differentiate when there are meaningful differences in how the samples are used in an assay. For example, you could designate one of the inputs as being a positive or negative control.

Maybe it's not appropriate to change the value that's being used here, but trying to demystify this just a little bit.

2020-03-25 17:39 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentMaterialMap.put(sample, "Sample");
Where do the roles manifest in the UI?

2020-03-25 17:40 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentDataMap = Collections.singletonMap(data, "Data");
Done locally.

2020-03-25 17:45 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentMaterialMap.put(sample, "Sample");
They show up in the run graphs and text views. See "AnalysisParameters", "FASTA", etc here as an example:

https://www.labkey.org/home/Demos/CPAS/demo/experiment-showRunGraph.view?rowId=402

2020-03-25 17:52 UTC, labkey-kevink requested changes

2020-03-25 17:52 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                        allParts.add(new Pair<String, String>(_parentCols.get(parentCol), ""));
I'm leaning toward using a sentinel value for this use case to make the intent of clearing the parent values explicit.

2020-03-25 17:52 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                    // TODO always clear? or only when parentcols is in input? or only when new derivation is specified?
Since we are now using blank to mean clear, I suspect we should also require all of the original parent columns from the initial derivation run to be blank.  Otherwise a single parent column that is now blank will clear the source run, right?

2020-03-25 17:52 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentMaterialMap.put(sample, "Sample");
The `UploadSamplesHelper.resolveInputsAndOutputs` uses `UploadSamplesHelper.sampleRole()` to get the role.

2020-03-25 17:52 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentDataMap = Collections.singletonMap(data, "Data");
`UploadSamplesHelper.dataRole()`

2020-03-25 17:53 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                        allParts.add(new Pair<String, String>(_parentCols.get(parentCol), ""));
OK, it looks like I can pass through null in the API call and it is not stripped out.

2020-03-25 17:53 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                currentMaterialMap.put(sample, "Sample");
Thanks!

2020-03-25 17:54 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                        allParts.add(new Pair<String, String>(_parentCols.get(parentCol), ""));
I'm disinclined toward a sentinel value since we use that nowhere else.

2020-03-25 18:12 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                    // TODO always clear? or only when parentcols is in input? or only when new derivation is specified?
I don't think behavior here has changed.  Previously we filtered out empty parent names before adding to _parentNames and simply did nothing if there were no parent names remaining (i.e., nothing added to _parentNames).  Now, if no parent names are non-empty, we'll not get here either, but will arrive with the ones that were non-empty just as before.  The TODO question still stands, but I don't think context has change here, has it?

2020-03-25 18:29 UTC, labkey-kevink commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +                                    // TODO always clear? or only when parentcols is in input? or only when new derivation is specified?
Sorry, I meant to add this comment to the `nonEmptyParentNames.isEmpty()` case.  After more head scratching, I agree with the current behavior.

2020-03-25 18:30 UTC, labkey-kevink approved these changes

2020-03-25 18:36 UTC, labkey-jeckels approved these changes

2020-03-27 21:30 UTC, labkey-kevink approved these changes

2020-03-30 13:55 UTC, merged