Item 7028: Source, Merge on import
LabKey/platform pull request #994
Opened 2020-03-25 16:55 UTC by XingY

Add support for data class merge by adding name and classId column to materialized dataclass table as use as them instead of lsid as key for merge.

Also added support to reselect objectURI, which is not used for this story due to performance issue.

2020-03-25 20:01 UTC, labkey-susanh reviewed
This all looks fine to me with a few minor suggestions and I defer to Matt who is more knowledgable about the Iterator stuff.

One question:  What happens if the data class is renamed?  Are we updating in both places?

2020-03-25 20:01 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExpDataIterators.java
> +
Remove commented out code?

2020-03-25 20:01 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +     * Called from exp-???.sql
```suggestion
     * Called from exp-20.001-20.002.sql
```

2020-03-25 20:01 UTC, labkey-susanh commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
> +            // use materialized classId so that parameter binding works for both exp.data as well as materializeed table
```suggestion
            // use materialized classId so that parameter binding works for both exp.data as well as materialized table
```

2020-03-26 05:35 UTC, XingY commented
RE: What happens if the data class is renamed? Are we updating in both places?

Yes, it will be updated on both places. For update, lsid is still the key field for properties table and all non key values will be updated, no custom code was needed.

2020-03-27 16:33 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +        try (DbScope.Transaction tx = ExperimentService.get().ensureTransaction())
Doesn't need to be changed, but I think(?) we usually don't bother with transaction in upgrade.  If upgrade fails it can't generally be recovered/fixed.  Have to start over from the backup anyway.

2020-03-27 16:50 UTC, labkey-jeckels commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +        try (DbScope.Transaction tx = ExperimentService.get().ensureTransaction())
That's certainly true for staging and production servers, but I find it handy to have transactions for troubleshooting on dev machines where it's easier to partially reset state to avoid needing backup/restore.

2020-03-27 16:58 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/ExperimentUpgradeCode.java
> +        try (DbScope.Transaction tx = ExperimentService.get().ensureTransaction())
👍

2020-03-27 17:40 UTC, labkey-matthewb requested changes

2020-03-27 17:40 UTC, labkey-matthewb commented on experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
> +    public SQLFragment getAliasedFilterSQLFragment(SqlDialect dialect, Map<FieldKey, ? extends ColumnInfo> columnMap, List<SimpleFilter.FilterClause> clauses)
I think there's an easier way to do this.  If you next the generated SQL with the JOIN in another level of ()'s, I think you can then use the filter as is.  
SELECT * FROM (..join sql) + getFilter().getSQLFragment()

2020-03-27 18:36 UTC, labkey-matthewb approved these changes

2020-03-27 19:58 UTC, merged